import {
  Trophy, Coins, Puzzle, Zap, Leaf, Heart, Target, BookOpen, GraduationCap, ShoppingCart, Book, Droplets, ClipboardList, Gift, Paintbrush, PenSquare, PartyPopper, HelpCircle, Recycle, Sun, Cloud, TreePine, Image, Clipboard
} from "lucide-react";

import buildIds from "../buildGameIds";

export const sustainabilityGameIdsKids = buildIds("sustainability", "kids")

export const getSustainabilityKidsGames = (gameCompletionStatus)=> {
    const sustainabilityGamesKids = [
        {
          id: "sustainability-kids-1",
          title: "Eco Sort Story",
          icon: <Leaf className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-1"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/eco-sort-story",
          index: 0,
        },
        {
          id: "sustainability-kids-2",
          title: "Quiz on Recycling",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-2"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-on-recycling",
          index: 1,
        },
        {
          id: "sustainability-kids-3",
          title: "Reflex Recycle",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-3"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-recycle",
          index: 2,
        },
        {
          id: "sustainability-kids-4",
          title: "Puzzle: Sort the Waste",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-4"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-sort-waste",
          index: 3,
        },
        {
          id: "sustainability-kids-5",
          title: "Litter Story",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-5"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/litter-story",
          index: 4,
        },
        {
          id: "sustainability-kids-6",
          title: "Poster: Reduce, Reuse, Recycle",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-6"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/poster-3rs",
          index: 5,
        },
        {
          id: "sustainability-kids-7",
          title: "Journal of Recycling",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-7"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/journal-recycling",
          index: 6,
        },
        {
          id: "sustainability-kids-8",
          title: "Plastic Bag Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-8"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/plastic-bag-story",
          index: 7,
        },
        {
          id: "sustainability-kids-9",
          title: "Reflex Waste Choice",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-9"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-waste-choice",
          index: 8,
        },
        {
          id: "sustainability-kids-10",
          title: "Badge: Eco Helper Kid",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-10"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-eco-helper-kid",
          index: 9,
        },
        {
          id: "sustainability-kids-11",
          title: "Lights Off Story",
          icon: <Sun className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-11"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/lights-off-story",
          index: 10,
        },
        {
          id: "sustainability-kids-12",
          title: "Quiz on Saving Energy",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-12"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-saving-energy",
          index: 11,
        },
        {
          id: "sustainability-kids-13",
          title: "Reflex Energy Saver",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-13"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-energy-saver",
          index: 12,
        },
        {
          id: "sustainability-kids-14",
          title: "Puzzle: Energy Sources",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-14"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-energy-sources",
          index: 13,
        },
        {
          id: "sustainability-kids-15",
          title: "Water Tap Story",
          icon: <Droplets className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-15"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/water-tap-story",
          index: 14,
        },
        {
          id: "sustainability-kids-16",
          title: "Poster: Save Water",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-16"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/poster-save-water",
          index: 15,
        },
        {
          id: "sustainability-kids-17",
          title: "Journal of Green Habits",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-17"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/journal-green-habits",
          index: 16,
        },
        {
          id: "sustainability-kids-18",
          title: "Tree Planting Story",
          icon: <TreePine className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-18"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/tree-planting-story",
          index: 17,
        },
        {
          id: "sustainability-kids-19",
          title: "Reflex Nature Care",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-19"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-nature-care",
          index: 18,
        },
        {
          id: "sustainability-kids-20",
          title: "Badge: Planet Protector Kid",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-20"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-planet-protector-kid",
          index: 19,
        },
        {
          id: "sustainability-kids-21",
          title: "Ocean Cleanup Story",
          icon: <Droplets className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-21"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/ocean-cleanup-story",
          index: 20,
        },
        {
          id: "sustainability-kids-22",
          title: "Quiz on Wildlife Protection",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-22"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-wildlife-protection",
          index: 21,
        },
        {
          id: "sustainability-kids-23",
          title: "Reflex Clean Air",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-23"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-clean-air",
          index: 22,
        },
        {
          id: "sustainability-kids-24",
          title: "Puzzle: Green Transportation",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-24"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-green-transportation",
          index: 23,
        },
        {
          id: "sustainability-kids-25",
          title: "Badge: Earth Guardian",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["sustainability-kids-25"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-earth-guardian",
          index: 24,
        },
        {
          id: "sustainability-kids-26",
          title: "Water Bottle Story",
          icon: <Droplets className="w-6 h-6" />, // Using droplets icon for water
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-26"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/water-bottle-story",
          index: 25,
        },
        {
          id: "sustainability-kids-27",
          title: "Quiz on Water Conservation",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-27"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-on-water-conservation",
          index: 26,
        },
        {
          id: "sustainability-kids-28",
          title: "Reflex Water Saver",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-28"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-water-saver",
          index: 27,
        },
        {
          id: "sustainability-kids-29",
          title: "Puzzle: Water Sources",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-29"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-water-sources",
          index: 28,
        },
        {
          id: "sustainability-kids-30",
          title: "Rain Story",
          icon: <Cloud className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-30"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/rain-story",
          index: 29,
        },
        {
          id: "sustainability-kids-31",
          title: "Poster: Clean Air",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-31"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/poster-clean-air",
          index: 30,
        },
        {
          id: "sustainability-kids-32",
          title: "Journal of Water Habits",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-32"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/journal-of-water-habits",
          index: 31,
        },
        {
          id: "sustainability-kids-33",
          title: "Plant Story",
          icon: <TreePine className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-33"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/plant-story",
          index: 32,
        },
        {
          id: "sustainability-kids-34",
          title: "Reflex Air Quality",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-34"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-air-quality",
          index: 33,
        },
        {
          id: "sustainability-kids-35",
          title: "Badge: Water Warrior Kid",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-35"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-water-warrior-kid",
          index: 34,
        },
        {
          id: "sustainability-kids-36",
          title: "Leftover Food Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-36"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/leftover-food-story",
          index: 35,
        },
        {
          id: "sustainability-kids-37",
          title: "Quiz on Food Waste",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-37"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-on-food-waste",
          index: 36,
        },
        {
          id: "sustainability-kids-38",
          title: "Reflex Food Saver",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-38"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-food-saver",
          index: 37,
        },
        {
          id: "sustainability-kids-39",
          title: "Puzzle: Compost Items",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-39"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-compost-items",
          index: 38,
        },
        {
          id: "sustainability-kids-40",
          title: "Garden Story",
          icon: <TreePine className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-40"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/garden-story",
          index: 39,
        },
        {
          id: "sustainability-kids-41",
          title: "Poster: Reduce Food Waste",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-41"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/poster-reduce-food-waste",
          index: 40,
        },
        {
          id: "sustainability-kids-42",
          title: "Journal of Food Habits",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-42"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/journal-of-food-habits",
          index: 41,
        },
        {
          id: "sustainability-kids-43",
          title: "Compost Story",
          icon: <TreePine className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-43"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/compost-story",
          index: 42,
        },
        {
          id: "sustainability-kids-44",
          title: "Reflex Compost Helper",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-44"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-compost-helper",
          index: 43,
        },
        {
          id: "sustainability-kids-45",
          title: "Badge: Food Saver Kid",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-45"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-food-saver-kid",
          index: 44,
        },
        {
          id: "sustainability-kids-46",
          title: "Bike Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-46"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/bike-story",
          index: 45,
        },
        {
          id: "sustainability-kids-47",
          title: "Quiz on Green Transport",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-47"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-on-green-transport",
          index: 46,
        },
        {
          id: "sustainability-kids-48",
          title: "Reflex Transport Choice",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-48"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-transport-choice",
          index: 47,
        },
        {
          id: "sustainability-kids-49",
          title: "Puzzle: Energy Choices",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-49"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-energy-choices",
          index: 48,
        },
        {
          id: "sustainability-kids-50",
          title: "Unplug Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["sustainability-kids-50"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/unplug-story",
          index: 49,
        },
        {
          id: "sustainability-kids-51",
          title: "Poster: Save Energy",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-51"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/poster-save-energy",
          index: 50,
        },
        {
          id: "sustainability-kids-52",
          title: "Journal of Transport",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-52"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/journal-of-transport",
          index: 51,
        },
        {
          id: "sustainability-kids-53",
          title: "Bus Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-53"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/bus-story",
          index: 52,
        },
        {
          id: "sustainability-kids-54",
          title: "Reflex Energy Wise",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-54"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-energy-wise",
          index: 53,
        },
        {
          id: "sustainability-kids-55",
          title: "Badge: Green Traveler Kid",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-55"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-green-traveler-kid",
          index: 54,
        },
        {
          id: "sustainability-kids-56",
          title: "Animal Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-56"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/animal-story",
          index: 55,
        },
        {
          id: "sustainability-kids-57",
          title: "Quiz on Wildlife",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-57"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-on-wildlife",
          index: 56,
        },
        {
          id: "sustainability-kids-58",
          title: "Reflex Animal Care",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-58"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-animal-care",
          index: 57,
        },
        {
          id: "sustainability-kids-59",
          title: "Puzzle: Animal Homes",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-59"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-animal-homes",
          index: 58,
        },
        {
          id: "sustainability-kids-60",
          title: "Forest Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-60"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/forest-story",
          index: 59,
        },
        {
          id: "sustainability-kids-61",
          title: "Poster: Protect Wildlife",
          icon: <Paintbrush className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-61"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/poster-protect-wildlife",
          index: 60,
        },
        {
          id: "sustainability-kids-62",
          title: "Journal of Nature Care",
          icon: <PenSquare className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-62"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/journal-nature-care",
          index: 61,
        },
        {
          id: "sustainability-kids-63",
          title: "Bee Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-63"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/bee-story",
          index: 62,
        },
        {
          id: "sustainability-kids-64",
          title: "Reflex Habitat Helper",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-64"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-habitat-helper",
          index: 63,
        },
        {
          id: "sustainability-kids-65",
          title: "Badge: Wildlife Friend Kid",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-65"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-wildlife-friend-kid",
          index: 64,
        },
        {
          id: "sustainability-kids-66",
          title: "Paper Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-66"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/paper-story",
          index: 65,
        },
        {
          id: "sustainability-kids-67",
          title: "Quiz on Upcycling",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-67"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-on-upcycling",
          index: 66,
        },
        {
          id: "sustainability-kids-68",
          title: "Reflex Upcycle Master",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-68"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-upcycle-master",
          index: 67,
        },
        {
          id: "sustainability-kids-69",
          title: "Puzzle: Material Life",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-69"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-material-life",
          index: 68,
        },
        {
          id: "sustainability-kids-70",
          title: "Craft Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-70"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/craft-story",
          index: 69,
        },
        {
          id: "sustainability-kids-71",
          title: "Poster: Upcycle Ideas",
          icon: <Paintbrush className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-71"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/poster-upcycle-ideas",
          index: 70,
        },
        {
          id: "sustainability-kids-72",
          title: "Journal of Reuse",
          icon: <PenSquare className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-72"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/journal-of-reuse",
          index: 71,
        },
        {
          id: "sustainability-kids-73",
          title: "Donation Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-73"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/donation-story",
          index: 72,
        },
        {
          id: "sustainability-kids-74",
          title: "Reflex Resource Saver",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-74"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-resource-saver",
          index: 73,
        },
        {
          id: "sustainability-kids-75",
          title: "Badge: Upcycle Champion Kid",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["sustainability-kids-75"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-upcycle-champion-kid",
          index: 74,
        },
        {
          id: "sustainability-kids-76",
          title: "Weather Story",
          icon: <Cloud className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-76"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/weather-story",
          index: 75,
        },
        {
          id: "sustainability-kids-77",
          title: "Quiz on Climate Change",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-77"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-on-climate-change",
          index: 76,
        },
        {
          id: "sustainability-kids-78",
          title: "Reflex Climate Helper",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-78"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-climate-helper",
          index: 77,
        },
        {
          id: "sustainability-kids-79",
          title: "Puzzle: Climate Solutions",
          icon: <Target className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-79"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-climate-solutions",
          index: 78,
        },
        {
          id: "sustainability-kids-80",
          title: "Season Story",
          icon: <Cloud className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-80"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/season-story",
          index: 79,
        },
        {
          id: "sustainability-kids-81",
          title: "Poster: Climate Action",
          icon: <Paintbrush className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "7 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-81"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/poster-climate-action",
          index: 80,
        },
        {
          id: "sustainability-kids-82",
          title: "Journal of Green Choices",
          icon: <PenSquare className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-82"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/journal-of-green-choices",
          index: 81,
        },
        {
          id: "sustainability-kids-83",
          title: "Carbon Story",
          icon: <Cloud className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-83"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/carbon-story",
          index: 82,
        },
        {
          id: "sustainability-kids-84",
          title: "Reflex Green Future",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-84"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-green-future",
          index: 83,
        },
        {
          id: "sustainability-kids-85",
          title: "Badge: Climate Helper Kid",
          icon: <Trophy className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-85"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-climate-helper-kid",
          index: 84,
        },
        {
          id: "sustainability-kids-86",
          title: "Community Story",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-86"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/community-story",
          index: 85,
        },
        {
          id: "sustainability-kids-87",
          title: "Quiz on Sustainable Living",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-87"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-on-sustainable-living",
          index: 86,
        },
        {
          id: "sustainability-kids-88",
          title: "Reflex Sustainable Life",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-88"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-sustainable-life",
          index: 87,
        },
        {
          id: "sustainability-kids-89",
          title: "Puzzle: Daily Habits",
          icon: <Target className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-89"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-daily-habits",
          index: 88,
        },
        {
          id: "sustainability-kids-90",
          title: "Neighbor Story",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-90"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/neighbor-story",
          index: 89,
        },
        {
          id: "sustainability-kids-91",
          title: "Poster: Community Action",
          icon: <Paintbrush className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "7 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-91"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/poster-community-action",
          index: 90,
        },
        {
          id: "sustainability-kids-92",
          title: "Journal of Community Help",
          icon: <PenSquare className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-92"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/journal-of-community-help",
          index: 91,
        },
        {
          id: "sustainability-kids-93",
          title: "Event Story",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-93"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/event-story",
          index: 92,
        },
        {
          id: "sustainability-kids-94",
          title: "Reflex Community Care",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-94"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-community-care",
          index: 93,
        },
        {
          id: "sustainability-kids-95",
          title: "Badge: Community Green Kid",
          icon: <Trophy className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-95"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-community-green-kid",
          index: 94,
        },
        {
          id: "sustainability-kids-96",
          title: "Future Story",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-96"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/future-story",
          index: 95,
        },
        {
          id: "sustainability-kids-97",
          title: "Quiz on Earth Care",
          icon: <BookOpen className="w-6 h-6" />, 
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-97"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/quiz-on-earth-care",
          index: 96,
        },
        {
          id: "sustainability-kids-98",
          title: "Reflex Earth Guardian",
          icon: <Zap className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-98"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/reflex-earth-guardian",
          index: 97,
        },
        {
          id: "sustainability-kids-99",
          title: "Puzzle: Earth Solutions",
          icon: <Target className="w-6 h-6" />, 
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-99"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/puzzle-earth-solutions",
          index: 98,
        },
        {
          id: "sustainability-kids-100",
          title: "Badge: Master Earth Guardian Kid",
          icon: <Trophy className="w-6 h-6" />, 
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["sustainability-kids-100"] || false,
          isSpecial: true,
          path: "/student/sustainability/kids/badge-master-earth-guardian-kid",
          index: 99,
        },
      ];

    return sustainabilityGamesKids;
}
