import {
  Heart,
  Users,
  Target,
  Award,
  BookOpen,
  Zap,
  Brain,
  Sparkles,
  Handshake,
  School,
  Medal,
  UserCheck,
  Volleyball,
  Star
} from "lucide-react";
import buildIds from "../buildGameIds";

export const crgcGameIdsKids = buildIds("civic-responsibility", "kids")

export const getCrgcKidsGames = (gameCompletionStatus) => {
    const crgcGamesKids = [
        {
            id: 'civic-responsibility-kids-1',
            title: 'Friend\'s Sad Story',
            description: 'Your friend is crying because her toy broke. What should you do?',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-1'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/friends-sad-story',
            index: 0
        },
        {
            id: 'civic-responsibility-kids-2',
            title: 'Quiz on Empathy',
            description: 'Empathy means? (a) Feeling with others, (b) Ignoring.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-2'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/quiz-on-empathy',
            index: 1
        },
        {
            id: 'civic-responsibility-kids-3',
            title: 'Reflex Kindness',
            description: 'Tap ❤️ for "Sharing Snacks," ❌ for "Laughing at Friend."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-3'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-kindness',
            index: 2
        },
        {
            id: 'civic-responsibility-kids-4',
            title: 'Puzzle: Match Feelings',
            description: 'Match "Happy → 😊 Smile, Sad → 😢 Cry, Angry → 😠 Frown."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-4'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/puzzle-match-feelings',
            index: 3
        },
        {
            id: 'civic-responsibility-kids-5',
            title: 'Animal Story',
            description: 'You see a hungry 🐕 dog. Should you feed or kick it?',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-5'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/animal-story',
            index: 4
        },
        {
            id: 'civic-responsibility-kids-6',
            title: 'Poster: Be Kind Always',
            description: 'Create/select poster: "Kindness is My Superpower."',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-6'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/poster-be-kind-always',
            index: 5
        },
        {
            id: 'civic-responsibility-kids-7',
            title: 'Journal of Empathy',
            description: 'Write: "I showed kindness today by ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-7'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/journal-of-empathy',
            index: 6
        },
        {
            id: 'civic-responsibility-kids-8',
            title: 'Bully Story',
            description: 'A bully teases a classmate. Should you join or stop him?',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-8'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/bully-story',
            index: 7
        },
        {
            id: 'civic-responsibility-kids-9',
            title: 'Reflex Help Alert',
            description: 'Tap 🙋 for "Help a Friend," ❌ for "Ignore Pain."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-9'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-help-alert',
            index: 8
        },
        {
            id: 'civic-responsibility-kids-10',
            title: 'Badge: Kind Kid',
            description: 'Show empathy in 5 cases to earn your badge.',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-10'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/badge-kind-kid',
            index: 9
        },
        {
            id: 'civic-responsibility-kids-11',
            title: 'Classroom Story',
            description: 'A classmate speaks a different language. Should you tease or respect?',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-11'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/classroom-story',
            index: 10
        },
        {
            id: 'civic-responsibility-kids-12',
            title: 'Quiz on Respect',
            description: 'Respect means? (a) Treating all kindly, (b) Ignoring others.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-12'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/quiz-on-respect',
            index: 11
        },
        {
            id: 'civic-responsibility-kids-13',
            title: 'Reflex Respect',
            description: 'Tap 👂 for "Listening," ❌ for "Interrupting."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-13'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-respect',
            index: 12
        },
        {
            id: 'civic-responsibility-kids-14',
            title: 'Puzzle: Respect Match',
            description: 'Match "Teacher → 👩‍🏫 Listen, Elder → 🧓 Help, Friend → 🤝 Share."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-14'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/puzzle-respect-match',
            index: 13
        },
        {
            id: 'civic-responsibility-kids-15',
            title: 'Gender Story',
            description: 'A boy says "Girls can\'t play football." What do you say?',
            icon: <UserCheck className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-15'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/gender-story',
            index: 14
        },
        {
            id: 'civic-responsibility-kids-16',
            title: 'Poster: Respect All',
            description: 'Create/select poster: "Every Voice Matters." 🗣️',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-16'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/poster-respect-all',
            index: 15
        },
        {
            id: 'civic-responsibility-kids-17',
            title: 'Journal of Respect',
            description: 'Write: "I showed respect today by ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-17'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/journal-of-respect',
            index: 16
        },
        {
            id: 'civic-responsibility-kids-18',
            title: 'Disability Story',
            description: 'A girl in a wheelchair joins school. Should you leave her out or include?',
            icon: <UserCheck className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-18'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/disability-story',
            index: 17
        },
        {
            id: 'civic-responsibility-kids-19',
            title: 'Reflex Inclusion',
            description: 'Tap 🙌 for "Invite Everyone," ❌ for "Exclude Friends."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-19'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-inclusion',
            index: 18
        },
        {
            id: 'civic-responsibility-kids-20',
            title: 'Badge: Respect Kid',
            description: 'Respect 5 classmates in examples to earn your badge.',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-20'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/badge-respect-kid',
            index: 19
        },
        {
            id: 'civic-responsibility-kids-21',
            title: 'Sports Story',
            description: 'Teacher asks who can play cricket. Should only boys join?',
            icon: <Volleyball className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-21'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/sports-story',
            index: 20
        },
        {
            id: 'civic-responsibility-kids-22',
            title: 'Quiz on Equality',
            description: 'Boys and girls should get? (a) Equal chances, (b) Only boys\' chances.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-22'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/quiz-on-equality',
            index: 21
        },
        {
            id: 'civic-responsibility-kids-23',
            title: 'Reflex Equality',
            description: 'Tap 📚 for "Girls Can Study," ❌ for "Girls Stay Home."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-23'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-equality',
            index: 22
        },
        {
            id: 'civic-responsibility-kids-24',
            title: 'Puzzle: Match Roles',
            description: 'Match "Doctor → 👩‍⚕️ Woman, Pilot → 👨‍✈️ Man, Teacher → 👩‍🏫 Both."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-24'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/puzzle-match-roles',
            index: 23
        },
        {
            id: 'civic-responsibility-kids-25',
            title: 'Homework Story',
            description: 'Mother asks only daughter to do chores. What is fair?',
            icon: <UserCheck className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-kids-25'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/homework-story',
            index: 24
        },
        {
            id: 'civic-responsibility-kids-26',
            title: 'Poster: Equal Rights',
            description: 'Create/select poster: "Equal Rights = Strong World." 🌍',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-26'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/poster-equal-rights',
            index: 25
        },
        {
            id: 'civic-responsibility-kids-27',
            title: 'Journal of Equality',
            description: 'Write: "One time I treated boys and girls equally was ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-27'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/journal-of-equality',
            index: 26
        },
        {
            id: 'civic-responsibility-kids-28',
            title: 'Classroom Story',
            description: 'Teacher only asks boys for answers. What should she do?',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-28'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/classroom-story-2',
            index: 27
        },
        {
            id: 'civic-responsibility-kids-29',
            title: 'Reflex Rights',
            description: 'Tap 👑 for "Girls Can Be Leaders," ❌ for "Girls Must Be Silent."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-29'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-rights',
            index: 28
        },
        {
            id: 'civic-responsibility-kids-30',
            title: 'Badge: Equality Kid',
            description: 'Show 5 equality actions to earn your badge.',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-30'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/badge-equality-kid',
            index: 29
        },
        {
            id: 'civic-responsibility-kids-31',
            title: 'Playground Story',
            description: 'A bigger kid pushes a smaller one. Should you laugh or help?',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-31'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/playground-story',
            index: 30
        },
        {
            id: 'civic-responsibility-kids-32',
            title: 'Quiz on Bullying',
            description: 'Bullying means? (a) Hurting others on purpose, (b) Helping others.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-32'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/quiz-on-bullying',
            index: 31
        },
        {
            id: 'civic-responsibility-kids-33',
            title: 'Reflex Bully Alert',
            description: 'Tap 🛡️ for "Stand Against Bully," ❌ for "Join Bully."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-33'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-bully-alert',
            index: 32
        },
        {
            id: 'civic-responsibility-kids-34',
            title: 'Puzzle: Anti-Bullying Match',
            description: 'Match "Speak Up → 🗣️ Courage, Support Friend -❤️ Care, Ignore Bully → ❌ Wrong."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-34'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/puzzle-anti-bullying-match',
            index: 33
        },
        {
            id: 'civic-responsibility-kids-35',
            title: 'Lunch Story',
            description: 'A classmate\'s lunch is stolen daily. Should you tell teacher?',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-35'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/lunch-story',
            index: 34
        },
        {
            id: 'civic-responsibility-kids-36',
            title: 'Poster: Stop Bullying',
            description: 'Create/select poster: "Bullying is Never Cool."',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-36'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/poster-stop-bullying',
            index: 35
        },
        {
            id: 'civic-responsibility-kids-37',
            title: 'Journal of Courage',
            description: 'Write: "One time I stood up for someone was ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-37'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/journal-of-courage',
            index: 36
        },
        {
            id: 'civic-responsibility-kids-38',
            title: 'Name-Calling Story',
            description: 'A boy is teased for glasses. Should you join or defend?',
            icon: <UserCheck className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-38'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/name-calling-story',
            index: 37
        },
        {
            id: 'civic-responsibility-kids-39',
            title: 'Reflex Safety',
            description: 'Tap 📢 for "Report Bully," ❌ for "Stay Silent."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-39'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-safety',
            index: 38
        },
        {
            id: 'civic-responsibility-kids-40',
            title: 'Badge: Bully Stopper Kid',
            description: 'Handle 5 bully-prevention cases to earn your badge.',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-40'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/badge-bully-stopper-kid',
            index: 39
        },
        {
            id: 'civic-responsibility-kids-41',
            title: 'Anger Story',
            description: 'Your friend is angry about something. How should you respond?',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-41'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/anger-story',
            index: 40
        },
        {
            id: 'civic-responsibility-kids-42',
            title: 'Quiz on Emotions',
            description: 'Identify different emotions and how to manage them.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-42'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/quiz-on-emotions',
            index: 41
        },
        {
            id: 'civic-responsibility-kids-43',
            title: 'Reflex Feelings',
            description: 'Tap 💙 for "Calm Down," ❌ for "Get Angry."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-43'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-feelings',
            index: 42
        },
        {
            id: 'civic-responsibility-kids-44',
            title: 'Puzzle: Match Feelings',
            description: 'Match emotions to appropriate responses.',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-44'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/puzzle-match-feelings-2',
            index: 43
        },
        {
            id: 'civic-responsibility-kids-45',
            title: 'Sharing Story',
            description: 'Two friends want to share a toy. How can they resolve this?',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-45'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/sharing-story',
            index: 44
        },
        {
            id: 'civic-responsibility-kids-46',
            title: 'Poster: Feelings Matter',
            description: 'Create/select poster: "All Feelings Are Important."',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-46'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/poster-feelings-matter',
            index: 45
        },
        {
            id: 'civic-responsibility-kids-47',
            title: 'Journal of Feelings',
            description: 'Write: "Today I managed my feelings by ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-47'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/journal-of-feelings',
            index: 46
        },
        {
            id: 'civic-responsibility-kids-48',
            title: 'Fight Story',
            description: 'Two friends are fighting. How can they make up?',
            icon: <Handshake className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-48'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/fight-story',
            index: 47
        },
        {
            id: 'civic-responsibility-kids-49',
            title: 'Reflex Emotion Alert',
            description: 'Tap 🤝 for "Make Up," ❌ for "Stay Angry."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-49'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-emotion-alert',
            index: 48
        },
        {
            id: 'civic-responsibility-kids-50',
            title: 'Badge: Emotion Aware Kid',
            description: 'Show emotional intelligence in 5 scenarios to earn your badge.',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-kids-50'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/badge-emotion-aware-kid',
            index: 49
        },
        {
            id: 'civic-responsibility-kids-51',
            title: 'Clean Park Story',
            description: 'You see litter in the park. Should you pick it up or ignore?',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-51'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/clean-park-story',
            index: 50
        },
        {
            id: 'civic-responsibility-kids-52',
            title: 'Quiz on Service',
            description: 'What does volunteering mean?',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-52'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/quiz-on-service',
            index: 51
        },
        {
            id: 'civic-responsibility-kids-53',
            title: 'Reflex Service Basics',
            description: 'Tap 🤝 for "Help Others," ❌ for "Ignore Needs."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-53'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-service-basics',
            index: 52
        },
        {
            id: 'civic-responsibility-kids-54',
            title: 'Puzzle: Community Helpers',
            description: 'Match helpers to their roles in the community.',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-54'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/puzzle-community-helpers',
            index: 53
        },
        {
            id: 'civic-responsibility-kids-55',
            title: 'Food Story',
            description: 'You have extra lunch. Should you share with a hungry child?',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-55'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/food-story',
            index: 54
        },
        {
            id: 'civic-responsibility-kids-56',
            title: 'Poster: Helping Hands',
            description: 'Create/select poster: "Little Hands Can Help Big."',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-56'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/poster-helping-hands',
            index: 55
        },
        {
            id: 'civic-responsibility-kids-57',
            title: 'Journal of Service',
            description: 'Write: "One way I helped in my community is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-57'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/journal-of-service',
            index: 56
        },
        {
            id: 'civic-responsibility-kids-58',
            title: 'Old Age Home Story',
            description: 'Class visits old age home. Should you sing to elders or stay silent?',
            icon: <Handshake className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-58'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/old-age-home-story',
            index: 57
        },
        {
            id: 'civic-responsibility-kids-59',
            title: 'Reflex Service Alert',
            description: 'Tap 🧹 for "Clean Area," ❌ for "Throw Trash."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-59'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-service-alert',
            index: 58
        },
        {
            id: 'civic-responsibility-kids-60',
            title: 'Badge: Little Volunteer',
            description: 'Do 5 volunteer actions to earn your badge.',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-60'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/badge-little-volunteer',
            index: 59
        },
        {
            id: 'civic-responsibility-kids-61',
            title: 'Playground Story',
            description: 'Teacher lets only boys play football. Is this fair?',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-61'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/playground-story-3',
            index: 60
        },
        {
            id: 'civic-responsibility-kids-62',
            title: 'Quiz on Rights',
            description: 'What is a human right?',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-62'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/quiz-on-rights',
            index: 61
        },
        {
            id: 'civic-responsibility-kids-63',
            title: 'Reflex Rights Alert',
            description: 'Tap 📚 for "Right to Education," ❌ for "No School for Girls."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-63'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-rights-alert',
            index: 62
        },
        {
            id: 'civic-responsibility-kids-64',
            title: 'Puzzle: Match Rights',
            description: 'Match basic rights to their categories.',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-64'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/puzzle-match-rights',
            index: 63
        },
        {
            id: 'civic-responsibility-kids-65',
            title: 'Hunger Story',
            description: 'A child is hungry. Which right is missing?',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-65'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/hunger-story',
            index: 64
        },
        {
            id: 'civic-responsibility-kids-66',
            title: 'Poster: Rights for All',
            description: 'Create/select poster: "Every Child Has Rights."',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-66'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/poster-rights-for-all',
            index: 65
        },
        {
            id: 'civic-responsibility-kids-67',
            title: 'Journal of Fairness',
            description: 'Write: "One right I am thankful for is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-67'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/journal-of-fairness',
            index: 66
        },
        {
            id: 'civic-responsibility-kids-68',
            title: 'Disabled Child Story',
            description: 'A disabled child is not allowed in school. Is this fair?',
            icon: <Handshake className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-68'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/disabled-child-story',
            index: 67
        },
        {
            id: 'civic-responsibility-kids-69',
            title: 'Reflex Justice Check',
            description: 'Tap ⚖️ for "Equal Treatment," ❌ for "Unfair Rules."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-69'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-justice-check',
            index: 68
        },
        {
            id: 'civic-responsibility-kids-70',
            title: 'Badge: Rights Kid',
            description: 'Identify 5 human rights cases to earn your badge.',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-70'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/badge-rights-kid',
            index: 69
        },
        {
            id: 'civic-responsibility-kids-71',
            title: 'Traffic Story',
            description: 'You see red light. Should you cross?',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-71'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/traffic-story',
            index: 70
        },
        {
            id: 'civic-responsibility-kids-72',
            title: 'Quiz on Rules',
            description: 'Why do we follow rules?',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-72'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/quiz-on-rules',
            index: 71
        },
        {
            id: 'civic-responsibility-kids-73',
            title: 'Reflex Rule Alert',
            description: 'Tap ✅ for "Follow Rules," ❌ for "Break Rules."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-73'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-rule-alert',
            index: 72
        },
        {
            id: 'civic-responsibility-kids-74',
            title: 'Puzzle: Match Rules',
            description: 'Match safety rules to their categories.',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-74'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/puzzle-match-rules',
            index: 73
        },
        {
            id: 'civic-responsibility-kids-75',
            title: 'School Rules Story',
            description: 'Should you cheat in exams?',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-kids-75'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/school-rules-story',
            index: 74
        },
        {
            id: 'civic-responsibility-kids-76',
            title: 'Poster: Rules Keep Us Safe',
            description: 'Create/select poster: "My Duty = My Safety."',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-76'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/poster-rules-keep-us-safe',
            index: 75
        },
        {
            id: 'civic-responsibility-kids-77',
            title: 'Journal of Duties',
            description: 'Write: "One rule I follow daily is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-77'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/journal-of-duties',
            index: 76
        },
        {
            id: 'civic-responsibility-kids-78',
            title: 'Neighbour Story',
            description: 'You see someone litter. What\'s your duty?',
            icon: <Handshake className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-78'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/neighbour-story',
            index: 77
        },
        {
            id: 'civic-responsibility-kids-79',
            title: 'Reflex Civic Duty',
            description: 'Tap 🇮🇳 for "Respect Rules," ❌ for "Ignore Duties."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-79'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/reflex-civic-duty',
            index: 78
        },
        {
            id: 'civic-responsibility-kids-80',
            title: 'Badge: Rule Follower Kid',
            description: 'Follow 5 civic duties to earn your badge.',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-80'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/badge-rule-follower-kid',
            index: 79
        },
        {
            id: 'civic-responsibility-kids-81',
            title: 'Food Story',
            description: 'Your friend brings sushi. Should you laugh or taste respectfully?',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-81'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/food-story-2',
            index: 80
        },
        {
            id: 'civic-responsibility-kids-82',
            title: 'Quiz on Cultures',
            description: 'Test your knowledge about different cultures and traditions.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-82'] || false,
            isSpecial: false,
            path: '/student/civic-responsibility/kids/quiz-on-cultures',
            index: 81
        },
        {
            id: 'civic-responsibility-kids-83',
            title: 'Reflex Culture Basics',
            description: 'Quick decisions about respecting cultural traditions.',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '2 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-83'] || false,
            isSpecial: false,
            path: '/student/civic-responsibility/kids/reflex-culture-basics',
            index: 82
        },
        {
            id: 'civic-responsibility-kids-84',
            title: 'Puzzle: Match Countries',
            description: 'Match countries with their traditional foods.',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-84'] || false,
            isSpecial: false,
            path: '/student/civic-responsibility/kids/puzzle-match-countries',
            index: 83
        },
        {
            id: 'civic-responsibility-kids-85',
            title: 'Greeting Story',
            description: 'A friend bows (Japanese style). Should you laugh or bow back?',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-85'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/greeting-story',
            index: 84
        },
        {
            id: 'civic-responsibility-kids-86',
            title: 'Poster: World Cultures',
            description: 'Create a poster about different but united cultures.',
            icon: <Star className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-86'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/poster-world-cultures',
            index: 85
        },
        {
            id: 'civic-responsibility-kids-87',
            title: 'Journal of Cultures',
            description: 'Write about a cultural thing you learned.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-87'] || false,
            isSpecial: false,
            path: '/student/civic-responsibility/kids/journal-of-cultures',
            index: 86
        },
        {
            id: 'civic-responsibility-kids-88',
            title: 'New Classmate Story',
            description: 'A refugee joins class. Should you exclude or include?',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-88'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/new-classmate-story',
            index: 87
        },
        {
            id: 'civic-responsibility-kids-89',
            title: 'Reflex Global Respect',
            description: 'Quick decisions about learning from cultures.',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '2 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-89'] || false,
            isSpecial: false,
            path: '/student/civic-responsibility/kids/reflex-global-respect',
            index: 88
        },
        {
            id: 'civic-responsibility-kids-90',
            title: 'Badge: Culture Friend Kid',
            description: 'Respect 5 cultures to earn your badge.',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-90'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/badge-culture-friend-kid',
            index: 89
        },
        {
            id: 'civic-responsibility-kids-91',
            title: 'School Cleanliness Story',
            description: 'The classroom is dirty. Should you complain or clean together?',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-91'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/school-cleanliness-story',
            index: 90
        },
        {
            id: 'civic-responsibility-kids-92',
            title: 'Quiz on Civic Action',
            description: 'Test your knowledge about civic action and community involvement.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-92'] || false,
            isSpecial: false,
            path: '/student/civic-responsibility/kids/quiz-on-civic-action',
            index: 91
        },
        {
            id: 'civic-responsibility-kids-93',
            title: 'Reflex Action',
            description: 'Quick decisions about leading clean-up efforts.',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '2 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-93'] || false,
            isSpecial: false,
            path: '/student/civic-responsibility/kids/reflex-action',
            index: 92
        },
        {
            id: 'civic-responsibility-kids-94',
            title: 'Puzzle: Match Leaders',
            description: 'Match leaders with their responsibilities.',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-94'] || false,
            isSpecial: false,
            path: '/student/civic-responsibility/kids/puzzle-match-leaders',
            index: 93
        },
        {
            id: 'civic-responsibility-kids-95',
            title: 'Planting Story',
            description: 'Kids want a green schoolyard. Should you plant trees or wait?',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-95'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/planting-story',
            index: 94
        },
        {
            id: 'civic-responsibility-kids-96',
            title: 'Poster: We Can Lead',
            description: 'Create a poster about kids leading change.',
            icon: <Star className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-96'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/poster-we-can-lead',
            index: 95
        },
        {
            id: 'civic-responsibility-kids-97',
            title: 'Journal of Action',
            description: 'Write about a civic action you took.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-97'] || false,
            isSpecial: false,
            path: '/student/civic-responsibility/kids/journal-of-action',
            index: 96
        },
        {
            id: 'civic-responsibility-kids-98',
            title: 'Team Story',
            description: 'Friends argue during project. Should you divide roles or fight?',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-98'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/team-story',
            index: 97
        },
        {
            id: 'civic-responsibility-kids-99',
            title: 'Reflex Leadership',
            description: 'Quick decisions about taking responsibility.',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '2 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-99'] || false,
            isSpecial: false,
            path: '/student/civic-responsibility/kids/reflex-leadership',
            index: 98
        },
        {
            id: 'civic-responsibility-kids-100',
            title: 'Badge: Young Leader Kid',
            description: 'Do 5 civic leadership acts to earn your badge.',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-kids-100'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/kids/badge-young-leader-kid',
            index: 99
        }
    ];

    return crgcGamesKids;
};

export default getCrgcKidsGames;