import {
  Heart,
  Users,
  Globe,
  Target,
  Award,
  BookOpen,
  Zap,
  Brain,
  Sparkles,
  Handshake,
  School,
  Medal,
  IndianRupee,
  MessageCircle,
  Monitor,
  Puzzle,
  Zap as Lightning,
  Droplets as Water,
  Gift,
  ShoppingCart as Cart,
  HeartPulse,
  Brain as BrainIcon,
  Eye as EyeIcon,
  Ear as EarIcon,
  Footprints as FootprintsIcon,
  Medal as MedalIcon,
  BookOpen as BookOpenIcon,
  Smartphone as SmartphoneIcon,
  Monitor as MonitorIcon,
  Radio as RadioIcon,
  Speaker as SpeakerIcon,
  Mic as MicIcon,
  Camera as CameraIcon,
  Droplets as DropletsIcon,
} from "lucide-react";
import buildIds from "../buildGameIds";

export const crgcGameIdsTeens = buildIds("civic-responsibility", "teens");

export const getCrgcTeensGames = (gameCompletionStatus) => {
    const crgcGamesTeens = [
        {
            id: 'civic-responsibility-teens-1',
            title: 'Stranger Story',
            description: 'You see an old woman carrying heavy bags. Should you help? → Yes. 🛍️',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-1'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/stranger-story',
            index: 0
        },
        {
            id: 'civic-responsibility-teens-2',
            title: 'Quiz on Compassion',
            description: 'What is compassion? (a) Caring for others, (b) Ignoring needs). Correct = Caring for others. ❤️',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-2'] || false,
            path: '/student/civic-responsibility/teens/quiz-on-compassion',
            index: 1
        },
        {
            id: 'civic-responsibility-teens-3',
            title: 'Reflex Teen Compassion',
            description: 'Tap ❤️ for "Help Others," ❌ for "Ignore." → Tap ❤️. ⚡',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-3'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-compassion',
            index: 2
        },
        {
            id: 'civic-responsibility-teens-4',
            title: 'Puzzle: Kind Acts',
            description: 'Match "Help Elderly → 🧓 Respect, Donate → 💝 Kindness, Volunteer → 🤝 Service." ✨',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-4'] || false,
            path: '/student/civic-responsibility/teens/puzzle-kind-acts',
            index: 3
        },
        {
            id: 'civic-responsibility-teens-5',
            title: 'Refugee Story',
            description: 'Teen meets refugee classmate. Should she include or exclude? → Include. 🌍',
            icon: <Globe className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-5'] || false,
            path: '/student/civic-responsibility/teens/refugee-story',
            index: 4
        },
        {
            id: 'civic-responsibility-teens-6',
            title: 'Debate: Kindness Wins?',
            description: 'Is kindness weakness or strength? → Strength. 🏆',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-6'] || false,
            path: '/student/civic-responsibility/teens/debate-kindness',
            index: 5
        },
        {
            id: 'civic-responsibility-teens-7',
            title: 'Journal of Compassion',
            description: 'Write: "One time I showed compassion was ___." ✍️',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-7'] || false,
            path: '/student/civic-responsibility/teens/journal-of-compassion',
            index: 6
        },
        {
            id: 'civic-responsibility-teens-8',
            title: 'Simulation: Hospital Visit',
            description: 'Options: Bring cheer / Ignore patients. Correct = Bring cheer. 🏥',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-8'] || false,
            path: '/student/civic-responsibility/teens/simulation-hospital-visit',
            index: 7
        },
        {
            id: 'civic-responsibility-teens-9',
            title: 'Reflex: Global Empathy',
            description: 'Tap 🤝 for "Global Care," ❌ for "Ignore World." → Tap 🤝. 🌎',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-9'] || false,
            path: '/student/civic-responsibility/teens/reflex-global-empathy',
            index: 8
        },
        {
            id: 'civic-responsibility-teens-10',
            title: 'Badge: Compassion Leader',
            description: 'Complete 5 compassionate acts to earn your badge. 🏅',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            isBadgeGame: true,
            badgeName: 'Badge: Compassion Leader',
            badgeImage: '/badges/civic-responsibility/teens/badge-compassion-leader.png',
            completed: gameCompletionStatus['civic-responsibility-teens-10'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/badge-compassion-leader',
            index: 9
        },
        // Games 11-20: Respect & Inclusion
        {
            id: 'civic-responsibility-teens-11',
            title: 'Cultural Story',
            description: 'Teen meets friend from another religion. Should she mock or learn? → Learn and respect. 🕌',
            icon: <Handshake className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-11'] || false,
            path: '/student/civic-responsibility/teens/cultural-story',
            index: 10
        },
        {
            id: 'civic-responsibility-teens-12',
            title: 'Quiz on Inclusion',
            description: 'Inclusion means? (a) Leaving out people, (b) Including all fairly). Correct = Including all fairly. 🎯',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-12'] || false,
            path: '/student/civic-responsibility/teens/quiz-on-inclusion',
            index: 11
        },
        {
            id: 'civic-responsibility-teens-13',
            title: 'Reflex Teen Respect',
            description: 'Tap 🙋‍♀️ for "Respect Women," ❌ for "Disrespect Women." → Tap 🙋‍♀️. ⚡',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-13'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-respect',
            index: 12
        },
        {
            id: 'civic-responsibility-teens-14',
            title: 'Puzzle: Inclusion Acts',
            description: 'Match "Invite → 🎒 New Student, Listen → 👥 Everyone, Share → 🤝 Team." ✨',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-14'] || false,
            path: '/student/civic-responsibility/teens/puzzle-inclusion-acts',
            index: 13
        },
        {
            id: 'civic-responsibility-teens-15',
            title: 'Religion Story',
            description: 'A friend prays differently. Should you laugh or respect? → Respect. 🙏',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-15'] || false,
            path: '/student/civic-responsibility/teens/religion-story',
            index: 14
        },
        {
            id: 'civic-responsibility-teens-16',
            title: 'Debate: Equality for All?',
            description: 'Should all students be treated equally? → Yes. 🏆',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-16'] || false,
            path: '/student/civic-responsibility/teens/debate-equality',
            index: 15
        },
        {
            id: 'civic-responsibility-teens-17',
            title: 'Journal of Inclusion',
            description: 'Write: "One time I included someone new was ___." ✍️',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-17'] || false,
            path: '/student/civic-responsibility/teens/journal-of-inclusion',
            index: 16
        },
        {
            id: 'civic-responsibility-teens-18',
            title: 'Simulation: School Event',
            description: 'Team excludes a new classmate. Options: Add her / Ignore / Laugh. Correct = Add her. 🎯',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-18'] || false,
            path: '/student/civic-responsibility/teens/simulation-school-event',
            index: 17
        },
        {
            id: 'civic-responsibility-teens-19',
            title: 'Reflex Teen Inclusion',
            description: 'Tap ⚖️ for "Equal Rights," ❌ for "Only Some Deserve." → Tap ⚖️. ⚡',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-19'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-inclusion',
            index: 18
        },
        {
            id: 'civic-responsibility-teens-20',
            title: 'Badge: Inclusion Leader',
            description: 'Complete 5 inclusion actions to earn your badge. 🏅',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            isBadgeGame: true,
            badgeName: 'Badge: Inclusion Leader',
            badgeImage: '/badges/civic-responsibility/teens/badge-inclusion-leader.png',
            completed: gameCompletionStatus['civic-responsibility-teens-20'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/badge-inclusion-leader',
            index: 19
        },
        // Games 21-30: Gender Equality & Rights
        {
            id: 'civic-responsibility-teens-21',
            title: 'Education Story',
            description: 'Teen girl wants to study engineering. Should parents stop her? → No. 🎓',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-21'] || false,
            path: '/student/civic-responsibility/teens/education-story',
            index: 20
        },
        {
            id: 'civic-responsibility-teens-22',
            title: 'Quiz on Teen Rights',
            description: 'Which is a gender right? (a) Equal education, (b) Unequal pay). Correct = Equal education. 🎯',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-22'] || false,
            path: '/student/civic-responsibility/teens/quiz-on-teen-rights',
            index: 21
        },
        {
            id: 'civic-responsibility-teens-23',
            title: 'Reflex Teen Rights',
            description: 'Tap 💼 for "Equal Opportunities," ❌ for "Only Boys Allowed." → Tap 💼. ⚡',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-23'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-rights',
            index: 22
        },
        {
            id: 'civic-responsibility-teens-24',
            title: 'Puzzle: Gender Barriers',
            description: 'Match "Equal Pay → ✅ Fair, Girls Out of School → ❌ Wrong, Women Leaders → 👍 Positive." ✨',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-24'] || false,
            path: '/student/civic-responsibility/teens/puzzle-gender-barriers',
            index: 23
        },
        {
            id: 'civic-responsibility-teens-25',
            title: 'Sports Story',
            description: 'Teen girl wants to join football team. Should coach stop her? → No. ⚽',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-25'] || false,
            path: '/student/civic-responsibility/teens/sports-story',
            index: 24
        },
        {
            id: 'civic-responsibility-teens-26',
            title: 'Debate: Girls as Leaders?',
            description: 'Should girls lead nations? → Yes, leadership has no gender. 🏆',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-26'] || false,
            path: '/student/civic-responsibility/teens/debate-girls-leaders',
            index: 25
        },
        {
            id: 'civic-responsibility-teens-27',
            title: 'Journal of Teen Equality',
            description: 'Write: "One gender stereotype I want to break is ___." ✍️',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-27'] || false,
            path: '/student/civic-responsibility/teens/journal-of-teen-equality',
            index: 26
        },
        {
            id: 'civic-responsibility-teens-28',
            title: 'Simulation: Teen Choices',
            description: 'Teen is told, "Girls can\'t code." Options: Believe it / Prove them wrong. Correct = Prove them wrong. 💻',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-28'] || false,
            path: '/student/civic-responsibility/teens/simulation-teen-choices',
            index: 27
        },
        {
            id: 'civic-responsibility-teens-29',
            title: 'Reflex Gender Alert',
            description: 'Tap 🤝 for "Equal Respect," ❌ for "Unequal Treatment." → Tap 🤝. ⚡',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-29'] || false,
            path: '/student/civic-responsibility/teens/reflex-gender-alert',
            index: 28
        },
        {
            id: 'civic-responsibility-teens-30',
            title: 'Badge: Gender Rights Teen',
            description: 'Show 5 gender rights actions to earn your badge. 🏅',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            isBadgeGame: true,
            badgeName: 'Badge: Gender Rights Teen',
            badgeImage: '/badges/civic-responsibility/teens/badge-gender-rights-teen.png',
            completed: gameCompletionStatus['civic-responsibility-teens-30'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/badge-gender-rights-teen',
            index: 29
        },
        // Games 31-40: Bullying Prevention & Peer Support
        {
            id: 'civic-responsibility-teens-31',
            title: 'Cyberbully Story',
            description: 'Teen receives mean messages online. Should she ignore or report? → Report. 💻',
            icon: <Monitor className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-31'] || false,
            path: '/student/civic-responsibility/teens/cyberbully-story',
            index: 30
        },
        {
            id: 'civic-responsibility-teens-32',
            title: 'Quiz on Cyberbullying',
            description: 'What is cyberbullying? (a) Online teasing/abuse, (b) Sports). Correct = Online teasing/abuse. 🎯',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-32'] || false,
            path: '/student/civic-responsibility/teens/quiz-on-cyberbullying',
            index: 31
        },
        {
            id: 'civic-responsibility-teens-33',
            title: 'Reflex Teen Bully Alert',
            description: 'Tap 🚫 for "Block + Report," ❌ for "Reply Angrily." → Tap 🚫. ⚡',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-33'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-bully-alert',
            index: 32
        },
        {
            id: 'civic-responsibility-teens-34',
            title: 'Puzzle: Peer Support',
            description: 'Match "Friend Sad → 🤗 Comfort, Cyberbully → 📱 Report, Bully Victim → 🛡️ Defend." ✨',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-34'] || false,
            path: '/student/civic-responsibility/teens/puzzle-peer-support',
            index: 33
        },
        {
            id: 'civic-responsibility-teens-35',
            title: 'School Story',
            description: 'A new girl is bullied for accent. Should you include or exclude? → Include. 🗣️',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-35'] || false,
            path: '/student/civic-responsibility/teens/school-story',
            index: 34
        },
        {
            id: 'civic-responsibility-teens-36',
            title: 'Debate: Ignore or Report?',
            description: 'Should bullying be ignored or reported? → Report. 🏆',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-36'] || false,
            path: '/student/civic-responsibility/teens/debate-ignore-or-report',
            index: 35
        },
        {
            id: 'civic-responsibility-teens-37',
            title: 'Journal of Peer Support',
            description: 'Write: "I helped a bullied friend by ___." ✍️',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-37'] || false,
            path: '/student/civic-responsibility/teens/journal-of-peer-support',
            index: 36
        },
        {
            id: 'civic-responsibility-teens-38',
            title: 'Simulation: Teen Bully Scene',
            description: 'Bully teases classmate. Options: Join / Stay silent / Defend. Correct = Defend. 🛡️',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-38'] || false,
            path: '/student/civic-responsibility/teens/simulation-teen-bully-scene',
            index: 37
        },
        {
            id: 'civic-responsibility-teens-39',
            title: 'Reflex Teen Courage',
            description: 'Tap 🗣️ for "Speak Against Bully," ❌ for "Be Silent." → Tap 🗣️. ⚡',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-39'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-courage',
            index: 38
        },
        {
            id: 'civic-responsibility-teens-40',
            title: 'Badge: Peer Protector Teen',
            description: 'Support peers in 5 bullying cases to earn your badge. 🏅',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            isBadgeGame: true,
            badgeName: 'Badge: Peer Protector Teen',
            badgeImage: '/badges/civic-responsibility/teens/badge-peer-protector-teen.png',
            completed: gameCompletionStatus['civic-responsibility-teens-40'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/badge-peer-protector-teen',
            index: 39
        },
        // Games 41-50: Emotional Intelligence & Conflict Resolution
        {
            id: 'civic-responsibility-teens-41',
            title: 'Disagreement Story',
            description: 'Teen friends fight over a project idea. Should they discuss calmly or fight? → Discuss calmly. 🗣️',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-41'] || false,
            path: '/student/civic-responsibility/teens/disagreement-story',
            index: 40
        },
        {
            id: 'civic-responsibility-teens-42',
            title: 'Quiz on Conflict',
            description: 'Best way to solve conflict? (a) Talk and listen, (b) Fight). Correct = Talk and listen. 🎯',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-42'] || false,
            path: '/student/civic-responsibility/teens/quiz-on-conflict',
            index: 41
        },
        {
            id: 'civic-responsibility-teens-43',
            title: 'Reflex Conflict Check',
            description: 'Tap 🤝 for "Solve by Dialogue," ❌ for "Solve by Fighting." → Tap 🤝. ⚡',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-43'] || false,
            path: '/student/civic-responsibility/teens/reflex-conflict-check',
            index: 42
        },
        {
            id: 'civic-responsibility-teens-44',
            title: 'Puzzle: Conflict Solutions',
            description: 'Match "Listen → 👂 Respect, Apologize → 🫂 Heal, Shout → 😠 Wrong." ✨',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-44'] || false,
            path: '/student/civic-responsibility/teens/puzzle-conflict-solutions',
            index: 43
        },
        {
            id: 'civic-responsibility-teens-45',
            title: 'Friendship Story',
            description: 'Teen argues with best friend. Should she apologize or stay angry? → Apologize. 🙏',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-45'] || false,
            path: '/student/civic-responsibility/teens/friendship-story',
            index: 44
        },
        {
            id: 'civic-responsibility-teens-46',
            title: 'Debate: Apology = Weakness?',
            description: 'Is saying sorry a weakness or strength? → Strength. 🏆',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-46'] || false,
            path: '/student/civic-responsibility/teens/debate-apology-strength',
            index: 45
        },
        {
            id: 'civic-responsibility-teens-47',
            title: 'Journal of Conflict',
            description: 'Write: "One time I solved a conflict by ___." ✍️',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-47'] || false,
            path: '/student/civic-responsibility/teens/journal-of-conflict',
            index: 46
        },
        {
            id: 'civic-responsibility-teens-48',
            title: 'Simulation: Teen Fight',
            description: 'Two classmates fight loudly. Options: Mediate / Join fight / Walk away. Correct = Mediate. 🕊️',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-48'] || false,
            path: '/student/civic-responsibility/teens/simulation-teen-fight',
            index: 47
        },
        {
            id: 'civic-responsibility-teens-49',
            title: 'Reflex Teen Peace',
            description: 'Tap 🧘 for "Stay Calm," ❌ for "Get Violent." → Tap 🧘. ⚡',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-49'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-peace',
            index: 48
        },
        {
            id: 'civic-responsibility-teens-50',
            title: 'Badge: Peace Maker Teen',
            description: 'Solve 5 conflicts positively to earn your badge. 🏅',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            isBadgeGame: true,
            badgeName: 'Badge: Peace Maker Teen',
            badgeImage: '/badges/civic-responsibility/teens/badge-peace-maker-teen.png',
            completed: gameCompletionStatus['civic-responsibility-teens-50'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/badge-peace-maker-teen',
            index: 49
        },
        // Games 51-60: Community Service & Volunteering
        {
            id: 'civic-responsibility-teens-51',
            title: 'Blood Donation Camp Story',
            description: 'Teen is too young to donate blood. How else can she help? → Assist in camp. 🩸',
            icon: <HeartPulse className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-51'] || false,
            path: '/student/civic-responsibility/teens/blood-donation-camp-story',
            index: 50
        },
        {
            id: 'civic-responsibility-teens-52',
            title: 'Quiz on Volunteering',
            description: 'Which is volunteering? (a) Helping at beach clean-up, (b) Watching TV). Correct = Helping at clean-up. 🎯',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-52'] || false,
            path: '/student/civic-responsibility/teens/quiz-on-volunteering',
            index: 51
        },
        {
            id: 'civic-responsibility-teens-53',
            title: 'Reflex Teen Volunteer',
            description: 'Tap 🌱 for "Plant Trees," ❌ for "Cut Trees." → Tap 🌱. ⚡',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-53'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-volunteer',
            index: 52
        },
        {
            id: 'civic-responsibility-teens-54',
            title: 'Puzzle: Volunteer Areas',
            description: 'Match "Hospital → 🏥 Support, School → 📚 Tutor, Nature → 🌳 Plant Trees." ✨',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-54'] || false,
            path: '/student/civic-responsibility/teens/puzzle-volunteer-areas',
            index: 53
        },
        {
            id: 'civic-responsibility-teens-55',
            title: 'Fundraising Story',
            description: 'Teen organizes bake sale for charity. What is this? → Volunteering with impact. 🧁',
            icon: <Gift className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-55'] || false,
            path: '/student/civic-responsibility/teens/fundraising-story',
            index: 54
        },
        {
            id: 'civic-responsibility-teens-56',
            title: 'Debate: Service = Waste?',
            description: 'Is community service a waste of time? → No, it builds society. 🏆',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '6 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-56'] || false,
            path: '/student/civic-responsibility/teens/debate-service-waste',
            index: 55
        },
        {
            id: 'civic-responsibility-teens-57',
            title: 'Journal of Teen Service',
            description: 'Write: "One volunteer activity I want to try is ___." ✍️',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-57'] || false,
            path: '/student/civic-responsibility/teens/journal-of-teen-service',
            index: 56
        },
        {
            id: 'civic-responsibility-teens-58',
            title: 'Simulation: Clean-Up Drive',
            description: 'Teen group sees garbage. Options: Organize clean-up / Walk away / Blame others. Correct = Organize clean-up. 🗑️',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-58'] || false,
            path: '/student/civic-responsibility/teens/simulation-clean-up-drive',
            index: 57
        },
        {
            id: 'civic-responsibility-teens-59',
            title: 'Reflex Service Mindset',
            description: 'Tap 🤲 for "Help Poor," ❌ for "Mock Poor." → Tap 🤲. ⚡',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-59'] || false,
            path: '/student/civic-responsibility/teens/reflex-service-mindset',
            index: 58
        },
        {
            id: 'civic-responsibility-teens-60',
            title: 'Badge: Volunteer Leader Teen',
            description: 'Complete 5 teen volunteer challenges to earn your badge. 🏅',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            isBadgeGame: true,
            badgeName: 'Badge: Volunteer Leader Teen',
            badgeImage: '/badges/civic-responsibility/teens/badge-volunteer-leader-teen.png',
            completed: gameCompletionStatus['civic-responsibility-teens-60'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/badge-volunteer-leader-teen',
            index: 59
        },
        // Games 61-70: Human Rights & Social Justice
        {
            id: 'civic-responsibility-teens-61',
            title: 'Education Story',
            description: 'Teen girl forced to quit school for marriage. Is this right? → No. 📚',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-61'] || false,
            path: '/student/civic-responsibility/teens/education-story-justice',
            index: 60
        },
        {
            id: 'civic-responsibility-teens-62',
            title: 'Quiz on Social Justice',
            description: 'Social justice means? (a) Fairness for all, (b) Favouritism). Correct = Fairness for all. 🎯',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-62'] || false,
            path: '/student/civic-responsibility/teens/quiz-on-social-justice',
            index: 61
        },
        {
            id: 'civic-responsibility-teens-63',
            title: 'Reflex Teen Justice',
            description: 'Tap ⚖️ for "Equality," ❌ for "Discrimination." → Tap ⚖️. ⚡',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-63'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-justice',
            index: 62
        },
        {
            id: 'civic-responsibility-teens-64',
            title: 'Puzzle: Justice Heroes',
            description: 'Match "Mahatma Gandhi → 🕊️ Freedom, Martin Luther King → ✊ Equality, Malala → 📖 Education." ✨',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-64'] || false,
            path: '/student/civic-responsibility/teens/puzzle-justice-heroes',
            index: 63
        },
        {
            id: 'civic-responsibility-teens-65',
            title: 'Wage Story',
            description: 'Teen reads workers not paid equally. What is this? → Injustice. 💰',
            icon: <IndianRupee className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-65'] || false,
            path: '/student/civic-responsibility/teens/wage-story',
            index: 64
        },
        {
            id: 'civic-responsibility-teens-66',
            title: 'Debate: All Humans Equal?',
            description: 'Should all humans have equal rights? → Yes. 🏆',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '6 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-66'] || false,
            path: '/student/civic-responsibility/teens/debate-all-humans-equal',
            index: 65
        },
        {
            id: 'civic-responsibility-teens-67',
            title: 'Journal of Justice',
            description: 'Write: "One unfair thing I noticed is ___." ✍️',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-67'] || false,
            path: '/student/civic-responsibility/teens/journal-of-justice',
            index: 66
        },
        {
            id: 'civic-responsibility-teens-68',
            title: 'Simulation: Teen Justice Act',
            description: 'Teen hears slurs against classmate. Options: Speak up / Stay silent / Join. Correct = Speak up. 🗣️',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-68'] || false,
            path: '/student/civic-responsibility/teens/simulation-teen-justice-act',
            index: 67
        },
        {
            id: 'civic-responsibility-teens-69',
            title: 'Reflex Teen Rights',
            description: 'Tap 🌍 for "Justice for All," ❌ for "Justice for Few." → Tap 🌍. ⚡',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-69'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-rights-2',
            index: 68
        },
        {
            id: 'civic-responsibility-teens-70',
            title: 'Badge: Justice Teen',
            description: 'Complete 5 social justice cases to earn your badge. 🏅',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            isBadgeGame: true,
            badgeName: 'Badge: Justice Teen',
            badgeImage: '/badges/civic-responsibility/teens/badge-justice-teen.png',
            completed: gameCompletionStatus['civic-responsibility-teens-70'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/badge-justice-teen',
            index: 69
        },
        // Games 71-80: Law, Duties & Civic Responsibility
        {
            id: 'civic-responsibility-teens-71',
            title: 'Constitution Story',
            description: 'What is the book of rules for our country? → The Constitution. 📖',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-71'] || false,
            path: '/student/civic-responsibility/teens/constitution-story',
            index: 70
        },
        {
            id: 'civic-responsibility-teens-72',
            title: 'Quiz on Rights & Duties',
            description: 'Which is a duty? (a) Pay taxes, (b) Waste resources). Correct = Pay taxes. 🎯',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-72'] || false,
            path: '/student/civic-responsibility/teens/quiz-on-rights-duties',
            index: 71
        },
        {
            id: 'civic-responsibility-teens-73',
            title: 'Reflex Teen Law',
            description: 'Tap ⚖️ for "Obey Laws," ❌ for "Break Laws." → Tap ⚖️. ⚡',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-73'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-law',
            index: 72
        },
        {
            id: 'civic-responsibility-teens-74',
            title: 'Puzzle: Match Civic Roles',
            description: 'Match "Judge → ⚖️ Court, Police → 🚓 Safety, Voter → 🗳️ Democracy." ✨',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-74'] || false,
            path: '/student/civic-responsibility/teens/puzzle-match-civic-roles',
            index: 73
        },
        {
            id: 'civic-responsibility-teens-75',
            title: 'Voter Story',
            description: 'At 18, what duty do you gain? → Right to vote. 🗳️',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-75'] || false,
            path: '/student/civic-responsibility/teens/voter-story',
            index: 74
        },
        {
            id: 'civic-responsibility-teens-76',
            title: 'Debate: Rights vs Duties',
            description: 'Are rights more important than duties? → Both must balance. 🏆',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-76'] || false,
            path: '/student/civic-responsibility/teens/debate-rights-vs-duties',
            index: 75
        },
        {
            id: 'civic-responsibility-teens-77',
            title: 'Journal of Law Awareness',
            description: 'Write: "One law that keeps me safe is ___." ✍️',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-77'] || false,
            path: '/student/civic-responsibility/teens/journal-of-law-awareness',
            index: 76
        },
        {
            id: 'civic-responsibility-teens-78',
            title: 'Simulation: Teen Citizen',
            description: 'Teen sees corruption. Options: Report / Join / Ignore. Correct = Report. 📢',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-78'] || false,
            path: '/student/civic-responsibility/teens/simulation-teen-citizen',
            index: 77
        },
        {
            id: 'civic-responsibility-teens-79',
            title: 'Reflex Teen Duty',
            description: 'Tap 🇮🇳 for "Respect Nation," ❌ for "Ignore Laws." → Tap 🇮🇳. ⚡',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-79'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-duty',
            index: 78
        },
        {
            id: 'civic-responsibility-teens-80',
            title: 'Badge: Responsible Citizen Teen',
            description: 'Complete 5 law-awareness activities to earn your badge. 🏅',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            isBadgeGame: true,
            badgeName: 'Badge: Responsible Citizen Teen',
            badgeImage: '/badges/civic-responsibility/teens/badge-responsible-citizen-teen.png',
            completed: gameCompletionStatus['civic-responsibility-teens-80'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/badge-responsible-citizen-teen',
            index: 79
        },
        // Games 81-90: Global Citizenship & Cultural Awareness
        {
            id: 'civic-responsibility-teens-81',
            title: 'Climate Story',
            description: 'Floods affect kids in another country. Should you care? → Yes. 🌍',
            icon: <Globe className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-81'] || false,
            path: '/student/civic-responsibility/teens/climate-story',
            index: 80
        },
        {
            id: 'civic-responsibility-teens-82',
            title: 'Quiz on Global Citizenship',
            description: 'Global citizenship means? (a) Caring for whole world, (b) Only self). Correct = Caring for whole world. 🎯',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-82'] || false,
            path: '/student/civic-responsibility/teens/quiz-on-global-citizenship',
            index: 81
        },
        {
            id: 'civic-responsibility-teens-83',
            title: 'Reflex Teen Global',
            description: 'Tap 🤝 for "Help Across Borders," ❌ for "Ignore Others." → Tap 🤝. ⚡',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-83'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-global',
            index: 82
        },
        {
            id: 'civic-responsibility-teens-84',
            title: 'Puzzle: Global Leaders',
            description: 'Match "UNICEF → 👧 Children, WHO → 🩺 Health, UNESCO → 📚 Education." ✨',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-84'] || false,
            path: '/student/civic-responsibility/teens/puzzle-global-leaders',
            index: 83
        },
        {
            id: 'civic-responsibility-teens-85',
            title: 'Teen Exchange Story',
            description: 'Teen meets student from another country. Should she share cultures? → Yes. 🌐',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-85'] || false,
            path: '/student/civic-responsibility/teens/teen-exchange-story',
            index: 84
        },
        {
            id: 'civic-responsibility-teens-86',
            title: 'Debate: One World?',
            description: 'Is the world one family? → Yes. 🏆',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-86'] || false,
            path: '/student/civic-responsibility/teens/debate-one-world',
            index: 85
        },
        {
            id: 'civic-responsibility-teens-87',
            title: 'Journal of Global Values',
            description: 'Write: "One way I can act like a global citizen is ___." ✍️',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-87'] || false,
            path: '/student/civic-responsibility/teens/journal-of-global-values',
            index: 86
        },
        {
            id: 'civic-responsibility-teens-88',
            title: 'Simulation: Global Project',
            description: 'Teens join online project. Options: Collaborate / Ignore / Mock. Correct = Collaborate. 💻',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-88'] || false,
            path: '/student/civic-responsibility/teens/simulation-global-project',
            index: 87
        },
        {
            id: 'civic-responsibility-teens-89',
            title: 'Reflex Teen Awareness',
            description: 'Tap 🌈 for "Cultural Respect," ❌ for "Cultural Hate." → Tap 🌈. ⚡',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-89'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-awareness',
            index: 88
        },
        {
            id: 'civic-responsibility-teens-90',
            title: 'Badge: Global Teen',
            description: 'Complete 5 global citizen acts to earn your badge. 🏅',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            isBadgeGame: true,
            badgeName: 'Badge: Global Teen',
            badgeImage: '/badges/civic-responsibility/teens/badge-global-teen.png',
            completed: gameCompletionStatus['civic-responsibility-teens-90'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/badge-global-teen',
            index: 89
        },
        // Games 91-100: Civic Action & Leadership
        {
            id: 'civic-responsibility-teens-91',
            title: 'Student Council Story',
            description: 'Teen elected as class rep. Should she serve all or only friends? → Serve all. 👥',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-91'] || false,
            path: '/student/civic-responsibility/teens/student-council-story',
            index: 90
        },
        {
            id: 'civic-responsibility-teens-92',
            title: 'Quiz on Leadership',
            description: 'A good leader is? (a) Fair, (b) Bossy). Correct = Fair. 🎯',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-92'] || false,
            path: '/student/civic-responsibility/teens/quiz-on-leadership',
            index: 91
        },
        {
            id: 'civic-responsibility-teens-93',
            title: 'Reflex Teen Leader',
            description: 'Tap 👂 for "Listen to Team," ❌ for "Ignore Team." → Tap 👂. ⚡',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-93'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-leader',
            index: 92
        },
        {
            id: 'civic-responsibility-teens-94',
            title: 'Puzzle: Leader Traits',
            description: 'Match "Honesty → 🤝 Trust, Courage -✨ Inspire, Respect → ❤️ Loyalty." ✨',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-94'] || false,
            path: '/student/civic-responsibility/teens/puzzle-leader-traits',
            index: 93
        },
        {
            id: 'civic-responsibility-teens-95',
            title: 'Protest Story',
            description: 'Students want safer roads. Should they protest violently or petition peacefully? → Petition peacefully. 🕊️',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-95'] || false,
            path: '/student/civic-responsibility/teens/protest-story',
            index: 94
        },
        {
            id: 'civic-responsibility-teens-96',
            title: 'Debate: Youth Leaders?',
            description: 'Can teens lead big change? → Yes. 🏆',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-96'] || false,
            path: '/student/civic-responsibility/teens/debate-youth-leaders',
            index: 95
        },
        {
            id: 'civic-responsibility-teens-97',
            title: 'Journal of Leadership',
            description: 'Write: "One leadership quality I have is ___." ✍️',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-97'] || false,
            path: '/student/civic-responsibility/teens/journal-of-leadership',
            index: 96
        },
        {
            id: 'civic-responsibility-teens-98',
            title: 'Simulation: Teen Civic Project',
            description: 'Teen team runs campaign. Options: Plan + Act / Waste time / Quit. Correct = Plan + Act. 📋',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-98'] || false,
            path: '/student/civic-responsibility/teens/simulation-teen-civic-project',
            index: 97
        },
        {
            id: 'civic-responsibility-teens-99',
            title: 'Reflex Teen Civic Duty',
            description: 'Tap 🌟 for "Lead With Respect," ❌ for "Lead With Fear." → Tap 🌟. ⚡',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-99'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-civic-duty',
            index: 98
        },
        {
            id: 'civic-responsibility-teens-100',
            title: 'Badge: Civic Leader Teen',
            description: 'Complete 5 civic leadership activities to earn your badge. 🏅',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            isBadgeGame: true,
            badgeName: 'Badge: Civic Leader Teen',
            badgeImage: '/badges/civic-responsibility/teens/badge-civic-leader-teen.png',
            completed: gameCompletionStatus['civic-responsibility-teens-100'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/badge-civic-leader-teen',
            index: 99
        }
    ];

    return crgcGamesTeens;
};
