import {
  Heart,
  Users,
  Globe,
  Target,
  Award,
  BookOpen,
  Zap,
  Brain,
  Sparkles,
  Handshake,
  School,
  Medal,
  IndianRupee,
  MessageCircle,
  Monitor,
  Puzzle,
  Zap as Lightning,
  Droplets as Water,
  Gift,
  ShoppingCart as Cart,
  HeartPulse,
  Brain as BrainIcon,
  Eye as EyeIcon,
  Ear as EarIcon,
  Footprints as FootprintsIcon,
  Medal as MedalIcon,
  BookOpen as BookOpenIcon,
  Smartphone as SmartphoneIcon,
  Monitor as MonitorIcon,
  Radio as RadioIcon,
  Speaker as SpeakerIcon,
  Mic as MicIcon,
  Camera as CameraIcon,
  Droplets as DropletsIcon,
} from "lucide-react";
import buildIds from "../buildGameIds";

export const crgcGameIdsTeens = buildIds("civic-responsibility", "teens");

export const getCrgcTeensGames = (gameCompletionStatus) => {
    const crgcGamesTeens = [
        {
            id: 'civic-responsibility-teens-1',
            title: 'Stranger Story',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-1'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/stranger-story',
            index: 0
        },
        {
            id: 'civic-responsibility-teens-2',
            title: 'Quiz on Compassion',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-2'] || false,
            path: '/student/civic-responsibility/teens/quiz-on-compassion',
            index: 1
        },
        {
            id: 'civic-responsibility-teens-3',
            title: 'Reflex Teen Compassion',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-3'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-compassion',
            index: 2
        },
        {
            id: 'civic-responsibility-teens-4',
            title: 'Puzzle: Kind Acts',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-4'] || false,
            path: '/student/civic-responsibility/teens/puzzle-kind-acts',
            index: 3
        },
        {
            id: 'civic-responsibility-teens-5',
            title: 'Refugee Story',
            icon: <Globe className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-5'] || false,
            path: '/student/civic-responsibility/teens/refugee-story',
            index: 4
        },
        {
            id: 'civic-responsibility-teens-6',
            title: 'Debate: Kindness Wins?',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-6'] || false,
            path: '/student/civic-responsibility/teens/debate-kindness',
            index: 5
        },
        {
            id: 'civic-responsibility-teens-7',
            title: 'Journal of Compassion',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-7'] || false,
            path: '/student/civic-responsibility/teens/journal-of-compassion',
            index: 6
        },
        {
            id: 'civic-responsibility-teens-8',
            title: 'Simulation: Hospital Visit',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-8'] || false,
            path: '/student/civic-responsibility/teens/simulation-hospital-visit',
            index: 7
        },
        {
            id: 'civic-responsibility-teens-9',
            title: 'Reflex: Global Empathy',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-9'] || false,
            path: '/student/civic-responsibility/teens/reflex-global-empathy',
            index: 8
        },
        {
            id: 'civic-responsibility-teens-10',
            title: 'Badge: Compassion Leader',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-10'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/badge-compassion-leader',
            index: 9
        },
        // Games 11-20: Respect & Inclusion
        {
            id: 'civic-responsibility-teens-11',
            title: 'Cultural Story',
            icon: <Handshake className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-11'] || false,
            path: '/student/civic-responsibility/teens/cultural-story',
            index: 10
        },
        {
            id: 'civic-responsibility-teens-12',
            title: 'Quiz on Inclusion',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-12'] || false,
            path: '/student/civic-responsibility/teens/quiz-on-inclusion',
            index: 11
        },
        {
            id: 'civic-responsibility-teens-13',
            title: 'Reflex Teen Respect',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-13'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-respect',
            index: 12
        },
        {
            id: 'civic-responsibility-teens-14',
            title: 'Puzzle: Inclusion Acts',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-14'] || false,
            path: '/student/civic-responsibility/teens/puzzle-inclusion-acts',
            index: 13
        },
        {
            id: 'civic-responsibility-teens-15',
            title: 'Religion Story',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-15'] || false,
            path: '/student/civic-responsibility/teens/religion-story',
            index: 14
        },
        {
            id: 'civic-responsibility-teens-16',
            title: 'Debate: Equality for All?',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-16'] || false,
            path: '/student/civic-responsibility/teens/debate-equality',
            index: 15
        },
        {
            id: 'civic-responsibility-teens-17',
            title: 'Journal of Inclusion',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-17'] || false,
            path: '/student/civic-responsibility/teens/journal-of-inclusion',
            index: 16
        },
        {
            id: 'civic-responsibility-teens-18',
            title: 'Simulation: School Event',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-18'] || false,
            path: '/student/civic-responsibility/teens/simulation-school-event',
            index: 17
        },
        {
            id: 'civic-responsibility-teens-19',
            title: 'Reflex Teen Inclusion',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-19'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-inclusion',
            index: 18
        },
        {
            id: 'civic-responsibility-teens-20',
            title: 'Badge: Inclusion Leader',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-20'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/badge-inclusion-leader',
            index: 19
        },
        // Games 21-30: Gender Equality & Rights
        {
            id: 'civic-responsibility-teens-21',
            title: 'Education Story',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-21'] || false,
            path: '/student/civic-responsibility/teens/education-story',
            index: 20
        },
        {
            id: 'civic-responsibility-teens-22',
            title: 'Quiz on Teen Rights',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-22'] || false,
            path: '/student/civic-responsibility/teens/quiz-on-teen-rights',
            index: 21
        },
        {
            id: 'civic-responsibility-teens-23',
            title: 'Reflex Teen Rights',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-23'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-rights',
            index: 22
        },
        {
            id: 'civic-responsibility-teens-24',
            title: 'Puzzle: Gender Barriers',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-24'] || false,
            path: '/student/civic-responsibility/teens/puzzle-gender-barriers',
            index: 23
        },
        {
            id: 'civic-responsibility-teens-25',
            title: 'Sports Story',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['civic-responsibility-teens-25'] || false,
            path: '/student/civic-responsibility/teens/sports-story',
            index: 24
        },
        {
            id: 'civic-responsibility-teens-26',
            title: 'Debate: Girls as Leaders?',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-26'] || false,
            path: '/student/civic-responsibility/teens/debate-girls-leaders',
            index: 25
        },
        {
            id: 'civic-responsibility-teens-27',
            title: 'Journal of Teen Equality',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-27'] || false,
            path: '/student/civic-responsibility/teens/journal-of-teen-equality',
            index: 26
        },
        {
            id: 'civic-responsibility-teens-28',
            title: 'Simulation: Teen Choices',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-28'] || false,
            path: '/student/civic-responsibility/teens/simulation-teen-choices',
            index: 27
        },
        {
            id: 'civic-responsibility-teens-29',
            title: 'Reflex Gender Alert',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-29'] || false,
            path: '/student/civic-responsibility/teens/reflex-gender-alert',
            index: 28
        },
        {
            id: 'civic-responsibility-teens-30',
            title: 'Badge: Gender Rights Teen',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-30'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/badge-gender-rights-teen',
            index: 29
        },
        // Games 31-40: Bullying Prevention & Peer Support
        {
            id: 'civic-responsibility-teens-31',
            title: 'Cyberbully Story',
            icon: <Monitor className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-31'] || false,
            path: '/student/civic-responsibility/teens/cyberbully-story',
            index: 30
        },
        {
            id: 'civic-responsibility-teens-32',
            title: 'Quiz on Cyberbullying',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-32'] || false,
            path: '/student/civic-responsibility/teens/quiz-on-cyberbullying',
            index: 31
        },
        {
            id: 'civic-responsibility-teens-33',
            title: 'Reflex Teen Bully Alert',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-33'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-bully-alert',
            index: 32
        },
        {
            id: 'civic-responsibility-teens-34',
            title: 'Puzzle: Peer Support',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-34'] || false,
            path: '/student/civic-responsibility/teens/puzzle-peer-support',
            index: 33
        },
        {
            id: 'civic-responsibility-teens-35',
            title: 'School Story',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-35'] || false,
            path: '/student/civic-responsibility/teens/school-story',
            index: 34
        },
        {
            id: 'civic-responsibility-teens-36',
            title: 'Debate: Ignore or Report?',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-36'] || false,
            path: '/student/civic-responsibility/teens/debate-ignore-or-report',
            index: 35
        },
        {
            id: 'civic-responsibility-teens-37',
            title: 'Journal of Peer Support',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-37'] || false,
            path: '/student/civic-responsibility/teens/journal-of-peer-support',
            index: 36
        },
        {
            id: 'civic-responsibility-teens-38',
            title: 'Simulation: Teen Bully Scene',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-38'] || false,
            path: '/student/civic-responsibility/teens/simulation-teen-bully-scene',
            index: 37
        },
        {
            id: 'civic-responsibility-teens-39',
            title: 'Reflex Teen Courage',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-39'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-courage',
            index: 38
        },
        {
            id: 'civic-responsibility-teens-40',
            title: 'Badge: Peer Protector Teen',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-40'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/badge-peer-protector-teen',
            index: 39
        },
        // Games 41-50: Emotional Intelligence & Conflict Resolution
        {
            id: 'civic-responsibility-teens-41',
            title: 'Disagreement Story',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-41'] || false,
            path: '/student/civic-responsibility/teens/disagreement-story',
            index: 40
        },
        {
            id: 'civic-responsibility-teens-42',
            title: 'Quiz on Conflict',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-42'] || false,
            path: '/student/civic-responsibility/teens/quiz-on-conflict',
            index: 41
        },
        {
            id: 'civic-responsibility-teens-43',
            title: 'Reflex Conflict Check',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-43'] || false,
            path: '/student/civic-responsibility/teens/reflex-conflict-check',
            index: 42
        },
        {
            id: 'civic-responsibility-teens-44',
            title: 'Puzzle: Conflict Solutions',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-44'] || false,
            path: '/student/civic-responsibility/teens/puzzle-conflict-solutions',
            index: 43
        },
        {
            id: 'civic-responsibility-teens-45',
            title: 'Friendship Story',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-45'] || false,
            path: '/student/civic-responsibility/teens/friendship-story',
            index: 44
        },
        {
            id: 'civic-responsibility-teens-46',
            title: 'Debate: Apology = Weakness?',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-46'] || false,
            path: '/student/civic-responsibility/teens/debate-apology-strength',
            index: 45
        },
        {
            id: 'civic-responsibility-teens-47',
            title: 'Journal of Conflict',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-47'] || false,
            path: '/student/civic-responsibility/teens/journal-of-conflict',
            index: 46
        },
        {
            id: 'civic-responsibility-teens-48',
            title: 'Simulation: Teen Fight',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-48'] || false,
            path: '/student/civic-responsibility/teens/simulation-teen-fight',
            index: 47
        },
        {
            id: 'civic-responsibility-teens-49',
            title: 'Reflex Teen Peace',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-49'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-peace',
            index: 48
        },
        {
            id: 'civic-responsibility-teens-50',
            title: 'Badge: Peace Maker Teen',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['civic-responsibility-teens-50'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/badge-peace-maker-teen',
            index: 49
        },
        // Games 51-60: Community Service & Volunteering
        {
            id: 'civic-responsibility-teens-51',
            title: 'Blood Donation Camp Story',
            icon: <HeartPulse className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-51'] || false,
            path: '/student/civic-responsibility/teens/blood-donation-camp-story',
            index: 50
        },
        {
            id: 'civic-responsibility-teens-52',
            title: 'Quiz on Volunteering',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-52'] || false,
            path: '/student/civic-responsibility/teens/quiz-on-volunteering',
            index: 51
        },
        {
            id: 'civic-responsibility-teens-53',
            title: 'Reflex Teen Volunteer',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-53'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-volunteer',
            index: 52
        },
        {
            id: 'civic-responsibility-teens-54',
            title: 'Puzzle: Volunteer Areas',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-54'] || false,
            path: '/student/civic-responsibility/teens/puzzle-volunteer-areas',
            index: 53
        },
        {
            id: 'civic-responsibility-teens-55',
            title: 'Fundraising Story',
            icon: <Gift className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-55'] || false,
            path: '/student/civic-responsibility/teens/fundraising-story',
            index: 54
        },
        {
            id: 'civic-responsibility-teens-56',
            title: 'Debate: Service = Waste?',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '6 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-56'] || false,
            path: '/student/civic-responsibility/teens/debate-service-waste',
            index: 55
        },
        {
            id: 'civic-responsibility-teens-57',
            title: 'Journal of Teen Service',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-57'] || false,
            path: '/student/civic-responsibility/teens/journal-of-teen-service',
            index: 56
        },
        {
            id: 'civic-responsibility-teens-58',
            title: 'Simulation: Clean-Up Drive',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-58'] || false,
            path: '/student/civic-responsibility/teens/simulation-clean-up-drive',
            index: 57
        },
        {
            id: 'civic-responsibility-teens-59',
            title: 'Reflex Service Mindset',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-59'] || false,
            path: '/student/civic-responsibility/teens/reflex-service-mindset',
            index: 58
        },
        {
            id: 'civic-responsibility-teens-60',
            title: 'Badge: Volunteer Leader Teen',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-60'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/badge-volunteer-leader-teen',
            index: 59
        },
        // Games 61-70: Human Rights & Social Justice
        {
            id: 'civic-responsibility-teens-61',
            title: 'Education Story',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-61'] || false,
            path: '/student/civic-responsibility/teens/education-story-justice',
            index: 60
        },
        {
            id: 'civic-responsibility-teens-62',
            title: 'Quiz on Social Justice',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-62'] || false,
            path: '/student/civic-responsibility/teens/quiz-on-social-justice',
            index: 61
        },
        {
            id: 'civic-responsibility-teens-63',
            title: 'Reflex Teen Justice',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-63'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-justice',
            index: 62
        },
        {
            id: 'civic-responsibility-teens-64',
            title: 'Puzzle: Justice Heroes',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-64'] || false,
            path: '/student/civic-responsibility/teens/puzzle-justice-heroes',
            index: 63
        },
        {
            id: 'civic-responsibility-teens-65',
            title: 'Wage Story',
            icon: <IndianRupee className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-65'] || false,
            path: '/student/civic-responsibility/teens/wage-story',
            index: 64
        },
        {
            id: 'civic-responsibility-teens-66',
            title: 'Debate: All Humans Equal?',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '6 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-66'] || false,
            path: '/student/civic-responsibility/teens/debate-all-humans-equal',
            index: 65
        },
        {
            id: 'civic-responsibility-teens-67',
            title: 'Journal of Justice',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-67'] || false,
            path: '/student/civic-responsibility/teens/journal-of-justice',
            index: 66
        },
        {
            id: 'civic-responsibility-teens-68',
            title: 'Simulation: Teen Justice Act',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-68'] || false,
            path: '/student/civic-responsibility/teens/simulation-teen-justice-act',
            index: 67
        },
        {
            id: 'civic-responsibility-teens-69',
            title: 'Reflex Teen Rights',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-69'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-rights-2',
            index: 68
        },
        {
            id: 'civic-responsibility-teens-70',
            title: 'Badge: Justice Teen',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-70'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/badge-justice-teen',
            index: 69
        },
        // Games 71-80: Law, Duties & Civic Responsibility
        {
            id: 'civic-responsibility-teens-71',
            title: 'Constitution Story',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-71'] || false,
            path: '/student/civic-responsibility/teens/constitution-story',
            index: 70
        },
        {
            id: 'civic-responsibility-teens-72',
            title: 'Quiz on Rights & Duties',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-72'] || false,
            path: '/student/civic-responsibility/teens/quiz-on-rights-duties',
            index: 71
        },
        {
            id: 'civic-responsibility-teens-73',
            title: 'Reflex Teen Law',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-73'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-law',
            index: 72
        },
        {
            id: 'civic-responsibility-teens-74',
            title: 'Puzzle: Match Civic Roles',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-74'] || false,
            path: '/student/civic-responsibility/teens/puzzle-match-civic-roles',
            index: 73
        },
        {
            id: 'civic-responsibility-teens-75',
            title: 'Voter Story',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['civic-responsibility-teens-75'] || false,
            path: '/student/civic-responsibility/teens/voter-story',
            index: 74
        },
        {
            id: 'civic-responsibility-teens-76',
            title: 'Debate: Rights vs Duties',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-76'] || false,
            path: '/student/civic-responsibility/teens/debate-rights-vs-duties',
            index: 75
        },
        {
            id: 'civic-responsibility-teens-77',
            title: 'Journal of Law Awareness',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-77'] || false,
            path: '/student/civic-responsibility/teens/journal-of-law-awareness',
            index: 76
        },
        {
            id: 'civic-responsibility-teens-78',
            title: 'Simulation: Teen Citizen',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-78'] || false,
            path: '/student/civic-responsibility/teens/simulation-teen-citizen',
            index: 77
        },
        {
            id: 'civic-responsibility-teens-79',
            title: 'Reflex Teen Duty',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-79'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-duty',
            index: 78
        },
        {
            id: 'civic-responsibility-teens-80',
            title: 'Badge: Responsible Citizen Teen',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-80'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/badge-responsible-citizen-teen',
            index: 79
        },
        // Games 81-90: Global Citizenship & Cultural Awareness
        {
            id: 'civic-responsibility-teens-81',
            title: 'Climate Story',
            icon: <Globe className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-81'] || false,
            path: '/student/civic-responsibility/teens/climate-story',
            index: 80
        },
        {
            id: 'civic-responsibility-teens-82',
            title: 'Quiz on Global Citizenship',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-82'] || false,
            path: '/student/civic-responsibility/teens/quiz-on-global-citizenship',
            index: 81
        },
        {
            id: 'civic-responsibility-teens-83',
            title: 'Reflex Teen Global',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-83'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-global',
            index: 82
        },
        {
            id: 'civic-responsibility-teens-84',
            title: 'Puzzle: Global Leaders',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-84'] || false,
            path: '/student/civic-responsibility/teens/puzzle-global-leaders',
            index: 83
        },
        {
            id: 'civic-responsibility-teens-85',
            title: 'Teen Exchange Story',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-85'] || false,
            path: '/student/civic-responsibility/teens/teen-exchange-story',
            index: 84
        },
        {
            id: 'civic-responsibility-teens-86',
            title: 'Debate: One World?',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-86'] || false,
            path: '/student/civic-responsibility/teens/debate-one-world',
            index: 85
        },
        {
            id: 'civic-responsibility-teens-87',
            title: 'Journal of Global Values',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-87'] || false,
            path: '/student/civic-responsibility/teens/journal-of-global-values',
            index: 86
        },
        {
            id: 'civic-responsibility-teens-88',
            title: 'Simulation: Global Project',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-88'] || false,
            path: '/student/civic-responsibility/teens/simulation-global-project',
            index: 87
        },
        {
            id: 'civic-responsibility-teens-89',
            title: 'Reflex Teen Awareness',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-89'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-awareness',
            index: 88
        },
        {
            id: 'civic-responsibility-teens-90',
            title: 'Badge: Global Teen',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-90'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/badge-global-teen',
            index: 89
        },
        // Games 91-100: Civic Action & Leadership
        {
            id: 'civic-responsibility-teens-91',
            title: 'Student Council Story',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-91'] || false,
            path: '/student/civic-responsibility/teens/student-council-story',
            index: 90
        },
        {
            id: 'civic-responsibility-teens-92',
            title: 'Quiz on Leadership',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-92'] || false,
            path: '/student/civic-responsibility/teens/quiz-on-leadership',
            index: 91
        },
        {
            id: 'civic-responsibility-teens-93',
            title: 'Reflex Teen Leader',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-93'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-leader',
            index: 92
        },
        {
            id: 'civic-responsibility-teens-94',
            title: 'Puzzle: Leader Traits',
            icon: <Puzzle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-94'] || false,
            path: '/student/civic-responsibility/teens/puzzle-leader-traits',
            index: 93
        },
        {
            id: 'civic-responsibility-teens-95',
            title: 'Protest Story',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-95'] || false,
            path: '/student/civic-responsibility/teens/protest-story',
            index: 94
        },
        {
            id: 'civic-responsibility-teens-96',
            title: 'Debate: Youth Leaders?',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-96'] || false,
            path: '/student/civic-responsibility/teens/debate-youth-leaders',
            index: 95
        },
        {
            id: 'civic-responsibility-teens-97',
            title: 'Journal of Leadership',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-97'] || false,
            path: '/student/civic-responsibility/teens/journal-of-leadership',
            index: 96
        },
        {
            id: 'civic-responsibility-teens-98',
            title: 'Simulation: Teen Civic Project',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-98'] || false,
            path: '/student/civic-responsibility/teens/simulation-teen-civic-project',
            index: 97
        },
        {
            id: 'civic-responsibility-teens-99',
            title: 'Reflex Teen Civic Duty',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Hard',
            duration: '2 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-99'] || false,
            path: '/student/civic-responsibility/teens/reflex-teen-civic-duty',
            index: 98
        },
        {
            id: 'civic-responsibility-teens-100',
            title: 'Badge: Civic Leader Teen',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['civic-responsibility-teens-100'] || false,
            isSpecial: true,
            path: '/student/civic-responsibility/teens/badge-civic-leader-teen',
            index: 99
        }
    ];

    return crgcGamesTeens;
};
