import {
    Users,
    Zap,
    Shield,
    Target,
    BookOpen,
    GraduationCap,
    ShoppingCart,
    MessageSquare,
    Award,
    Palette,
  } from "lucide-react";
import buildIds from "../buildGameIds";


export const moralGamesKidsIds = buildIds("moral", "kids")

export const getMoralKidsGames = (gameCompletionStatus)=> {
    const moralGamesKid = [
        {
          id: "moral-kids-1",
          title: "Lost Pencil Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-1"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/lost-pencil-story",
          index: 0,
        },
        {
          id: "moral-kids-2",
          title: "Homework Quiz",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-2"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/homework-quiz",
          index: 1,
        },
        {
          id: "moral-kids-3",
          title: "Truth Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-3"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/truth-reflex",
          index: 2,
        },
        {
          id: "moral-kids-4",
          title: "Puzzle of Trust",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-4"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/puzzle-of-trust",
          index: 3,
        },
        {
          id: "moral-kids-5",
          title: "Cheating Story",
          icon: <Shield className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-5"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/cheating-story",
          index: 4,
        },
        {
          id: "moral-kids-6",
          title: "Poster of Honesty",
          icon: <Palette className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-6"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/poster-of-honesty",
          index: 5,
        },
        {
          id: "moral-kids-7",
          title: "Journal of Truth",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-7"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/journal-of-truth",
          index: 6,
        },
        {
          id: "moral-kids-8",
          title: "Candy Shop Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-8"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/candy-shop-story",
          index: 7,
        },
        {
          id: "moral-kids-9",
          title: "Reflex Quick Choice",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-9"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/reflex-quick-choice",
          index: 8,
        },
        {
          id: "moral-kids-10",
          title: "Badge: Truthful Kid",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-10"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/badge-truthful-kid",
          index: 9,
        },
        {
          id: "moral-kids-11",
          title: "Respect Elders Story",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-11"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/respect-elders-story",
          index: 10,
        },
        {
          id: "moral-kids-12",
          title: "Polite Words Quiz",
          icon: <MessageSquare className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-12"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/polite-words-quiz2",
          index: 11,
        },
        {
          id: "moral-kids-13",
          title: "Reflex Respect",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-13"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/reflex-respect",
          index: 12,
        },
        {
          id: "moral-kids-14",
          title: "Puzzle: Respect Match",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-14"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/puzzle-respect-match",
          index: 13,
        },
        {
          id: "moral-kids-15",
          title: "Teacher Greeting Story",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-15"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/teacher-greeting-story",
          index: 14,
        },
        {
          id: "moral-kids-16",
          title: "Gratitude Poster",
          icon: <Palette className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-16"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/gratitude-poster",
          index: 15,
        },
        {
          id: "moral-kids-17",
          title: "Journal of Gratitude",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-17"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/journal-of-gratitude",
          index: 16,
        },
        {
          id: "moral-kids-18",
          title: "Playground Respect Story",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-18"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/playground-respect-story",
          index: 17,
        },
        {
          id: "moral-kids-19",
          title: "Reflex Help",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-19"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/reflex-help",
          index: 18,
        },
        {
          id: "moral-kids-20",
          title: "Badge: Respect Kid",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-20"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/badge-respect-kid",
          index: 19,
        },
        {
          id: "moral-kids-21",
          title: "Sharing Story",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-21"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/sharing-story",
          index: 20,
        },
        {
          id: "moral-kids-22",
          title: "Kind or Rude Quiz",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-22"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/kind-or-rude-quiz",
          index: 21,
        },
        {
          id: "moral-kids-23",
          title: "Reflex Kindness",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-23"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/reflex-kindnesss",
          index: 22,
        },
        {
          id: "moral-kids-24",
          title: "Puzzle: Acts of Kindness",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-kids-24"] || false,
          isSpecial: true,
          path: "/student/moral-values/kids/puzzle-acts-of-kindness",
          index: 23,
        },
            {
            id: "moral-kids-25",
            title: "Animal Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus["moral-kids-25"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/animal-storyy",
            index: 24,
            },
            {
            id: "moral-kids-26",
            title: "Poster Task: Kindness",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "10-15 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-26"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/poster-kindness",
            index: 25,
            },
            {
            id: "moral-kids-27",
            title: "Journal of Kindness",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-27"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/journal-of-kindness",
            index: 26,
            },
            {
            id: "moral-kids-28",
            title: "Lost Ball Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-28"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/lost-ball-story",
            index: 27,
            },
            {
            id: "moral-kids-29",
            title: "Reflex Help Fast",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "4-6 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-29"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/reflex-help-fast",
            index: 28,
            },
            {
            id: "moral-kids-30",
            title: "Badge: Kind Kid",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "N/A",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-30"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/badge-kind-kidd",
            index: 29,
            },
            {
            id: "moral-kids-31",
            title: "Homework Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-31"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/homework-storyy",
            index: 30,
            },
            {
            id: "moral-kids-32",
            title: "Quiz on Responsibility",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-32"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/quiz-responsibility",
            index: 31,
            },
            {
            id: "moral-kids-33",
            title: "Reflex Discipline",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "4-6 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-33"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/reflex-discipline",
            index: 32,
            },
            {
            id: "moral-kids-34",
            title: "Puzzle of Duties",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "6-8 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-34"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/puzzle-of-duties",
            index: 33,
            },
            {
            id: "moral-kids-35",
            title: "Chores Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-35"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/chores-story",
            index: 34,
            },
            {
            id: "moral-kids-36",
            title: "Poster Task: Discipline",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "10-15 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-36"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/poster-discipline",
            index: 35,
            },
            {
            id: "moral-kids-37",
            title: "Journal of Duty",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-37"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/journal-duty",
            index: 36,
            },
            {
            id: "moral-kids-38",
            title: "Playground Rules Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-38"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/playground-rules-story",
            index: 37,
            },
            {
            id: "moral-kids-39",
            title: "Reflex Daily Habits",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "4-6 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-39"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/reflex-daily-habits",
            index: 38,
            },
            {
            id: "moral-kids-40",
            title: "Badge: Responsible Kid",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "N/A",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-40"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/badge-responsible-kidd",
            index: 39,
            },
            {
            id: "moral-kids-41",
            title: "Playground Game Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-41"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/playground-game-story",
            index: 40,
            },
            {
            id: "moral-kids-42",
            title: "Fairness Quiz",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-42"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/fairness-quiz",
            index: 41,
            },
            {
            id: "moral-kids-43",
            title: "Reflex Fair Play",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "4-6 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-43"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/reflex-fair-play",
            index: 42,
            },
            {
            id: "moral-kids-44",
            title: "Puzzle of Fairness",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "6-8 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-44"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/puzzle-of-fairness",
            index: 43,
            },
            {
            id: "moral-kids-45",
            title: "Lost Wallet Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-45"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/lost-wallet-story",
            index: 44,
            },
            {
            id: "moral-kids-46",
            title: "Poster Task: Fairness",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "10-15 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-46"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/poster-fairness",
            index: 45,
            },
            {
            id: "moral-kids-47",
            title: "Journal of Justice",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-47"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/journal-justice",
            index: 46,
            },
            {
            id: "moral-kids-48",
            title: "Sharing Sweets Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-48"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/sharing-sweets-story",
            index: 47,
            },
            {
            id: "moral-kids-49",
            title: "Reflex Equal Share",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "4-6 min",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-49"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/reflex-equal-share",
            index: 48,
            },
            {
            id: "moral-kids-50",
            title: "Badge: Fair Kid",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "N/A",
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus["moral-kids-50"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/badge-fair-kid",
            index: 49,
            },
            {
            id: "moral-kids-51",
            title: "Dark Room Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-51"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/dark-room-story",
            index: 50,
            },
            {
            id: "moral-kids-52",
            title: "Courage Quiz",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-52"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/courage-quiz",
            index: 51,
            },
            {
            id: "moral-kids-53",
            title: "Reflex Brave vs Scared",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "4-6 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-53"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/reflex-brave-scared",
            index: 52,
            },
            {
            id: "moral-kids-54",
            title: "Puzzle of Courage",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "6-8 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-54"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/puzzle-courage",
            index: 53,
            },
            {
            id: "moral-kids-55",
            title: "Confess Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-55"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/confess-story",
            index: 54,
            },
            {
            id: "moral-kids-56",
            title: "Poster Task: Courage",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "10-15 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-56"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/poster-courage",
            index: 55,
            },
            {
            id: "moral-kids-57",
            title: "Journal of Courage",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-57"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/journal-courage",
            index: 56,
            },
            {
            id: "moral-kids-58",
            title: "Bully Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-58"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/bully-story1",
            index: 57,
            },
            {
            id: "moral-kids-59",
            title: "Reflex Brave Symbol",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "4-6 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-59"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/reflex-brave-symbol",
            index: 58,
            },
            {
            id: "moral-kids-60",
            title: "Badge: Brave Kid",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "N/A",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-60"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/badge-brave-kid",
            index: 59,
            },
            {
            id: "moral-kids-61",
            title: "Football Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-61"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/football-story",
            index: 60,
            },
            {
            id: "moral-kids-62",
            title: "Quiz on Cooperation",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-62"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/quiz-cooperation",
            index: 61,
            },
            {
            id: "moral-kids-63",
            title: "Reflex Team Acts",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "4-6 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-63"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/reflex-team-acts",
            index: 62,
            },
            {
            id: "moral-kids-64",
            title: "Puzzle of Team Roles",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "6-8 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-64"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/puzzle-team-roles",
            index: 63,
            },
            {
            id: "moral-kids-65",
            title: "Classroom Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-65"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/classroom-story1",
            index: 64,
            },
            {
            id: "moral-kids-66",
            title: "Poster: Team Spirit",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "10-15 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-66"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/poster-team-spirit",
            index: 65,
            },
            {
            id: "moral-kids-67",
            title: "Journal of Teamwork",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-67"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/journal-teamwork",
            index: 66,
            },
            {
            id: "moral-kids-68",
            title: "Playground Sharing Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-68"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/playground-sharing-story",
            index: 67,
            },
            {
            id: "moral-kids-69",
            title: "Reflex Cooperation",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "4-6 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-69"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/reflex-cooperation",
            index: 68,
            },
            {
            id: "moral-kids-70",
            title: "Badge: Team Kid",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "N/A",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-70"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/badge-team-kid",
            index: 69,
            },
            {
            id: "moral-kids-71",
            title: "Old Lady Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-71"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/old-lady-story",
            index: 70,
            },
            {
            id: "moral-kids-72",
            title: "Quiz on Service",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-72"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/quiz-service",
            index: 71,
            },
            {
            id: "moral-kids-73",
            title: "Reflex Service",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "4-6 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-73"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/reflex-service",
            index: 72,
            },
            {
            id: "moral-kids-74",
            title: "Puzzle: Service Match",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "6-8 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-74"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/puzzle-service-match",
            index: 73,
            },
            {
            id: "moral-kids-75",
            title: "School Clean-Up Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus["moral-kids-75"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/school-cleanup-story",
            index: 74,
            },
            {
            id: "moral-kids-76",
            title: "Poster: Helping Hands",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "10-15 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-76"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/poster-helping-hands",
            index: 75,
            },
            {
            id: "moral-kids-77",
            title: "Journal of Service",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-77"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/journal-service",
            index: 76,
            },
            {
            id: "moral-kids-78",
            title: "Animal Care Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-78"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/animal-care-story",
            index: 77,
            },
            {
            id: "moral-kids-79",
            title: "Reflex Quick Help",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "4-6 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-79"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/reflex-quick-help",
            index: 78,
            },
            {
            id: "moral-kids-80",
            title: "Badge: Service Kid",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "N/A",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-80"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/badge-service-kid",
            index: 79,
            },
            {
            id: "moral-kids-81",
            title: "Playground Fight Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-81"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/playground-fight-story",
            index: 80,
            },
            {
            id: "moral-kids-82",
            title: "Quiz on Peace",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-82"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/quiz-peace",
            index: 81,
            },
            {
            id: "moral-kids-83",
            title: "Reflex Peace Acts",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "4-6 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-83"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/reflex-peace-acts",
            index: 82,
            },
            {
            id: "moral-kids-84",
            title: "Puzzle: Peace Match",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "6-8 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-84"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/puzzle-peace-match",
            index: 83,
            },
            {
            id: "moral-kids-85",
            title: "Broken Toy Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-85"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/broken-toy-story",
            index: 84,
            },
            {
            id: "moral-kids-86",
            title: "Poster: Choose Peace",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "10-15 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-86"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/poster-choose-peace",
            index: 85,
            },
            {
            id: "moral-kids-87",
            title: "Journal of Peace",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-87"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/journal-peace",
            index: 86,
            },
            {
            id: "moral-kids-88",
            title: "Name Calling Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-88"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/name-calling-story",
            index: 87,
            },
            {
            id: "moral-kids-89",
            title: "Reflex Stop Fight",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "4-6 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-89"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/reflex-stop-fight",
            index: 88,
            },
            {
            id: "moral-kids-90",
            title: "Badge: Peace Kid",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "N/A",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-90"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/badge-peace-kid",
            index: 89,
            },
            {
            id: "moral-kids-91",
            title: "Candy Dilemma Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-91"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/candy-dilemma-story",
            index: 90,
            },
            {
            id: "moral-kids-92",
            title: "Quiz on Right Choice",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-92"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/quiz-right-choice",
            index: 91,
            },
            {
            id: "moral-kids-93",
            title: "Reflex Choices",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "4-6 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-93"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/reflex-choices",
            index: 92,
            },
            {
            id: "moral-kids-94",
            title: "Puzzle of Dilemmas",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "6-8 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-94"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/puzzle-dilemmas",
            index: 93,
            },
            {
            id: "moral-kids-95",
            title: "Friendâ€™s Secret Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-95"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/friends-secret-story",
            index: 94,
            },
            {
            id: "moral-kids-96",
            title: "Poster Task: Right Choice",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Medium",
            duration: "10-15 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-96"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/poster-right-choice",
            index: 95,
            },
            {
            id: "moral-kids-97",
            title: "Journal of Decisions",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-97"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/journal-decisions",
            index: 96,
            },
            {
            id: "moral-kids-98",
            title: "Cheating Offer Story",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "5-7 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-98"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/cheating-offer-story",
            index: 97,
            },
            {
            id: "moral-kids-99",
            title: "Reflex Honesty",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "4-6 min",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-99"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/reflex-honesty",
            index: 98,
            },
            {
            id: "moral-kids-100",
            title: "Badge: Right Choice Kid",
            icon: <Award className="w-6 h-6" />,
            difficulty: "Easy",
            duration: "N/A",
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus["moral-kids-100"] || false,
            isSpecial: true,
            path: "/student/moral-values/kids/badge-right-choice-kid",
            index: 99,
            },

    ];

    return moralGamesKid;
}
