import {
    Coins,
    Puzzle,
    Users,
    Zap,
    Heart,
    Shield,
    Target,
    BookOpen,
    GraduationCap,
    HandHeart,
    Eye,
    MessageSquare,
    Award,
    HelpCircle,
    Mic,
    Notebook,
    Edit3,
    Moon,
    PenTool,
    UserCheck,
  } from "lucide-react";
import buildIds from "../buildGameIds";


export const moralGamesTeenIds = buildIds("moral", "teen")

export const getMoralTeenGames = (gameCompletionStatus)=> {
    const moralGamesTeen = [
        {
          id: "moral-teen-1",
          title: "Friend's Lie Story",
          icon: <Shield className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-1"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/friend-lie-story",
          index: 0,
        },
        {
          id: "moral-teen-2",
          title: "White Lie Quiz",
          icon: <MessageSquare className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-2"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/white-lie-quiz",
          index: 1,
        },
        {
          id: "moral-teen-3",
          title: "Reflex: Spot Fake",
          icon: <Eye className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-3"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/reflex-spot-fake",
          index: 2,
        },
        {
          id: "moral-teen-4",
          title: "Puzzle of Integrity",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-4"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/puzzle-of-integrity",
          index: 3,
        },
        {
          id: "moral-teen-5",
          title: "Bribe Simulation",
          icon: <Shield className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7-9 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-5"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/bribe-simulation",
          index: 4,
        },
        {
          id: "moral-teen-6",
          title: "Debate: Lying for Friend",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "15-20 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-6"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/debate-lying-for-friend",
          index: 5,
        },
        {
          id: "moral-teen-7",
          title: "Integrity Journal",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-7"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/integrity-journal",
          index: 6,
        },
        {
          id: "moral-teen-8",
          title: "Exam Cheating Story",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-8"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/exam-cheating-story",
          index: 7,
        },
        {
          id: "moral-teen-9",
          title: "Roleplay: Truthful Leader",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-9"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/roleplay-truthful-leader",
          index: 8,
        },
        {
          id: "moral-teen-10",
          title: "Badge: Integrity Hero",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-10"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/badge-integrity-hero",
          index: 9,
        },
        {
          id: "moral-teen-11",
          title: "Debate: Obey or Question",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "15-20 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-11"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/debate-obey-or-question",
          index: 10,
        },
        {
          id: "moral-teen-12",
          title: "Gratitude Story",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-12"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/gratitude-story",
          index: 11,
        },
        {
          id: "moral-teen-13",
          title: "Reflex: Politeness",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-13"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/reflex-politeness",
          index: 12,
        },
        {
          id: "moral-teen-14",
          title: "Puzzle of Gratitude",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-14"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/puzzle-of-gratitude",
          index: 13,
        },
        {
          id: "moral-teen-15",
          title: "Service Story",
          icon: <Coins className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-15"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/service-story",
          index: 14,
        },
        {
          id: "moral-teen-16",
          title: "Respect Journal",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-16"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/respect-journal",
          index: 15,
        },
        {
          id: "moral-teen-17",
          title: "Debate: Respect Teachers",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "15-20 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-17"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/debate-respect-teachers",
          index: 16,
        },
        {
          id: "moral-teen-18",
          title: "Roleplay: Respect Leader",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-18"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/roleplay-respect-leader",
          index: 17,
        },
        {
          id: "moral-teen-19",
          title: "Reflex: Gratitude",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-19"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/reflex-gratitude",
          index: 18,
        },
        {
          id: "moral-teen-20",
          title: "Badge: Gratitude Hero",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["moral-teen-20"] || false,
          isSpecial: true,
          path: "/student/moral-values/teen/badge-gratitude-hero",
          index: 19,
        },
        {
        id: "moral-teen-21",
        title: "Empathy Story",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-21"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/empathy-story",
        index: 20,
        },
        {
        id: "moral-teen-22",
        title: "Quiz of Feelings",
        icon: <HelpCircle className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "4 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-22"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/quiz-feelings",
        index: 21,
        },
        {
        id: "moral-teen-23",
        title: "Reflex Empathy",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "3 min",
          coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-23"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-empathy",
        index: 22,
        },
        {
        id: "moral-teen-24",
        title: "Puzzle: Feelings Match",
        icon: <Puzzle className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-24"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/feelings-puzzle",
        index: 23,
        },
        {
        id: "moral-teen-25",
        title: "Roleplay: Walk in Shoes",
        icon: <Users className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6 min",
        coins: 5,
        xp: 10,
        completed: gameCompletionStatus["moral-teen-25"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/roleplay-walk-in-shoes",
        index: 24,
        },
        {
        id: "moral-teen-26",
        title: "Debate: Kindness or Strength",
        icon: <Mic className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "7 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-26"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/debate-kindness-strength",
        index: 25,
        },
        {
        id: "moral-teen-27",
        title: "Journal of Empathy",
        icon: <Notebook className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-27"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/journal-empathy1",
        index: 26,
        },
        {
        id: "moral-teen-28",
        title: "Helping Hand Story",
        icon: <HandHeart className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "4 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-28"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/helping-hand-story",
        index: 27,
        },
        {
        id: "moral-teen-29",
        title: "Reflex Comfort",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "3 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-29"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-comfort",
        index: 28,
        },
        {
        id: "moral-teen-30",
        title: "Badge: Empathy Hero",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6-8 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-30"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/badge-empathy-hero",
        index: 29,
        },
        {
        id: "moral-teen-31",
        title: "Responsibility Story",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-31"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/responsibility-story",
        index: 30,
        },
        {
        id: "moral-teen-32",
        title: "Quiz of Discipline",
        icon: <HelpCircle className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "4 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-32"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/quiz-discipline",
        index: 31,
        },
        {
        id: "moral-teen-33",
        title: "Reflex Time Management",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "3 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-33"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-time-management",
        index: 32,
        },
        {
        id: "moral-teen-34",
        title: "Puzzle of Self Control",
        icon: <Puzzle className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-34"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/puzzle-of-self-control",
        index: 33,
        },
        {
        id: "moral-teen-35",
        title: "Late Night Party Story",
        icon: <Moon className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-35"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/late-night-party-story",
        index: 34,
        },
        {
        id: "moral-teen-36",
        title: "Debate: Rules vs Freedom",
        icon: <Mic className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "7 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-36"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/debate-rules-vs-freedom",
        index: 35,
        },
        {
        id: "moral-teen-37",
        title: "Journal of Discipline",
        icon: <Notebook className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-37"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/journal-discipline",
        index: 36,
        },
        {
        id: "moral-teen-38",
        title: "Roleplay: Group Leader",
        icon: <Users className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-38"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/roleplay-group-leader",
        index: 37,
        },
        {
        id: "moral-teen-39",
        title: "Reflex Duty Check",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "3 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-39"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-duty-check",
        index: 38,
        },
        {
        id: "moral-teen-40",
        title: "Badge: Discipline Hero",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6-8 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-40"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/badge-discipline-hero",
        index: 39,
        },
        {
        id: "moral-teen-41",
        title: "Classroom Story",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-41"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/classroom-story2",
        index: 40,
        },
        {
        id: "moral-teen-42",
        title: "Justice Quiz",
        icon: <HelpCircle className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "4 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-42"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/justice-quiz",
        index: 41,
        },
        {
        id: "moral-teen-43",
        title: "Reflex Justice Symbols",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "3 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-43"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-justice-symbols",
        index: 42,
        },
        {
        id: "moral-teen-44",
        title: "Puzzle of Fairness",
        icon: <Puzzle className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-44"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/puzzle-fairness1",
        index: 43,
        },
        {
        id: "moral-teen-45",
        title: "Bully Story",
        icon: <Users className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-45"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/bully-story2",
        index: 44,
        },
        {
        id: "moral-teen-46",
        title: "Debate: Equal vs Fair",
        icon: <Mic className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "7 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-46"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/debate-equal-vs-fair",
        index: 45,
        },
        {
        id: "moral-teen-47",
        title: "Journal of Fairness",
        icon: <Notebook className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-47"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/journal-fairness",
        index: 46,
        },
        {
        id: "moral-teen-48",
        title: "Roleplay: Justice Leader",
        icon: <Users className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-48"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/roleplay-justice-leader",
        index: 47,
        },
        {
        id: "moral-teen-49",
        title: "Reflex Stand Up",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "3 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-49"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-stand-up",
        index: 48,
        },
        {
        id: "moral-teen-50",
        title: "Badge: Justice Hero",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6â€“8 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["moral-teen-50"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/badge-justice-hero",
        index: 49,
        },
        {
        id: "moral-teen-51",
        title: "Witness Story",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-51"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/witness-story",
        index: 50,
        },
        {
        id: "moral-teen-52",
        title: "Courage Quiz",
        icon: <HelpCircle className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "4 min",
          coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-52"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/courage-quiz1",
        index: 51,
        },
        {
        id: "moral-teen-53",
        title: "Reflex Moral Courage",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "3 min",
          coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-53"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-moral-courage",
        index: 52,
        },
        {
        id: "moral-teen-54",
        title: "Puzzle of Heroes",
        icon: <Puzzle className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-54"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/puzzle-heroes",
        index: 53,
        },
        {
        id: "moral-teen-55",
        title: "Group Pressure Story",
        icon: <Users className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-55"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/group-pressure-story",
        index: 54,
        },
        {
        id: "moral-teen-56",
        title: "Debate: Fear vs Courage",
        icon: <Mic className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "7 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-56"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/debate-fear-vs-courage",
        index: 55,
        },
        {
        id: "moral-teen-57",
        title: "Courage Journal",
        icon: <Notebook className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-57"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/courage-journal1",
        index: 56,
        },
        {
        id: "moral-teen-58",
        title: "Bravery Story",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-58"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/bravery-story",
        index: 57,
        },
        {
        id: "moral-teen-59",
        title: "Roleplay: Courageous Leader",
        icon: <Users className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-59"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/roleplay-courageous-leader",
        index: 58,
        },
        {
        id: "moral-teen-60",
        title: "Badge: Courage Hero",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6â€“8 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-60"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/badge-courage-hero",
        index: 59,
        },
        {
        id: "moral-teen-61",
        title: "Group Project Story",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-61"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/group-project-story",
        index: 60,
        },
        {
        id: "moral-teen-62",
        title: "Quiz on Team Skills",
        icon: <HelpCircle className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-62"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/quiz-team-skills",
        index: 61,
        },
        {
        id: "moral-teen-63",
        title: "Reflex Collaboration",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "2 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-63"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-collaboration",
        index: 62,
        },
        {
        id: "moral-teen-64",
        title: "Puzzle: Great Teams",
        icon: <Puzzle className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "4 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-64"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/puzzle-great-teams",
        index: 63,
        },
        {
        id: "moral-teen-65",
        title: "Leadership Story",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-65"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/leadership-story",
        index: 64,
        },
        {
        id: "moral-teen-66",
        title: "Debate: Team vs Individual",
        icon: <Mic className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "8 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-66"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/debate-team-vs-individual",
        index: 65,
        },
        {
        id: "moral-teen-67",
        title: "Journal of Cooperation",
        icon: <Edit3 className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-67"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/journal-cooperation",
        index: 66,
        },
        {
        id: "moral-teen-68",
        title: "Roleplay: Good Teammate",
        icon: <Users className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-68"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/roleplay-good-teammate",
        index: 67,
        },
        {
        id: "moral-teen-69",
        title: "Reflex Fair Share",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "2 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-69"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-fair-share",
        index: 68,
        },
        {
        id: "moral-teen-70",
        title: "Badge: Team Hero",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "10 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-70"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/badge-team-hero",
        index: 69,
        },
        {
        id: "moral-teen-71",
        title: "Leader Story",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-71"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/leader-story",
        index: 70,
        },
        {
        id: "moral-teen-72",
        title: "Quiz on Leadership",
        icon: <HelpCircle className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-72"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/quiz-leadership",
        index: 71,
        },
        {
        id: "moral-teen-73",
        title: "Reflex Leadership Traits",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "2 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-73"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-leadership-traits",
        index: 72,
        },
        {
        id: "moral-teen-74",
        title: "Puzzle of Leaders",
        icon: <Puzzle className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "4 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-74"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/puzzle-of-leaders",
        index: 73,
        },
        {
        id: "moral-teen-75",
        title: "Community Story",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["moral-teen-75"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/community-story",
        index: 74,
        },
        {
        id: "moral-teen-76",
        title: "Debate: Boss vs Leader",
        icon: <Mic className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "8 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-76"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/debate-boss-vs-leader",
        index: 75,
        },
        {
        id: "moral-teen-77",
        title: "Journal of Leadership",
        icon: <Edit3 className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-77"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/journal-leadership",
        index: 76,
        },
        {
        id: "moral-teen-78",
        title: "Roleplay: True Leader",
        icon: <Users className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-78"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/roleplay-true-leader",
        index: 77,
        },
        {
        id: "moral-teen-79",
        title: "Reflex Team First",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "2 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-79"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-team-first",
        index: 78,
        },
        {
        id: "moral-teen-80",
        title: "Badge: Service Leader",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "10 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-80"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/badge-service-leader",
        index: 79,
        },
        {
        id: "moral-teen-81",
        title: "Class Argument Story",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-81"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/class-argument-story",
        index: 80,
        },
        {
        id: "moral-teen-82",
        title: "Quiz on Conflict",
        icon: <HelpCircle className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-82"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/quiz-on-conflict",
        index: 81,
        },
        {
        id: "moral-teen-83",
        title: "Reflex Peace Symbols",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "2 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-83"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-peace-symbols",
        index: 82,
        },
        {
        id: "moral-teen-84",
        title: "Puzzle of Resolution",
        icon: <Puzzle className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "4 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-84"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/puzzle-of-resolution",
        index: 83,
        },
        {
        id: "moral-teen-85",
        title: "Friend Group Story",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-85"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/friend-group-story",
        index: 84,
        },
        {
        id: "moral-teen-86",
        title: "Debate: Peace vs Revenge",
        icon: <Mic className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "8 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-86"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/debate-peace-vs-revenge",
        index: 85,
        },
        {
        id: "moral-teen-87",
        title: "Journal of Resolution",
        icon: <Edit3 className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-87"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/journal-of-resolution",
        index: 86,
        },
        {
        id: "moral-teen-88",
        title: "Roleplay: Mediator",
        icon: <Users className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-88"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/roleplay-mediator",
        index: 87,
        },
        {
        id: "moral-teen-89",
        title: "Reflex Calm Action",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "2 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-89"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-calm-action",
        index: 88,
        },
        {
        id: "moral-teen-90",
        title: "Badge: Peace Hero",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "10 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-90"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/badge-peace-hero",
        index: 89,
        },
        {
        id: "moral-teen-91",
        title: "Money Found Story",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3-4 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-91"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/money-found-story",
        index: 90,
        },
        {
        id: "moral-teen-92",
        title: "Ethical Quiz",
        icon: <HelpCircle className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "2-3 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-92"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/ethical-quiz",
        index: 91,
        },
        {
        id: "moral-teen-93",
        title: "Reflex: Right vs Easy",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "2-3 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-93"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-right-vs-easy",
        index: 92,
        },
        {
        id: "moral-teen-94",
        title: "Puzzle of Ethics",
        icon: <Puzzle className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "4-5 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-94"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/puzzle-of-ethics",
        index: 93,
        },
        {
        id: "moral-teen-95",
        title: "Peer Pressure Story",
        icon: <Users className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "3-4 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-95"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/peer-pressure-story1",
        index: 94,
        },
        {
        id: "moral-teen-96",
        title: "Debate: Right vs Popular",
        icon: <Mic className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "5-6 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-96"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/debate-right-vs-popular",
        index: 95,
        },
        {
        id: "moral-teen-97",
        title: "Journal of Ethics",
        icon: <PenTool className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "4-5 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-97"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/journal-of-ethics",
        index: 96,
        },
        {
        id: "moral-teen-98",
        title: "Roleplay: Ethical Leader",
        icon: <UserCheck className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5-6 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-98"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/roleplay-ethical-leader",
        index: 97,
        },
        {
        id: "moral-teen-99",
        title: "Reflex: True Hero",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "2-3 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-99"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/reflex-true-hero",
        index: 98,
        },
        {
        id: "moral-teen-100",
        title: "Badge: Ethical Hero",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6-8 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["moral-teen-100"] || false,
        isSpecial: true,
        path: "/student/moral-values/teen/badge-ethical-hero",
        index: 99,
        },

    ];

    return moralGamesTeen;
}
