import {
  Lightbulb,
  GraduationCap,
  Briefcase,
  Users,
  Target,
  TrendingUp,
  Award,
  BookOpen,
  Zap,
  Brain,
  Sparkles,
  Stethoscope,
  School,
  Medal,
  ShoppingCart,
  PiggyBank,
  IndianRupee,
  Banknote,
  Droplets,
  Wrench,
  Smartphone,
  Gamepad2,
  Music,
  ChefHat
} from "lucide-react";
import buildIds from "../buildGameIds";

export const eheGameIdsKids = buildIds("ehe", "kids")

export const getEheKidsGames = (gameCompletionStatus) => {
    const eheGamesKids = [
        {
            id: 'ehe-kids-1',
            title: 'Doctor Story',
            description: 'Learn about the important job of a doctor and how they help people!',
            icon: <Stethoscope className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-1'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/doctor-story',
            index: 0
        },
        {
            id: 'ehe-kids-2',
            title: 'Quiz on Jobs',
            description: 'Answer 5 questions about different jobs and what people do!',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-2'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-jobs',
            index: 1
        },
        {
            id: 'ehe-kids-3',
            title: 'Reflex Job Match',
            description: 'Quick! Match jobs to the right places - test your reflexes!',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-3'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-job-match',
            index: 2
        },
        {
            id: 'ehe-kids-4',
            title: 'Puzzle: Who Does What?',
            description: 'Match workers to their jobs! Farmer → Crops, Pilot → Plane, Chef → Food.',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-4'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-who-does-what',
            index: 3
        },
        {
            id: 'ehe-kids-5',
            title: 'Dream Job Story',
            description: 'Discover which job suits you based on your interests!',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-5'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/dream-job-story',
            index: 4
        },
        {
            id: 'ehe-kids-6',
            title: 'Poster: My Dream Job',
            description: 'Create/select poster: "I want to be a ___.',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-6'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-my-dream-job',
            index: 5
        },
        {
            id: 'ehe-kids-7',
            title: 'Journal of Jobs',
            description: 'Write: "When I grow up, I want to be ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-7'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-jobs',
            index: 6
        },
        {
            id: 'ehe-kids-8',
            title: 'School Helper Story',
            description: 'Learn about all the people who help keep school running!',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-8'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/school-helper-story',
            index: 7
        },
        {
            id: 'ehe-kids-9',
            title: 'Reflex Career Check',
            description: 'Quick career decisions! Choose correct job roles - pass 3/5!',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-9'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-career-check',
            index: 8
        },
        {
            id: 'ehe-kids-10',
            title: 'Badge: Career Explorer Kid',
            description: 'Identify 5 jobs correctly to earn your Career Explorer Kid Badge!',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-10'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-career-explorer-kid',
            index: 9
        },
        {
            id: 'ehe-kids-11',
            title: 'Idea Story',
            description: 'You want to sell lemonade. What is your first step?',
            icon: <Lightbulb className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-11'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/idea-story',
            index: 10
        },
        {
            id: 'ehe-kids-12',
            title: 'Quiz on Skills',
            description: 'Which skill helps entrepreneurs?',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-12'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-skills',
            index: 11
        },
        {
            id: 'ehe-kids-13',
            title: 'Reflex Skill Check',
            description: 'Tap 💡 for "Creativity," ❌ for "Cheating."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-13'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-skill-check',
            index: 12
        },
        {
            id: 'ehe-kids-14',
            title: 'Puzzle: Match Skills',
            description: 'Match "Leader → Guide, Innovator → Invent, Team Player → Support."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-14'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-match-skills',
            index: 13
        },
        {
            id: 'ehe-kids-15',
            title: 'Teamwork Story',
            description: 'You start a project. Should you work alone or with friends?',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-15'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/teamwork-story',
            index: 14
        },
        {
            id: 'ehe-kids-16',
            title: 'Poster: Skills for Success',
            description: 'Create/select poster: "Dream + Work + Team = Success."',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-16'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-skills-success',
            index: 15
        },
        {
            id: 'ehe-kids-17',
            title: 'Journal of Skills',
            description: 'Write: "One skill I want to improve is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-17'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-skills',
            index: 16
        },
        {
            id: 'ehe-kids-18',
            title: 'Risk Story',
            description: 'You want to try a new school club. Should you?',
            icon: <TrendingUp className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-18'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/risk-story',
            index: 17
        },
        {
            id: 'ehe-kids-19',
            title: 'Reflex Innovation',
            description: 'Tap 🛠️ for "Solve Problems," ❌ for "Ignore Problems."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-19'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-innovation',
            index: 18
        },
        {
            id: 'ehe-kids-20',
            title: 'Badge: Young Innovator',
            description: 'Show 5 entrepreneur skills to earn your badge.',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-20'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-young-innovator',
            index: 19
        },
        {
            id: 'ehe-kids-21',
            title: 'Lemonade Stand Story',
            description: 'You sell 5 cups of lemonade. What do you get?',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-21'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/lemonade-stand-story',
            index: 20
        },
        {
            id: 'ehe-kids-22',
            title: 'Quiz on Money Use',
            description: 'What do we use money for?',
            icon: <IndianRupee className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-22'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-money-use',
            index: 21
        },
        {
            id: 'ehe-kids-23',
            title: 'Reflex Money Basics',
            description: 'Tap 💰 for "Money = Value," ❌ for "Money = Toy."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-23'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-money-basics',
            index: 22
        },
        {
            id: 'ehe-kids-24',
            title: 'Puzzle: Match Money Terms',
            description: 'Match "Earning → Work, Spending → Shop, Saving → Piggy Bank."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-24'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-match-money-terms',
            index: 23
        },
        {
            id: 'ehe-kids-25',
            title: 'Saving Story',
            description: 'You get pocket money. Should you spend all or save some?',
            icon: <PiggyBank className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-25'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/saving-story',
            index: 24
        },
        {
            id: 'ehe-kids-26',
            title: 'Poster: Smart Money',
            description: 'Create/select poster: "Earn, Save, Spend Wisely."',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-26'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-smart-money',
            index: 25
        },
        {
            id: 'ehe-kids-27',
            title: 'Journal of Pocket Money',
            description: 'Write: "I saved ___ from my allowance."',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-27'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-pocket-money',
            index: 26
        },
        {
            id: 'ehe-kids-28',
            title: 'Shop Story',
            description: 'You have ₹50. Ice cream = ₹40, Toy = ₹60. What can you buy?',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-28'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/shop-story',
            index: 27
        },
        {
            id: 'ehe-kids-29',
            title: 'Reflex Money Alert',
            description: 'Tap 🏦 for "Save in Bank," ❌ for "Throw Away Money."',
            icon: <Banknote className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-29'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-money-alert',
            index: 28
        },
        {
            id: 'ehe-kids-30',
            title: 'Badge: Money Smart Kid',
            description: 'Complete 5 money basics to earn your badge.',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-30'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-money-smart-kid',
            index: 29
        },
        {
            id: 'ehe-kids-31',
            title: 'Problem Story',
            description: 'School taps are leaking. What should you do?',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-31'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/problem-story',
            index: 30
        },
        {
            id: 'ehe-kids-32',
            title: 'Quiz on Creativity',
            description: 'Which is innovation?',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-32'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-creativity',
            index: 31
        },
        {
            id: 'ehe-kids-33',
            title: 'Reflex Innovation Basics',
            description: 'Tap 💡 for "New Idea," ❌ for "Copy Idea."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-33'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-innovation-basics',
            index: 32
        },
        {
            id: 'ehe-kids-34',
            title: 'Puzzle: Match Innovators',
            description: 'Match "Edison → Bulb, Wright Brothers → Plane, Jobs → iPhone."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-34'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-match-innovators',
            index: 33
        },
        {
            id: 'ehe-kids-35',
            title: 'School Project Story',
            description: 'You\'re asked to make a science model. Should you copy or create your own?',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-35'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/school-project-story',
            index: 34
        },
        {
            id: 'ehe-kids-36',
            title: 'Poster: Think Different',
            description: 'Create/select poster: "Every Big Change Starts with a Small Idea."',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-36'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-think-different',
            index: 35
        },
        {
            id: 'ehe-kids-37',
            title: 'Journal of Ideas',
            description: 'Write: "One idea I have to solve a problem is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-37'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-ideas',
            index: 36
        },
        {
            id: 'ehe-kids-38',
            title: 'Game Story',
            description: 'Friends can\'t decide a game. Should you invent new rules?',
            icon: <Gamepad2 className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-38'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/game-story',
            index: 37
        },
        {
            id: 'ehe-kids-39',
            title: 'Reflex Design Thinking',
            description: 'Tap 🔧 for "Test Ideas," ❌ for "Ignore Problems."',
            icon: <Wrench className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-39'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-design-thinking',
            index: 38
        },
        {
            id: 'ehe-kids-40',
            title: 'Badge: Little Innovator',
            description: 'Complete 5 creative problem-solving cases to earn your badge.',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-40'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-little-innovator',
            index: 39
        },
        {
            id: 'ehe-kids-41',
            title: 'Ice Cream Kid Story',
            description: 'A 10-year-old sells ice cream in summer. Why?',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-41'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/ice-cream-kid-story',
            index: 40
        },
        {
            id: 'ehe-kids-42',
            title: 'Quiz on Young Entrepreneurs',
            description: 'What do young entrepreneurs show?',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-42'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-young-entrepreneurs',
            index: 41
        },
        {
            id: 'ehe-kids-43',
            title: 'Reflex Entrepreneur Basics',
            description: 'Tap 💪 for "Hard Work," ❌ for "Giving Up."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-43'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-entrepreneur-basics',
            index: 42
        },
        {
            id: 'ehe-kids-44',
            title: 'Puzzle: Match Stories',
            description: 'Match "Girl Sells Crafts → Creativity, Boy Runs App → Tech, Teen Sells Cakes → Cooking."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-44'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-match-stories',
            index: 43
        },
        {
            id: 'ehe-kids-45',
            title: 'Craft Story',
            description: 'A girl makes friendship bands to sell at school fair. What is she?',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-45'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/craft-story',
            index: 44
        },
        {
            id: 'ehe-kids-46',
            title: 'Poster: Young Bosses',
            description: 'Create/select poster: "Kids Can Be Entrepreneurs Too!"',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-46'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-young-bosses',
            index: 45
        },
        {
            id: 'ehe-kids-47',
            title: 'Journal of Inspiration',
            description: 'Write: "The young entrepreneur I admire is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-47'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-inspiration',
            index: 46
        },
        {
            id: 'ehe-kids-48',
            title: 'Toy Repair Story',
            description: 'A boy repairs toys for friends. What skill is he using?',
            icon: <Wrench className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-48'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/toy-repair-story',
            index: 47
        },
        {
            id: 'ehe-kids-49',
            title: 'Reflex Story Learner',
            description: 'Tap 📚 for "Learn From Failures," ❌ for "Quit Quickly."',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-49'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-story-learner',
            index: 48
        },
        {
            id: 'ehe-kids-50',
            title: 'Badge: Young Business Explorer',
            description: 'Understand 5 young entrepreneur stories to earn your badge.',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-50'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-young-business-explorer',
            index: 49
        },
        {
            id: 'ehe-kids-51',
            title: 'College Story',
            description: 'After school, many students go to college. What do they study there?',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-51'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/college-story',
            index: 50
        },
        {
            id: 'ehe-kids-52',
            title: 'Quiz on Pathways',
            description: 'Which is a career path?',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-52'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-pathways',
            index: 51
        },
        {
            id: 'ehe-kids-53',
            title: 'Reflex Path Check',
            description: 'Tap 🎓 for "Study After School," ❌ for "No Learning Forever."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-53'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-path-check',
            index: 52
        },
        {
            id: 'ehe-kids-54',
            title: 'Puzzle: Match Careers',
            description: 'Match "Farmer → Agriculture School, Engineer → College, Chef → Culinary School."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-54'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-match-careers',
            index: 53
        },
        {
            id: 'ehe-kids-55',
            title: 'Vocational Story',
            description: 'A student learns carpentry skills. What is this?',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-55'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/vocational-story',
            index: 54
        },
        {
            id: 'ehe-kids-56',
            title: 'Poster: Many Roads Ahead',
            description: 'Create/select poster: "After School = Many Choices."',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-56'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-many-roads-ahead',
            index: 55
        },
        {
            id: 'ehe-kids-57',
            title: 'Journal of Dreams',
            description: 'Write: "After school, I dream of becoming ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-57'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-dreams',
            index: 56
        },
        {
            id: 'ehe-kids-58',
            title: 'Apprenticeship Story',
            description: 'A girl joins a tailoring apprenticeship. What is she doing?',
            icon: <Wrench className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-58'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/apprenticeship-story',
            index: 57
        },
        {
            id: 'ehe-kids-59',
            title: 'Reflex Career Alert',
            description: 'Tap 💼 for "Scholarship," ❌ for "Drop Out Too Early."',
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-59'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-career-alert',
            index: 58
        },
        {
            id: 'ehe-kids-60',
            title: 'Badge: Path Explorer Kid',
            description: 'Explore 5 pathways after school to earn your badge.',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-60'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-path-explorer-kid',
            index: 59
        },
        {
            id: 'ehe-kids-61',
            title: 'College Story',
            description: 'After school, some students go to college. What is college for?',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-61'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/college-story-61',
            index: 60
        },
        {
            id: 'ehe-kids-62',
            title: 'Quiz on College Basics',
            description: 'What is a university? (a) Place for higher studies, (b) Playground).',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-62'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-college-basics',
            index: 61
        },
        {
            id: 'ehe-kids-63',
            title: 'Reflex College Awareness',
            description: 'Tap 🏫 for "Study in College," ❌ for "College = Shopping Mall."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-63'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-college-awareness',
            index: 62
        },
        {
            id: 'ehe-kids-64',
            title: 'Puzzle: Match Studies',
            description: 'Match "Doctor → Medical College, Lawyer → Law College, Artist → Design College."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-64'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-match-studies',
            index: 63
        },
        {
            id: 'ehe-kids-65',
            title: 'Entrance Exam Story',
            description: 'Some careers need entrance exams. Should you prepare?',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-65'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/entrance-exam-story',
            index: 64
        },
        {
            id: 'ehe-kids-66',
            title: 'Poster: My College Dream',
            description: 'Create/select poster: "One Day I Will Go to College."',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-66'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-my-college-dream',
            index: 65
        },
        {
            id: 'ehe-kids-67',
            title: 'Journal of College Dreams',
            description: 'Write: "The college I dream of joining is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-67'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-college-dreams',
            index: 66
        },
        {
            id: 'ehe-kids-68',
            title: 'Scholarship Story',
            description: 'Student has no money for fees. What can help?',
            icon: <IndianRupee className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-68'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/scholarship-story',
            index: 67
        },
        {
            id: 'ehe-kids-69',
            title: 'Reflex Higher Education',
            description: 'Tap 📚 for "College = Learning," ❌ for "College = Party Only."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-69'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-higher-education',
            index: 68
        },
        {
            id: 'ehe-kids-70',
            title: 'Badge: College Dreamer',
            description: 'Complete 5 higher-education awareness cases to earn your badge.',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-70'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-college-dreamer',
            index: 69
        },
        {
            id: 'ehe-kids-71',
            title: 'Robot Helper Story',
            description: 'Robots help in factories. What career works with robots?',
            icon: <Wrench className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-71'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/robot-helper-story',
            index: 70
        },
        {
            id: 'ehe-kids-72',
            title: 'Quiz on Future Jobs',
            description: 'Which is a new career? (a) AI Engineer, (b) Dinosaur Hunter).',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-72'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-future-jobs',
            index: 71
        },
        {
            id: 'ehe-kids-73',
            title: 'Reflex Career Basics',
            description: 'Tap 🌱 for "Green Jobs," ❌ for "Jobs That Harm Earth."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-73'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-career-basics',
            index: 72
        },
        {
            id: 'ehe-kids-74',
            title: 'Puzzle: Match Future Jobs',
            description: 'Match "Game Designer → Games, Drone Pilot → Flying Robots, Data Scientist → Numbers."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-74'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-match-future-jobs',
            index: 73
        },
        {
            id: 'ehe-kids-75',
            title: 'E-Sports Story',
            description: 'A kid loves gaming. Can this be a career?',
            icon: <Gamepad2 className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-75'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/e-sports-story',
            index: 74
        },
        {
            id: 'ehe-kids-76',
            title: 'Poster: Jobs of Tomorrow',
            description: 'Create/select poster: "AI, Space, Green Energy Careers."',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-76'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-jobs-of-tomorrow',
            index: 75
        },
        {
            id: 'ehe-kids-77',
            title: 'Journal of Dream Future Job',
            description: 'Write: "One new career I want to explore is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-77'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-dream-future-job',
            index: 76
        },
        {
            id: 'ehe-kids-78',
            title: 'Online Career Story',
            description: 'A girl posts videos and earns. What career is this?',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-78'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/online-career-story',
            index: 77
        },
        {
            id: 'ehe-kids-79',
            title: 'Reflex Job Alert',
            description: 'Tap 🚀 for "Space Careers," ❌ for "Time Travel Jobs."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-79'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-job-alert',
            index: 78
        },
        {
            id: 'ehe-kids-80',
            title: 'Badge: Future Job Explorer',
            description: 'Identify 5 emerging careers to earn your badge.',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-80'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-future-job-explorer',
            index: 79
        },
        {
            id: 'ehe-kids-81',
            title: 'Food Waste Story',
            description: 'A boy collects leftover food to give poor children. What is this?',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-81'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/food-waste-story',
            index: 80
        },
        {
            id: 'ehe-kids-82',
            title: 'Quiz on Social Impact',
            description: 'Social entrepreneurship means? (a) Helping society + business, (b) Only money).',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-82'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-social-impact',
            index: 81
        },
        {
            id: 'ehe-kids-83',
            title: 'Reflex Social Basics',
            description: 'Tap 🤝 for "Help + Earn," ❌ for "Ignore Problems."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-83'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-social-basics',
            index: 82
        },
        {
            id: 'ehe-kids-84',
            title: 'Puzzle: Social Examples',
            description: 'Match "Solar Lamps → Villages, Clean Water → Rural Areas, Microloans → Poor Families."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-84'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-social-examples',
            index: 83
        },
        {
            id: 'ehe-kids-85',
            title: 'Eco Bag Story',
            description: 'A girl makes cloth bags to replace plastic. What is she solving?',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-85'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/eco-bag-story',
            index: 84
        },
        {
            id: 'ehe-kids-86',
            title: 'Poster: Business for Good',
            description: 'Create/select poster: "Change the World with Ideas."',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-86'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-business-for-good',
            index: 85
        },
        {
            id: 'ehe-kids-87',
            title: 'Journal of Social Ideas',
            description: 'Write: "One problem I want to solve is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-87'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-social-ideas',
            index: 86
        },
        {
            id: 'ehe-kids-88',
            title: 'Village Solar Story',
            description: 'A teen sets up solar lamps in a dark village. What is this?',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-88'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/village-solar-story',
            index: 87
        },
        {
            id: 'ehe-kids-89',
            title: 'Reflex Social Alert',
            description: 'Tap ⚖️ for "Fair Business," ❌ for "Cheating."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-89'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-social-alert',
            index: 88
        },
        {
            id: 'ehe-kids-90',
            title: 'Badge: Social Helper Kid',
            description: 'Learn 5 social entrepreneurship cases to earn your badge.',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-90'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-social-helper-kid',
            index: 89
        },
        {
            id: 'ehe-kids-91',
            title: 'Book Story',
            description: 'You finish one book. Should you stop reading forever or read more?',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-91'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/book-story',
            index: 90
        },
        {
            id: 'ehe-kids-92',
            title: 'Quiz on Lifelong Learning',
            description: 'Learning stops when? (a) After school, (b) Never).',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-92'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-lifelong-learning',
            index: 91
        },
        {
            id: 'ehe-kids-93',
            title: 'Reflex Learning Basics',
            description: 'Tap ❓ for "Ask Questions," ❌ for "Stop Curiosity."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-93'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-learning-basics',
            index: 92
        },
        {
            id: 'ehe-kids-94',
            title: 'Puzzle: Learning Tools',
            description: 'Match "Books → Knowledge, Internet → Information, Practice → Skills."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-94'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-learning-tools',
            index: 93
        },
        {
            id: 'ehe-kids-95',
            title: 'Music Story',
            description: 'A girl loves music. Should she stop after school?',
            icon: <Music className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-95'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/music-story',
            index: 94
        },
        {
            id: 'ehe-kids-96',
            title: 'Poster: Keep Growing',
            description: 'Create/select poster: "Learning = Growth for Life."',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-96'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-keep-growing',
            index: 95
        },
        {
            id: 'ehe-kids-97',
            title: 'Journal of Curiosity',
            description: 'Write: "One new thing I want to learn is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-97'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-curiosity',
            index: 96
        },
        {
            id: 'ehe-kids-98',
            title: 'Cooking Story',
            description: 'A boy learns cooking from his grandmother. Is this learning?',
            icon: <ChefHat className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-98'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/cooking-story',
            index: 97
        },
        {
            id: 'ehe-kids-99',
            title: 'Reflex Growth Check',
            description: 'Tap 🌱 for "Try New Skills," ❌ for "Stop Exploring."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-99'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-growth-check',
            index: 98
        },
        {
            id: 'ehe-kids-100',
            title: 'Badge: Lifelong Learner Kid',
            description: 'Show 5 habits of lifelong learning to earn your badge.',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-100'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-lifelong-learner-kid',
            index: 99
        }
    ];

    return eheGamesKids;
};

export default getEheKidsGames;