import {
  Lightbulb,
  GraduationCap,
  Briefcase,
  Users,
  Target,
  TrendingUp,
  Award,
  BookOpen,
  Zap,
  Brain,
  Sparkles,
  Stethoscope,
  School,
  Medal,
  ShoppingCart,
  PiggyBank,
  IndianRupee,
  Banknote,
  Droplets,
  Wrench,
  Smartphone,
  Gamepad2,
  Music,
  ChefHat
} from "lucide-react";
import buildIds from "../buildGameIds";

export const eheGameIdsKids = buildIds("ehe", "kids")

export const getEheKidsGames = (gameCompletionStatus) => {
    const eheGamesKids = [
        {
            id: 'ehe-kids-1',
            title: 'Doctor Story',
            icon: <Stethoscope className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-1'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/doctor-story',
            index: 0
        },
        {
            id: 'ehe-kids-2',
            title: 'Quiz on Jobs',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-2'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-jobs',
            index: 1
        },
        {
            id: 'ehe-kids-3',
            title: 'Reflex Job Match',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-3'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-job-match',
            index: 2
        },
        {
            id: 'ehe-kids-4',
            title: 'Puzzle: Who Does What?',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-4'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-who-does-what',
            index: 3
        },
        {
            id: 'ehe-kids-5',
            title: 'Dream Job Story',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-5'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/dream-job-story',
            index: 4
        },
        {
            id: 'ehe-kids-6',
            title: 'Poster: My Dream Job',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-6'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-my-dream-job',
            index: 5
        },
        {
            id: 'ehe-kids-7',
            title: 'Journal of Jobs',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-7'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-jobs',
            index: 6
        },
        {
            id: 'ehe-kids-8',
            title: 'School Helper Story',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-8'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/school-helper-story',
            index: 7
        },
        {
            id: 'ehe-kids-9',
            title: 'Reflex Career Check',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-9'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-career-check',
            index: 8
        },
        {
            id: 'ehe-kids-10',
            title: 'Badge: Career Explorer Kid',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-10'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-career-explorer-kid',
            index: 9
        },
        {
            id: 'ehe-kids-11',
            title: 'Idea Story',
            icon: <Lightbulb className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-11'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/idea-story',
            index: 10
        },
        {
            id: 'ehe-kids-12',
            title: 'Quiz on Skills',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-12'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-skills',
            index: 11
        },
        {
            id: 'ehe-kids-13',
            title: 'Reflex Skill Check',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-13'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-skill-check',
            index: 12
        },
        {
            id: 'ehe-kids-14',
            title: 'Puzzle: Match Skills',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-14'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-match-skills',
            index: 13
        },
        {
            id: 'ehe-kids-15',
            title: 'Teamwork Story',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-15'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/teamwork-story',
            index: 14
        },
        {
            id: 'ehe-kids-16',
            title: 'Poster: Skills for Success',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-16'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-skills-success',
            index: 15
        },
        {
            id: 'ehe-kids-17',
            title: 'Journal of Skills',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-17'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-skills',
            index: 16
        },
        {
            id: 'ehe-kids-18',
            title: 'Risk Story',
            icon: <TrendingUp className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-18'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/risk-story',
            index: 17
        },
        {
            id: 'ehe-kids-19',
            title: 'Reflex Innovation',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-19'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-innovation',
            index: 18
        },
        {
            id: 'ehe-kids-20',
            title: 'Badge: Young Innovator',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-20'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-young-innovator',
            index: 19
        },
        {
            id: 'ehe-kids-21',
            title: 'Lemonade Stand Story',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-21'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/lemonade-stand-story',
            index: 20
        },
        {
            id: 'ehe-kids-22',
            title: 'Quiz on Money Use',
            icon: <IndianRupee className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-22'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-money-use',
            index: 21
        },
        {
            id: 'ehe-kids-23',
            title: 'Reflex Money Basics',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-23'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-money-basics',
            index: 22
        },
        {
            id: 'ehe-kids-24',
            title: 'Puzzle: Match Money Terms',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-24'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-match-money-terms',
            index: 23
        },
        {
            id: 'ehe-kids-25',
            title: 'Saving Story',
            icon: <PiggyBank className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-kids-25'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/saving-story',
            index: 24
        },
        {
            id: 'ehe-kids-26',
            title: 'Poster: Smart Money',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-26'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-smart-money',
            index: 25
        },
        {
            id: 'ehe-kids-27',
            title: 'Journal of Pocket Money',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-27'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-pocket-money',
            index: 26
        },
        {
            id: 'ehe-kids-28',
            title: 'Shop Story',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-28'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/shop-story',
            index: 27
        },
        {
            id: 'ehe-kids-29',
            title: 'Reflex Money Alert',
            icon: <Banknote className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-29'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-money-alert',
            index: 28
        },
        {
            id: 'ehe-kids-30',
            title: 'Badge: Money Smart Kid',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-30'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-money-smart-kid',
            index: 29
        },
        {
            id: 'ehe-kids-31',
            title: 'Problem Story',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-31'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/problem-story',
            index: 30
        },
        {
            id: 'ehe-kids-32',
            title: 'Quiz on Creativity',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-32'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-creativity',
            index: 31
        },
        {
            id: 'ehe-kids-33',
            title: 'Reflex Innovation Basics',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-33'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-innovation-basics',
            index: 32
        },
        {
            id: 'ehe-kids-34',
            title: 'Puzzle: Match Innovators',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-34'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-match-innovators',
            index: 33
        },
        {
            id: 'ehe-kids-35',
            title: 'School Project Story',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-35'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/school-project-story',
            index: 34
        },
        {
            id: 'ehe-kids-36',
            title: 'Poster: Think Different',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-36'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-think-different',
            index: 35
        },
        {
            id: 'ehe-kids-37',
            title: 'Journal of Ideas',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-37'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-ideas',
            index: 36
        },
        {
            id: 'ehe-kids-38',
            title: 'Game Story',
            icon: <Gamepad2 className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-38'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/game-story',
            index: 37
        },
        {
            id: 'ehe-kids-39',
            title: 'Reflex Design Thinking',
            icon: <Wrench className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-39'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-design-thinking',
            index: 38
        },
        {
            id: 'ehe-kids-40',
            title: 'Badge: Little Innovator',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-40'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-little-innovator',
            index: 39
        },
        {
            id: 'ehe-kids-41',
            title: 'Ice Cream Kid Story',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-41'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/ice-cream-kid-story',
            index: 40
        },
        {
            id: 'ehe-kids-42',
            title: 'Quiz on Young Entrepreneurs',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-42'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-young-entrepreneurs',
            index: 41
        },
        {
            id: 'ehe-kids-43',
            title: 'Reflex Entrepreneur Basics',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-43'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-entrepreneur-basics',
            index: 42
        },
        {
            id: 'ehe-kids-44',
            title: 'Puzzle: Match Stories',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-44'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-match-stories',
            index: 43
        },
        {
            id: 'ehe-kids-45',
            title: 'Craft Story',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-45'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/craft-story',
            index: 44
        },
        {
            id: 'ehe-kids-46',
            title: 'Poster: Young Bosses',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-46'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-young-bosses',
            index: 45
        },
        {
            id: 'ehe-kids-47',
            title: 'Journal of Inspiration',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-47'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-inspiration',
            index: 46
        },
        {
            id: 'ehe-kids-48',
            title: 'Toy Repair Story',
            icon: <Wrench className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-48'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/toy-repair-story',
            index: 47
        },
        {
            id: 'ehe-kids-49',
            title: 'Reflex Story Learner',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-49'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-story-learner',
            index: 48
        },
        {
            id: 'ehe-kids-50',
            title: 'Badge: Young Business Explorer',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-kids-50'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-young-business-explorer',
            index: 49
        },
        {
            id: 'ehe-kids-51',
            title: 'College Story',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-51'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/college-story',
            index: 50
        },
        {
            id: 'ehe-kids-52',
            title: 'Quiz on Pathways',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-52'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-pathways',
            index: 51
        },
        {
            id: 'ehe-kids-53',
            title: 'Reflex Path Check',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-53'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-path-check',
            index: 52
        },
        {
            id: 'ehe-kids-54',
            title: 'Puzzle: Match Careers',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-54'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-match-careers',
            index: 53
        },
        {
            id: 'ehe-kids-55',
            title: 'Vocational Story',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-55'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/vocational-story',
            index: 54
        },
        {
            id: 'ehe-kids-56',
            title: 'Poster: Many Roads Ahead',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-56'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-many-roads-ahead',
            index: 55
        },
        {
            id: 'ehe-kids-57',
            title: 'Journal of Dreams',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-57'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-dreams',
            index: 56
        },
        {
            id: 'ehe-kids-58',
            title: 'Apprenticeship Story',
            icon: <Wrench className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-58'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/apprenticeship-story',
            index: 57
        },
        {
            id: 'ehe-kids-59',
            title: 'Reflex Career Alert',
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-59'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-career-alert',
            index: 58
        },
        {
            id: 'ehe-kids-60',
            title: 'Badge: Path Explorer Kid',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-60'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-path-explorer-kid',
            index: 59
        },
        {
            id: 'ehe-kids-61',
            title: 'College Story',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-61'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/college-story-61',
            index: 60
        },
        {
            id: 'ehe-kids-62',
            title: 'Quiz on College Basics',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-62'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-college-basics',
            index: 61
        },
        {
            id: 'ehe-kids-63',
            title: 'Reflex College Awareness',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-63'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-college-awareness',
            index: 62
        },
        {
            id: 'ehe-kids-64',
            title: 'Puzzle: Match Studies',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-64'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-match-studies',
            index: 63
        },
        {
            id: 'ehe-kids-65',
            title: 'Entrance Exam Story',
            icon: <School className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-65'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/entrance-exam-story',
            index: 64
        },
        {
            id: 'ehe-kids-66',
            title: 'Poster: My College Dream',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-66'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-my-college-dream',
            index: 65
        },
        {
            id: 'ehe-kids-67',
            title: 'Journal of College Dreams',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-67'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-college-dreams',
            index: 66
        },
        {
            id: 'ehe-kids-68',
            title: 'Scholarship Story',
            icon: <IndianRupee className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-68'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/scholarship-story',
            index: 67
        },
        {
            id: 'ehe-kids-69',
            title: 'Reflex Higher Education',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-69'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-higher-education',
            index: 68
        },
        {
            id: 'ehe-kids-70',
            title: 'Badge: College Dreamer',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-70'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-college-dreamer',
            index: 69
        },
        {
            id: 'ehe-kids-71',
            title: 'Robot Helper Story',
            icon: <Wrench className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-71'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/robot-helper-story',
            index: 70
        },
        {
            id: 'ehe-kids-72',
            title: 'Quiz on Future Jobs',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-72'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-future-jobs',
            index: 71
        },
        {
            id: 'ehe-kids-73',
            title: 'Reflex Career Basics',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-73'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-career-basics',
            index: 72
        },
        {
            id: 'ehe-kids-74',
            title: 'Puzzle: Match Future Jobs',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-74'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-match-future-jobs',
            index: 73
        },
        {
            id: 'ehe-kids-75',
            title: 'E-Sports Story',
            icon: <Gamepad2 className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-kids-75'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/e-sports-story',
            index: 74
        },
        {
            id: 'ehe-kids-76',
            title: 'Poster: Jobs of Tomorrow',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-76'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-jobs-of-tomorrow',
            index: 75
        },
        {
            id: 'ehe-kids-77',
            title: 'Journal of Dream Future Job',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-77'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-dream-future-job',
            index: 76
        },
        {
            id: 'ehe-kids-78',
            title: 'Online Career Story',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-78'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/online-career-story',
            index: 77
        },
        {
            id: 'ehe-kids-79',
            title: 'Reflex Job Alert',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-79'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-job-alert',
            index: 78
        },
        {
            id: 'ehe-kids-80',
            title: 'Badge: Future Job Explorer',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-80'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-future-job-explorer',
            index: 79
        },
        {
            id: 'ehe-kids-81',
            title: 'Food Waste Story',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-81'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/food-waste-story',
            index: 80
        },
        {
            id: 'ehe-kids-82',
            title: 'Quiz on Social Impact',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-82'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-social-impact',
            index: 81
        },
        {
            id: 'ehe-kids-83',
            title: 'Reflex Social Basics',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-83'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-social-basics',
            index: 82
        },
        {
            id: 'ehe-kids-84',
            title: 'Puzzle: Social Examples',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-84'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-social-examples',
            index: 83
        },
        {
            id: 'ehe-kids-85',
            title: 'Eco Bag Story',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-85'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/eco-bag-story',
            index: 84
        },
        {
            id: 'ehe-kids-86',
            title: 'Poster: Business for Good',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-86'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-business-for-good',
            index: 85
        },
        {
            id: 'ehe-kids-87',
            title: 'Journal of Social Ideas',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-87'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-social-ideas',
            index: 86
        },
        {
            id: 'ehe-kids-88',
            title: 'Village Solar Story',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-88'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/village-solar-story',
            index: 87
        },
        {
            id: 'ehe-kids-89',
            title: 'Reflex Social Alert',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-89'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-social-alert',
            index: 88
        },
        {
            id: 'ehe-kids-90',
            title: 'Badge: Social Helper Kid',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-90'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-social-helper-kid',
            index: 89
        },
        {
            id: 'ehe-kids-91',
            title: 'Book Story',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-91'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/book-story',
            index: 90
        },
        {
            id: 'ehe-kids-92',
            title: 'Quiz on Lifelong Learning',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-92'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/quiz-on-lifelong-learning',
            index: 91
        },
        {
            id: 'ehe-kids-93',
            title: 'Reflex Learning Basics',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-93'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-learning-basics',
            index: 92
        },
        {
            id: 'ehe-kids-94',
            title: 'Puzzle: Learning Tools',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-94'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/puzzle-learning-tools',
            index: 93
        },
        {
            id: 'ehe-kids-95',
            title: 'Music Story',
            icon: <Music className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-95'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/music-story',
            index: 94
        },
        {
            id: 'ehe-kids-96',
            title: 'Poster: Keep Growing',
            icon: <Award className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-96'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/poster-keep-growing',
            index: 95
        },
        {
            id: 'ehe-kids-97',
            title: 'Journal of Curiosity',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-97'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/journal-of-curiosity',
            index: 96
        },
        {
            id: 'ehe-kids-98',
            title: 'Cooking Story',
            icon: <ChefHat className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-98'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/cooking-story',
            index: 97
        },
        {
            id: 'ehe-kids-99',
            title: 'Reflex Growth Check',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-99'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/reflex-growth-check',
            index: 98
        },
        {
            id: 'ehe-kids-100',
            title: 'Badge: Lifelong Learner Kid',
            icon: <Medal className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-kids-100'] || false,
            isSpecial: true,
            path: '/student/ehe/kids/badge-lifelong-learner-kid',
            index: 99
        }
    ];

    return eheGamesKids;
};

export default getEheKidsGames;
