import {
    Lightbulb,
    GraduationCap,
    Briefcase,
    Target,
    Zap,
    BookOpen,
    MessageCircle,
    Smartphone,
    Badge,
    Users,
    TrendingUp,
    Brain,
    Hammer,
    Wallet,
    PiggyBank,
    Calculator,
    ChartLine,
    Heart,
    Cpu,
    Wrench,
    RotateCcw,
    Rocket,
    Shirt,
    ShoppingCart,
    Calendar,
    Sun,
    Laptop,
    Globe,
    Recycle,
    Droplets,
    UserPlus,
} from "lucide-react";
import buildIds from "../buildGameIds";

export const eheGameIdsTeen = buildIds("ehe", "teen");

export const getEheTeenGames = (gameCompletionStatus)=> {
    const eheTeenGames = [
        {
            id: 'ehe-teen-1',
            title: 'Career Story',
            icon: <Lightbulb className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-1'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/career-story',
            index: 0
        },
        {
            id: 'ehe-teen-2',
            title: 'Quiz on Careers',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-2'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/quiz-on-careers',
            index: 1
        },
        {
            id: 'ehe-teen-3',
            title: 'Reflex Teen Career',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-3'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-career',
            index: 2
        },
        {
            id: 'ehe-teen-4',
            title: 'Puzzle: Career Match',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-4'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/puzzle-career-match',
            index: 3
        },
        {
            id: 'ehe-teen-5',
            title: 'Passion Story',
            icon: <Lightbulb className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-5'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/passion-story',
            index: 4
        },
        {
            id: 'ehe-teen-6',
            title: 'Debate: One Career or Many?',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-6'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/debate-one-career-or-many',
            index: 5
        },
        {
            id: 'ehe-teen-7',
            title: 'Journal of Career Choice',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-7'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/journal-of-career-choice',
            index: 6
        },
        {
            id: 'ehe-teen-8',
            title: 'Simulation: Career Fair',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-8'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/simulation-career-fair',
            index: 7
        },
        {
            id: 'ehe-teen-9',
            title: 'Reflex Future Check',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-9'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-future-check',
            index: 8
        },
        {
            id: 'ehe-teen-10',
            title: 'Badge: Career Aware Teen',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-10'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/badge-career-aware-teen',
            index: 9
        },
        // Games 11-20
        {
            id: 'ehe-teen-11',
            title: 'Opportunity Story',
            icon: <Lightbulb className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-11'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/opportunity-story',
            index: 10
        },
        {
            id: 'ehe-teen-12',
            title: 'Quiz on Entrepreneur Traits',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-12'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/quiz-entrepreneur-traits',
            index: 11
        },
        {
            id: 'ehe-teen-13',
            title: 'Reflex Teen Skills',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-13'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-skills',
            index: 12
        },
        {
            id: 'ehe-teen-14',
            title: 'Puzzle: Match Traits',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-14'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/puzzle-match-traits',
            index: 13
        },
        {
            id: 'ehe-teen-15',
            title: 'Failure Story',
            icon: <TrendingUp className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-15'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/failure-story',
            index: 14
        },
        {
            id: 'ehe-teen-16',
            title: 'Debate: Born or Made?',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-16'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/debate-born-or-made',
            index: 15
        },
        {
            id: 'ehe-teen-17',
            title: 'Journal of Strengths',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-17'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/journal-of-strengths',
            index: 16
        },
        {
            id: 'ehe-teen-18',
            title: 'Simulation: Team Project',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-18'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/simulation-team-project',
            index: 17
        },
        {
            id: 'ehe-teen-19',
            title: 'Reflex Teen Innovator',
            icon: <Hammer className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-19'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-innovator',
            index: 18
        },
        {
            id: 'ehe-teen-20',
            title: 'Badge: Future Entrepreneur',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-20'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/badge-future-entrepreneur',
            index: 19
        },
        // Games 21-30
        {
            id: 'ehe-teen-21',
            title: 'Cost Story',
            icon: <Wallet className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-21'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/cost-story',
            index: 20
        },
        {
            id: 'ehe-teen-22',
            title: 'Quiz on Business Terms',
            icon: <Calculator className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-22'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/quiz-business-terms',
            index: 21
        },
        {
            id: 'ehe-teen-23',
            title: 'Reflex Teen Money',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-23'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-money',
            index: 22
        },
        {
            id: 'ehe-teen-24',
            title: 'Puzzle: Match Business Terms',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-24'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/puzzle-business-terms',
            index: 23
        },
        {
            id: 'ehe-teen-25',
            title: 'Budget Story',
            icon: <PiggyBank className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-25'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/budget-story',
            index: 24
        },
        {
            id: 'ehe-teen-26',
            title: 'Debate: Save or Spend?',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-26'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/debate-save-or-spend',
            index: 25
        },
        {
            id: 'ehe-teen-27',
            title: 'Journal of Business Money',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-27'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/journal-business-money',
            index: 26
        },
        {
            id: 'ehe-teen-28',
            title: 'Simulation: Teen Shop',
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-28'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/simulation-teen-shop',
            index: 27
        },
        {
            id: 'ehe-teen-29',
            title: 'Reflex Business Alert',
            icon: <ChartLine className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-29'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-business-alert',
            index: 28
        },
        {
            id: 'ehe-teen-30',
            title: 'Badge: Money Wise Teen',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-30'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/badge-money-wise-teen',
            index: 29
        },
        // Games 31-40
        {
            id: 'ehe-teen-31',
            title: 'Empathy Story',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-31'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/empathy-story',
            index: 30
        },
        {
            id: 'ehe-teen-32',
            title: 'Quiz on Design Thinking',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-32'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/quiz-design-thinking',
            index: 31
        },
        {
            id: 'ehe-teen-33',
            title: 'Reflex Teen Innovator',
            icon: <Wrench className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-33'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-innovator-2',
            index: 32
        },
        {
            id: 'ehe-teen-34',
            title: 'Puzzle: Process Match',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-34'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/puzzle-process-match',
            index: 33
        },
        {
            id: 'ehe-teen-35',
            title: 'Idea Story',
            icon: <Lightbulb className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-35'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/idea-story',
            index: 34
        },
        {
            id: 'ehe-teen-36',
            title: 'Debate: Innovation = Only Tech?',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-36'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/debate-innovation-tech',
            index: 35
        },
        {
            id: 'ehe-teen-37',
            title: 'Journal of Teen Innovation',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-37'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/journal-teen-innovation',
            index: 36
        },
        {
            id: 'ehe-teen-38',
            title: 'Simulation: Prototype Test',
            icon: <Cpu className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-38'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/simulation-prototype-test',
            index: 37
        },
        {
            id: 'ehe-teen-39',
            title: 'Reflex Teen Design Thinking',
            icon: <RotateCcw className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-39'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-design-thinking',
            index: 38
        },
        {
            id: 'ehe-teen-40',
            title: 'Badge: Teen Innovator',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-40'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/badge-teen-innovator',
            index: 39
        },
        // New games (levels 41-50)
        {
            id: 'ehe-teen-41',
            title: 'App Builder Story',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-41'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/app-builder-story',
            index: 40
        },
        {
            id: 'ehe-teen-42',
            title: 'Quiz on Teen Entrepreneurs',
            icon: <Rocket className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-42'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/quiz-teen-entrepreneurs',
            index: 41
        },
        {
            id: 'ehe-teen-43',
            title: 'Reflex Teen Entrepreneur',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-43'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-entrepreneur',
            index: 42
        },
        {
            id: 'ehe-teen-44',
            title: 'Puzzle: Famous Teens',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-44'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/puzzle-famous-teens',
            index: 43
        },
        {
            id: 'ehe-teen-45',
            title: 'Fashion Story',
            icon: <Shirt className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-45'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/fashion-story',
            index: 44
        },
        {
            id: 'ehe-teen-46',
            title: 'Debate: Too Young to Start?',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-46'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/debate-too-young-start',
            index: 45
        },
        {
            id: 'ehe-teen-47',
            title: 'Journal of Role Models',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-47'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/journal-role-models',
            index: 46
        },
        {
            id: 'ehe-teen-48',
            title: 'Simulation: Teen Business',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-48'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/simulation-teen-business',
            index: 47
        },
        {
            id: 'ehe-teen-49',
            title: 'Reflex Teen Boss',
            icon: <TrendingUp className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-49'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-boss',
            index: 48
        },
        {
            id: 'ehe-teen-50',
            title: 'Badge: Teenpreneur',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-50'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/badge-teenpreneur',
            index: 49
        },
        // New games (levels 51-60)
        {
            id: 'ehe-teen-51',
            title: 'Higher Education Story',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-51'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/higher-education-story',
            index: 50
        },
        {
            id: 'ehe-teen-52',
            title: 'Quiz on Teen Paths',
            icon: <Rocket className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-52'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/quiz-teen-paths',
            index: 51
        },
        {
            id: 'ehe-teen-53',
            title: 'Reflex Teen Career',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-53'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-career-2',
            index: 52
        },
        {
            id: 'ehe-teen-54',
            title: 'Puzzle: Pathway Match',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-54'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/puzzle-pathway-match',
            index: 53
        },
        {
            id: 'ehe-teen-55',
            title: 'Gap Year Story',
            icon: <Calendar className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-55'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/gap-year-story',
            index: 54
        },
        {
            id: 'ehe-teen-56',
            title: 'Debate: Degree or Skill?',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-56'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/debate-degree-or-skill',
            index: 55
        },
        {
            id: 'ehe-teen-57',
            title: 'Journal of Teen Paths',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-57'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/journal-teen-paths',
            index: 56
        },
        {
            id: 'ehe-teen-58',
            title: 'Simulation: Career Decision',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-58'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/simulation-career-decision',
            index: 57
        },
        {
            id: 'ehe-teen-59',
            title: 'Reflex Teen Direction',
            icon: <TrendingUp className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-59'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-direction',
            index: 58
        },
        {
            id: 'ehe-teen-60',
            title: 'Badge: Career Path Finder',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-60'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/badge-career-path-finder',
            index: 59
        },
        // New games (levels 61-70)
        {
            id: 'ehe-teen-61',
            title: 'Stream Choice Story',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-61'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/stream-choice-story',
            index: 60
        },
        {
            id: 'ehe-teen-62',
            title: 'Quiz on Higher Studies',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-62'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/quiz-higher-studies',
            index: 61
        },
        {
            id: 'ehe-teen-63',
            title: 'Reflex Teen Higher Ed',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-63'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-higher-ed',
            index: 62
        },
        {
            id: 'ehe-teen-64',
            title: 'Puzzle: Career Paths',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-64'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/puzzle-career-paths',
            index: 63
        },
        {
            id: 'ehe-teen-65',
            title: 'Abroad Study Story',
            icon: <Globe className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-65'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/abroad-study-story',
            index: 64
        },
        {
            id: 'ehe-teen-66',
            title: 'Debate: Local vs Global',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-66'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/debate-local-vs-global',
            index: 65
        },
        {
            id: 'ehe-teen-67',
            title: 'Journal of Teen Goals',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-67'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/journal-teen-goals',
            index: 66
        },
        {
            id: 'ehe-teen-68',
            title: 'Simulation: Entrance Prep',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-68'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/simulation-entrance-prep',
            index: 67
        },
        {
            id: 'ehe-teen-69',
            title: 'Reflex Teen Awareness',
            icon: <TrendingUp className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-69'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-awareness',
            index: 68
        },
        {
            id: 'ehe-teen-70',
            title: 'Badge: Higher Ed Ready Teen',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-70'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/badge-higher-ed-ready-teen',
            index: 69
        },
        // New games (levels 71-80)
        {
            id: 'ehe-teen-71',
            title: 'Green Energy Story',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-71'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/green-energy-story',
            index: 70
        },
        {
            id: 'ehe-teen-72',
            title: 'Quiz on Emerging Careers',
            icon: <Rocket className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-72'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/quiz-emerging-careers',
            index: 71
        },
        {
            id: 'ehe-teen-73',
            title: 'Reflex Teen Future Check',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-73'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-future-check',
            index: 72
        },
        {
            id: 'ehe-teen-74',
            title: 'Puzzle: Match Careers',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-74'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/puzzle-match-careers',
            index: 73
        },
        {
            id: 'ehe-teen-75',
            title: 'Freelance Story',
            icon: <Laptop className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-75'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/freelance-story',
            index: 74
        },
        {
            id: 'ehe-teen-76',
            title: 'Debate: Robots Take Jobs?',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-76'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/debate-robots-take-jobs',
            index: 75
        },
        {
            id: 'ehe-teen-77',
            title: 'Journal of Future Skills',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-77'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/journal-future-skills',
            index: 76
        },
        {
            id: 'ehe-teen-78',
            title: 'Simulation: Teen Career Fair',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-78'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/simulation-teen-career-fair',
            index: 77
        },
        {
            id: 'ehe-teen-79',
            title: 'Reflex Teen Alert',
            icon: <TrendingUp className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-79'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-alert',
            index: 78
        },
        {
            id: 'ehe-teen-80',
            title: 'Badge: Future Ready Teen',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-80'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/badge-future-ready-teen',
            index: 79
        },
        // New games (levels 81-90)
        {
            id: 'ehe-teen-81',
            title: 'Social Business Story',
            icon: <Globe className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-81'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/social-business-story',
            index: 80
        },
        {
            id: 'ehe-teen-82',
            title: 'Quiz on Changemakers',
            icon: <Rocket className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-82'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/quiz-changemakers',
            index: 81
        },
        {
            id: 'ehe-teen-83',
            title: 'Reflex Teen Changemaker',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-83'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-changemaker',
            index: 82
        },
        {
            id: 'ehe-teen-84',
            title: 'Puzzle: Social Leaders',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-84'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/puzzle-social-leaders',
            index: 83
        },
        {
            id: 'ehe-teen-85',
            title: 'Clean Water Story',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-85'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/clean-water-story',
            index: 84
        },
        {
            id: 'ehe-teen-86',
            title: 'Debate: Profit vs Purpose',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-86'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/debate-profit-vs-purpose',
            index: 85
        },
        {
            id: 'ehe-teen-87',
            title: 'Journal of Impact',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-87'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/journal-of-impact',
            index: 86
        },
        {
            id: 'ehe-teen-88',
            title: 'Simulation: Teen Startup',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-88'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/simulation-teen-startup',
            index: 87
        },
        {
            id: 'ehe-teen-89',
            title: 'Reflex Teen Responsibility',
            icon: <Recycle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-89'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-responsibility',
            index: 88
        },
        {
            id: 'ehe-teen-90',
            title: 'Badge: Teen Changemaker',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-90'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/badge-teen-changemaker',
            index: 89
        },
        // New games (levels 91-100)
        {
            id: 'ehe-teen-91',
            title: 'Skill Upgrade Story',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-91'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/skill-upgrade-story',
            index: 90
        },
        {
            id: 'ehe-teen-92',
            title: 'Quiz on Career Growth',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-92'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/quiz-career-growth',
            index: 91
        },
        {
            id: 'ehe-teen-93',
            title: 'Reflex Teen Growth',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-93'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-growth',
            index: 92
        },
        {
            id: 'ehe-teen-94',
            title: 'Puzzle: Career Growth Steps',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-94'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/puzzle-career-growth-steps',
            index: 93
        },
        {
            id: 'ehe-teen-95',
            title: 'Mentor Story',
            icon: <UserPlus className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-95'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/mentor-story',
            index: 94
        },
        {
            id: 'ehe-teen-96',
            title: 'Debate: Learning Ends After College?',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-96'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/debate-learning-ends-college',
            index: 95
        },
        {
            id: 'ehe-teen-97',
            title: 'Journal of Growth Plans',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-97'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/journal-growth-plans',
            index: 96
        },
        {
            id: 'ehe-teen-98',
            title: 'Simulation: Career Upgrade',
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-98'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/simulation-career-upgrade',
            index: 97
        },
        {
            id: 'ehe-teen-99',
            title: 'Reflex Career Alert',
            icon: <TrendingUp className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-99'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-career-alert',
            index: 98
        },
        {
            id: 'ehe-teen-100',
            title: 'Badge: Lifelong Learner Pro',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-100'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/badge-lifelong-learner-pro',
            index: 99
        }
    ];

    return eheTeenGames;
};

export default getEheTeenGames;
