import {
    Lightbulb,
    GraduationCap,
    Briefcase,
    Target,
    Zap,
    BookOpen,
    MessageCircle,
    Smartphone,
    Badge,
    Users,
    TrendingUp,
    Brain,
    Hammer,
    Wallet,
    PiggyBank,
    Calculator,
    ChartLine,
    Heart,
    Cpu,
    Wrench,
    RotateCcw,
    Rocket,
    Shirt,
    ShoppingCart,
    Calendar,
    Sun,
    Laptop,
    Globe,
    Recycle,
    Droplets,
    UserPlus,
} from "lucide-react";
import buildIds from "../buildGameIds";

export const eheGameIdsTeen = buildIds("ehe", "teen");

export const getEheTeenGames = (gameCompletionStatus)=> {
    const eheTeenGames = [
        {
            id: 'ehe-teen-1',
            title: 'Career Story',
            description: 'Teen loves drawing. Which career fits? → Designer/Artist.',
            icon: <Lightbulb className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-1'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/career-story',
            index: 0
        },
        {
            id: 'ehe-teen-2',
            title: 'Quiz on Careers',
            description: 'Which career needs coding? (a) Teacher, (b) Software Engineer, (c) Farmer). Correct = Software Engineer.',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-2'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/quiz-on-careers',
            index: 1
        },
        {
            id: 'ehe-teen-3',
            title: 'Reflex Teen Career',
            description: 'Tap ⚖️ for "Lawyer = Court," ❌ for "Lawyer = Hospital."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-3'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-career',
            index: 2
        },
        {
            id: 'ehe-teen-4',
            title: 'Puzzle: Career Match',
            description: 'Match "Scientist → Research, Chef → Food, Pilot → Airplane."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-4'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/puzzle-career-match',
            index: 3
        },
        {
            id: 'ehe-teen-5',
            title: 'Passion Story',
            description: 'Teen loves helping people. Best career? → Social Worker/Doctor.',
            icon: <Lightbulb className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-5'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/passion-story',
            index: 4
        },
        {
            id: 'ehe-teen-6',
            title: 'Debate: One Career or Many?',
            description: 'Should teens pick one career early or explore many? → Explore first.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-6'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/debate-one-career-or-many',
            index: 5
        },
        {
            id: 'ehe-teen-7',
            title: 'Journal of Career Choice',
            description: 'Write: "A career I want to explore is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-7'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/journal-of-career-choice',
            index: 6
        },
        {
            id: 'ehe-teen-8',
            title: 'Simulation: Career Fair',
            description: 'Teen visits a career fair. Options: Ask questions / Stay silent / Leave early. Correct = Ask questions.',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-8'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/simulation-career-fair',
            index: 7
        },
        {
            id: 'ehe-teen-9',
            title: 'Reflex Future Check',
            description: 'Tap 🏗️ for "Engineer = Build," ❌ for "Engineer = Cook."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-9'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-future-check',
            index: 8
        },
        {
            id: 'ehe-teen-10',
            title: 'Badge: Career Aware Teen',
            description: 'Explore 5 careers responsibly to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-10'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/badge-career-aware-teen',
            index: 9
        },
        // Games 11-20
        {
            id: 'ehe-teen-11',
            title: 'Opportunity Story',
            description: 'Teen notices friends need healthy snacks. Should she start a snack stall? → Yes.',
            icon: <Lightbulb className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-11'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/opportunity-story',
            index: 10
        },
        {
            id: 'ehe-teen-12',
            title: 'Quiz on Entrepreneur Traits',
            description: 'Which is key? (a) Creativity, (b) Laziness, (c) Quitting). Correct = Creativity.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-12'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/quiz-entrepreneur-traits',
            index: 11
        },
        {
            id: 'ehe-teen-13',
            title: 'Reflex Teen Skills',
            description: 'Tap 👑 for "Leadership," ❌ for "Bullying."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-13'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-skills',
            index: 12
        },
        {
            id: 'ehe-teen-14',
            title: 'Puzzle: Match Traits',
            description: 'Match "Leader → Inspire, Risk-Taker → Try New, Innovator → Create."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-14'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/puzzle-match-traits',
            index: 13
        },
        {
            id: 'ehe-teen-15',
            title: 'Failure Story',
            description: 'Teen\'s first project fails. Should she give up? → No, try again.',
            icon: <TrendingUp className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-15'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/failure-story',
            index: 14
        },
        {
            id: 'ehe-teen-16',
            title: 'Debate: Born or Made?',
            description: 'Are entrepreneurs born or made? → Made, with skills.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-16'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/debate-born-or-made',
            index: 15
        },
        {
            id: 'ehe-teen-17',
            title: 'Journal of Strengths',
            description: 'Write: "One strength I have as a future entrepreneur is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-17'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/journal-of-strengths',
            index: 16
        },
        {
            id: 'ehe-teen-18',
            title: 'Simulation: Team Project',
            description: 'Team disagrees. Options: Listen + solve / Shout / Quit. Correct = Listen + solve.',
            icon: <Users className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-18'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/simulation-team-project',
            index: 17
        },
        {
            id: 'ehe-teen-19',
            title: 'Reflex Teen Innovator',
            description: 'Tap 💡 for "Creative Ideas," ❌ for "Copy Others."',
            icon: <Hammer className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-19'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-innovator',
            index: 18
        },
        {
            id: 'ehe-teen-20',
            title: 'Badge: Future Entrepreneur',
            description: 'Master 5 entrepreneur skills to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-20'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/badge-future-entrepreneur',
            index: 19
        },
        // Games 21-30
        {
            id: 'ehe-teen-21',
            title: 'Cost Story',
            description: 'Teen sells sandwiches. Ingredients cost ₹100, selling ₹200. What is left? → Profit ₹100.',
            icon: <Wallet className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-21'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/cost-story',
            index: 20
        },
        {
            id: 'ehe-teen-22',
            title: 'Quiz on Business Terms',
            description: 'Profit means? (a) Extra money after costs, (b) Total sales). Correct = Extra money.',
            icon: <Calculator className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-22'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/quiz-business-terms',
            index: 21
        },
        {
            id: 'ehe-teen-23',
            title: 'Reflex Teen Money',
            description: 'Tap 💰 for "Profit = Good," ❌ for "Loss = Happy."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-23'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-money',
            index: 22
        },
        {
            id: 'ehe-teen-24',
            title: 'Puzzle: Match Business Terms',
            description: 'Match "Cost → Raw Material, Profit → Extra, Loss → Overspend."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-24'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/puzzle-business-terms',
            index: 23
        },
        {
            id: 'ehe-teen-25',
            title: 'Budget Story',
            description: 'Teen earns ₹500. Should she spend all or make a budget? → Make a budget.',
            icon: <PiggyBank className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['ehe-teen-25'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/budget-story',
            index: 24
        },
        {
            id: 'ehe-teen-26',
            title: 'Debate: Save or Spend?',
            description: 'Is saving more important than spending? → Balance is best.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-26'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/debate-save-or-spend',
            index: 25
        },
        {
            id: 'ehe-teen-27',
            title: 'Journal of Business Money',
            description: 'Write: "I learned profit is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-27'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/journal-business-money',
            index: 26
        },
        {
            id: 'ehe-teen-28',
            title: 'Simulation: Teen Shop',
            description: 'Teen opens shop. Options: Keep accounts / Spend blindly / Close shop. Correct = Keep accounts.',
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-28'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/simulation-teen-shop',
            index: 27
        },
        {
            id: 'ehe-teen-29',
            title: 'Reflex Business Alert',
            description: 'Tap 📊 for "Budget Plan," ❌ for "Random Spend."',
            icon: <ChartLine className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-29'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-business-alert',
            index: 28
        },
        {
            id: 'ehe-teen-30',
            title: 'Badge: Money Wise Teen',
            description: 'Handle 5 business money cases to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-30'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/badge-money-wise-teen',
            index: 29
        },
        // Games 31-40
        {
            id: 'ehe-teen-31',
            title: 'Empathy Story',
            description: 'A friend struggles to carry books. What\'s first step in design thinking? → Understand problem (empathy).',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-31'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/empathy-story',
            index: 30
        },
        {
            id: 'ehe-teen-32',
            title: 'Quiz on Design Thinking',
            description: 'First stage of design thinking? (a) Empathy, (b) Random guessing). Correct = Empathy.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-32'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/quiz-design-thinking',
            index: 31
        },
        {
            id: 'ehe-teen-33',
            title: 'Reflex Teen Innovator',
            description: 'Tap 🛠️ for "Prototype," ❌ for "Ignore Ideas."',
            icon: <Wrench className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-33'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-innovator-2',
            index: 32
        },
        {
            id: 'ehe-teen-34',
            title: 'Puzzle: Process Match',
            description: 'Match "Empathize → Understand, Ideate → Brainstorm, Prototype → Build."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-34'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/puzzle-process-match',
            index: 33
        },
        {
            id: 'ehe-teen-35',
            title: 'Idea Story',
            description: 'Teen notices waste in canteen. What should she do? → Think of waste-reduction ideas.',
            icon: <Lightbulb className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-35'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/idea-story',
            index: 34
        },
        {
            id: 'ehe-teen-36',
            title: 'Debate: Innovation = Only Tech?',
            description: 'Is innovation only about gadgets? → No, any new idea counts.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-36'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/debate-innovation-tech',
            index: 35
        },
        {
            id: 'ehe-teen-37',
            title: 'Journal of Teen Innovation',
            description: 'Write: "One problem I want to solve is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-37'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/journal-teen-innovation',
            index: 36
        },
        {
            id: 'ehe-teen-38',
            title: 'Simulation: Prototype Test',
            description: 'Teen designs app idea. Options: Test with friends / Hide / Give up. Correct = Test with friends.',
            icon: <Cpu className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-38'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/simulation-prototype-test',
            index: 37
        },
        {
            id: 'ehe-teen-39',
            title: 'Reflex Teen Design Thinking',
            description: 'Tap 🔄 for "Improve After Feedback," ❌ for "Never Change Idea."',
            icon: <RotateCcw className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-39'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-design-thinking',
            index: 38
        },
        {
            id: 'ehe-teen-40',
            title: 'Badge: Teen Innovator',
            description: 'Complete 5 design thinking activities to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-40'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/badge-teen-innovator',
            index: 39
        },
        // New games (levels 41-50)
        {
            id: 'ehe-teen-41',
            title: 'App Builder Story',
            description: 'A 15-year-old creates a mobile app. What did she do? → Innovated.',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-41'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/app-builder-story',
            index: 40
        },
        {
            id: 'ehe-teen-42',
            title: 'Quiz on Teen Entrepreneurs',
            description: 'Which quality do they show? (a) Risk-taking, (b) Doing nothing). Correct = Risk-taking.',
            icon: <Rocket className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-42'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/quiz-teen-entrepreneurs',
            index: 41
        },
        {
            id: 'ehe-teen-43',
            title: 'Reflex Teen Entrepreneur',
            description: 'Tap 🚀 for "Start Early," ❌ for "Wait Forever."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-43'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-entrepreneur',
            index: 42
        },
        {
            id: 'ehe-teen-44',
            title: 'Puzzle: Famous Teens',
            description: 'Match "Moziah Bridges → Tie Business, Cory Nieves → Cookies, Alina Morse → Candy."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-44'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/puzzle-famous-teens',
            index: 43
        },
        {
            id: 'ehe-teen-45',
            title: 'Fashion Story',
            description: 'A 16-year-old starts a clothing brand. What did she show? → Creativity & Business Mind.',
            icon: <Shirt className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-45'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/fashion-story',
            index: 44
        },
        {
            id: 'ehe-teen-46',
            title: 'Debate: Too Young to Start?',
            description: 'Can teens run businesses successfully? → Yes.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-46'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/debate-too-young-start',
            index: 45
        },
        {
            id: 'ehe-teen-47',
            title: 'Journal of Role Models',
            description: 'Write: "The teen entrepreneur who inspires me is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-47'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/journal-role-models',
            index: 46
        },
        {
            id: 'ehe-teen-48',
            title: 'Simulation: Teen Business',
            description: 'Teen runs online store. Options: Deliver on time / Delay / Quit. Correct = Deliver on time.',
            icon: <ShoppingCart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-48'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/simulation-teen-business',
            index: 47
        },
        {
            id: 'ehe-teen-49',
            title: 'Reflex Teen Boss',
            description: 'Tap 📈 for "Learn & Grow," ❌ for "Stay Idle."',
            icon: <TrendingUp className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-49'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-boss',
            index: 48
        },
        {
            id: 'ehe-teen-50',
            title: 'Badge: Teenpreneur',
            description: 'Explore 5 teen entrepreneur stories to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['ehe-teen-50'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/badge-teenpreneur',
            index: 49
        },
        // New games (levels 51-60)
        {
            id: 'ehe-teen-51',
            title: 'Higher Education Story',
            description: 'Teen wants to be a doctor. What must she study? → Medicine in college.',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-51'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/higher-education-story',
            index: 50
        },
        {
            id: 'ehe-teen-52',
            title: 'Quiz on Teen Paths',
            description: 'Which is a career path after school? (a) College, (b) Vocational training, (c) Both). Correct = Both.',
            icon: <Rocket className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-52'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/quiz-teen-paths',
            index: 51
        },
        {
            id: 'ehe-teen-53',
            title: 'Reflex Teen Career',
            description: 'Tap 🎯 for "Choose Path," ❌ for "No Direction."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-53'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-career-2',
            index: 52
        },
        {
            id: 'ehe-teen-54',
            title: 'Puzzle: Pathway Match',
            description: 'Match "Lawyer → Law School, Artist → Design College, Engineer → Tech College."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-54'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/puzzle-pathway-match',
            index: 53
        },
        {
            id: 'ehe-teen-55',
            title: 'Gap Year Story',
            description: 'Teen takes gap year to learn coding. Is this useful? → Yes, if skills are built.',
            icon: <Calendar className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-55'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/gap-year-story',
            index: 54
        },
        {
            id: 'ehe-teen-56',
            title: 'Debate: Degree or Skill?',
            description: 'Which is more important—degree or skill? → Skills with degree are best.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-56'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/debate-degree-or-skill',
            index: 55
        },
        {
            id: 'ehe-teen-57',
            title: 'Journal of Teen Paths',
            description: 'Write: "One career path I want to explore is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-57'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/journal-teen-paths',
            index: 56
        },
        {
            id: 'ehe-teen-58',
            title: 'Simulation: Career Decision',
            description: 'Teen has choices: Medicine / Engineering / Arts. Should she decide based on parents only or interests + research? → Interests + research.',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-58'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/simulation-career-decision',
            index: 57
        },
        {
            id: 'ehe-teen-59',
            title: 'Reflex Teen Direction',
            description: 'Tap 🗺️ for "Career Planning," ❌ for "No Planning."',
            icon: <TrendingUp className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-59'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-direction',
            index: 58
        },
        {
            id: 'ehe-teen-60',
            title: 'Badge: Career Path Finder',
            description: 'Explore 5 teen pathways responsibly to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-60'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/badge-career-path-finder',
            index: 59
        },
        // New games (levels 61-70)
        {
            id: 'ehe-teen-61',
            title: 'Stream Choice Story',
            description: 'Teen loves biology. Which higher education path suits her? → Medicine.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-61'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/stream-choice-story',
            index: 60
        },
        {
            id: 'ehe-teen-62',
            title: 'Quiz on Higher Studies',
            description: 'Which is a higher education stream? (a) Arts, (b) Science, (c) Commerce, (d) All). Correct = All.',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-62'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/quiz-higher-studies',
            index: 61
        },
        {
            id: 'ehe-teen-63',
            title: 'Reflex Teen Higher Ed',
            description: 'Tap 🎓 for "Choose Based on Interests," ❌ for "Copy Friends."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-63'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-higher-ed',
            index: 62
        },
        {
            id: 'ehe-teen-64',
            title: 'Puzzle: Career Paths',
            description: 'Match "Engineer → Tech College, Lawyer → Law College, Artist → Fine Arts College."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-64'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/puzzle-career-paths',
            index: 63
        },
        {
            id: 'ehe-teen-65',
            title: 'Abroad Study Story',
            description: 'Teen dreams of studying abroad. What is needed? → Preparation + exams + funds.',
            icon: <Globe className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-65'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/abroad-study-story',
            index: 64
        },
        {
            id: 'ehe-teen-66',
            title: 'Debate: Local vs Global',
            description: 'Is studying abroad better than local? → Both have value.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-66'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/debate-local-vs-global',
            index: 65
        },
        {
            id: 'ehe-teen-67',
            title: 'Journal of Teen Goals',
            description: 'Write: "One higher education goal I have is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-67'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/journal-teen-goals',
            index: 66
        },
        {
            id: 'ehe-teen-68',
            title: 'Simulation: Entrance Prep',
            description: 'Teen has an exam. Options: Study regularly / Skip prep / Last-minute panic. Correct = Study regularly.',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-68'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/simulation-entrance-prep',
            index: 67
        },
        {
            id: 'ehe-teen-69',
            title: 'Reflex Teen Awareness',
            description: 'Tap 💸 for "Scholarships Help," ❌ for "Give Up on Dreams."',
            icon: <TrendingUp className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-69'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-awareness',
            index: 68
        },
        {
            id: 'ehe-teen-70',
            title: 'Badge: Higher Ed Ready Teen',
            description: 'Complete 5 higher education challenges to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-70'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/badge-higher-ed-ready-teen',
            index: 69
        },
        // New games (levels 71-80)
        {
            id: 'ehe-teen-71',
            title: 'Green Energy Story',
            description: 'Teen sees solar panels. What career works here? → Renewable Energy Engineer.',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-71'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/green-energy-story',
            index: 70
        },
        {
            id: 'ehe-teen-72',
            title: 'Quiz on Emerging Careers',
            description: 'Which is an emerging field? (a) AI & Data Science, (b) Basket Weaving only). Correct = AI & Data Science.',
            icon: <Rocket className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-72'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/quiz-emerging-careers',
            index: 71
        },
        {
            id: 'ehe-teen-73',
            title: 'Reflex Teen Future Check',
            description: 'Tap 🛡️ for "Cybersecurity Jobs," ❌ for "Ghost Hunters."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-73'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-future-check',
            index: 72
        },
        {
            id: 'ehe-teen-74',
            title: 'Puzzle: Match Careers',
            description: 'Match "Space Scientist → Mars, Geneticist → DNA, Climate Scientist → Earth."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-74'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/puzzle-match-careers',
            index: 73
        },
        {
            id: 'ehe-teen-75',
            title: 'Freelance Story',
            description: 'Teen learns coding and works online. What is this called? → Freelancing.',
            icon: <Laptop className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['ehe-teen-75'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/freelance-story',
            index: 74
        },
        {
            id: 'ehe-teen-76',
            title: 'Debate: Robots Take Jobs?',
            description: 'Will robots take jobs or create new ones? → Create new ones too.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-76'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/debate-robots-take-jobs',
            index: 75
        },
        {
            id: 'ehe-teen-77',
            title: 'Journal of Future Skills',
            description: 'Write: "One skill I need for the future is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-77'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/journal-future-skills',
            index: 76
        },
        {
            id: 'ehe-teen-78',
            title: 'Simulation: Teen Career Fair',
            description: 'Teen explores AI, green jobs, gaming. Should she choose what excites her? → Yes.',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-78'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/simulation-teen-career-fair',
            index: 77
        },
        {
            id: 'ehe-teen-79',
            title: 'Reflex Teen Alert',
            description: 'Tap 🔄 for "Adapt to Change," ❌ for "Refuse Learning."',
            icon: <TrendingUp className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-79'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-alert',
            index: 78
        },
        {
            id: 'ehe-teen-80',
            title: 'Badge: Future Ready Teen',
            description: 'Complete 5 future job awareness activities to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-80'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/badge-future-ready-teen',
            index: 79
        },
        // New games (levels 81-90)
        {
            id: 'ehe-teen-81',
            title: 'Social Business Story',
            description: 'Teen creates an app to connect farmers to buyers. What is this? → Social business.',
            icon: <Globe className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-81'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/social-business-story',
            index: 80
        },
        {
            id: 'ehe-teen-82',
            title: 'Quiz on Changemakers',
            description: 'Which is a social entrepreneur\'s goal? (a) Profit only, (b) Social impact + profit). Correct = Social impact + profit.',
            icon: <Rocket className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-82'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/quiz-changemakers',
            index: 81
        },
        {
            id: 'ehe-teen-83',
            title: 'Reflex Teen Changemaker',
            description: 'Tap 🌍 for "Solve Problems," ❌ for "Ignore Society."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-83'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-changemaker',
            index: 82
        },
        {
            id: 'ehe-teen-84',
            title: 'Puzzle: Social Leaders',
            description: 'Match "Muhammad Yunus → Microfinance, Bunker Roy → Barefoot College, Kiran Mazumdar → Biotech."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-84'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/puzzle-social-leaders',
            index: 83
        },
        {
            id: 'ehe-teen-85',
            title: 'Clean Water Story',
            description: 'Teen designs filter for clean water in villages. What problem is solved? → Safe drinking water.',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-85'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/clean-water-story',
            index: 84
        },
        {
            id: 'ehe-teen-86',
            title: 'Debate: Profit vs Purpose',
            description: 'Which is more important? → Purpose with profit.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-86'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/debate-profit-vs-purpose',
            index: 85
        },
        {
            id: 'ehe-teen-87',
            title: 'Journal of Impact',
            description: 'Write: "The social problem I care most about is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-87'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/journal-of-impact',
            index: 86
        },
        {
            id: 'ehe-teen-88',
            title: 'Simulation: Teen Startup',
            description: 'Teen must choose: Cheap harmful product / Safe eco-product. Correct = Safe eco-product.',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-88'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/simulation-teen-startup',
            index: 87
        },
        {
            id: 'ehe-teen-89',
            title: 'Reflex Teen Responsibility',
            description: 'Tap ♻️ for "Eco-Friendly Business," ❌ for "Polluting Business."',
            icon: <Recycle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-89'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-responsibility',
            index: 88
        },
        {
            id: 'ehe-teen-90',
            title: 'Badge: Teen Changemaker',
            description: 'Complete 5 social entrepreneurship activities to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-90'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/badge-teen-changemaker',
            index: 89
        },
        // New games (levels 91-100)
        {
            id: 'ehe-teen-91',
            title: 'Skill Upgrade Story',
            description: 'Teen wants a promotion. Should she learn new skills? → Yes.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-91'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/skill-upgrade-story',
            index: 90
        },
        {
            id: 'ehe-teen-92',
            title: 'Quiz on Career Growth',
            description: 'Which helps in career growth? (a) Continuous learning, (b) Doing nothing new). Correct = Continuous learning.',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-92'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/quiz-career-growth',
            index: 91
        },
        {
            id: 'ehe-teen-93',
            title: 'Reflex Teen Growth',
            description: 'Tap 📚 for "Skill Upgrade," ❌ for "No Learning."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-93'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-teen-growth',
            index: 92
        },
        {
            id: 'ehe-teen-94',
            title: 'Puzzle: Career Growth Steps',
            description: 'Match "Courses → New Skills, Practice → Expertise, Feedback → Improvement."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-94'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/puzzle-career-growth-steps',
            index: 93
        },
        {
            id: 'ehe-teen-95',
            title: 'Mentor Story',
            description: 'Teen meets a mentor. Should she ask questions and learn? → Yes.',
            icon: <UserPlus className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-95'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/mentor-story',
            index: 94
        },
        {
            id: 'ehe-teen-96',
            title: 'Debate: Learning Ends After College?',
            description: 'Does learning stop after degree? → No, it continues.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-96'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/debate-learning-ends-college',
            index: 95
        },
        {
            id: 'ehe-teen-97',
            title: 'Journal of Growth Plans',
            description: 'Write: "One way I will keep learning is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-97'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/journal-growth-plans',
            index: 96
        },
        {
            id: 'ehe-teen-98',
            title: 'Simulation: Career Upgrade',
            description: 'Teen works at a company. Options: Take new course / Do same work / Quit. Correct = Take new course.',
            icon: <Briefcase className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-98'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/simulation-career-upgrade',
            index: 97
        },
        {
            id: 'ehe-teen-99',
            title: 'Reflex Career Alert',
            description: 'Tap 🚀 for "Adapt & Learn," ❌ for "Stay Stuck."',
            icon: <TrendingUp className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-99'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/reflex-career-alert',
            index: 98
        },
        {
            id: 'ehe-teen-100',
            title: 'Badge: Lifelong Learner Pro',
            description: 'Master 5 career growth challenges to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['ehe-teen-100'] || false,
            isSpecial: true,
            path: '/student/ehe/teens/badge-lifelong-learner-pro',
            index: 99
        }
    ];

    return eheTeenGames;
};

export default getEheTeenGames;