import {
  Trophy, Coins, Puzzle, Zap, Wallet, Heart, Target, BookOpen, GraduationCap,  ShoppingCart, Book, Candy, ClipboardList, Gift, Paintbrush, PenSquare, PartyPopper, HelpCircle, PiggyBank, CreditCard, Brush, HeartHandshake, ShoppingBag, Image, Clipboard
} from "lucide-react";

import buildIds from "../buildGameIds";


export const financegGameIdsKids = buildIds("finance", "kids")

export const getFinanceKidsGames = (gameCompletionStatus)=> {
    const financeGamesKids = [
        {
          id: "finance-kids-1",
          title: "Money Bank Story",
          icon: <Wallet className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-1"] || false,
          isSpecial: true,
          path: "/student/finance/kids/money-bank-story",
          index: 0,
        },
        {
          id: "finance-kids-2",
          title: "Quiz on Saving",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-2"] || false,
          isSpecial: true,
          path: "/student/finance/kids/quiz-on-saving",
          index: 1,
        },
        {
          id: "finance-kids-3",
          title: "Reflex Savings",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-3"] || false,
          isSpecial: true,
          path: "/student/finance/kids/reflex-savings",
          index: 2,
        },
        {
          id: "finance-kids-4",
          title: "Puzzle: Save or Spend",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-4"] || false,
          isSpecial: true,
          path: "/student/finance/kids/puzzle-save-or-spend",
          index: 3,
        },
        {
          id: "finance-kids-5",
          title: "Birthday Money Story",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-5"] || false,
          isSpecial: true,
          path: "/student/finance/kids/birthday-money-story",
          index: 4,
        },
        {
          id: "finance-kids-6",
          title: "Poster: Saving Habit",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-6"] || false,
          isSpecial: true,
          path: "/student/finance/kids/poster-saving-habit",
          index: 5,
        },
        {
          id: "finance-kids-7",
          title: "Journal of Saving",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-7"] || false,
          isSpecial: true,
          path: "/student/finance/kids/journal-of-saving",
          index: 6,
        },
        {
          id: "finance-kids-8",
          title: "Shop Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-8"] || false,
          isSpecial: true,
          path: "/student/finance/kids/shop-story",
          index: 7,
        },
        {
          id: "finance-kids-9",
          title: "Reflex Money Choice",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-9"] || false,
          isSpecial: true,
          path: "/student/finance/kids/reflex-money-choice",
          index: 8,
        },
        {
          id: "finance-kids-10",
          title: "Badge: Saver Kid",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-10"] || false,
          isSpecial: true,
          path: "/student/finance/kids/badge-saver-kid",
          index: 9,
        },
        {
          id: "finance-kids-11",
          title: "Ice Cream Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-11"] || false,
          isSpecial: true,
          path: "/student/finance/kids/ice-cream-story",
          index: 10,
        },
        {
          id: "finance-kids-12",
          title: "Quiz on Spending",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-12"] || false,
          isSpecial: true,
          path: "/student/finance/kids/quiz-on-spending",
          index: 11,
        },
        {
          id: "finance-kids-13",
          title: "Reflex Spending",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-13"] || false,
          isSpecial: true,
          path: "/student/finance/kids/reflex-spending",
          index: 12,
        },
        {
          id: "finance-kids-14",
          title: "Puzzle: Smart vs Waste",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-14"] || false,
          isSpecial: true,
          path: "/student/finance/kids/puzzle-smart-vs-waste",
          index: 13,
        },
        {
          id: "finance-kids-15",
          title: "Shop Story 2",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-15"] || false,
          isSpecial: true,
          path: "/student/finance/kids/shop-story-2",
          index: 14,
        },
        {
          id: "finance-kids-16",
          title: "Poster: Smart Shopping",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-16"] || false,
          isSpecial: true,
          path: "/student/finance/kids/poster-smart-shopping",
          index: 15,
        },
        {
          id: "finance-kids-17",
          title: "Journal of Smart Buy",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-17"] || false,
          isSpecial: true,
          path: "/student/finance/kids/journal-of-smart-buy",
          index: 16,
        },
        {
          id: "finance-kids-18",
          title: "Candy Offer Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-18"] || false,
          isSpecial: true,
          path: "/student/finance/kids/candy-offer-story",
          index: 17,
        },
        {
          id: "finance-kids-19",
          title: "Reflex Needs First",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-19"] || false,
          isSpecial: true,
          path: "/student/finance/kids/reflex-needs-first",
          index: 18,
        },
        {
          id: "finance-kids-20",
          title: "Badge: Smart Spender Kid",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-20"] || false,
          isSpecial: true,
          path: "/student/finance/kids/badge-smart-spender-kid",
          index: 19,
        },
        {
          id: "finance-kids-21",
          title: "Candy Story",
          icon: <Candy className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-21"] || false,
          isSpecial: true,
          path: "/student/finance/kids/Candy-Story",
          index: 20,
        },
        {
          id: "finance-kids-22",
          title: "Quiz on Budgeting",
          icon: <ClipboardList className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-22"] || false,
          isSpecial: true,
          path: "/student/finance/kids/Budgeting-Quiz",
          index: 21,
        },
        {
          id: "finance-kids-23",
          title: "Reflex Budget",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-23"] || false,
          isSpecial: true,
          path: "/student/finance/kids/Reflex-Budget",
          index: 22,
        },
        {
          id: "finance-kids-24",
          title: "Puzzle: Budget Items",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-24"] || false,
          isSpecial: true,
          path: "/student/finance/kids/Budget-Items-Puzzle",
          index: 23,
        },
        {
          id: "finance-kids-25",
          title: "Birthday Money Story",
          icon: <Gift className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-kids-25"] || false,
          isSpecial: true,
          path: "/student/finance/kids/Birthday-Money",
          index: 24,
        },
        {
          id: "finance-kids-26",
          title: "Poster: Plan First",
          icon: <Paintbrush className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-26"] || false,
          isSpecial: true,
          path: "/student/finance/kids/Poster-Plan-First",
          index: 25,
        },
        {
          id: "finance-kids-27",
          title: "Journal of Budgeting",
          icon: <PenSquare className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-27"] || false,
          isSpecial: true,
          path: "/student/finance/kids/Journal-Of-Budgeting",
          index: 26,
        },
        {
          id: "finance-kids-28",
          title: "School Fair Story",
          icon: <PartyPopper className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-28"] || false,
          isSpecial: true,
          path: "/student/finance/kids/School-Fair-Story",
          index: 27,
        },
        {
          id: "finance-kids-29",
          title: "Reflex Money Plan",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-29"] || false,
          isSpecial: true,
          path: "/student/finance/kids/Reflex-Money-Plan",
          index: 28,
        },
        {
          id: "finance-kids-30",
          title: "Badge: Budget Kid",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-30"] || false,
          isSpecial: true,
          path: "/student/finance/kids/Badge-Budget-Kid",
          index: 29,
        },
        {
          id: "finance-kids-31",
          title: "Ice Cream vs School Book Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-31"] || false,
          isSpecial: true,
          path: "/student/finance/kids/ice-cream-vs-book-story",
          index: 30,
        },
        {
          id: "finance-kids-32",
          title: "Quiz on Needs",
          icon: <ClipboardList className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-32"] || false,
          isSpecial: true,
          path: "/student/finance/kids/quiz-on-needs",
          index: 31,
        },
        {
          id: "finance-kids-33",
          title: "Reflex Need vs Want",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-33"] || false,
          isSpecial: true,
          path: "/student/finance/kids/reflex-need-vs-want",
          index: 32,
        },
        {
          id: "finance-kids-34",
          title: "Puzzle of Needs/Wants",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-34"] || false,
          isSpecial: true,
          path: "/student/finance/kids/puzzle-needs-wants",
          index: 33,
        },
        {
          id: "finance-kids-35",
          title: "Snack Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-35"] || false,
          isSpecial: true,
          path: "/student/finance/kids/snack-story",
          index: 34,
        },
        {
          id: "finance-kids-36",
          title: "Poster: Needs First",
          icon: <ClipboardList className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-36"] || false,
          isSpecial: true,
          path: "/student/finance/kids/poster-needs-first",
          index: 35,
        },
        {
          id: "finance-kids-37",
          title: "Journal of Needs",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-37"] || false,
          isSpecial: true,
          path: "/student/finance/kids/journal-of-needs",
          index: 36,
        },
        {
          id: "finance-kids-38",
          title: "Gift Money Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-38"] || false,
          isSpecial: true,
          path: "/student/finance/kids/gift-money-story",
          index: 37,
        },
        {
          id: "finance-kids-39",
          title: "Reflex Smart Pick",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-39"] || false,
          isSpecial: true,
          path: "/student/finance/kids/reflex-smart-pick",
          index: 38,
        },
        {
          id: "finance-kids-40",
          title: "Badge: Needs First Kid",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-40"] || false,
          isSpecial: true,
          path: "/student/finance/kids/needs-first-kid-badge",
          index: 39,
        },
        {
          id: "finance-kids-41",
          title: "Bank Visit Story",
          icon: <PiggyBank className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-41"] || false,
          isSpecial: true,
          path: "/student/finance/kids/bank-visit-story",
          index: 40,
        },
        {
          id: "finance-kids-42",
          title: "Quiz on Banks",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-42"] || false,
          isSpecial: true,
          path: "/student/finance/kids/quiz-banks",
          index: 41,
        },
        {
          id: "finance-kids-43",
          title: "Reflex Bank Basics",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-43"] || false,
          isSpecial: true,
          path: "/student/finance/kids/reflex-bank",
          index: 42,
        },
        {
          id: "finance-kids-44",
          title: "Puzzle: Bank Uses",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-44"] || false,
          isSpecial: true,
          path: "/student/finance/kids/puzzle-bank-uses",
          index: 43,
        },
        {
          id: "finance-kids-45",
          title: "Savings Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-45"] || false,
          isSpecial: true,
          path: "/student/finance/kids/savings-story",
          index: 44,
        },
        {
          id: "finance-kids-46",
          title: "Poster: Banks Help",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-46"] || false,
          isSpecial: true,
          path: "/student/finance/kids/poster-banks-help",
          index: 45,
        },
        {
          id: "finance-kids-47",
          title: "Journal of First Bank Visit",
          icon: <Book className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-47"] || false,
          isSpecial: true,
          path: "/student/finance/kids/journal-first-bank",
          index: 46,
        },
        {
          id: "finance-kids-48",
          title: "ATM Story",
          icon: <CreditCard className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-48"] || false,
          isSpecial: true,
          path: "/student/finance/kids/atm-story",
          index: 47,
        },
        {
          id: "finance-kids-49",
          title: "Reflex Banking Symbols",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-49"] || false,
          isSpecial: true,
          path: "/student/finance/kids/reflex-bank-symbols",
          index: 48,
        },
        {
          id: "finance-kids-50",
          title: "Badge: Bank Explorer",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-kids-50"] || false,
          isSpecial: true,
          path: "/student/finance/kids/badge-bank-explorer",
          index: 49,
        },
        {
          id: "finance-kids-51",
          title: "Pencil Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-51"] || false,
          isSpecial: true,
          path: "/student/finance/kids/pencil-story",
          index: 50,
        },
        {
          id: "finance-kids-52",
          title: "Quiz on Borrowing",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-52"] || false,
          isSpecial: true,
          path: "/student/finance/kids/quiz-borrowing",
          index: 51,
        },
        {
          id: "finance-kids-53",
          title: "Reflex Borrow/Steal",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-53"] || false,
          isSpecial: true,
          path: "/student/finance/kids/reflex-borrow-steal",
          index: 52,
        },
        {
          id: "finance-kids-54",
          title: "Puzzle: Borrow Match",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-54"] || false,
          isSpecial: true,
          path: "/student/finance/kids/puzzle-borrow-match",
          index: 53,
        },
        {
          id: "finance-kids-55",
          title: "Lunch Box Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-55"] || false,
          isSpecial: true,
          path: "/student/finance/kids/lunch-box-story",
          index: 54,
        },
        {
          id: "finance-kids-56",
          title: "Poster: Return What You Borrow",
          icon: <Clipboard className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-56"] || false,
          isSpecial: true,
          path: "/student/finance/kids/poster-return-borrow",
          index: 55,
        },
        {
          id: "finance-kids-57",
          title: "Journal of Borrowing",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-57"] || false,
          isSpecial: true,
          path: "/student/finance/kids/journal-borrowing",
          index: 56,
        },
        {
          id: "finance-kids-58",
          title: "Toy Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-58"] || false,
          isSpecial: true,
          path: "/student/finance/kids/toy-story",
          index: 57,
        },
        {
          id: "finance-kids-59",
          title: "Reflex Borrow Right",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-59"] || false,
          isSpecial: true,
          path: "/student/finance/kids/reflex-borrow-right",
          index: 58,
        },
        {
          id: "finance-kids-60",
          title: "Badge: Good Borrower",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-60"] || false,
          isSpecial: true,
          path: "/student/finance/kids/badge-good-borrower",
          index: 59,
        },
        {
          id: "finance-kids-61",
          title: "Tree Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-61"] || false,
          isSpecial: true,
          path: "/student/finance/kids/tree-story",
          index: 60,
        },
        {
          id: "finance-kids-62",
          title: "Quiz on Growth",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-62"] || false,
          isSpecial: true,
          path: "/student/finance/kids/quiz-on-growth",
          index: 61,
        },
        {
          id: "finance-kids-63",
          title: "Reflex Investment Basics",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-63"] || false,
          isSpecial: true,
          path: "/student/finance/kids/reflex-investment-basics",
          index: 62,
        },
        {
          id: "finance-kids-64",
          title: "Puzzle of Growth",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-64"] || false,
          isSpecial: true,
          path: "/student/finance/kids/puzzle-of-growth",
          index: 63,
        },
        {
          id: "finance-kids-65",
          title: "Bank vs Piggy Bank",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-65"] || false,
          isSpecial: true,
          path: "/student/finance/kids/piggy-bank",
          index: 64,
        },
        {
          id: "finance-kids-66",
          title: "Poster: Grow Your Money",
          icon: <Brush className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-66"] || false,
          isSpecial: true,
          path: "/student/finance/kids/poster-grow-your-money",
          index: 65,
        },
        {
          id: "finance-kids-67",
          title: "Journal of Growth",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-67"] || false,
          isSpecial: true,
          path: "/student/finance/kids/journal-of-growth",
          index: 66,
        },
        {
          id: "finance-kids-68",
          title: "Toy vs Saving Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-68"] || false,
          isSpecial: true,
          path: "/student/finance/kids/toy-vs-saving-story",
          index: 67,
        },
        {
          id: "finance-kids-69",
          title: "Reflex Growth Check",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-69"] || false,
          isSpecial: true,
          path: "/student/finance/kids/reflex-growth-check",
          index: 68,
        },
        {
          id: "finance-kids-70",
          title: "Badge: Money Gardener",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-70"] || false,
          isSpecial: true,
          path: "/student/finance/kids/badge-money-gardener",
          index: 69,
        },
        {
          id: "finance-kids-71",
          title: "Lemonade Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-71"] || false,
          isSpecial: true,
          path: "/student/finance/kids/lemonade-story",
          index: 70,
        },
        {
          id: "finance-kids-72",
          title: "Quiz on Earning",
          icon: <Clipboard className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-72"] || false,
          isSpecial: true,
          path: "/student/finance/kids/quiz-on-earning",
          index: 71,
        },
        {
          id: "finance-kids-73",
          title: "Reflex Work vs Play",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-73"] || false,
          isSpecial: true,
          path: "/student/finance/kids/reflex-work-vs-play",
          index: 72,
        },
        {
          id: "finance-kids-74",
          title: "Puzzle of Jobs",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-74"] || false,
          isSpecial: true,
          path: "/student/finance/kids/puzzle-of-jobs",
          index: 73,
        },
        {
          id: "finance-kids-75",
          title: "Helping Parents Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-kids-75"] || false,
          isSpecial: true,
          path: "/student/finance/kids/helping-parents-story",
          index: 74,
        },
        {
          id: "finance-kids-76",
          title: "Poster: Work to Earn",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-76"] || false,
          isSpecial: true,
          path: "/student/finance/kids/poster-work-to-earn",
          index: 75,
        },
        {
          id: "finance-kids-77",
          title: "Journal of Earning",
          icon: <ClipboardList className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-77"] || false,
          isSpecial: true,
          path: "/student/finance/kids/journal-of-earning",
          index: 76,
        },
        {
          id: "finance-kids-78",
          title: "Pet Sitting Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-78"] || false,
          isSpecial: true,
          path: "/student/finance/kids/pet-sitting-story",
          index: 77,
        },
        {
          id: "finance-kids-79",
          title: "Reflex Small Business",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-79"] || false,
          isSpecial: true,
          path: "/student/finance/kids/reflex-small-business",
          index: 78,
        },
        {
          id: "finance-kids-80",
          title: "Badge: Young Earner",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-80"] || false,
          isSpecial: true,
          path: "/student/finance/kids/badge-young-earner",
          index: 79,
        },

        {
          id: "finance-kids-81",
          title: "Candy Shop Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-81"] || false,
          isSpecial: true,
          path: "/student/finance/kids/candy-shop-storyy",
          index: 80,
        },
        {
          id: "finance-kids-82",
          title: "Quiz on Honesty",
          icon: <ClipboardList className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-82"] || false,
          isSpecial: true,
          path: "/student/finance/kids/quiz-on-honesty",
          index: 81,
        },
        {
          id: "finance-kids-83",
          title: "Reflex Scam Alert",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-83"] || false,
          isSpecial: true,
          path: "/student/finance/kids/reflex-scam-alert",
          index: 82,
        },
        {
          id: "finance-kids-84",
          title: "Puzzle: Honest vs Fraud",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-84"] || false,
          isSpecial: true,
          path: "/student/finance/kids/puzzle-honest-vs-fraud",
          index: 83,
        },
        {
          id: "finance-kids-85",
          title: "Stranger Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-85"] || false,
          isSpecial: true,
          path: "/student/finance/kids/stranger-story",
          index: 84,
        },
        {
          id: "finance-kids-86",
          title: "Poster: Be Alert",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-86"] || false,
          isSpecial: true,
          path: "/student/finance/kids/poster-be-alert",
          index: 85,
        },
        {
          id: "finance-kids-87",
          title: "Journal of Safety",
          icon: <ClipboardList className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-87"] || false,
          isSpecial: true,
          path: "/student/finance/kids/journal-safety",
          index: 86,
        },
        {
          id: "finance-kids-88",
          title: "Toy Shop Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-88"] || false,
          isSpecial: true,
          path: "/student/finance/kids/toy-shop-story",
          index: 87,
        },
        {
          id: "finance-kids-89",
          title: "Reflex Check First",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-89"] || false,
          isSpecial: true,
          path: "/student/finance/kids/reflex-check-first",
          index: 88,
        },
        {
          id: "finance-kids-90",
          title: "Badge: Scam Spotter Kid",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-90"] || false,
          isSpecial: true,
          path: "/student/finance/kids/badge-scam-spotter-kid",
          index: 89,
        },
        {
          id: "finance-kids-91",
          title: "Lost Coin Story",
          icon: <Coins className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-91"] || false,
          isSpecial: true,
          path: "/student/finance/kids/lost-coin-story-game",
          index: 90,
        },
        {
          id: "finance-kids-92",
          title: "Quiz on Money Honesty",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-92"] || false,
          isSpecial: true,
          path: "/student/finance/kids/money-honesty-quiz-game",
          index: 91,
        },
        {
          id: "finance-kids-93",
          title: "Reflex Ethics",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-93"] || false,
          isSpecial: true,
          path: "/student/finance/kids/reflex-ethics-game",
          index: 92,
        },
        {
          id: "finance-kids-94",
          title: "Puzzle of Honesty",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-94"] || false,
          isSpecial: true,
          path: "/student/finance/kids/honesty-puzzle-game",
          index: 93,
        },
        {
          id: "finance-kids-95",
          title: "Friend's Money Story",
          icon: <HeartHandshake className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-95"] || false,
          isSpecial: true,
          path: "/student/finance/kids/friends-money-story-game",
          index: 94,
        },
        {
          id: "finance-kids-96",
          title: "Poster: Honesty Pays",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Creative",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-96"] || false,
          isSpecial: true,
          path: "/student/finance/kids/honesty-poster-game",
          index: 95,
        },
        {
          id: "finance-kids-97",
          title: "Journal of Ethics",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Reflective",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-97"] || false,
          isSpecial: true,
          path: "/student/finance/kids/ethics-journal-game",
          index: 96,
        },
        {
          id: "finance-kids-98",
          title: "Shop Story",
          icon: <ShoppingBag className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-98"] || false,
          isSpecial: true,
          path: "/student/finance/kids/shop-story-game",
          index: 97,
        },
        {
          id: "finance-kids-99",
          title: "Reflex Money Truth",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-99"] || false,
          isSpecial: true,
          path: "/student/finance/kids/reflex-money-truth-game",
          index: 98,
        },
        {
          id: "finance-kids-100",
          title: "Badge: Honest Kid",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "7 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-kids-100"] || false,
          isSpecial: true,
          path: "/student/finance/kids/honest-kid-badge-game",
          index: 99,
        },
      ];

    return financeGamesKids;
}
