import {
   Trophy,  Puzzle, Users,TrendingUp, Zap, Wallet, Heart,Target, BookOpen, GraduationCap, ShoppingCart, BarChart4, MessageSquare,  HelpCircle,  CreditCard,  ShoppingBag, Clipboard, School, FileText, Calculator, Video, Mic, PenTool, AlertTriangle, AlertCircle
  } from "lucide-react";
  
import buildIds from "../buildGameIds";


export const financegGameIdsTeen = buildIds("finance", "teens")

export const getFinanceTeenGames = (gameCompletionStatus)=> {
    const financeGamesTeen =  [
        {
          id: "finance-teens-1",
          title: "Pocket Money Story",
          description:
            "You receive pocket money. Do you save a portion or spend it all?",
          icon: <Wallet className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-1"] || false,
          isSpecial: true,
          path: "/student/finance/teen/pocket-money-story",
          index: 0,
        },
        {
          id: "finance-teens-2",
          title: "Quiz on Savings Rate",
          description:
            "What percentage of income should you save? (a) 0%, (b) 10%, (c) 20%+",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-2"] || false,
          isSpecial: true,
          path: "/student/finance/teen/quiz-on-savings-rate",
          index: 1,
        },
        {
          id: "finance-teens-3",
          title: "Reflex Smart Saver",
          description: 'Tap quickly for "Save" words, avoid "Waste" words',
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-3"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-smart-saver",
          index: 2,
        },
        {
          id: "finance-teens-4",
          title: "Puzzle of Saving Goals",
          description: "Match saving goals with timeframes",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-4"] || false,
          isSpecial: true,
          path: "/student/finance/teen/puzzle-of-saving-goals",
          index: 3,
        },
        {
          id: "finance-teens-5",
          title: "Salary Story",
          description:
            "You get your first part-time job salary. How do you manage it?",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-5"] || false,
          isSpecial: true,
          path: "/student/finance/teen/salary-story",
          index: 4,
        },
        {
          id: "finance-teens-6",
          title: "Debate: Save vs Spend",
          description: "Participate in a debate on saving vs spending",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-6"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debate-save-vs-spend",
          index: 5,
        },
        {
          id: "finance-teens-7",
          title: "Journal of Saving Goal",
          description: "Write about your personal saving goals",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-7"] || false,
          isSpecial: true,
          path: "/student/finance/teen/journal-of-saving-goal",
          index: 6,
        },
        {
          id: "finance-teens-8",
          title: "Simulation: Monthly Money",
          description: "Manage a monthly budget with income and expenses",
          icon: <BarChart4 className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-8"] || false,
          isSpecial: true,
          path: "/student/finance/teen/simulation-monthly-money",
          index: 7,
        },
        {
          id: "finance-teens-9",
          title: "Reflex: Wise Use",
          description:
            "Tap for wise financial decisions, avoid impulsive choices",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-9"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-wise-use",
          index: 8,
        },
        {
          id: "finance-teens-10",
          title: "Badge: Smart Saver",
          description: "Earn your badge for completing saving challenges",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-10"] || false,
          isSpecial: true,
          path: "/student/finance/teen/badge-smart-saver",
          index: 9,
        },
        {
          id: "finance-teens-11",
          title: "Savings Saga",
          description:
            "You get ₹500 monthly. Spend all on food or divide into needs/wants/savings? → Divide.",
          icon: <Wallet className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-11"] || false,
          isSpecial: true,
          path: "/student/finance/teen/savings-saga",
          index: 10,
        },
        {
          id: "finance-teens-12",
          title: "Spending Quiz",
          description: "Test your knowledge on smart spending habits",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-12"] || false,
          isSpecial: true,
          path: "/student/finance/teen/spending-quiz",
          index: 11,
        },
        {
          id: "finance-teens-13",
          title: "Reflex: Wise Choices",
          description: "Make quick decisions between needs and wants",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-13"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-wise-choices",
          index: 12,
        },
        {
          id: "finance-teens-14",
          title: "Puzzle: Smart Spending",
          description: "Match spending concepts with their definitions",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-14"] || false,
          isSpecial: true,
          path: "/student/finance/teen/puzzle-smart-spending",
          index: 13,
        },
        {
          id: "finance-teens-15",
          title: "Party Story",
          description: "Plan a party within budget constraints",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-15"] || false,
          isSpecial: true,
          path: "/student/finance/teen/party-story",
          index: 14,
        },
        {
          id: "finance-teens-16",
          title: "Debate: Needs vs Wants",
          description: "Debate the difference between needs and wants",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-16"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debate-needs-vs-wants",
          index: 15,
        },
        {
          id: "finance-teens-17",
          title: "Journal of Spending",
          description: "Reflect on your spending habits",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-17"] || false,
          isSpecial: true,
          path: "/student/finance/teen/journal-of-spending",
          index: 16,
        },
        {
          id: "finance-teens-18",
          title: "Simulation: Shopping Mall",
          description:
            "Make purchasing decisions in a shopping mall simulation",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-18"] || false,
          isSpecial: true,
          path: "/student/finance/teen/simulation-shopping-mall",
          index: 17,
        },
        {
          id: "finance-teens-19",
          title: "Reflex: Control",
          description: "Practice spending control with quick decisions",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-19"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-control",
          index: 18,
        },
        {
          id: "finance-teens-20",
          title: "Badge: Smart Spender Teen",
          description:
            "Earn your badge for completing all teen finance challenges",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-20"] || false,
          isSpecial: true,
          path: "/student/finance/teen/badge-smart-spender-teen",
          index: 19,
        },
        {
          id: "finance-teens-21",
          title: "Allowance Story",
          description:
            "You get ₹500 monthly. Spend wisely or divide into needs/wants/savings?",
          icon: <Wallet className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-21"] || false,
          isSpecial: true,
          path: "/student/finance/teen/allowance-story",
          index: 20,
        },
        {
          id: "finance-teens-22",
          title: "Budget Quiz",
          description:
            "If you spend ₹300 and save ₹200 from ₹500, what % is saved?",
          icon: <Clipboard className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-22"] || false,
          isSpecial: true,
          path: "/student/finance/teen/budget-quiz",
          index: 21,
        },
        {
          id: "finance-teens-23",
          title: "Reflex Budget Check",
          description:
            "Tap quickly to track expenses and avoid forgetting to save",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-23"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-budget-check",
          index: 22,
        },
        {
          id: "finance-teens-24",
          title: "Puzzle of Priorities",
          description: "Match Must vs Want expenses correctly",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-24"] || false,
          isSpecial: true,
          path: "/student/finance/teen/puzzle-priorities",
          index: 23,
        },
        {
          id: "finance-teens-25",
          title: "College Story",
          description: "Smart spending choices as a student with pocket money",
          icon: <School className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-25"] || false,
          isSpecial: true,
          path: "/student/finance/teen/college-story",
          index: 24,
        },
        {
          id: "finance-teens-26",
          title: "Debate: Budget Freedom",
          description:
            "Does budgeting give freedom or limit it? Participate in the debate.",
          icon: <MessageSquare className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-26"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debate-budget-freedom",
          index: 25,
        },
        {
          id: "finance-teens-27",
          title: "Journal of Planning",
          description: "Write: 'One monthly budget I want to create is ___.'",
          icon: <FileText className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-27"] || false,
          isSpecial: true,
          path: "/student/finance/teen/journal-planning",
          index: 26,
        },
        {
          id: "finance-teens-28",
          title: "Simulation: Monthly Allowance",
          description:
            "Allocate ₹1000: ₹400 food, ₹300 transport, ₹200 save, ₹100 fun. Correct = balanced budget.",
          icon: <Calculator className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-28"] || false,
          isSpecial: true,
          path: "/student/finance/teen/simulation-allowance",
          index: 27,
        },
        {
          id: "finance-teens-29",
          title: "Reflex Budget Smarts",
          description:
            "Tap quickly: 'Plan Future' or 'Empty Wallet' to test reflex budget skills.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-29"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-budget-smarts",
          index: 28,
        },
        {
          id: "finance-teens-30",
          title: "Badge: Budget Hero",
          description:
            "Finish 5 budgeting scenarios to earn the 'Budget Hero' badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-30"] || false,
          isSpecial: true,
          path: "/student/finance/teen/badge-budget-hero",
          index: 29,
        },
        {
          id: "finance-teens-31",
          title: "Movie vs Bus Fare Story",
          description:
            "You have ₹100. Do you spend on a movie or keep for a bus pass? → Choose bus pass.",
          icon: <Video className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-31"] || false,
          isSpecial: true,
          path: "/student/finance/teen/movie-vs-bus-fare-story",
          index: 30,
        },
        {
          id: "finance-teens-32",
          title: "Needs vs Wants Quiz",
          description:
            "Which is a want? (a) Medicine, (b) School clothes, (c) Luxury watch). Correct = Luxury watch.",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-32"] || false,
          isSpecial: true,
          path: "/student/finance/teen/needs-vs-wants-quiz",
          index: 31,
        },
        {
          id: "finance-teens-33",
          title: "Reflex Decision",
          description:
            "Tap quickly: 'Pay Fees' or 'Skip Fees for Gadgets.' Correct = Pay Fees.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-33"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-decision",
          index: 32,
        },
        {
          id: "finance-teens-34",
          title: "Puzzle: Real Priorities",
          description: "Match items: Shelter → Need, Gaming Console → Want.",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-34"] || false,
          isSpecial: true,
          path: "/student/finance/teen/puzzle-real-priorities",
          index: 33,
        },
        {
          id: "finance-teens-35",
          title: "Exam Prep Story",
          description:
            "You have some money left — spend on tuition or snacks? Correct = Tuition.",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-35"] || false,
          isSpecial: true,
          path: "/student/finance/teen/exam-prep-story",
          index: 34,
        },
        {
          id: "finance-teens-36",
          title: "Debate: Wants Matter Too?",
          description: "Should we ignore wants completely? → No, balance both.",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-36"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debate-wants-matter-too",
          index: 35,
        },
        {
          id: "finance-teens-37",
          title: "Journal of Balance",
          description: "Write: 'One want I sacrificed for a need was ___.'",
          icon: <PenTool className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-37"] || false,
          isSpecial: true,
          path: "/student/finance/teen/journal-of-balance",
          index: 36,
        },
        {
          id: "finance-teens-38",
          title: "Simulation: Monthly Budget",
          description:
            "₹2000 allowance. Needs: ₹1200, Wants: ₹800. Correct balance = Pay needs first.",
          icon: <Calculator className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-38"] || false,
          isSpecial: true,
          path: "/student/finance/teen/simulation-monthly-budget",
          index: 37,
        },
        {
          id: "finance-teens-39",
          title: "Reflex Smart Spend",
          description:
            "Tap for 'Pay Rent' or 'Luxury Party.' Correct = Pay Rent.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-39"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-smart-spend",
          index: 38,
        },
        {
          id: "finance-teens-40",
          title: "Badge: Wise Chooser",
          description:
            "Handle 5 needs vs wants dilemmas correctly to earn the 'Wise Chooser' badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-40"] || false,
          isSpecial: true,
          path: "/student/finance/teen/badge-wise-chooser",
          index: 39,
        },
        {
          id: "finance-teens-41",
          title: "Online Payment Story",
          description:
            "You buy a book online. Pay with cash or UPI safely? → Choose UPI safely.",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-41"] || false,
          isSpecial: true,
          path: "/student/finance/teen/online-payment-story",
          index: 40,
        },
        {
          id: "finance-teens-42",
          title: "Quiz on Digital Money",
          description:
            "Which is safer? (a) Share PIN, (b) Keep PIN secret). Correct = Keep PIN secret.",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-42"] || false,
          isSpecial: true,
          path: "/student/finance/teen/quiz-on-digital-money",
          index: 41,
        },
        {
          id: "finance-teens-43",
          title: "Reflex Secure Use",
          description:
            "Tap for 'Strong Password' or '1234.' Correct = Strong Password.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-43"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-secure-use",
          index: 42,
        },
        {
          id: "finance-teens-44",
          title: "Puzzle of Digital Tools",
          description:
            "Match: UPI → PhonePe, Debit Card → ATM, OTP → Security.",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-44"] || false,
          isSpecial: true,
          path: "/student/finance/teen/puzzle-of-digital-tools",
          index: 43,
        },
        {
          id: "finance-teens-45",
          title: "Online Fraud Story",
          description: "A stranger asks for your bank PIN. Do you share? → No.",
          icon: <AlertTriangle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-45"] || false,
          isSpecial: true,
          path: "/student/finance/teen/online-fraud-story",
          index: 44,
        },
        {
          id: "finance-teens-46",
          title: "Debate: Cash vs Digital",
          description:
            "Which is better for the future — cash or digital money? → Digital with safety.",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-46"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debate-cash-vs-digital",
          index: 45,
        },
        {
          id: "finance-teens-47",
          title: "Journal of Digital Use",
          description: "Write: 'One safe way I used online money was ___.'",
          icon: <PenTool className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-47"] || false,
          isSpecial: true,
          path: "/student/finance/teen/journal-of-digital-use",
          index: 46,
        },
        {
          id: "finance-teens-48",
          title: "Simulation: Digital Spend",
          description:
            "Balance ₹1000. Pay ₹200 for food, ₹300 for a book. Correct balance left = ₹500.",
          icon: <Calculator className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-48"] || false,
          isSpecial: true,
          path: "/student/finance/teen/simulation-digital-spend",
          index: 47,
        },
        {
          id: "finance-teens-49",
          title: "Reflex Fraud Alert",
          description:
            "Tap for 'Ignore Scam Link' or 'Click Suspicious Link.' Correct = Ignore Scam Link.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-49"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-fraud-alert",
          index: 48,
        },
        {
          id: "finance-teens-50",
          title: "Badge: Digital Money Smart",
          description:
            "Safely use digital money in 5 cases to earn the 'Digital Money Smart' badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-50"] || false,
          isSpecial: true,
          path: "/student/finance/teen/badge-digital-money-smart",
          index: 49,
        },
        {
          id: "finance-teens-51",
          title: "Money Borrow Story",
          description:
            "Teen borrows ₹100 from a friend. Forgetting to repay? → Wrong.",
          icon: <CreditCard className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-51"] || false,
          isSpecial: true,
          path: "/student/finance/teen/money-borrow-story",
          index: 50,
        },
        {
          id: "finance-teens-52",
          title: "Debt Quiz",
          description:
            "Borrow ₹100, repay ₹120. What is extra ₹20 called? → Interest.",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-52"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debt-quiz",
          index: 51,
        },
        {
          id: "finance-teens-53",
          title: "Reflex Debt Dangers",
          description:
            "Tap for 'Repay Loan' or 'Ignore Loan.' Correct = Repay Loan.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-53"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-debt-dangers",
          index: 52,
        },
        {
          id: "finance-teens-54",
          title: "Puzzle: Loan Basics",
          description: "Match: Principal → Original, Interest → Extra.",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-54"] || false,
          isSpecial: true,
          path: "/student/finance/teen/puzzle-loan-basics",
          index: 53,
        },
        {
          id: "finance-teens-55",
          title: "Borrowing Story",
          description:
            "Teen borrows for a new phone. Can't repay? Result → Debt.",
          icon: <CreditCard className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-55"] || false,
          isSpecial: true,
          path: "/student/finance/teen/borrowing-story",
          index: 54,
        },
        {
          id: "finance-teens-56",
          title: "Debate: Borrow Good or Bad?",
          description:
            "Is borrowing always bad? → No, good if planned & repaid.",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-56"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debate-borrow-good-or-bad",
          index: 55,
        },
        {
          id: "finance-teens-57",
          title: "Journal of Borrowing",
          description:
            "Write: 'One time I borrowed money and handled it responsibly was ___.'",
          icon: <PenTool className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-57"] || false,
          isSpecial: true,
          path: "/student/finance/teen/journal-of-borrowing",
          index: 56,
        },
        {
          id: "finance-teens-58",
          title: "Simulation: Loan Repayment",
          description: "Borrow ₹1000. Repay ₹200/month. How many months? → 5.",
          icon: <Calculator className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-58"] || false,
          isSpecial: true,
          path: "/student/finance/teen/simulation-loan-repayment",
          index: 57,
        },
        {
          id: "finance-teens-59",
          title: "Reflex Debt Control",
          description:
            "Tap for 'Borrow Wisely' or 'Overspend + Debt.' Correct = Borrow Wisely.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-59"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-debt-control",
          index: 58,
        },
        {
          id: "finance-teens-60",
          title: "Badge: Debt Smart",
          description:
            "Handle 5 borrowing dilemmas responsibly to earn the 'Debt Smart' badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-60"] || false,
          isSpecial: true,
          path: "/student/finance/teen/badge-debt-smart",
          index: 59,
        },
        {
          id: "finance-teens-61",
          title: "Savings Account Story",
          description:
            "You deposit ₹1000. After a year, it becomes ₹1050. Why? → Interest.",
          icon: <CreditCard className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-61"] || false,
          isSpecial: true,
          path: "/student/finance/teen/savings-account-story",
          index: 60,
        },
        {
          id: "finance-teens-62",
          title: "Investment Quiz",
          description:
            "Which is riskier but higher return? (a) Fixed Deposit, (b) Stock Market). Correct = Stock Market.",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-62"] || false,
          isSpecial: true,
          path: "/student/finance/teen/investment-quiz",
          index: 61,
        },
        {
          id: "finance-teens-63",
          title: "Reflex Investor Smartness",
          description:
            "Tap for 'Diversify' or 'Put All in One.' Correct = Diversify.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-63"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-investor-smartness",
          index: 62,
        },
        {
          id: "finance-teens-64",
          title: "Puzzle of Investment Types",
          description: "Match: FD → Safe, Stocks → Risky, Mutual Fund → Mixed.",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-64"] || false,
          isSpecial: true,
          path: "/student/finance/teen/puzzle-investment-types",
          index: 63,
        },
        {
          id: "finance-teens-65",
          title: "Startup Story",
          description:
            "Friend invests ₹100 in a lemonade stand. Earns ₹150. Smart? → Yes.",
          icon: <TrendingUp className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-65"] || false,
          isSpecial: true,
          path: "/student/finance/teen/startup-story",
          index: 64,
        },
        {
          id: "finance-teens-66",
          title: "Debate: Save vs Invest",
          description:
            "Is saving enough or should we invest too? → Invest wisely.",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-66"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debate-save-vs-invest",
          index: 65,
        },
        {
          id: "finance-teens-67",
          title: "Journal of Future Investing",
          description:
            "Write: 'One investment I'd like to try when older is ___.'",
          icon: <PenTool className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-67"] || false,
          isSpecial: true,
          path: "/student/finance/teen/journal-future-investing",
          index: 66,
        },
        {
          id: "finance-teens-68",
          title: "Simulation: ₹1000 Choice",
          description:
            "₹1000 → Options: (a) FD, (b) Stocks, (c) Spend. Best = Mix FD + Stocks.",
          icon: <Calculator className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-68"] || false,
          isSpecial: true,
          path: "/student/finance/teen/simulation-1000-choice",
          index: 67,
        },
        {
          id: "finance-teens-69",
          title: "Reflex Smart Growth",
          description:
            "Tap for 'Long-term Invest' or 'Instant Spend.' Correct = Long-term Invest.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-69"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-smart-growth",
          index: 68,
        },
        {
          id: "finance-teens-70",
          title: "Badge: Smart Investor",
          description:
            "Handle 5 investment challenges to earn the 'Smart Investor' badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-70"] || false,
          isSpecial: true,
          path: "/student/finance/teen/badge-smart-investor",
          index: 69,
        },
        {
          id: "finance-teens-71",
          title: "Startup Idea Story",
          description:
            "Teen sells handmade crafts online. Is this entrepreneurship? → Yes.",
          icon: <ShoppingBag className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-71"] || false,
          isSpecial: true,
          path: "/student/finance/teen/startup-idea-story",
          index: 70,
        },
        {
          id: "finance-teens-72",
          title: "Quiz on Entrepreneurship",
          description:
            "Who is an entrepreneur? (a) Creates new business, (b) Only spends, (c) Does nothing). Correct = Creates new business.",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-72"] || false,
          isSpecial: true,
          path: "/student/finance/teen/quiz-on-entrepreneurship",
          index: 71,
        },
        {
          id: "finance-teens-73",
          title: "Reflex Entrepreneur Traits",
          description:
            "Tap for 'Innovate' or 'Copy Always.' Correct = Innovate.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-73"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-entrepreneur-traits",
          index: 72,
        },
        {
          id: "finance-teens-74",
          title: "Puzzle of Entrepreneurs",
          description:
            "Match: Ratan Tata → Industry, Elon Musk → Innovation, Narayana Murthy → IT.",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-74"] || false,
          isSpecial: true,
          path: "/student/finance/teen/puzzle-of-entrepreneurs",
          index: 73,
        },
        {
          id: "finance-teens-75",
          title: "Business Risk Story",
          description:
            "You invest ₹200 in snacks to sell. Earn ₹300. Good? → Yes.",
          icon: <TrendingUp className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-75"] || false,
          isSpecial: true,
          path: "/student/finance/teen/business-risk-story",
          index: 74,
        },
        {
          id: "finance-teens-76",
          title: "Debate: Job vs Business",
          description:
            "Is it better to do a job or start a business? → Depends, but business builds independence.",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-76"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debate-job-vs-business",
          index: 75,
        },
        {
          id: "finance-teens-77",
          title: "Journal of Entrepreneur Dream",
          description: "Write: 'One business I want to start is ___.'",
          icon: <PenTool className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-77"] || false,
          isSpecial: true,
          path: "/student/finance/teen/journal-entrepreneur-dream",
          index: 76,
        },
        {
          id: "finance-teens-78",
          title: "Simulation: Mini Startup",
          description:
            "You have ₹500 to start a snack stall. Buy ingredients (₹300), profit ₹200. Smart? → Yes.",
          icon: <Calculator className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-78"] || false,
          isSpecial: true,
          path: "/student/finance/teen/simulation-mini-startup",
          index: 77,
        },
        {
          id: "finance-teens-79",
          title: "Reflex Smart Entrepreneur",
          description:
            "Tap for 'Plan + Risk' or 'Spend All.' Correct = Plan + Risk.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-79"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-smart-entrepreneur",
          index: 78,
        },
        {
          id: "finance-teens-80",
          title: "Badge: Young Entrepreneur",
          description:
            "Complete 5 business challenges to earn the 'Young Entrepreneur' badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-80"] || false,
          isSpecial: true,
          path: "/student/finance/teen/badge-young-entrepreneur",
          index: 79,
        },
        {
          id: "finance-teens-81",
          title: "Fake Online Offer Story",
          description:
            "Website offers free phone if you pay ₹100. Correct = Refuse.",
          icon: <AlertTriangle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-81"] || false,
          isSpecial: true,
          path: "/student/finance/teen/fake-online-offer-story",
          index: 80,
        },
        {
          id: "finance-teens-82",
          title: "Consumer Quiz",
          description:
            "If shopkeeper cheats, where can you complain? (a) Consumer Court, (b) Playground). Correct = Consumer Court.",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-82"] || false,
          isSpecial: true,
          path: "/student/finance/teen/consumer-quiz",
          index: 81,
        },
        {
          id: "finance-teens-83",
          title: "Reflex Fraud Safety",
          description:
            "Tap for 'Don't Share OTP' or 'Share OTP.' Correct = Don't Share OTP.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-83"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-fraud-safety",
          index: 82,
        },
        {
          id: "finance-teens-84",
          title: "Puzzle of Rights",
          description:
            "Match: Right to Safety → Safe Goods, Right to Information → Honest Label.",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-84"] || false,
          isSpecial: true,
          path: "/student/finance/teen/puzzle-of-rights",
          index: 83,
        },
        {
          id: "finance-teens-85",
          title: "Fake Call Story",
          description: "Caller asks bank details. Do you share? → No.",
          icon: <AlertCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-85"] || false,
          isSpecial: true,
          path: "/student/finance/teen/fake-call-story",
          index: 84,
        },
        {
          id: "finance-teens-86",
          title: "Debate: Cash vs Online Safety",
          description:
            "Is online money more risky than cash? → Both need safety.",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-86"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debate-cash-vs-online-safety",
          index: 85,
        },
        {
          id: "finance-teens-87",
          title: "Journal of Consumer Rights",
          description: "Write: 'One right I know as a consumer is ___.'",
          icon: <PenTool className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-87"] || false,
          isSpecial: true,
          path: "/student/finance/teen/journal-consumer-rights",
          index: 86,
        },
        {
          id: "finance-teens-88",
          title: "Simulation: Fraud Alert",
          description: "Message: 'Win ₹1 lakh, click link.' Correct = Delete.",
          icon: <Calculator className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-88"] || false,
          isSpecial: true,
          path: "/student/finance/teen/simulation-fraud-alert",
          index: 87,
        },
        {
          id: "finance-teens-89",
          title: "Reflex Scam Check",
          description:
            "Tap for 'Report Scam' or 'Ignore Fraud.' Correct = Report Scam.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-89"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-scam-check",
          index: 88,
        },
        {
          id: "finance-teens-90",
          title: "Badge: Consumer Protector",
          description:
            "Solve 5 fraud cases to earn the 'Consumer Protector' badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-90"] || false,
          isSpecial: true,
          path: "/student/finance/teen/badge-consumer-protector",
          index: 89,
        },
        {
          id: "finance-teens-91",
          title: "Scholarship Story",
          description:
            "Student lies to get extra scholarship. Correct action? → Be truthful.",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-91"] || false,
          isSpecial: true,
          path: "/student/finance/teen/scholarship-story",
          index: 90,
        },
        {
          id: "finance-teens-92",
          title: "Ethics Quiz",
          description: "Is bribing for marks ethical? → No.",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-92"] || false,
          isSpecial: true,
          path: "/student/finance/teen/ethics-quiz",
          index: 91,
        },
        {
          id: "finance-teens-93",
          title: "Reflex Ethical Choice",
          description: "Tap for 'Fair Pay' or 'Cheat Pay.' Correct = Fair Pay.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-93"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-ethical-choice",
          index: 92,
        },
        {
          id: "finance-teens-94",
          title: "Puzzle: Right vs Wrong",
          description: "Match: Donation → Good, Stealing → Bad.",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-94"] || false,
          isSpecial: true,
          path: "/student/finance/teen/puzzle-right-vs-wrong",
          index: 93,
        },
        {
          id: "finance-teens-95",
          title: "Bribery Story",
          description: "Official asks for bribe. Correct = Refuse.",
          icon: <AlertTriangle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-95"] || false,
          isSpecial: true,
          path: "/student/finance/teen/bribery-story",
          index: 94,
        },
        {
          id: "finance-teens-96",
          title: "Debate: Money & Morals",
          description: "Does money test character? → Yes, ethics matter more.",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-96"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debate-money-morals",
          index: 95,
        },
        {
          id: "finance-teens-97",
          title: "Journal of Responsibility",
          description: "Write: 'One way I will use money responsibly is ___.'",
          icon: <PenTool className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-97"] || false,
          isSpecial: true,
          path: "/student/finance/teen/journal-responsibility",
          index: 96,
        },
        {
          id: "finance-teens-98",
          title: "Simulation: Charity Choice",
          description:
            "You have ₹1000. Spend all on gadgets or donate ₹200 + save ₹300 + spend ₹500? → Balanced.",
          icon: <Calculator className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-98"] || false,
          isSpecial: true,
          path: "/student/finance/teen/simulation-charity-choice",
          index: 97,
        },
        {
          id: "finance-teens-99",
          title: "Reflex Fairness",
          description:
            "Tap for 'Be Fair' or 'Cheat Others.' Correct = Be Fair.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-99"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-fairness",
          index: 98,
        },
        {
          id: "finance-teens-100",
          title: "Badge: Ethical Financier",
          description:
            "Complete 5 ethical finance dilemmas to earn the 'Ethical Financier' badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-100"] || false,
          isSpecial: true,
          path: "/student/finance/teen/badge-ethical-financier",
          index: 99,
        },
      ];

    return financeGamesTeen;
}
