import {
   Trophy,  Puzzle, Users,TrendingUp, Zap, Wallet, Heart,Target, BookOpen, GraduationCap, ShoppingCart, BarChart4, MessageSquare,  HelpCircle,  CreditCard,  ShoppingBag, Clipboard, School, FileText, Calculator, Video, Mic, PenTool, AlertTriangle, AlertCircle
  } from "lucide-react";
  
import buildIds from "../buildGameIds";


export const financegGameIdsTeen = buildIds("finance", "teens")

export const getFinanceTeenGames = (gameCompletionStatus)=> {
    const financeGamesTeen =  [
        {
          id: "finance-teens-1",
          title: "Pocket Money Story",
          icon: <Wallet className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-1"] || false,
          isSpecial: true,
          path: "/student/finance/teen/pocket-money-story",
          index: 0,
        },
        {
          id: "finance-teens-2",
          title: "Quiz on Savings Rate",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-2"] || false,
          isSpecial: true,
          path: "/student/finance/teen/quiz-on-savings-rate",
          index: 1,
        },
        {
          id: "finance-teens-3",
          title: "Reflex Smart Saver",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-3"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-smart-saver",
          index: 2,
        },
        {
          id: "finance-teens-4",
          title: "Puzzle of Saving Goals",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-4"] || false,
          isSpecial: true,
          path: "/student/finance/teen/puzzle-of-saving-goals",
          index: 3,
        },
        {
          id: "finance-teens-5",
          title: "Salary Story",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-5"] || false,
          isSpecial: true,
          path: "/student/finance/teen/salary-story",
          index: 4,
        },
        {
          id: "finance-teens-6",
          title: "Debate: Save vs Spend",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-6"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debate-save-vs-spend",
          index: 5,
        },
        {
          id: "finance-teens-7",
          title: "Journal of Saving Goal",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-7"] || false,
          isSpecial: true,
          path: "/student/finance/teen/journal-of-saving-goal",
          index: 6,
        },
        {
          id: "finance-teens-8",
          title: "Simulation: Monthly Money",
          icon: <BarChart4 className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-8"] || false,
          isSpecial: true,
          path: "/student/finance/teen/simulation-monthly-money",
          index: 7,
        },
        {
          id: "finance-teens-9",
          title: "Reflex: Wise Use",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-9"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-wise-use",
          index: 8,
        },
        {
          id: "finance-teens-10",
          title: "Badge: Smart Saver",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-10"] || false,
          isSpecial: true,
          path: "/student/finance/teen/badge-smart-saver",
          index: 9,
        },
        {
          id: "finance-teens-11",
          title: "Savings Saga",
          icon: <Wallet className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-11"] || false,
          isSpecial: true,
          path: "/student/finance/teen/savings-saga",
          index: 10,
        },
        {
          id: "finance-teens-12",
          title: "Spending Quiz",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-12"] || false,
          isSpecial: true,
          path: "/student/finance/teen/spending-quiz",
          index: 11,
        },
        {
          id: "finance-teens-13",
          title: "Reflex: Wise Choices",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-13"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-wise-choices",
          index: 12,
        },
        {
          id: "finance-teens-14",
          title: "Puzzle: Smart Spending",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-14"] || false,
          isSpecial: true,
          path: "/student/finance/teen/puzzle-smart-spending",
          index: 13,
        },
        {
          id: "finance-teens-15",
          title: "Party Story",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-15"] || false,
          isSpecial: true,
          path: "/student/finance/teen/party-story",
          index: 14,
        },
        {
          id: "finance-teens-16",
          title: "Debate: Needs vs Wants",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-16"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debate-needs-vs-wants",
          index: 15,
        },
        {
          id: "finance-teens-17",
          title: "Journal of Spending",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-17"] || false,
          isSpecial: true,
          path: "/student/finance/teen/journal-of-spending",
          index: 16,
        },
        {
          id: "finance-teens-18",
          title: "Simulation: Shopping Mall",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-18"] || false,
          isSpecial: true,
          path: "/student/finance/teen/simulation-shopping-mall",
          index: 17,
        },
        {
          id: "finance-teens-19",
          title: "Reflex: Control",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-19"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-control",
          index: 18,
        },
        {
          id: "finance-teens-20",
          title: "Badge: Smart Spender Teen",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-20"] || false,
          isSpecial: true,
          path: "/student/finance/teen/badge-smart-spender-teen",
          index: 19,
        },
        {
          id: "finance-teens-21",
          title: "Allowance Story",
          icon: <Wallet className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-21"] || false,
          isSpecial: true,
          path: "/student/finance/teen/allowance-story",
          index: 20,
        },
        {
          id: "finance-teens-22",
          title: "Budget Quiz",
          icon: <Clipboard className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-22"] || false,
          isSpecial: true,
          path: "/student/finance/teen/budget-quiz",
          index: 21,
        },
        {
          id: "finance-teens-23",
          title: "Reflex Budget Check",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-23"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-budget-check",
          index: 22,
        },
        {
          id: "finance-teens-24",
          title: "Puzzle of Priorities",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-24"] || false,
          isSpecial: true,
          path: "/student/finance/teen/puzzle-priorities",
          index: 23,
        },
        {
          id: "finance-teens-25",
          title: "College Story",
          icon: <School className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["finance-teens-25"] || false,
          isSpecial: true,
          path: "/student/finance/teen/college-story",
          index: 24,
        },
        {
          id: "finance-teens-26",
          title: "Debate: Budget Freedom",
          icon: <MessageSquare className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-26"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debate-budget-freedom",
          index: 25,
        },
        {
          id: "finance-teens-27",
          title: "Journal of Planning",
          icon: <FileText className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-27"] || false,
          isSpecial: true,
          path: "/student/finance/teen/journal-planning",
          index: 26,
        },
        {
          id: "finance-teens-28",
          title: "Simulation: Monthly Allowance",
          icon: <Calculator className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-28"] || false,
          isSpecial: true,
          path: "/student/finance/teen/simulation-allowance",
          index: 27,
        },
        {
          id: "finance-teens-29",
          title: "Reflex Budget Smarts",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-29"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-budget-smarts",
          index: 28,
        },
        {
          id: "finance-teens-30",
          title: "Badge: Budget Hero",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-30"] || false,
          isSpecial: true,
          path: "/student/finance/teen/badge-budget-hero",
          index: 29,
        },
        {
          id: "finance-teens-31",
          title: "Movie vs Bus Fare Story",
          icon: <Video className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-31"] || false,
          isSpecial: true,
          path: "/student/finance/teen/movie-vs-bus-fare-story",
          index: 30,
        },
        {
          id: "finance-teens-32",
          title: "Needs vs Wants Quiz",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-32"] || false,
          isSpecial: true,
          path: "/student/finance/teen/needs-vs-wants-quiz",
          index: 31,
        },
        {
          id: "finance-teens-33",
          title: "Reflex Decision",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-33"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-decision",
          index: 32,
        },
        {
          id: "finance-teens-34",
          title: "Puzzle: Real Priorities",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-34"] || false,
          isSpecial: true,
          path: "/student/finance/teen/puzzle-real-priorities",
          index: 33,
        },
        {
          id: "finance-teens-35",
          title: "Exam Prep Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-35"] || false,
          isSpecial: true,
          path: "/student/finance/teen/exam-prep-story",
          index: 34,
        },
        {
          id: "finance-teens-36",
          title: "Debate: Wants Matter Too?",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-36"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debate-wants-matter-too",
          index: 35,
        },
        {
          id: "finance-teens-37",
          title: "Journal of Balance",
          icon: <PenTool className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-37"] || false,
          isSpecial: true,
          path: "/student/finance/teen/journal-of-balance",
          index: 36,
        },
        {
          id: "finance-teens-38",
          title: "Simulation: Monthly Budget",
          icon: <Calculator className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-38"] || false,
          isSpecial: true,
          path: "/student/finance/teen/simulation-monthly-budget",
          index: 37,
        },
        {
          id: "finance-teens-39",
          title: "Reflex Smart Spend",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-39"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-smart-spend",
          index: 38,
        },
        {
          id: "finance-teens-40",
          title: "Badge: Wise Chooser",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-40"] || false,
          isSpecial: true,
          path: "/student/finance/teen/badge-wise-chooser",
          index: 39,
        },
        {
          id: "finance-teens-41",
          title: "Online Payment Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-41"] || false,
          isSpecial: true,
          path: "/student/finance/teen/online-payment-story",
          index: 40,
        },
        {
          id: "finance-teens-42",
          title: "Quiz on Digital Money",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-42"] || false,
          isSpecial: true,
          path: "/student/finance/teen/quiz-on-digital-money",
          index: 41,
        },
        {
          id: "finance-teens-43",
          title: "Reflex Secure Use",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-43"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-secure-use",
          index: 42,
        },
        {
          id: "finance-teens-44",
          title: "Puzzle of Digital Tools",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-44"] || false,
          isSpecial: true,
          path: "/student/finance/teen/puzzle-of-digital-tools",
          index: 43,
        },
        {
          id: "finance-teens-45",
          title: "Online Fraud Story",
          icon: <AlertTriangle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-45"] || false,
          isSpecial: true,
          path: "/student/finance/teen/online-fraud-story",
          index: 44,
        },
        {
          id: "finance-teens-46",
          title: "Debate: Cash vs Digital",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-46"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debate-cash-vs-digital",
          index: 45,
        },
        {
          id: "finance-teens-47",
          title: "Journal of Digital Use",
          icon: <PenTool className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-47"] || false,
          isSpecial: true,
          path: "/student/finance/teen/journal-of-digital-use",
          index: 46,
        },
        {
          id: "finance-teens-48",
          title: "Simulation: Digital Spend",
          icon: <Calculator className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-48"] || false,
          isSpecial: true,
          path: "/student/finance/teen/simulation-digital-spend",
          index: 47,
        },
        {
          id: "finance-teens-49",
          title: "Reflex Fraud Alert",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-49"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-fraud-alert",
          index: 48,
        },
        {
          id: "finance-teens-50",
          title: "Badge: Digital Money Smart",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["finance-teens-50"] || false,
          isSpecial: true,
          path: "/student/finance/teen/badge-digital-money-smart",
          index: 49,
        },
        {
          id: "finance-teens-51",
          title: "Money Borrow Story",
          icon: <CreditCard className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-51"] || false,
          isSpecial: true,
          path: "/student/finance/teen/money-borrow-story",
          index: 50,
        },
        {
          id: "finance-teens-52",
          title: "Debt Quiz",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-52"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debt-quiz",
          index: 51,
        },
        {
          id: "finance-teens-53",
          title: "Reflex Debt Dangers",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-53"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-debt-dangers",
          index: 52,
        },
        {
          id: "finance-teens-54",
          title: "Puzzle: Loan Basics",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-54"] || false,
          isSpecial: true,
          path: "/student/finance/teen/puzzle-loan-basics",
          index: 53,
        },
        {
          id: "finance-teens-55",
          title: "Borrowing Story",
          icon: <CreditCard className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-55"] || false,
          isSpecial: true,
          path: "/student/finance/teen/borrowing-story",
          index: 54,
        },
        {
          id: "finance-teens-56",
          title: "Debate: Borrow Good or Bad?",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-56"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debate-borrow-good-or-bad",
          index: 55,
        },
        {
          id: "finance-teens-57",
          title: "Journal of Borrowing",
          icon: <PenTool className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-57"] || false,
          isSpecial: true,
          path: "/student/finance/teen/journal-of-borrowing",
          index: 56,
        },
        {
          id: "finance-teens-58",
          title: "Simulation: Loan Repayment",
          icon: <Calculator className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-58"] || false,
          isSpecial: true,
          path: "/student/finance/teen/simulation-loan-repayment",
          index: 57,
        },
        {
          id: "finance-teens-59",
          title: "Reflex Debt Control",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-59"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-debt-control",
          index: 58,
        },
        {
          id: "finance-teens-60",
          title: "Badge: Debt Smart",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-60"] || false,
          isSpecial: true,
          path: "/student/finance/teen/badge-debt-smart",
          index: 59,
        },
        {
          id: "finance-teens-61",
          title: "Savings Account Story",
          icon: <CreditCard className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-61"] || false,
          isSpecial: true,
          path: "/student/finance/teen/savings-account-story",
          index: 60,
        },
        {
          id: "finance-teens-62",
          title: "Investment Quiz",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-62"] || false,
          isSpecial: true,
          path: "/student/finance/teen/investment-quiz",
          index: 61,
        },
        {
          id: "finance-teens-63",
          title: "Reflex Investor Smartness",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-63"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-investor-smartness",
          index: 62,
        },
        {
          id: "finance-teens-64",
          title: "Puzzle of Investment Types",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-64"] || false,
          isSpecial: true,
          path: "/student/finance/teen/puzzle-investment-types",
          index: 63,
        },
        {
          id: "finance-teens-65",
          title: "Startup Story",
          icon: <TrendingUp className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-65"] || false,
          isSpecial: true,
          path: "/student/finance/teen/startup-story",
          index: 64,
        },
        {
          id: "finance-teens-66",
          title: "Debate: Save vs Invest",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-66"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debate-save-vs-invest",
          index: 65,
        },
        {
          id: "finance-teens-67",
          title: "Journal of Future Investing",
          icon: <PenTool className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-67"] || false,
          isSpecial: true,
          path: "/student/finance/teen/journal-future-investing",
          index: 66,
        },
        {
          id: "finance-teens-68",
          title: "Simulation: â‚¹1000 Choice",
          icon: <Calculator className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-68"] || false,
          isSpecial: true,
          path: "/student/finance/teen/simulation-1000-choice",
          index: 67,
        },
        {
          id: "finance-teens-69",
          title: "Reflex Smart Growth",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-69"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-smart-growth",
          index: 68,
        },
        {
          id: "finance-teens-70",
          title: "Badge: Smart Investor",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-70"] || false,
          isSpecial: true,
          path: "/student/finance/teen/badge-smart-investor",
          index: 69,
        },
        {
          id: "finance-teens-71",
          title: "Startup Idea Story",
          icon: <ShoppingBag className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-71"] || false,
          isSpecial: true,
          path: "/student/finance/teen/startup-idea-story",
          index: 70,
        },
        {
          id: "finance-teens-72",
          title: "Quiz on Entrepreneurship",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-72"] || false,
          isSpecial: true,
          path: "/student/finance/teen/quiz-on-entrepreneurship",
          index: 71,
        },
        {
          id: "finance-teens-73",
          title: "Reflex Entrepreneur Traits",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-73"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-entrepreneur-traits",
          index: 72,
        },
        {
          id: "finance-teens-74",
          title: "Puzzle of Entrepreneurs",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-74"] || false,
          isSpecial: true,
          path: "/student/finance/teen/puzzle-of-entrepreneurs",
          index: 73,
        },
        {
          id: "finance-teens-75",
          title: "Business Risk Story",
          icon: <TrendingUp className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["finance-teens-75"] || false,
          isSpecial: true,
          path: "/student/finance/teen/business-risk-story",
          index: 74,
        },
        {
          id: "finance-teens-76",
          title: "Debate: Job vs Business",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-76"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debate-job-vs-business",
          index: 75,
        },
        {
          id: "finance-teens-77",
          title: "Journal of Entrepreneur Dream",
          icon: <PenTool className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-77"] || false,
          isSpecial: true,
          path: "/student/finance/teen/journal-entrepreneur-dream",
          index: 76,
        },
        {
          id: "finance-teens-78",
          title: "Simulation: Mini Startup",
          icon: <Calculator className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-78"] || false,
          isSpecial: true,
          path: "/student/finance/teen/simulation-mini-startup",
          index: 77,
        },
        {
          id: "finance-teens-79",
          title: "Reflex Smart Entrepreneur",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-79"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-smart-entrepreneur",
          index: 78,
        },
        {
          id: "finance-teens-80",
          title: "Badge: Young Entrepreneur",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-80"] || false,
          isSpecial: true,
          path: "/student/finance/teen/badge-young-entrepreneur",
          index: 79,
        },
        {
          id: "finance-teens-81",
          title: "Fake Online Offer Story",
          icon: <AlertTriangle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-81"] || false,
          isSpecial: true,
          path: "/student/finance/teen/fake-online-offer-story",
          index: 80,
        },
        {
          id: "finance-teens-82",
          title: "Consumer Quiz",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-82"] || false,
          isSpecial: true,
          path: "/student/finance/teen/consumer-quiz",
          index: 81,
        },
        {
          id: "finance-teens-83",
          title: "Reflex Fraud Safety",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-83"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-fraud-safety",
          index: 82,
        },
        {
          id: "finance-teens-84",
          title: "Puzzle of Rights",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-84"] || false,
          isSpecial: true,
          path: "/student/finance/teen/puzzle-of-rights",
          index: 83,
        },
        {
          id: "finance-teens-85",
          title: "Fake Call Story",
          icon: <AlertCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-85"] || false,
          isSpecial: true,
          path: "/student/finance/teen/fake-call-story",
          index: 84,
        },
        {
          id: "finance-teens-86",
          title: "Debate: Cash vs Online Safety",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-86"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debate-cash-vs-online-safety",
          index: 85,
        },
        {
          id: "finance-teens-87",
          title: "Journal of Consumer Rights",
          icon: <PenTool className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-87"] || false,
          isSpecial: true,
          path: "/student/finance/teen/journal-consumer-rights",
          index: 86,
        },
        {
          id: "finance-teens-88",
          title: "Simulation: Fraud Alert",
          icon: <Calculator className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-88"] || false,
          isSpecial: true,
          path: "/student/finance/teen/simulation-fraud-alert",
          index: 87,
        },
        {
          id: "finance-teens-89",
          title: "Reflex Scam Check",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-89"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-scam-check",
          index: 88,
        },
        {
          id: "finance-teens-90",
          title: "Badge: Consumer Protector",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-90"] || false,
          isSpecial: true,
          path: "/student/finance/teen/badge-consumer-protector",
          index: 89,
        },
        {
          id: "finance-teens-91",
          title: "Scholarship Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-91"] || false,
          isSpecial: true,
          path: "/student/finance/teen/scholarship-story",
          index: 90,
        },
        {
          id: "finance-teens-92",
          title: "Ethics Quiz",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-92"] || false,
          isSpecial: true,
          path: "/student/finance/teen/ethics-quiz",
          index: 91,
        },
        {
          id: "finance-teens-93",
          title: "Reflex Ethical Choice",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-93"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-ethical-choice",
          index: 92,
        },
        {
          id: "finance-teens-94",
          title: "Puzzle: Right vs Wrong",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-94"] || false,
          isSpecial: true,
          path: "/student/finance/teen/puzzle-right-vs-wrong",
          index: 93,
        },
        {
          id: "finance-teens-95",
          title: "Bribery Story",
          icon: <AlertTriangle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-95"] || false,
          isSpecial: true,
          path: "/student/finance/teen/bribery-story",
          index: 94,
        },
        {
          id: "finance-teens-96",
          title: "Debate: Money & Morals",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-96"] || false,
          isSpecial: true,
          path: "/student/finance/teen/debate-money-morals",
          index: 95,
        },
        {
          id: "finance-teens-97",
          title: "Journal of Responsibility",
          icon: <PenTool className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-97"] || false,
          isSpecial: true,
          path: "/student/finance/teen/journal-responsibility",
          index: 96,
        },
        {
          id: "finance-teens-98",
          title: "Simulation: Charity Choice",
          icon: <Calculator className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-98"] || false,
          isSpecial: true,
          path: "/student/finance/teen/simulation-charity-choice",
          index: 97,
        },
        {
          id: "finance-teens-99",
          title: "Reflex Fairness",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-99"] || false,
          isSpecial: true,
          path: "/student/finance/teen/reflex-fairness",
          index: 98,
        },
        {
          id: "finance-teens-100",
          title: "Badge: Ethical Financier",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["finance-teens-100"] || false,
          isSpecial: true,
          path: "/student/finance/teen/badge-ethical-financier",
          index: 99,
        },
      ];

    return financeGamesTeen;
}
