import {
  Hand,
  Sparkles,
  Zap,
  Target,
  Droplets,
  Sun,
  BookOpen,
  Shirt,
  Shield,
  Badge,
  Apple,
  Brain,
  Carrot,
  Activity,
  Heart,
  HandHeart
} from "lucide-react";
import buildIds from "../buildGameIds";

export const healthFemaleGameIdsKids = buildIds("health-female", "kids")

export const getHealthFemaleKidsGames = (gameCompletionStatus) => {
    const healthFemaleGamesKids = [
        {
            id: 'health-female-kids-1',
            title: 'Handwash Heroine',
            icon: <Hand className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-1'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/handwash-heroine',
            index: 0
        },
        {
            id: 'health-female-kids-2',
            title: 'Cleanliness Quiz',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-2'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/cleanliness-quiz',
            index: 1
        },
        {
            id: 'health-female-kids-3',
            title: 'Reflex Hygiene Check',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-3'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-hygiene',
            index: 2
        },
        {
            id: 'health-female-kids-4',
            title: 'Hygiene Match',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-4'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/hygiene-match',
            index: 3
        },
        {
            id: 'health-female-kids-5',
            title: 'Bath Time Story',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-5'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/bath-time-story',
            index: 4
        },
        {
            id: 'health-female-kids-6',
            title: 'Fresh & Neat Poster',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-6'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/fresh-poster',
            index: 5
        },
        {
            id: 'health-female-kids-7',
            title: 'Hygiene Journal',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-7'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/hygiene-journal',
            index: 6
        },
        {
            id: 'health-female-kids-8',
            title: 'Hair Care Story',
            icon: <Shirt className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-8'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/hair-care-story',
            index: 7
        },
        {
            id: 'health-female-kids-9',
            title: 'Dress Up Reflex',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-9'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-hygiene-alert',
            index: 8
        },
        {
            id: 'health-female-kids-10',
            title: 'Vaccine Story',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-10'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/vaccine-story',
            index: 9
        },
        
        {
            id: 'health-female-kids-11',
            title: 'Fruit vs Candy Story',
            icon: <Apple className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-11'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/fruit-vs-candy-story',
            index: 10
        },
        {
            id: 'health-female-kids-12',
            title: 'Quiz on Food Groups',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-12'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/quiz-food-groups',
            index: 11
        },
        {
            id: 'health-female-kids-13',
            title: 'Reflex Healthy Food',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-13'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-healthy-food',
            index: 12
        },
        {
            id: 'health-female-kids-14',
            title: 'Puzzle: Nutrition Match',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-14'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/nutrition-match-puzzle',
            index: 13
        },
        {
            id: 'health-female-kids-15',
            title: 'Lunchbox Story',
            icon: <Carrot className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-15'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/lunchbox-story',
            index: 14
        },
        {
            id: 'health-female-kids-16',
            title: 'Poster: My Healthy Plate',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-16'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/healthy-plate-poster',
            index: 15
        },
        {
            id: 'health-female-kids-17',
            title: 'Journal of Healthy Food',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-17'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/healthy-food-journal',
            index: 16
        },
        {
            id: 'health-female-kids-18',
            title: 'Junk Food Story',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-18'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/junk-food-story',
            index: 17
        },
        {
            id: 'health-female-kids-19',
            title: 'Reflex Smart Drink',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-19'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-smart-drink',
            index: 18
        },
        {
            id: 'health-female-kids-20',
            title: 'Badge: Nutrition Smart Kid',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-20'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/nutrition-smart-badge',
            index: 19
        },
        {
            id: 'health-female-kids-21',
            title: 'Growing Taller Story',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-21'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/growing-taller-story',
            index: 20
        },
        {
            id: 'health-female-kids-22',
            title: 'Quiz on Growth',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-22'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/quiz-growth',
            index: 21
        },
        {
            id: 'health-female-kids-23',
            title: 'Reflex Growth Check',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-23'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-growth-check',
            index: 22
        },
        {
            id: 'health-female-kids-24',
            title: 'Puzzle: Growth Helpers',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-24'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/growth-helpers-puzzle',
            index: 23
        },
        {
            id: 'health-female-kids-25',
            title: 'Hair Growth Story',
            icon: <Shirt className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-kids-25'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/hair-growth-story',
            index: 24
        },
        {
            id: 'health-female-kids-26',
            title: 'Poster: Growing Up is Natural',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-26'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/growing-up-poster',
            index: 25
        },
        {
            id: 'health-female-kids-27',
            title: 'Journal of Body Changes',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-27'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/body-changes-journal',
            index: 26
        },
        {
            id: 'health-female-kids-28',
            title: 'Mood Change Story',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-28'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/mood-change-story',
            index: 27
        },
        {
            id: 'health-female-kids-29',
            title: 'Reflex Growth Alert',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-29'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-growth-alert',
            index: 28
        },
        {
            id: 'health-female-kids-30',
            title: 'Badge: Growing Strong Girl',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-30'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/growing-strong-badge',
            index: 29
        },
        {
            id: 'health-female-kids-31',
            title: 'Morning Routine Story',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-31'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/morning-routine-story',
            index: 30
        },
        {
            id: 'health-female-kids-32',
            title: 'Quiz on Daily Habits',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-32'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/quiz-daily-habits',
            index: 31
        },
        {
            id: 'health-female-kids-33',
            title: 'Reflex Habit Alert',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-33'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-habit-alert',
            index: 32
        },
        {
            id: 'health-female-kids-34',
            title: 'Puzzle: Healthy Matches',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-34'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/healthy-matches-puzzle',
            index: 33
        },
        {
            id: 'health-female-kids-35',
            title: 'Screen-Time Story',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-35'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/screen-time-story',
            index: 34
        },
        {
            id: 'health-female-kids-36',
            title: 'Poster: Healthy Girls Win',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-36'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/healthy-girls-win-poster',
            index: 35
        },
        {
            id: 'health-female-kids-37',
            title: 'Journal of Habits',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-37'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/journal-of-habits',
            index: 36
        },
        {
            id: 'health-female-kids-38',
            title: 'Reading Story',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-38'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reading-story',
            index: 37
        },
        {
            id: 'health-female-kids-39',
            title: 'Reflex Daily Check',
            icon: <HandHeart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-39'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-daily-check',
            index: 38
        },
        {
            id: 'health-female-kids-40',
            title: 'Badge: Healthy Routine Kid',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-40'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/healthy-routine-kid-badge',
            index: 39
        },
        
        {
            id: 'health-female-kids-41',
            title: 'Sweat Story',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-41'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/sweat-story',
            index: 40
        },
        {
            id: 'health-female-kids-42',
            title: 'Quiz on Hygiene',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-42'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/quiz-hygiene',
            index: 41
        },
        {
            id: 'health-female-kids-43',
            title: 'Reflex Hygiene Alert',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-43'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-hygiene-alert-3',
            index: 42
        },
        {
            id: 'health-female-kids-44',
            title: 'Puzzle: Hygiene Match',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-44'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/hygiene-match-puzzle',
            index: 43
        },
        {
            id: 'health-female-kids-45',
            title: 'Dentist Visit Story',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-45'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/dentist-visit-story',
            index: 44
        },
        {
            id: 'health-female-kids-46',
            title: 'Poster: Stay Fresh Everyday',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-46'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/stay-fresh-poster',
            index: 45
        },
        {
            id: 'health-female-kids-47',
            title: 'Journal: Hygiene Habits',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-47'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/hygiene-habits-journal',
            index: 46
        },
        {
            id: 'health-female-kids-48',
            title: 'Skin Care Story',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-48'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/skin-care-story',
            index: 47
        },
        {
            id: 'health-female-kids-49',
            title: 'Reflex Cleanliness',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-49'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-cleanliness',
            index: 48
        },
        {
            id: 'health-female-kids-50',
            title: 'Badge: Fresh Girl',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-kids-50'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/fresh-girl-badge',
            index: 49
        },
        {
            id: 'health-female-kids-51',
            title: 'Feelings Story',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-51'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/feelings-story',
            index: 50
        },
        {
            id: 'health-female-kids-52',
            title: 'Quiz on Emotions',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-52'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/quiz-emotions',
            index: 51
        },
        {
            id: 'health-female-kids-53',
            title: 'Reflex Emotion Basics',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-53'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-emotion-basics',
            index: 52
        },
        {
            id: 'health-female-kids-54',
            title: 'Puzzle: Emotion Match',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-54'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/emotion-match-puzzle',
            index: 53
        },
        {
            id: 'health-female-kids-55',
            title: 'Sharing Story',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-55'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/sharing-story',
            index: 54
        },
        {
            id: 'health-female-kids-56',
            title: 'Poster: All Feelings Are Okay',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-56'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/all-feelings-poster',
            index: 55
        },
        {
            id: 'health-female-kids-57',
            title: 'Journal of Feelings',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-57'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/feelings-journal',
            index: 56
        },
        {
            id: 'health-female-kids-58',
            title: 'Anger Story',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-58'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/anger-story',
            index: 57
        },
        {
            id: 'health-female-kids-59',
            title: 'Reflex Emotion Safety',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-59'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-emotion-safety',
            index: 58
        },
        {
            id: 'health-female-kids-60',
            title: 'Badge: Emotion Explorer',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-60'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/emotion-explorer-badge',
            index: 59
        },
        {
            id: 'health-female-kids-61',
            title: 'Friend\'s Dare Story',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-61'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/friends-dare-story',
            index: 60
        },
        {
            id: 'health-female-kids-62',
            title: 'Quiz on Peer Pressure',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-62'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/quiz-peer-pressure',
            index: 61
        },
        {
            id: 'health-female-kids-63',
            title: 'Reflex Peer Safety',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-63'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-peer-safety',
            index: 62
        },
        {
            id: 'health-female-kids-64',
            title: 'Puzzle: Peer Choices',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-64'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/peer-choices-puzzle',
            index: 63
        },
        {
            id: 'health-female-kids-65',
            title: 'Bully Story',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-65'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/bully-story',
            index: 64
        },
        {
            id: 'health-female-kids-66',
            title: 'Poster: Power of No',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-66'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/power-of-no-poster',
            index: 65
        },
        {
            id: 'health-female-kids-67',
            title: 'Journal of Peer Choices',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-67'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/peer-choices-journal',
            index: 66
        },
        {
            id: 'health-female-kids-68',
            title: 'Mobile Pressure Story',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-68'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/mobile-pressure-story',
            index: 67
        },
        {
            id: 'health-female-kids-69',
            title: 'Reflex Respect Alert',
            icon: <HandHeart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-69'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-respect-alert',
            index: 68
        },
        {
            id: 'health-female-kids-70',
            title: 'Badge: Peer Pressure Fighter',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-70'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/peer-pressure-fighter-badge',
            index: 69
        },
        {
            id: 'health-female-kids-71',
            title: 'Clean Girl Badge',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '1 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-71'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/clean-girl-badge',
            index: 70
        },
        {
            id: 'health-female-kids-72',
            title: 'Quiz on Prevention',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-72'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/quiz-prevention',
            index: 71
        },
        {
            id: 'health-female-kids-73',
            title: 'Reflex Safety',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-73'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-safety',
            index: 72
        },
        {
            id: 'health-female-kids-74',
            title: 'Puzzle: Safety Tools',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-74'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/safety-tools-puzzle',
            index: 73
        },
        {
            id: 'health-female-kids-75',
            title: 'Sick Day Story',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-kids-75'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/sick-day-story',
            index: 74
        },
        {
            id: 'health-female-kids-76',
            title: 'Poster: Prevention First',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-76'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/prevention-first-poster',
            index: 75
        },
        {
            id: 'health-female-kids-77',
            title: 'Journal of Safety',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-77'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/journal-of-safety',
            index: 76
        },
        {
            id: 'health-female-kids-78',
            title: 'Period Hygiene Story',
            icon: <Shirt className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-78'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/period-hygiene-story',
            index: 77
        },
        
        {
            id: 'health-female-kids-79',
            title: 'Reflex Doctor Alert',
            icon: <HandHeart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-79'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-doctor-alert',
            index: 78
        },
        {
            id: 'health-female-kids-80',
            title: 'Badge: Safety Smart Girl',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-80'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/safety-smart-girl-badge',
            index: 79
        },
        {
            id: 'health-female-kids-81',
            title: 'Cigarette Story',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-81'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/cigarette-story',
            index: 80
        },
        {
            id: 'health-female-kids-82',
            title: 'Quiz on Harmful Things',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-82'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/quiz-harmful-things',
            index: 81
        },
        {
            id: 'health-female-kids-83',
            title: 'Reflex Safe Choice',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-83'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-safe-choice',
            index: 82
        },
        {
            id: 'health-female-kids-84',
            title: 'Puzzle: Healthy vs Harmful',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-84'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/healthy-vs-harmful-puzzle',
            index: 83
        },
        {
            id: 'health-female-kids-85',
            title: 'Energy Drinks story',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-85'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/energy-drinks-story',
            index: 84
        },
        {
            id: 'health-female-kids-86',
            title: 'Poster: Say No to Substances',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-86'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/say-no-substances-poster',
            index: 85
        },
        {
            id: 'health-female-kids-87',
            title: 'Journal of Refusal',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-87'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/journal-of-refusal',
            index: 86
        },
        {
            id: 'health-female-kids-88',
            title: 'Peer Story',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-88'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/peer-story',
            index: 87
        },
        {
            id: 'health-female-kids-89',
            title: 'Reflex Danger Alert',
            icon: <HandHeart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-89'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-danger-alert',
            index: 88
        },
        {
            id: 'health-female-kids-90',
            title: 'Badge: Safe Girl',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-90'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/safe-girl-badge',
            index: 89
        },
        {
            id: 'health-female-kids-91',
            title: 'First Period Story',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-91'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/first-period-story',
            index: 90
        },
        {
            id: 'health-female-kids-92',
            title: 'Quiz on Period Basics',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-92'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/quiz-period-basics',
            index: 91
        },
        {
            id: 'health-female-kids-93',
            title: 'Reflex Period Awareness',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-93'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-period-awareness',
            index: 92
        },
        {
            id: 'health-female-kids-94',
            title: 'Puzzle: Period Tools',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-94'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/period-tools-puzzle',
            index: 93
        },
        {
            id: 'health-female-kids-95',
            title: 'Support Story',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-95'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/support-story',
            index: 94
        },
        {
            id: 'health-female-kids-96',
            title: 'Poster: Periods Are Normal',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-96'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/periods-are-normal-poster',
            index: 95
        },
        {
            id: 'health-female-kids-97',
            title: 'Journal of Period Awareness',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-97'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/period-awareness-journal',
            index: 96
        },
        {
            id: 'health-female-kids-98',
            title: 'Hygiene Story',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-98'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/hygiene-story',
            index: 97
        },
        {
            id: 'health-female-kids-99',
            title: 'Reflex Hygiene Alert',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-99'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/reflex-hygiene-alert-2',
            index: 98
        },
        {
            id: 'health-female-kids-100',
            title: 'Badge: Period Ready Kid',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-kids-100'] || false,
            isSpecial: true,
            path: '/student/health-female/kids/period-ready-badge',
            index: 99
        },
    ];

    return healthFemaleGamesKids;
};

export default getHealthFemaleKidsGames;
