import {
    Activity,
    Apple,
    Moon,
    Shield,
    Dumbbell,
    Heart,
    Target,
    BookOpen,
    GraduationCap,
    Trophy,
    Zap,
    Droplets,
    Sun,
    Brain,
    HandHeart,
    Hand,
    Sparkles,
    Shirt,
    Badge,
    MessageCircle,
    Smartphone
} from "lucide-react";
import buildIds from "../buildGameIds";

export const healthFemaleGameIdsTeen = buildIds("health-female", "teen");

export const getHealthFemaleTeenGames = (gameCompletionStatus)=> {
    const healthFemaleGamesTeens = [
        {
            id: 'health-female-teen-1',
            title: 'Puberty Hygiene Story',
            description: 'You sweat more as a teen. Should you bathe daily? Learn proper puberty hygiene for girls!',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-1'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/puberty-hygiene-story',
            index: 0
        },
        {
            id: 'health-female-teen-2',
            title: 'Quiz on Hygiene Needs',
            description: 'What helps prevent body odor? (a) Bathing, (b) Skipping bath). Test your hygiene knowledge!',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-2'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/quiz-hygiene-needs',
            index: 1
        },
        {
            id: 'health-female-teen-3',
            title: 'Reflex Hygiene Check',
            description: 'Quick! Tap 🧴 for "Use Deodorant," ❌ for "Ignore Sweat" in fast hygiene decisions!',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-3'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reflex-hygiene-check',
            index: 2
        },
        {
            id: 'health-female-teen-4',
            title: 'Puzzle: Hygiene Tools',
            description: 'Match "Sanitary Pad → Periods, Soap → Bath, Comb → Hair" in hygiene tool puzzles!',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-4'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/hygiene-tools-puzzle',
            index: 3
        },
        {
            id: 'health-female-teen-5',
            title: 'Oily Skin Story',
            description: 'Teen notices oily skin. Should she wash gently or scrub harshly? Learn proper skincare!',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-5'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/oily-skin-story',
            index: 4
        },
        {
            id: 'health-female-teen-6',
            title: 'Debate: Hygiene = Confidence?',
            description: 'Does personal hygiene improve confidence in teens? Debate the connection between hygiene and self-esteem!',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-6'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/hygiene-confidence-debate',
            index: 5
        },
        {
            id: 'health-female-teen-7',
            title: 'Journal of Self-Care',
            description: 'Write: "One new hygiene routine I started as a teen is ___." Reflect on personal hygiene growth!',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-7'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/self-care-journal',
            index: 6
        },
        {
            id: 'health-female-teen-8',
            title: 'Simulation: Morning Routine',
            description: 'Teen wakes up. Options: (a) Brush + shower, (b) Only brush, (c) Skip both. Choose the healthy routine!',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-8'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/morning-routine-simulation',
            index: 7
        },
        {
            id: 'health-female-teen-9',
            title: 'Reflex Hygiene Alert',
            description: 'Quick! Tap 👚 for "Fresh Clothes," ❌ for "Repeat Dirty Clothes" in hygiene reflex challenges!',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-9'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reflex-hygiene-alert',
            index: 8
        },
        {
            id: 'health-female-teen-10',
            title: 'Badge: Hygiene Pro Girl',
            description: 'Complete 5 teen hygiene tasks to earn your Hygiene Pro Girl Badge!',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            isBadgeGame: true,
            badgeName: 'Badge: Hygiene Pro Girl',
            badgeImage: '/badges/health-female/teens/hygiene-pro-girl-badge.png',
            completed: gameCompletionStatus['health-female-teen-10'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/hygiene-pro-girl-badge',
            index: 9
        },
        // New games (levels 11-20)
        {
            id: 'health-female-teen-11',
            title: 'Balanced Diet Story',
            description: 'Teen chooses fast food daily or balanced plate with dal, rice, veggies. Correct = Balanced plate.',
            icon: <Apple className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-11'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/balanced-diet-story',
            index: 10
        },
        {
            id: 'health-female-teen-12',
            title: 'Quiz on Nutrition',
            description: 'Which supports skin + energy? (a) Fruits + water, (b) Only chips). Correct = Fruits + water.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-12'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/quiz-nutrition',
            index: 11
        },
        {
            id: 'health-female-teen-13',
            title: 'Reflex Teen Food Check',
            description: 'Tap 🥗 for "Balanced Plate," ❌ for "Pizza Every Day."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-13'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reflex-food-check',
            index: 12
        },
        {
            id: 'health-female-teen-14',
            title: 'Puzzle: Nutrients Match',
            description: 'Match "Iron → Spinach, Vitamin C → Orange, Protein → Eggs."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-14'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/nutrients-match-puzzle',
            index: 13
        },
        {
            id: 'health-female-teen-15',
            title: 'Sports Energy Story',
            description: 'After sports, should you drink soda or water + fruits? → Water + fruits.',
            icon: <Dumbbell className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-15'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/sports-energy-story',
            index: 14
        },
        {
            id: 'health-female-teen-16',
            title: 'Debate: Junk Food Sometimes?',
            description: 'Is junk food okay once in a while? → Yes, but limited.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-16'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/junk-food-debate',
            index: 15
        },
        {
            id: 'health-female-teen-17',
            title: 'Journal of Food Choices',
            description: 'Write: "One change I made in my eating habits is ___."',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-17'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/food-choices-journal',
            index: 16
        },
        {
            id: 'health-female-teen-18',
            title: 'Simulation: Weekly Meals',
            description: 'Teen plans meals. Options: All fast food / Balanced meals / Skipping meals. Correct = Balanced meals.',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-18'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/weekly-meals-simulation',
            index: 17
        },
        {
            id: 'health-female-teen-19',
            title: 'Reflex Teen Drink Choice',
            description: 'Tap 💧 for "Water," ❌ for "Cola."',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-19'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reflex-drink-choice',
            index: 18
        },
        {
            id: 'health-female-teen-20',
            title: 'Badge: Nutrition Pro Girl',
            description: 'Complete 5 smart nutrition challenges to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            isBadgeGame: true,
            badgeName: 'Badge: Nutrition Pro Girl',
            badgeImage: '/badges/health-female/teens/badge-nutrition-pro-girl.png',
            completed: gameCompletionStatus['health-female-teen-20'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/nutrition-pro-girl-badge',
            index: 19
        },
        // New games (levels 21-30)
        {
            id: 'health-female-teen-21',
            title: 'Puberty Story',
            description: 'You start noticing new changes like breast growth. What is this? → Puberty.',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-21'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/puberty-story',
            index: 20
        },
        {
            id: 'health-female-teen-22',
            title: 'Quiz on Puberty',
            description: 'Which is a puberty sign in girls? (a) Breast development, (b) Menstruation, (c) Both). Correct = Both.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-22'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/quiz-puberty',
            index: 21
        },
        {
            id: 'health-female-teen-23',
            title: 'Reflex Puberty Basics',
            description: 'Tap ✅ for "Normal Changes," ❌ for "Shame."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-23'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reflex-puberty-basics',
            index: 22
        },
        {
            id: 'health-female-teen-24',
            title: 'Puzzle: Puberty Signs',
            description: 'Match "Acne → Puberty, Periods → Puberty, Mood Swings → Puberty."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-24'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/puberty-signs-puzzle',
            index: 23
        },
        {
            id: 'health-female-teen-25',
            title: 'Acne Story',
            description: 'Teen gets pimples. Should she squeeze them? → No, wash gently.',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-female-teen-25'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/acne-story',
            index: 24
        },
        {
            id: 'health-female-teen-26',
            title: 'Debate: Puberty = Awkward?',
            description: 'Is puberty embarrassing or natural? → Natural.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-26'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/puberty-debate',
            index: 25
        },
        {
            id: 'health-female-teen-27',
            title: 'Journal of Teen Growth',
            description: 'Write: "One puberty change I learned to manage is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-27'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/teen-growth-journal',
            index: 26
        },
        {
            id: 'health-female-teen-28',
            title: 'Simulation: Teen Day',
            description: 'Teen\'s day includes study, bath, food. Options: Balanced routine or Skip hygiene. Correct = Balanced routine.',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-28'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/teen-day-simulation',
            index: 27
        },
        {
            id: 'health-female-teen-29',
            title: 'Reflex Teen Health',
            description: 'Tap 🥗 for "Balanced Diet," ❌ for "Skip Meals."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-29'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reflex-teen-health',
            index: 28
        },
        {
            id: 'health-female-teen-30',
            title: 'Badge: Puberty Smart Teen Girl',
            description: 'Handle 5 puberty scenarios responsibly to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            isBadgeGame: true,
            badgeName: 'Badge: Puberty Smart Teen Girl',
            badgeImage: '/badges/health-female/teens/badge-puberty-smart-teen-girl.png',
            completed: gameCompletionStatus['health-female-teen-30'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/puberty-smart-girl-badge',
            index: 29
        },
        // New games (levels 31-40)
        {
            id: 'health-female-teen-31',
            title: 'Reproductive Story',
            description: 'Teacher explains reproductive health is part of growing up. What should girls do? → Listen calmly.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-31'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reproductive-story',
            index: 30
        },
        {
            id: 'health-female-teen-32',
            title: 'Quiz on Reproductive Basics',
            description: 'Which organ releases eggs? (a) Ovaries, (b) Stomach, (c) Heart). Correct = Ovaries.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-32'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/quiz-reproductive-basics',
            index: 31
        },
        {
            id: 'health-female-teen-33',
            title: 'Reflex Teen Awareness',
            description: 'Tap ✅ for "Reproductive Health = Natural," ❌ for "Reproductive Health = Shame."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-33'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reflex-teen-awareness',
            index: 32
        },
        {
            id: 'health-female-teen-34',
            title: 'Puzzle: System Match',
            description: 'Match "Ovaries → Eggs, Uterus → Growth, Hormones → Changes."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-34'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/puzzle-system-match',
            index: 33
        },
        {
            id: 'health-female-teen-35',
            title: 'Period Pain Story',
            description: 'A girl has cramps. What helps? → Rest + hot water bag.',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-35'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/period-pain-story',
            index: 34
        },
        {
            id: 'health-female-teen-36',
            title: 'Debate: Talking About Periods',
            description: 'Should periods be openly discussed? → Yes, with respect.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-36'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/debate-talking-about-periods',
            index: 35
        },
        {
            id: 'health-female-teen-37',
            title: 'Journal of Awareness',
            description: 'Write: "One fact I learned about reproductive health is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-37'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/journal-of-awareness',
            index: 36
        },
        {
            id: 'health-female-teen-38',
            title: 'Simulation: School Scenario',
            description: 'Teen gets period in class. Options: Stay silent, Tell teacher, Ask friend. Correct = Tell teacher/Ask friend.',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-38'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/simulation-school-scenario',
            index: 37
        },
        {
            id: 'health-female-teen-39',
            title: 'Reflex Health Choice',
            description: 'Tap 🏥 for "Visit Doctor if Needed," ❌ for "Ignore Pain."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-39'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reflex-health-choice',
            index: 38
        },
        {
            id: 'health-female-teen-40',
            title: 'Badge: Repro Health Smart Teen',
            description: 'Complete 5 reproductive health tasks to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            isBadgeGame: true,
            badgeName: 'Badge: Repro Health Smart Teen',
            badgeImage: '/badges/health-female/teens/badge-repro-health-smart-teen.png',
            completed: gameCompletionStatus['health-female-teen-40'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/repro-health-smart-teen-badge',
            index: 39
        },
        // New games (levels 41-50)
        {
            id: 'health-female-teen-41',
            title: 'Sweat Control Story',
            description: 'Teen girl plays sports. Should she shower after? → Yes.',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-41'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/sweat-control-story',
            index: 40
        },
        {
            id: 'health-female-teen-42',
            title: 'Quiz on Teen Hygiene',
            description: 'Which helps skin health? (a) Gentle wash, (b) Ignoring pimples). Correct = Gentle wash.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-42'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/quiz-teen-hygiene',
            index: 41
        },
        {
            id: 'health-female-teen-43',
            title: 'Reflex Teen Hygiene',
            description: 'Tap 🩹 for "Change Pads Often," ❌ for "Keep Same Pad."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-43'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reflex-teen-hygiene',
            index: 42
        },
        {
            id: 'health-female-teen-44',
            title: 'Puzzle: Hygiene Tools',
            description: 'Match "Face Wash → Acne, Pad → Periods, Soap → Bath."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-44'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/puzzle-hygiene-tools',
            index: 43
        },
        {
            id: 'health-female-teen-45',
            title: 'Period Routine Story',
            description: 'Teen has heavy flow. Should she use pad + change often? → Yes.',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-45'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/period-routine-story',
            index: 44
        },
        {
            id: 'health-female-teen-46',
            title: 'Debate: Period Hygiene in Schools',
            description: 'Should schools teach period hygiene openly? → Yes.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-46'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/debate-period-hygiene-schools',
            index: 45
        },
        {
            id: 'health-female-teen-47',
            title: 'Journal of Teen Hygiene',
            description: 'Write: "One hygiene challenge I overcame is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-47'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/journal-teen-hygiene',
            index: 46
        },
        {
            id: 'health-female-teen-48',
            title: 'Simulation: Daily Routine',
            description: 'Teen routine → Brush + Bath + Pad Change vs Skip hygiene. Correct = Brush + Bath + Pad Change.',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-48'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/simulation-daily-routine',
            index: 47
        },
        {
            id: 'health-female-teen-49',
            title: 'Reflex Teen Freshness',
            description: 'Tap 👚 for "Fresh Clothes," ❌ for "Dirty Clothes."',
            icon: <Shirt className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-female-teen-49'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reflex-teen-freshness',
            index: 48
        },
        {
            id: 'health-female-teen-50',
            title: 'Badge: Hygiene Pro Girl',
            description: 'Complete all hygiene mastery tasks to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            isBadgeGame: true,
            badgeName: 'Badge: Hygiene Pro Girl',
            badgeImage: '/badges/health-female/teens/badge-hygiene-pro-girl.png',
            completed: gameCompletionStatus['health-female-teen-50'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/badge-hygiene-pro-girl',
            index: 49
        },
        // New games (levels 51-60)
        {
            id: 'health-female-teen-51',
            title: 'Stress Story',
            description: 'Exams coming. Should you plan breaks or panic? → Plan breaks.',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-51'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/stress-story',
            index: 50
        },
        {
            id: 'health-female-teen-52',
            title: 'Quiz on Stress Relief',
            description: 'Which reduces stress? (a) Yoga + sleep, (b) Worry more). Correct = Yoga + sleep.',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-52'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/quiz-stress-relief',
            index: 51
        },
        {
            id: 'health-female-teen-53',
            title: 'Reflex Stress Check',
            description: 'Tap 💬 for "Talk to Friend," ❌ for "Bottle Emotions."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-53'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reflex-stress-check',
            index: 52
        },
        {
            id: 'health-female-teen-54',
            title: 'Puzzle: Mind-Body Match',
            description: 'Match "Sleep → Relax, Deep Breath → Calm, Exercise → Energy."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-54'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/puzzle-mind-body-match',
            index: 53
        },
        {
            id: 'health-female-teen-55',
            title: 'Body Image Story',
            description: 'Teen feels bad about weight. Should she compare or accept herself? → Accept.',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-55'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/body-image-story',
            index: 54
        },
        {
            id: 'health-female-teen-56',
            title: 'Debate: Girls Should Not Cry?',
            description: 'Is crying weakness or natural? → Natural.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-56'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/debate-girls-should-not-cry',
            index: 55
        },
        {
            id: 'health-female-teen-57',
            title: 'Journal of Stress Relief',
            description: 'Write: "One way I manage stress is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-57'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/journal-stress-relief',
            index: 56
        },
        {
            id: 'health-female-teen-58',
            title: 'Simulation: Teen Stress Day',
            description: 'Teen has exams + practice. Options: Plan & Relax / Panic / Quit. Correct = Plan & Relax.',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-58'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/simulation-teen-stress-day',
            index: 57
        },
        {
            id: 'health-female-teen-59',
            title: 'Reflex Emotional Health',
            description: 'Tap 🆘 for "Seek Help," ❌ for "Stay Silent."',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-59'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reflex-emotional-health',
            index: 58
        },
        {
            id: 'health-female-teen-60',
            title: 'Badge: Emotion Smart Teen Girl',
            description: 'Handle 5 emotional health cases to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            isBadgeGame: true,
            badgeName: 'Badge: Emotion Smart Teen Girl',
            badgeImage: '/badges/health-female/teens/badge-emotion-smart-teen-girl.png',
            completed: gameCompletionStatus['health-female-teen-60'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/badge-emotion-smart-teen-girl',
            index: 59
        },
        // New games (levels 61-70)
        {
            id: 'health-female-teen-61',
            title: 'Self-Image Story',
            description: 'Teen feels she is not pretty. Should she compare or value herself? → Value herself.',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-61'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/self-image-story',
            index: 60
        },
        {
            id: 'health-female-teen-62',
            title: 'Quiz on Self-Esteem',
            description: 'Which builds confidence? (a) Positive self-talk, (b) Negative comparisons). Correct = Positive self-talk.',
            icon: <GraduationCap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-62'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/quiz-self-esteem',
            index: 61
        },
        {
            id: 'health-female-teen-63',
            title: 'Reflex Confidence Check',
            description: 'Tap 💪 for "I Can Try," ❌ for "I Am Useless."',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-63'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reflex-confidence-check',
            index: 62
        },
        {
            id: 'health-female-teen-64',
            title: 'Puzzle: Self-Value Match',
            description: 'Match "Courage → Speak Up, Self-Respect → Say No, Kindness → Confidence."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-64'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/puzzle-self-value-match',
            index: 63
        },
        {
            id: 'health-female-teen-65',
            title: 'Social Media Story',
            description: 'Teen feels bad after comparing photos online. What should she do? → Limit social media, focus on real life.',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-65'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/social-media-story',
            index: 64
        },
        {
            id: 'health-female-teen-66',
            title: 'Debate: Beauty = Confidence?',
            description: 'Is beauty or character more important? → Character.',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-66'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/debate-beauty-confidence',
            index: 65
        },
        {
            id: 'health-female-teen-67',
            title: 'Journal of Self-Respect',
            description: 'Write: "One thing I like about myself is ___.',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-67'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/journal-self-respect',
            index: 66
        },
        {
            id: 'health-female-teen-68',
            title: 'Simulation: Peer Test',
            description: 'Friends tease a girl for her dress. Options: Stay silent / Join them / Defend her. Correct = Defend her.',
            icon: <Hand className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-68'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/simulation-peer-test',
            index: 67
        },
        {
            id: 'health-female-teen-69',
            title: 'Reflex Teen Esteem',
            description: 'Tap ❤️ for "Respect Myself," ❌ for "Put Myself Down."',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-69'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reflex-teen-esteem',
            index: 68
        },
        {
            id: 'health-female-teen-70',
            title: 'Badge: Confident Teen Girl',
            description: 'Complete 5 confidence-building activities to earn your badge.',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            isBadgeGame: true,
            badgeName: 'Badge: Confident Teen Girl',
            badgeImage: '/badges/health-female/teens/badge-confident-teen-girl.png',
            completed: gameCompletionStatus['health-female-teen-70'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/badge-confident-teen-girl',
            index: 69
        },
        // New preventive care games (levels 71-80)
        {
            id: 'health-female-teen-71',
            title: 'Health Check Story',
            description: 'Teen feels dizzy often. Should she visit doctor? Learn about health checkups!',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-71'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/health-check-story',
            index: 70
        },
        {
            id: 'health-female-teen-72',
            title: 'Quiz on Preventive Health',
            description: 'Which is preventive care? (a) Vaccines, (b) Ignoring illness). Test your knowledge!',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-72'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/quiz-preventive-health',
            index: 71
        },
        {
            id: 'health-female-teen-73',
            title: 'Reflex Teen Health',
            description: 'Tap 🏥 for "Regular Checkups," ❌ for "Avoid Doctor." Test your reflexes!',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-73'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reflex-preventive-care',
            index: 72
        },
        {
            id: 'health-female-teen-74',
            title: 'Puzzle: Doctor Tools',
            description: 'Match "Stethoscope → Heart, Thermometer → Fever, Vaccine → Protection."',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-74'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/puzzle-doctor-tools',
            index: 73
        },
        {
            id: 'health-female-teen-75',
            title: 'Specialist Story',
            description: 'Teen has skin allergy. Should she visit dermatologist? Learn about specialists!',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-female-teen-75'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/specialist-story',
            index: 74
        },
        {
            id: 'health-female-teen-76',
            title: 'Debate: Doctor Fear',
            description: 'Are doctor visits scary or safe? Debate the importance of medical care!',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-76'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/debate-doctor-fear',
            index: 75
        },
        {
            id: 'health-female-teen-77',
            title: 'Journal of Doctor Visits',
            description: 'Write: "One time I visited a doctor for ___." Reflect on healthcare experiences!',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-77'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/journal-doctor-visits',
            index: 76
        },
        {
            id: 'health-female-teen-78',
            title: 'Simulation: Clinic Visit',
            description: 'Teen books appointment. Options: Wait calmly / Panic / Leave. Choose wisely!',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-78'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/simulation-clinic-visit',
            index: 77
        },
        {
            id: 'health-female-teen-79',
            title: 'Reflex Teen Alert',
            description: 'Tap 💊 for "Take Medicine as Advised," ❌ for "Skip Dose." Quick decisions!',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-79'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reflex-teen-alert',
            index: 78
        },
        {
            id: 'health-female-teen-80',
            title: 'Badge: Preventive Care Teen',
            description: 'Complete 5 preventive care activities to earn your Preventive Care Teen Badge!',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            isBadgeGame: true,
            badgeName: 'Badge: Preventive Care Teen',
            badgeImage: '/badges/health-female/teens/badge-preventive-care-teen.png',
            completed: gameCompletionStatus['health-female-teen-80'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/preventive-care-teen-badge',
            index: 79
        },
        // New substance abuse prevention games (levels 81-90)
        {
            id: 'health-female-teen-81',
            title: 'Peer Pressure Story',
            description: 'Friends push you to smoke once. Should you? Learn to resist peer pressure!',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-81'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/peer-pressure-story',
            index: 80
        },
        {
            id: 'health-female-teen-82',
            title: 'Quiz on Dangers',
            description: 'Smoking can cause? (a) Lung damage, (b) Healthy teeth). Test your knowledge!',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-82'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/quiz-dangers',
            index: 81
        },
        {
            id: 'health-female-teen-83',
            title: 'Reflex Teen Choice',
            description: 'Tap ⚽ for "Sports," ❌ for "Alcohol." Make healthy choices quickly!',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-83'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reflex-teen-choice',
            index: 82
        },
        {
            id: 'health-female-teen-84',
            title: 'Puzzle: Substance Effects',
            description: 'Match "Smoking → Lungs, Alcohol → Liver, Drugs → Brain." Learn the effects!',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-84'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/puzzle-substance-effects',
            index: 83
        },
        {
            id: 'health-female-teen-85',
            title: 'Party Story',
            description: 'Teen sees drugs at a party. Should she try? Learn to make safe choices!',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-85'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/party-story',
            index: 84
        },
        {
            id: 'health-female-teen-86',
            title: 'Debate: Is Smoking Cool?',
            description: 'Does smoking make you cool? Debate the truth about substance use!',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-86'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/debate-smoking-cool',
            index: 85
        },
        {
            id: 'health-female-teen-87',
            title: 'Journal of Awareness',
            description: 'Write: "The substance I will never use is ___." Reflect on your commitments!',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-87'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/journal-awareness',
            index: 86
        },
        {
            id: 'health-female-teen-88',
            title: 'Simulation: Peer Test',
            description: 'Friends force you at a party. Options: Say No / Walk Away / Try. Choose wisely!',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-88'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/simulation-peer-test-substance',
            index: 87
        },
        {
            id: 'health-female-teen-89',
            title: 'Reflex Teen Safety',
            description: 'Tap 🆘 for "Seek Help," ❌ for "Use Substances." Quick safety decisions!',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-89'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reflex-teen-safety',
            index: 88
        },
        {
            id: 'health-female-teen-90',
            title: 'Badge: Drug-Free Teen Girl',
            description: 'Complete 5 drug-prevention scenarios to earn your Drug-Free Teen Girl Badge!',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            isBadgeGame: true,
            badgeName: 'Badge: Drug-Free Teen Girl',
            badgeImage: '/badges/health-female/teens/badge-drug-free-teen-girl.png',
            completed: gameCompletionStatus['health-female-teen-90'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/drug-free-teen-girl-badge',
            index: 89
        },
        // New healthy habits games (levels 91-100)
        {
            id: 'health-female-teen-91',
            title: 'Routine Story',
            description: 'Teen girl sleeps late and wakes tired. Should she fix routine? Learn about healthy routines!',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-91'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/routine-story',
            index: 90
        },
        {
            id: 'health-female-teen-92',
            title: 'Quiz on Teen Habits',
            description: 'Which builds long-term health? (a) Balanced diet + sleep, (b) Skipping meals). Test your knowledge!',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-92'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/quiz-teen-habits',
            index: 91
        },
        {
            id: 'health-female-teen-93',
            title: 'Reflex Teen Habits',
            description: 'Tap 🏃‍♀️ for "Exercise Daily," ❌ for "Ignore Health." Build healthy reflexes!',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-93'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reflex-teen-habits',
            index: 92
        },
        {
            id: 'health-female-teen-94',
            title: 'Puzzle: Habit Builder',
            description: 'Match "Water → Hydration, Exercise → Fitness, Study → Focus." Build healthy habits!',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-94'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/puzzle-habit-builder',
            index: 93
        },
        {
            id: 'health-female-teen-95',
            title: 'Chores Story',
            description: 'Teen refuses to help at home. Should she? Learn about responsibility through chores!',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-95'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/chores-story',
            index: 94
        },
        {
            id: 'health-female-teen-96',
            title: 'Debate: Discipline = Freedom?',
            description: 'Does discipline give freedom or restrict? Debate the power of self-discipline!',
            icon: <MessageCircle className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-96'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/debate-discipline-freedom',
            index: 95
        },
        {
            id: 'health-female-teen-97',
            title: 'Journal of Teen Habits',
            description: 'Write: "One habit I built as a teen is ___." Reflect on positive habits!',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-97'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/journal-teen-habits',
            index: 96
        },
        {
            id: 'health-female-teen-98',
            title: 'Simulation: Time Balance',
            description: 'Teen has exams + sports. Options: Balance time / Waste time. Learn time management!',
            icon: <Smartphone className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-98'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/simulation-time-balance',
            index: 97
        },
        {
            id: 'health-female-teen-99',
            title: 'Reflex Teen Alert',
            description: 'Tap 🔄 for "Consistency," ❌ for "Skipping Habits." Maintain healthy consistency!',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-female-teen-99'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/reflex-teen-alert-habits',
            index: 98
        },
        {
            id: 'health-female-teen-100',
            title: 'Badge: Lifelong Healthy Girl',
            description: 'Complete all healthy habit activities to earn your Lifelong Healthy Girl Badge!',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            isBadgeGame: true,
            badgeName: 'Badge: Lifelong Healthy Girl',
            badgeImage: '/badges/health-female/teens/badge-lifelong-healthy-girl.png',
            completed: gameCompletionStatus['health-female-teen-100'] || false,
            isSpecial: true,
            path: '/student/health-female/teens/lifelong-healthy-girl-badge',
            index: 99
        }
    ];

    return healthFemaleGamesTeens;
};

export default getHealthFemaleTeenGames;
