import {
   Trophy, Puzzle, Users, Zap, Gamepad2, Brain, Heart, Target, BookOpen, GraduationCap, ShoppingCart, Award,  Sun, HelpCircle, Brush, Image, FileText, BookOpenCheck, ToyBrick, MessageCircle, CloudRain, Moon, Tablet, Key, Activity
  } from "lucide-react";
  
import buildIds from "../buildGameIds";

export const brainGamesKidsIds = buildIds("brain", "kids");

export const getBrainKidsGames = (gameCompletionStatus)=> {
    const brainKidsGames = [
        {
          id: "brain-kids-1",
          title: "Water Story",
          icon: <Brain className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-1"] || false,
          isSpecial: true,
          path: "/student/brain/kids/water-story",
          index: 0,
        },
        {
          id: "brain-kids-2",
          title: "Quiz on Brain Food",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-2"] || false,
          isSpecial: true,
          path: "/student/brain/kids/quiz-on-brain-food",
          index: 1,
        },
        {
          id: "brain-kids-3",
          title: "Reflex Brain Boost",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-3"] || false,
          isSpecial: true,
          path: "/student/brain/kids/reflex-brain-boost",
          index: 2,
        },
        {
          id: "brain-kids-4",
          title: "Puzzle of Brain Care",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-4"] || false,
          isSpecial: true,
          path: "/student/brain/kids/puzzle-of-brain-care",
          index: 3,
        },
        {
          id: "brain-kids-5",
          title: "Breakfast Story",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-5"] || false,
          isSpecial: true,
          path: "/student/brain/kids/breakfast-story",
          index: 4,
        },
        {
          id: "brain-kids-6",
          title: "Poster: Brain Health",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-6"] || false,
          isSpecial: true,
          path: "/student/brain/kids/poster-brain-health",
          index: 5,
        },
        {
          id: "brain-kids-7",
          title: "Journal of Habits",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-7"] || false,
          isSpecial: true,
          path: "/student/brain/kids/journal-of-habits",
          index: 6,
        },
        {
          id: "brain-kids-8",
          title: "Sports Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-8"] || false,
          isSpecial: true,
          path: "/student/brain/kids/sports-story",
          index: 7,
        },
        {
          id: "brain-kids-9",
          title: "Reflex Daily Habit",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-9"] || false,
          isSpecial: true,
          path: "/student/brain/kids/reflex-daily-habit",
          index: 8,
        },
        {
          id: "brain-kids-10",
          title: "Badge: Brain Care Kid",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-10"] || false,
          isSpecial: true,
          path: "/student/brain/kids/badge-brain-care-kid",
          index: 9,
        },
        {
          id: "brain-kids-11",
          title: "Classroom Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-11"] || false,
          isSpecial: true,
          path: "/student/brain/kids/classroom-story",
          index: 10,
        },
        {
          id: "brain-kids-12",
          title: "Quiz on Focus",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-12"] || false,
          isSpecial: true,
          path: "/student/brain/kids/quiz-on-focus",
          index: 11,
        },
        {
          id: "brain-kids-13",
          title: "Reflex Attention",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-13"] || false,
          isSpecial: true,
          path: "/student/brain/kids/reflex-attention",
          index: 12,
        },
        {
          id: "brain-kids-14",
          title: "Puzzle of Focus",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-14"] || false,
          isSpecial: true,
          path: "/student/brain/kids/puzzle-of-focus",
          index: 13,
        },
        {
          id: "brain-kids-15",
          title: "Homework Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-15"] || false,
          isSpecial: true,
          path: "/student/brain/kids/homework-story",
          index: 14,
        },
        {
          id: "brain-kids-16",
          title: "Poster: Focus Matters",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-16"] || false,
          isSpecial: true,
          path: "/student/brain/kids/poster-focus-matters",
          index: 15,
        },
        {
          id: "brain-kids-17",
          title: "Journal of Focus",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-17"] || false,
          isSpecial: true,
          path: "/student/brain/kids/journal-of-focus",
          index: 16,
        },
        {
          id: "brain-kids-18",
          title: "Game Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-18"] || false,
          isSpecial: true,
          path: "/student/brain/kids/game-story",
          index: 17,
        },
        {
          id: "brain-kids-19",
          title: "Reflex Quick Attention",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-19"] || false,
          isSpecial: true,
          path: "/student/brain/kids/reflex-quick-attention",
          index: 18,
        },
        {
          id: "brain-kids-20",
          title: "Badge: Focus Kid",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-20"] || false,
          isSpecial: true,
          path: "/student/brain/kids/badge-focus-kid",
          index: 19,
        },
        {
          id: "brain-kids-21",
          title: "Shopping List Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-21"] || false,
          isSpecial: true,
          path: "/student/brain/kids/shopping-list-story",
          index: 20,
        },
        {
          id: "brain-kids-22",
          title: "Quiz on Memory",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-22"] || false,
          isSpecial: true,
          path: "/student/brain/kids/quiz-on-memory",
          index: 21,
        },
        {
          id: "brain-kids-23",
          title: "Reflex Recall",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-23"] || false,
          isSpecial: true,
          path: "/student/brain/kids/reflex-recall",
          index: 22,
        },
        {
          id: "brain-kids-24",
          title: "Puzzle: Memory Match",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-24"] || false,
          isSpecial: true,
          path: "/student/brain/kids/memory-match",
          index: 23,
        },
        {
          id: "brain-kids-25",
          title: "Story of Repetition",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-kids-25"] || false,
          isSpecial: true,
          path: "/student/brain/kids/story-of-repetition",
          index: 24,
        },
        {
          id: "brain-kids-26",
          title: "Poster: Strong Memory",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-26"] || false,
          isSpecial: true,
          path: "/student/brain/kids/poster-strong-memory",
          index: 25,
        },
        {
          id: "brain-kids-27",
          title: "Journal of Recall",
          icon: <FileText className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-27"] || false,
          isSpecial: true,
          path: "/student/brain/kids/journal-of-recall",
          index: 26,
        },
        {
          id: "brain-kids-28",
          title: "Game Story",
          icon: <Gamepad2 className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-28"] || false,
          isSpecial: true,
          path: "/student/brain/kids/game",
          index: 27,
        },
        {
          id: "brain-kids-29",
          title: "Reflex Sequence",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-29"] || false,
          isSpecial: true,
          path: "/student/brain/kids/reflex-sequence",
          index: 28,
        },
        {
          id: "brain-kids-30",
          title: "Badge: Memory Kid",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-30"] || false,
          isSpecial: true,
          path: "/student/brain/kids/badge-memory-kid",
          index: 29,
        },
        {
          id: "brain-kids-31",
          title: "Homework Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-31"] || false,
          isSpecial: true,
          path: "/student/brain/kids/homework-calm-story",
          index: 30,
        },
        {
          id: "brain-kids-32",
          title: "Quiz on Calmness",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-32"] || false,
          isSpecial: true,
          path: "/student/brain/kids/quiz-on-calmness",
          index: 31,
        },
        {
          id: "brain-kids-33",
          title: "Reflex Calm",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-33"] || false,
          isSpecial: true,
          path: "/student/brain/kids/reflex-calm",
          index: 32,
        },
        {
          id: "brain-kids-34",
          title: "Puzzle of Relaxing",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-34"] || false,
          isSpecial: true,
          path: "/student/brain/kids/puzzle-of-relaxing",
          index: 33,
        },
        {
          id: "brain-kids-35",
          title: "Exam Story",
          icon: <BookOpenCheck className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-35"] || false,
          isSpecial: true,
          path: "/student/brain/kids/exam-storyy",
          index: 34,
        },
        {
          id: "brain-kids-36",
          title: "Poster: Stay Cool",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-36"] || false,
          isSpecial: true,
          path: "/student/brain/kids/poster-stay-cool",
          index: 35,
        },
        {
          id: "brain-kids-37",
          title: "Journal of Calmness",
          icon: <FileText className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-37"] || false,
          isSpecial: true,
          path: "/student/brain/kids/journal-of-calmness",
          index: 36,
        },
        {
          id: "brain-kids-38",
          title: "Sports Story",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-38"] || false,
          isSpecial: true,
          path: "/student/brain/kids/sports",
          index: 37,
        },
        {
          id: "brain-kids-39",
          title: "Reflex Quick Calm",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-39"] || false,
          isSpecial: true,
          path: "/student/brain/kids/reflex-quick-calm",
          index: 38,
        },
        {
          id: "brain-kids-40",
          title: "Badge: Calm Kid",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-40"] || false,
          isSpecial: true,
          path: "/student/brain/kids/badge-calm-kid",
          index: 39,
        },
        {
          id: "brain-kids-41",
          title: "Toy Broken Story",
          icon: <ToyBrick className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-41"] || false,
          isSpecial: true,
          path: "/student/brain/kids/toy-broken-story",
          index: 40,
        },
        {
          id: "brain-kids-42",
          title: "Quiz on Feelings",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-42"] || false,
          isSpecial: true,
          path: "/student/brain/kids/quiz-on-feelings",
          index: 41,
        },
        {
          id: "brain-kids-43",
          title: "Reflex Emotions",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-43"] || false,
          isSpecial: true,
          path: "/student/brain/kids/reflex-emotions",
          index: 42,
        },
        {
          id: "brain-kids-44",
          title: "Puzzle: Match Feelings",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-44"] || false,
          isSpecial: true,
          path: "/student/brain/kids/match-feelings",
          index: 43,
        },
        {
          id: "brain-kids-45",
          title: "Sharing Story",
          icon: <MessageCircle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-45"] || false,
          isSpecial: true,
          path: "/student/brain/kids/sharing-story",
          index: 44,
        },
        {
          id: "brain-kids-46",
          title: "Poster: Feelings Matter",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-46"] || false,
          isSpecial: true,
          path: "/student/brain/kids/poster-feelings-matter",
          index: 45,
        },
        {
          id: "brain-kids-47",
          title: "Journal of Feelings",
          icon: <FileText className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-47"] || false,
          isSpecial: true,
          path: "/student/brain/kids/journal-of-feelings",
          index: 46,
        },
        {
          id: "brain-kids-48",
          title: "Lost Game Story",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-48"] || false,
          isSpecial: true,
          path: "/student/brain/kids/lost-game-story",
          index: 47,
        },
        {
          id: "brain-kids-49",
          title: "Reflex Quick Emotion",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-49"] || false,
          isSpecial: true,
          path: "/student/brain/kids/reflex-quick-emotion",
          index: 48,
        },
        {
          id: "brain-kids-50",
          title: "Badge: Emotion Kid",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-kids-50"] || false,
          isSpecial: true,
          path: "/student/brain/kids/badge-emotion-kid",
          index: 49,
        },
        {
          id: "brain-kids-51",
          title: "Rainy Day Story",
          icon: <CloudRain className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-51"] || false,
          isSpecial: true,
          path: "/student/brain/kids/rainy-day-story",
          index: 50,
        },
        {
          id: "brain-kids-52",
          title: "Quiz on Positivity",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-52"] || false,
          isSpecial: true,
          path: "/student/brain/kids/quiz-on-positivity",
          index: 51,
        },
        {
          id: "brain-kids-53",
          title: "Reflex Happy Thoughts",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-53"] || false,
          isSpecial: true,
          path: "/student/brain/kids/reflex-happy-thoughts",
          index: 52,
        },
        {
          id: "brain-kids-54",
          title: "Puzzle of Positive Words",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-54"] || false,
          isSpecial: true,
          path: "/student/brain/kids/puzzle-of-positive-words",
          index: 53,
        },
        {
          id: "brain-kids-55",
          title: "Lost Match Story",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-55"] || false,
          isSpecial: true,
          path: "/student/brain/kids/lost-match-story",
          index: 54,
        },
        {
          id: "brain-kids-56",
          title: "Poster: Stay Positive",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-56"] || false,
          isSpecial: true,
          path: "/student/brain/kids/poster-stay-positive",
          index: 55,
        },
        {
          id: "brain-kids-57",
          title: "Journal of Good Things",
          icon: <FileText className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-57"] || false,
          isSpecial: true,
          path: "/student/brain/kids/journal-of-good-things",
          index: 56,
        },
        {
          id: "brain-kids-58",
          title: "Homework Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-58"] || false,
          isSpecial: true,
          path: "/student/brain/kids/homework-positive-story",
          index: 57,
        },
        {
          id: "brain-kids-59",
          title: "Reflex Positive/Negative",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-59"] || false,
          isSpecial: true,
          path: "/student/brain/kids/reflex-positive-negative",
          index: 58,
        },
        {
          id: "brain-kids-60",
          title: "Badge: Positive Kid",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-60"] || false,
          isSpecial: true,
          path: "/student/brain/kids/badge-positive-kid",
          index: 59,
        },
        {
          id: "brain-kids-61",
          title: "Bedtime Story",
          icon: <Moon className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-61"] || false,
          isSpecial: true,
          path: "/student/brain/kids/bedtime-story",
          index: 60,
        },
        {
          id: "brain-kids-62",
          title: "Quiz on Sleep",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-62"] || false,
          isSpecial: true,
          path: "/student/brain/kids/quiz-sleep",
          index: 61,
        },
        {
          id: "brain-kids-63",
          title: "Reflex Sleep Habits",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-63"] || false,
          isSpecial: true,
          path: "/student/brain/kids/reflex-sleep-habits",
          index: 62,
        },
        {
          id: "brain-kids-64",
          title: "Puzzle of Rest",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-64"] || false,
          isSpecial: true,
          path: "/student/brain/kids/puzzle-rest",
          index: 63,
        },
        {
          id: "brain-kids-65",
          title: "Exam Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-65"] || false,
          isSpecial: true,
          path: "/student/brain/kids/exam-stori",
          index: 64,
        },
        {
          id: "brain-kids-66",
          title: "Poster: Sleep Well",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-66"] || false,
          isSpecial: true,
          path: "/student/brain/kids/poster-sleep-well",
          index: 65,
        },
        {
          id: "brain-kids-67",
          title: "Journal of Rest",
          icon: <FileText className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-67"] || false,
          isSpecial: true,
          path: "/student/brain/kids/journal-rest",
          index: 66,
        },
        {
          id: "brain-kids-68",
          title: "Holiday Story",
          icon: <Sun className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-68"] || false,
          isSpecial: true,
          path: "/student/brain/kids/holiday-story",
          index: 67,
        },
        {
          id: "brain-kids-69",
          title: "Reflex Rest Alert",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-69"] || false,
          isSpecial: true,
          path: "/student/brain/kids/reflex-rest-alert",
          index: 68,
        },
        {
          id: "brain-kids-70",
          title: "Badge: Sleep Champ",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-70"] || false,
          isSpecial: true,
          path: "/student/brain/kids/badge-sleep-champ",
          index: 69,
        },
        {
          id: "brain-kids-71",
          title: "Tablet Story",
          icon: <Tablet className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-71"] || false,
          isSpecial: true,
          path: "/student/brain/kids/tablet-story",
          index: 70,
        },
        {
          id: "brain-kids-72",
          title: "Quiz on Screens",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-72"] || false,
          isSpecial: true,
          path: "/student/brain/kids/quiz-screens",
          index: 71,
        },
        {
          id: "brain-kids-73",
          title: "Reflex Digital Choice",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-73"] || false,
          isSpecial: true,
          path: "/student/brain/kids/reflex-digital-choice",
          index: 72,
        },
        {
          id: "brain-kids-74",
          title: "Puzzle of Balance",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-74"] || false,
          isSpecial: true,
          path: "/student/brain/kids/puzzle-balance",
          index: 73,
        },
        {
          id: "brain-kids-75",
          title: "Homework Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-kids-75"] || false,
          isSpecial: true,
          path: "/student/brain/kids/homework-balance-story",
          index: 74,
        },
        {
          id: "brain-kids-76",
          title: "Poster: Balance Tech",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-76"] || false,
          isSpecial: true,
          path: "/student/brain/kids/poster-balance-tech",
          index: 75,
        },
        {
          id: "brain-kids-77",
          title: "Journal of Screen Use",
          icon: <FileText className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-77"] || false,
          isSpecial: true,
          path: "/student/brain/kids/journal-screen-use",
          index: 76,
        },
        {
          id: "brain-kids-78",
          title: "Outdoor Story",
          icon: <Sun className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-78"] || false,
          isSpecial: true,
          path: "/student/brain/kids/outdoor-story",
          index: 77,
        },
        {
          id: "brain-kids-79",
          title: "Reflex Screen Alert",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-79"] || false,
          isSpecial: true,
          path: "/student/brain/kids/reflex-screen-alert",
          index: 78,
        },
        {
          id: "brain-kids-80",
          title: "Badge: Balanced Kid",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-80"] || false,
          isSpecial: true,
          path: "/student/brain/kids/badge-balanced-kid",
          index: 79,
        },
        {
          id: "brain-kids-81",
          title: "Lost Key Story",
          icon: <Key className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-81"] || false,
          isSpecial: true,
          path: "/student/brain/kids/lost-key-story",
          index: 80,
        },
        {
          id: "brain-kids-82",
          title: "Quiz on Creativity",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-82"] || false,
          isSpecial: true,
          path: "/student/brain/kids/quiz-creativity",
          index: 81,
        },
        {
          id: "brain-kids-83",
          title: "Reflex Problem Solver",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-83"] || false,
          isSpecial: true,
          path: "/student/brain/kids/reflex-problem-solver",
          index: 82,
        },
        {
          id: "brain-kids-84",
          title: "Puzzle of Solutions",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-84"] || false,
          isSpecial: true,
          path: "/student/brain/kids/puzzle-solutions",
          index: 83,
        },
        {
          id: "brain-kids-85",
          title: "Group Story",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-85"] || false,
          isSpecial: true,
          path: "/student/brain/kids/group-story",
          index: 84,
        },
        {
          id: "brain-kids-86",
          title: "Poster: Be Creative",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-86"] || false,
          isSpecial: true,
          path: "/student/brain/kids/poster-be-creative",
          index: 85,
        },
        {
          id: "brain-kids-87",
          title: "Journal of Ideas",
          icon: <FileText className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-87"] || false,
          isSpecial: true,
          path: "/student/brain/kids/journal-ideas",
          index: 86,
        },
        {
          id: "brain-kids-88",
          title: "Art Story",
          icon: <Brush className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-88"] || false,
          isSpecial: true,
          path: "/student/brain/kids/art-story",
          index: 87,
        },
        {
          id: "brain-kids-89",
          title: "Reflex Creative Thinking",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-89"] || false,
          isSpecial: true,
          path: "/student/brain/kids/reflex-creative-thinking",
          index: 88,
        },
        {
          id: "brain-kids-90",
          title: "Badge: Creative Kid",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-90"] || false,
          isSpecial: true,
          path: "/student/brain/kids/badge-creative-kid",
          index: 89,
        },
        {
          id: "brain-kids-91",
          title: "Fall Story",
          icon: <Activity className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-91"] || false,
          isSpecial: true,
          path: "/student/brain/kids/fall-story",
          index: 90,
        },
        {
          id: "brain-kids-92",
          title: "Quiz on Resilience",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-92"] || false,
          isSpecial: true,
          path: "/student/brain/kids/quiz-resilience",
          index: 91,
        },
        {
          id: "brain-kids-93",
          title: "Reflex Try Again",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-93"] || false,
          isSpecial: true,
          path: "/student/brain/kids/reflex-try-again",
          index: 92,
        },
        {
          id: "brain-kids-94",
          title: "Puzzle of Resilience",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-94"] || false,
          isSpecial: true,
          path: "/student/brain/kids/puzzle-resilience",
          index: 93,
        },
        {
          id: "brain-kids-95",
          title: "Test Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-95"] || false,
          isSpecial: true,
          path: "/student/brain/kids/test-story",
          index: 94,
        },
        {
          id: "brain-kids-96",
          title: "Poster: Don't Give Up",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-96"] || false,
          isSpecial: true,
          path: "/student/brain/kids/poster-dont-give-up",
          index: 95,
        },
        {
          id: "brain-kids-97",
          title: "Journal of Bounce Back",
          icon: <FileText className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-97"] || false,
          isSpecial: true,
          path: "/student/brain/kids/journal-bounce-back",
          index: 96,
        },
        {
          id: "brain-kids-98",
          title: "Sports Story",
          icon: <Activity className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-98"] || false,
          isSpecial: true,
          path: "/student/brain/kids/sports-story-resilience",
          index: 97,
        },
        {
          id: "brain-kids-99",
          title: "Reflex Growth Thinking",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-99"] || false,
          isSpecial: true,
          path: "/student/brain/kids/reflex-growth-thinking",
          index: 98,
        },
        {
          id: "brain-kids-100",
          title: "Badge: Bounce Back Kid",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-kids-100"] || false,
          isSpecial: true,
          path: "/student/brain/kids/badge-bounce-back-kid",
          index: 99,
        },
      ];

    return brainKidsGames;
}
