import {
  Trophy, 
  Puzzle,  
  Lightbulb, 
  Zap, 
  Brain, 
  Heart, 
  Target, 
  BookOpen, 
  GraduationCap, 
  ShoppingCart, 
  BarChart4, 
  Cpu, 
  Book,  
  HelpCircle,  
  Mic, 
  BookOpenCheck,  
  Activity, 
  PlayCircle
} from "lucide-react";
  
import buildIds from "../buildGameIds";


export const brainGamesTeenIds = buildIds("brain", "teens")

export const getBrainTeenGames = (gameCompletionStatus) => {
    const brainTeenGames = [
        {
          id: "brain-teens-1",
          title: "Exercise Story",
          icon: <Brain className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-1"] || false,
          isSpecial: true,
          path: "/student/brain/teen/exercise-story",
          index: 0,
        },
        {
          id: "brain-teens-2",
          title: "Quiz on Habits",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-2"] || false,
          isSpecial: true,
          path: "/student/brain/teen/quiz-on-habits",
          index: 1,
        },
        {
          id: "brain-teens-3",
          title: "Reflex Mind Check",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-3"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-mind-check",
          index: 2,
        },
        {
          id: "brain-teens-4",
          title: "Puzzle: Brain Fuel",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-4"] || false,
          isSpecial: true,
          path: "/student/brain/teen/puzzle-brain-fuel",
          index: 3,
        },
        {
          id: "brain-teens-5",
          title: "Junk Food Story",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-5"] || false,
          isSpecial: true,
          path: "/student/brain/teen/junk-food-story",
          index: 4,
        },
        {
          id: "brain-teens-6",
          title: "Debate: Brain vs Body",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-6"] || false,
          isSpecial: true,
          path: "/student/brain/teen/debate-brain-vs-body",
          index: 5,
        },
        {
          id: "brain-teens-7",
          title: "Journal of Brain Fitness",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-7"] || false,
          isSpecial: true,
          path: "/student/brain/teen/journal-of-brain-fitness",
          index: 6,
        },
        {
          id: "brain-teens-8",
          title: "Simulation: Daily Routine",
          icon: <BarChart4 className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-8"] || false,
          isSpecial: true,
          path: "/student/brain/teen/simulation-daily-routine",
          index: 7,
        },
        {
          id: "brain-teens-9",
          title: "Reflex Brain Boost",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-9"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-brain-boost",
          index: 8,
        },
        {
          id: "brain-teens-10",
          title: "Badge: Brain Health Hero",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-10"] || false,
          isSpecial: true,
          path: "/student/brain/teen/badge-brain-health-hero",
          index: 9,
        },
        {
          id: "brain-teens-11",
          title: "Exam Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-11"] || false,
          isSpecial: true,
          path: "/student/brain/teen/exam-story",
          index: 10,
        },
        {
          id: "brain-teens-12",
          title: "Quiz on Attention",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-12"] || false,
          isSpecial: true,
          path: "/student/brain/teen/quiz-on-attention",
          index: 11,
        },
        {
          id: "brain-teens-13",
          title: "Reflex Concentration",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-13"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-concentration",
          index: 12,
        },
        {
          id: "brain-teens-14",
          title: "Puzzle of Distractions",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-14"] || false,
          isSpecial: true,
          path: "/student/brain/teen/puzzle-of-distractions",
          index: 13,
        },
        {
          id: "brain-teens-15",
          title: "Social Media Story",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-15"] || false,
          isSpecial: true,
          path: "/student/brain/teen/social-media-story",
          index: 14,
        },
        {
          id: "brain-teens-16",
          title: "Debate: Multitask vs Focus",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-16"] || false,
          isSpecial: true,
          path: "/student/brain/teen/debate-multitask-vs-focus",
          index: 15,
        },
        {
          id: "brain-teens-17",
          title: "Journal of Attention",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-17"] || false,
          isSpecial: true,
          path: "/student/brain/teen/journal-of-attention",
          index: 16,
        },
        {
          id: "brain-teens-18",
          title: "Simulation: Study Plan",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-18"] || false,
          isSpecial: true,
          path: "/student/brain/teen/simulation-study-plan",
          index: 17,
        },
        {
          id: "brain-teens-19",
          title: "Reflex Distraction Alert",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-19"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-distraction-alert",
          index: 18,
        },
        {
          id: "brain-teens-20",
          title: "Badge: Focus Hero",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-20"] || false,
          isSpecial: true,
          path: "/student/brain/teen/badge-focus-hero",
          index: 19,
        },
        {
          id: "brain-teens-21",
          title: "Exam Recall Story",
          icon: <Activity className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-21"] || false,
          isSpecial: true,
          path: "/student/brain/teen/exam-recall-story",
          index: 20,
        },
        {
          id: "brain-teens-22",
          title: "Quiz on Memory Hacks",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-22"] || false,
          isSpecial: true,
          path: "/student/brain/teen/quiz-on-memory-hacks",
          index: 21,
        },
        {
          id: "brain-teens-23",
          title: "Reflex Memory Boost",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-23"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-memory-boost",
          index: 22,
        },
        {
          id: "brain-teens-24",
          title: "Puzzle: Mnemonic Match",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-24"] || false,
          isSpecial: true,
          path: "/student/brain/teen/puzzle-mnemonic-match",
          index: 23,
        },
        {
          id: "brain-teens-25",
          title: "Note-taking Story",
          icon: <BookOpenCheck className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-25"] || false,
          isSpecial: true,
          path: "/student/brain/teen/note-taking-story",
          index: 24,
        },
        {
          id: "brain-teens-26",
          title: "Debate: Rote vs Understanding",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-26"] || false,
          isSpecial: true,
          path: "/student/brain/teen/debate-rote-vs-understanding",
          index: 25,
        },
        {
          id: "brain-teens-27",
          title: "Journal of Tricks",
          icon: <BookOpenCheck className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-27"] || false,
          isSpecial: true,
          path: "/student/brain/teen/journal-of-tricks",
          index: 26,
        },
        {
          id: "brain-teens-28",
          title: "Simulation: Study Plan",
          icon: <Cpu className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-28"] || false,
          isSpecial: true,
          path: "/student/brain/teen/simulation-studyy-plan",
          index: 27,
        },
        {
          id: "brain-teens-29",
          title: "Reflex Recall Quick",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-29"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-recall-quick",
          index: 28,
        },
        {
          id: "brain-teens-30",
          title: "Badge: Memory Hero",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-30"] || false,
          isSpecial: true,
          path: "/student/brain/teen/badge-memory-hero",
          index: 29,
        },
        {
          id: "brain-teens-31",
          title: "Study Pressure Story",
          icon: <Activity className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-31"] || false,
          isSpecial: true,
          path: "/student/brain/teen/study-pressure-story",
          index: 30,
        },
        {
          id: "brain-teens-32",
          title: "Stress Quiz",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-32"] || false,
          isSpecial: true,
          path: "/student/brain/teen/stresss-quiz",
          index: 31,
        },
        {
          id: "brain-teens-33",
          title: "Reflex Stress Check",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-33"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-stress-check",
          index: 32,
        },
        {
          id: "brain-teens-34",
          title: "Puzzle of Relief",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-34"] || false,
          isSpecial: true,
          path: "/student/brain/teen/puzzle-of-relief",
          index: 33,
        },
        {
          id: "brain-teens-35",
          title: "Failure Story",
          icon: <Activity className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-35"] || false,
          isSpecial: true,
          path: "/student/brain/teen/failuree-story",
          index: 34,
        },
        {
          id: "brain-teens-36",
          title: "Debate: Stress Good or Bad?",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-36"] || false,
          isSpecial: true,
          path: "/student/brain/teen/debate-stress-good-or-bad",
          index: 35,
        },
        {
          id: "brain-teens-37",
          title: "Journal of Stress Relief",
          icon: <BookOpenCheck className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-37"] || false,
          isSpecial: true,
          path: "/student/brain/teen/journal-of-stress-relief",
          index: 36,
        },
        {
          id: "brain-teens-38",
          title: "Simulation: Stress Day",
          icon: <Cpu className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-38"] || false,
          isSpecial: true,
          path: "/student/brain/teen/simulation-stress-day",
          index: 37,
        },
        {
          id: "brain-teens-39",
          title: "Reflex Healthy Calm",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-39"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-healthy-calm",
          index: 38,
        },
        {
          id: "brain-teens-40",
          title: "Badge: Stress Manager",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-40"] || false,
          isSpecial: true,
          path: "/student/brain/teen/badge-stress-manager",
          index: 39,
        },
        {
          id: "brain-teens-41",
          title: "Peer Pressure Story",
          icon: <Activity className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-41"] || false,
          isSpecial: true,
          path: "/student/brain/teen/peer-pressuree-story",
          index: 40,
        },
        {
          id: "brain-teens-42",
          title: "Emotion Quiz",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-42"] || false,
          isSpecial: true,
          path: "/student/brain/teen/emotion-quiz",
          index: 41,
        },
        {
          id: "brain-teens-43",
          title: "Reflex Emotion Control",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-43"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-emotion-control",
          index: 42,
        },
        {
          id: "brain-teens-44",
          title: "Puzzle: Emotion Match",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-44"] || false,
          isSpecial: true,
          path: "/student/brain/teen/puzzle-emotion-match",
          index: 43,
        },
        {
          id: "brain-teens-45",
          title: "Anger Story",
          icon: <Activity className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-45"] || false,
          isSpecial: true,
          path: "/student/brain/teen/anger-story",
          index: 44,
        },
        {
          id: "brain-teens-46",
          title: "Debate: Show or Hide Emotions?",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-46"] || false,
          isSpecial: true,
          path: "/student/brain/teen/debate-show-hide-emotions",
          index: 45,
        },
        {
          id: "brain-teens-47",
          title: "Journal of Emotional Moment",
          icon: <BookOpenCheck className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-47"] || false,
          isSpecial: true,
          path: "/student/brain/teen/journal-emotional-moment",
          index: 46,
        },
        {
          id: "brain-teens-48",
          title: "Simulation: Stressful Day",
          icon: <Cpu className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-48"] || false,
          isSpecial: true,
          path: "/student/brain/teen/simulation-stressful-day",
          index: 47,
        },
        {
          id: "brain-teens-49",
          title: "Reflex Positive Emotion",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-49"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-positive-emotion",
          index: 48,
        },
        {
          id: "brain-teens-50",
          title: "Badge: Emotion Hero",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-50"] || false,
          isSpecial: true,
          path: "/student/brain/teen/badge-emotion-hero",
          index: 49,
        },
        {
          id: "brain-teens-51",
          title: "Failure Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-51"] || false,
          isSpecial: true,
          path: "/student/brain/teen/faillure-story",
          index: 50,
        },
        {
          id: "brain-teens-52",
          title: "Positivity Quiz",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-52"] || false,
          isSpecial: true,
          path: "/student/brain/teen/positivitty-quiz",
          index: 51,
        },
        {
          id: "brain-teens-53",
          title: "Reflex Optimism",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-53"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-optimism",
          index: 52,
        },
        {
          id: "brain-teens-54",
          title: "Puzzle: Positive Practices",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-54"] || false,
          isSpecial: true,
          path: "/student/brain/teen/puzzle-positive-practices",
          index: 53,
        },
        {
          id: "brain-teens-55",
          title: "Friend Betrayal Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-55"] || false,
          isSpecial: true,
          path: "/student/brain/teen/friend-betrayal-story",
          index: 54,
        },
        {
          id: "brain-teens-56",
          title: "Debate: Optimism vs Realism",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-56"] || false,
          isSpecial: true,
          path: "/student/brain/teen/debate-optimism-vs-realism",
          index: 55,
        },
        {
          id: "brain-teens-57",
          title: "Journal of Gratitude",
          icon: <BookOpenCheck className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-57"] || false,
          isSpecial: true,
          path: "/student/brain/teen/journall-of-gratitude",
          index: 56,
        },
        {
          id: "brain-teens-58",
          title: "Simulation: Negative Day",
          icon: <PlayCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-58"] || false,
          isSpecial: true,
          path: "/student/brain/teen/simulation-negative-day",
          index: 57,
        },
        {
          id: "brain-teens-59",
          title: "Reflex Mindset Check",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-59"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-mindset-check",
          index: 58,
        },
        {
          id: "brain-teens-60",
          title: "Badge: Optimist Hero",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-60"] || false,
          isSpecial: true,
          path: "/student/brain/teen/badge-optimist-hero",
          index: 59,
        },
        {
          id: "brain-teens-61",
          title: "Sleep Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-61"] || false,
          isSpecial: true,
          path: "/student/brain/teen/sleep-story",
          index: 60,
        },
        {
          id: "brain-teens-62",
          title: "Sleep Quiz",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-62"] || false,
          isSpecial: true,
          path: "/student/brain/teen/sleepp-quiz",
          index: 61,
        },
        {
          id: "brain-teens-63",
          title: "Reflex Rest Habits",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-63"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-rest-habits",
          index: 62,
        },
        {
          id: "brain-teens-64",
          title: "Puzzle of Sleep Health",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-64"] || false,
          isSpecial: true,
          path: "/student/brain/teen/puzzle-of-sleep-health",
          index: 63,
        },
        {
          id: "brain-teens-65",
          title: "Phone Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-65"] || false,
          isSpecial: true,
          path: "/student/brain/teen/phone-story",
          index: 64,
        },
        {
          id: "brain-teens-66",
          title: "Debate: Sleep vs Study",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-66"] || false,
          isSpecial: true,
          path: "/student/brain/teen/debate-sleep-vs-study",
          index: 65,
        },
        {
          id: "brain-teens-67",
          title: "Journal of Sleep Health",
          icon: <BookOpenCheck className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-67"] || false,
          isSpecial: true,
          path: "/student/brain/teen/journal-of-sleep-health",
          index: 66,
        },
        {
          id: "brain-teens-68",
          title: "Simulation: Exam Prep",
          icon: <PlayCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-68"] || false,
          isSpecial: true,
          path: "/student/brain/teen/simulation-exam-prep",
          index: 67,
        },
        {
          id: "brain-teens-69",
          title: "Reflex Smart Rest",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-69"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-smart-rest",
          index: 68,
        },
        {
          id: "brain-teens-70",
          title: "Badge: Rest Hero",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-70"] || false,
          isSpecial: true,
          path: "/student/brain/teen/badge-rest-hero",
          index: 69,
        },
        {
          id: "brain-teens-71",
          title: "Midnight Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-71"] || false,
          isSpecial: true,
          path: "/student/brain/teen/midnight-story",
          index: 70,
        },
        {
          id: "brain-teens-72",
          title: "Quiz on Digital Balance",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-72"] || false,
          isSpecial: true,
          path: "/student/brain/teen/quiz-on-digital-balance",
          index: 71,
        },
        {
          id: "brain-teens-73",
          title: "Reflex Tech Control",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-73"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-tech-control",
          index: 72,
        },
        {
          id: "brain-teens-74",
          title: "Puzzle of Balance Habits",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-74"] || false,
          path: "/student/brain/teen/puzzle-of-balance-habits",
          isSpecial: true,
          index: 73,
        },
        {
          id: "brain-teens-75",
          title: "Gaming Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-75"] || false,
          isSpecial: true,
          path: "/student/brain/teen/gaming-story",
          index: 74,
        },
        {
          id: "brain-teens-76",
          title: "Debate: Tech Good or Bad?",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "7 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-76"] || false,
          isSpecial: true,
          path: "/student/brain/teen/debate-tech-good-or-bad",
          index: 75,
        },
        {
          id: "brain-teens-77",
          title: "Journal of Balance",
          icon: <BookOpenCheck className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-77"] || false,
          path: "/student/brain/teen/journal-balancee",
          isSpecial: true,
          index: 76,
        },
        {
          id: "brain-teens-78",
          title: "Simulation: Daily Routine",
          icon: <PlayCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-78"] || false,
          path: "/student/brain/teen/simulation-daily-routinee",
          isSpecial: true,
          index: 77,
        },
        {
          id: "brain-teens-79",
          title: "Reflex Healthy Use",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-79"] || false,
          path: "/student/brain/teen/reflex-healthy-use",
          isSpecial: true,
          index: 78,
        },
        {
          id: "brain-teens-80",
          title: "Badge: Digital Hero",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-80"] || false,
          isSpecial: true,
          path: "/student/brain/teen/badge-digital-hero",
          index: 79,
        },
        {
          id: "brain-teens-81",
          title: "Science Project Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-81"] || false,
          isSpecial: true,
          path: "/student/brain/teen/science-project-story",
          index: 80,
        },
        {
          id: "brain-teens-82",
          title: "Quiz on Innovation",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-82"] || false,
          isSpecial: true,
          path: "/student/brain/teen/quiz-on-innovation",
          index: 81,
        },
        {
          id: "brain-teens-83",
          title: "Reflex Solution Mode",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-83"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-solution-mode",
          index: 82,
        },
        {
          id: "brain-teens-84",
          title: "Puzzle: Innovators",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-84"] || false,
          isSpecial: true,
          path: "/student/brain/teen/puzzle-innovators",
          index: 83,
        },
        {
          id: "brain-teens-85",
          title: "Startup Idea Story",
          icon: <Lightbulb className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-85"] || false,
          path: "/student/brain/teen/startup-idea-story",
          isSpecial: true,
          index: 84,
        },
        {
          id: "brain-teens-86",
          title: "Debate: Copy vs Create",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-86"] || false,
          isSpecial: true,
          path: "/student/brain/teen/debate-copy-vs-create",
          index: 85,
        },
        {
          id: "brain-teens-87",
          title: "Journal of Creativity",
          icon: <Book className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-87"] || false,
          isSpecial: true,
          path: "/student/brain/teen/journal-of-creativity",
          index: 86,
        },
        {
          id: "brain-teens-88",
          title: "Simulation: School Fair",
          icon: <PlayCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-88"] || false,
          isSpecial: true,
          path: "/student/brain/teen/simulation-school-fair",
          index: 87,
        },
        {
          id: "brain-teens-89",
          title: "Reflex Innovator's Choice",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-89"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-innovators-choice",
          index: 88,
        },
        {
          id: "brain-teens-90",
          title: "Badge: Innovator Hero",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-90"] || false,
          isSpecial: true,
          path: "/student/brain/teen/badge-innovator-hero",
          index: 89,
        },
        {
          id: "brain-teens-91",
          title: "Exam Failure Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-91"] || false,
          isSpecial: true,
          path: "/student/brain/teen/exam-failure-story",
          index: 90,
        },
        {
          id: "brain-teens-92",
          title: "Growth Mindset Quiz",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-92"] || false,
          isSpecial: true,
          path: "/student/brain/teen/growth-mindset-quiz",
          index: 91,
        },
        {
          id: "brain-teens-93",
          title: "Reflex Growth Attitude",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-93"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-growth-attitude",
          index: 92,
        },
        {
          id: "brain-teens-94",
          title: "Puzzle of Growth",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-94"] || false,
          isSpecial: true,
          path: "/student/brain/teen/puzzle-of-growth",
          index: 93,
        },
        {
          id: "brain-teens-95",
          title: "Career Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-95"] || false,
          isSpecial: true,
          path: "/student/brain/teen/career-story",
          index: 94,
        },
        {
          id: "brain-teens-96",
          title: "Debate: Talent vs Effort",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-96"] || false,
          isSpecial: true,
          path: "/student/brain/teen/debate-talent-vs-effort",
          index: 95,
        },
        {
          id: "brain-teens-97",
          title: "Journal of Growth",
          icon: <Book className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-97"] || false,
          isSpecial: true,
          path: "/student/brain/teen/journal-of-growth",
          index: 96,
        },
        {
          id: "brain-teens-98",
          title: "Simulation: Life Choices",
          icon: <PlayCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-98"] || false,
          isSpecial: true,
          path: "/student/brain/teen/simulation-life-choices",
          index: 97,
        },
        {
          id: "brain-teens-99",
          title: "Reflex Never Quit",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-99"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-never-quit",
          index: 98,
        },
        {
          id: "brain-teens-100",
          title: "Badge: Growth Champion",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-100"] || false,
          isSpecial: true,
          path: "/student/brain/teen/badge-growth-champion",
          index: 99,
        },
      ];

    return brainTeenGames;
}
