import {
  Trophy, 
  Puzzle,  
  Lightbulb, 
  Zap, 
  Brain, 
  Heart, 
  Target, 
  BookOpen, 
  GraduationCap, 
  ShoppingCart, 
  BarChart4, 
  Cpu, 
  Book,  
  HelpCircle,  
  Mic, 
  BookOpenCheck,  
  Activity, 
  PlayCircle
} from "lucide-react";
  
import buildIds from "../buildGameIds";


export const brainGamesTeenIds = buildIds("brain", "teens")

export const getBrainTeenGames = (gameCompletionStatus) => {
    const brainTeenGames = [
        {
          id: "brain-teens-1",
          title: "Exercise Story",
          description: "Learn how daily exercise benefits brain health",
          icon: <Brain className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-1"] || false,
          isSpecial: true,
          path: "/student/brain/teen/exercise-story",
          index: 0,
        },
        {
          id: "brain-teens-2",
          title: "Quiz on Habits",
          description: "Test your knowledge of brain-healthy habits",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-2"] || false,
          isSpecial: true,
          path: "/student/brain/teen/quiz-on-habits",
          index: 1,
        },
        {
          id: "brain-teens-3",
          title: "Reflex Mind Check",
          description: "Tap quickly for mind-boosting actions",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-3"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-mind-check",
          index: 2,
        },
        {
          id: "brain-teens-4",
          title: "Puzzle: Brain Fuel",
          description: "Match brain fuels with their sources or benefits",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-4"] || false,
          isSpecial: true,
          path: "/student/brain/teen/puzzle-brain-fuel",
          index: 3,
        },
        {
          id: "brain-teens-5",
          title: "Junk Food Story",
          description: "Learn how junk food affects brain function",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-5"] || false,
          isSpecial: true,
          path: "/student/brain/teen/junk-food-story",
          index: 4,
        },
        {
          id: "brain-teens-6",
          title: "Debate: Brain vs Body",
          description: "Participate in a debate on brain vs body health",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-6"] || false,
          isSpecial: true,
          path: "/student/brain/teen/debate-brain-vs-body",
          index: 5,
        },
        {
          id: "brain-teens-7",
          title: "Journal of Brain Fitness",
          description: "Reflect on daily brain fitness habits",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-7"] || false,
          isSpecial: true,
          path: "/student/brain/teen/journal-of-brain-fitness",
          index: 6,
        },
        {
          id: "brain-teens-8",
          title: "Simulation: Daily Routine",
          description: "Choose the best daily routine for brain health",
          icon: <BarChart4 className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-8"] || false,
          isSpecial: true,
          path: "/student/brain/teen/simulation-daily-routine",
          index: 7,
        },
        {
          id: "brain-teens-9",
          title: "Reflex Brain Boost",
          description: "Tap for brain-boosting foods, avoid harmful ones",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-9"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-brain-boost",
          index: 8,
        },
        {
          id: "brain-teens-10",
          title: "Badge: Brain Health Hero",
          description: "Earn your badge for completing brain health practices",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-10"] || false,
          isSpecial: true,
          path: "/student/brain/teen/badge-brain-health-hero",
          index: 9,
        },
        {
          id: "brain-teens-11",
          title: "Exam Story",
          description: "Learn how distractions affect exam performance",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-11"] || false,
          isSpecial: true,
          path: "/student/brain/teen/exam-story",
          index: 10,
        },
        {
          id: "brain-teens-12",
          title: "Quiz on Attention",
          description: "Test your knowledge of attention boosters",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-12"] || false,
          isSpecial: true,
          path: "/student/brain/teen/quiz-on-attention",
          index: 11,
        },
        {
          id: "brain-teens-13",
          title: "Reflex Concentration",
          description: "Practice concentration-boosting actions",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-13"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-concentration",
          index: 12,
        },
        {
          id: "brain-teens-14",
          title: "Puzzle of Distractions",
          description: "Match environments with their effects on focus",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-14"] || false,
          isSpecial: true,
          path: "/student/brain/teen/puzzle-of-distractions",
          index: 13,
        },
        {
          id: "brain-teens-15",
          title: "Social Media Story",
          description: "Learn how social media affects focus",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-15"] || false,
          isSpecial: true,
          path: "/student/brain/teen/social-media-story",
          index: 14,
        },
        {
          id: "brain-teens-16",
          title: "Debate: Multitask vs Focus",
          description: "Debate the effectiveness of multitasking",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-16"] || false,
          isSpecial: true,
          path: "/student/brain/teen/debate-multitask-vs-focus",
          index: 15,
        },
        {
          id: "brain-teens-17",
          title: "Journal of Attention",
          description: "Reflect on attention strategies",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-17"] || false,
          isSpecial: true,
          path: "/student/brain/teen/journal-of-attention",
          index: 16,
        },
        {
          id: "brain-teens-18",
          title: "Simulation: Study Plan",
          description: "Choose the best study environment",
          icon: <ShoppingCart className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-18"] || false,
          isSpecial: true,
          path: "/student/brain/teen/simulation-study-plan",
          index: 17,
        },
        {
          id: "brain-teens-19",
          title: "Reflex Distraction Alert",
          description: "Practice focus-boosting actions",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-19"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-distraction-alert",
          index: 18,
        },
        {
          id: "brain-teens-20",
          title: "Badge: Focus Hero",
          description: "Earn your badge for conquering distraction challenges",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-20"] || false,
          isSpecial: true,
          path: "/student/brain/teen/badge-focus-hero",
          index: 19,
        },
        {
          id: "brain-teens-21",
          title: "Exam Recall Story",
          description: "Teen revises one night before. Memory strong? → No.",
          icon: <Activity className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-21"] || false,
          isSpecial: true,
          path: "/student/brain/teen/exam-recall-story",
          index: 20,
        },
        {
          id: "brain-teens-22",
          title: "Quiz on Memory Hacks",
          description:
            "Which helps memory? (a) Mnemonics, (b) Ignoring, (c) Skipping sleep). Correct = Mnemonics.",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-22"] || false,
          isSpecial: true,
          path: "/student/brain/teen/quiz-on-memory-hacks",
          index: 21,
        },
        {
          id: "brain-teens-23",
          title: "Reflex Memory Boost",
          description: "Tap for 'Revision,' avoid 'Forget.'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-23"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-memory-boost",
          index: 22,
        },
        {
          id: "brain-teens-24",
          title: "Puzzle: Mnemonic Match",
          description: "Match 'VIBGYOR → Rainbow' and 'BODMAS → Maths Order.'",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-24"] || false,
          isSpecial: true,
          path: "/student/brain/teen/puzzle-mnemonic-match",
          index: 23,
        },
        {
          id: "brain-teens-25",
          title: "Note-taking Story",
          description: "Teen takes notes in class. Does memory improve? → Yes.",
          icon: <BookOpenCheck className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["brain-teens-25"] || false,
          isSpecial: true,
          path: "/student/brain/teen/note-taking-story",
          index: 24,
        },
        {
          id: "brain-teens-26",
          title: "Debate: Rote vs Understanding",
          description:
            "Is rote learning better than understanding? → No, understanding is better.",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-26"] || false,
          isSpecial: true,
          path: "/student/brain/teen/debate-rote-vs-understanding",
          index: 25,
        },
        {
          id: "brain-teens-27",
          title: "Journal of Tricks",
          description: "Write: 'One memory trick I use is ___.'",
          icon: <BookOpenCheck className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-27"] || false,
          isSpecial: true,
          path: "/student/brain/teen/journal-of-tricks",
          index: 26,
        },
        {
          id: "brain-teens-28",
          title: "Simulation: Study Plan",
          description: "Study 30 min daily or cram 3 hrs once? → Daily.",
          icon: <Cpu className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-28"] || false,
          isSpecial: true,
          path: "/student/brain/teen/simulation-studyy-plan",
          index: 27,
        },
        {
          id: "brain-teens-29",
          title: "Reflex Recall Quick",
          description: "Tap for 'Repeat,' avoid 'Forget Fast.'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-29"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-recall-quick",
          index: 28,
        },
        {
          id: "brain-teens-30",
          title: "Badge: Memory Hero",
          description:
            "Apply 5 memory boosters to earn your Memory Hero badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-30"] || false,
          isSpecial: true,
          path: "/student/brain/teen/badge-memory-hero",
          index: 29,
        },
        {
          id: "brain-teens-31",
          title: "Study Pressure Story",
          description:
            "Teen stressed before exam. Better choice? → Revise calmly.",
          icon: <Activity className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-31"] || false,
          isSpecial: true,
          path: "/student/brain/teen/study-pressure-story",
          index: 30,
        },
        {
          id: "brain-teens-32",
          title: "Stress Quiz",
          description:
            "What is a healthy stress reliever? (a) Exercise, (b) Overeating, (c) Yelling). Correct = Exercise.",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-32"] || false,
          isSpecial: true,
          path: "/student/brain/teen/stresss-quiz",
          index: 31,
        },
        {
          id: "brain-teens-33",
          title: "Reflex Stress Check",
          description: "Tap for 'Meditate,' avoid 'Overthink.'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-33"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-stress-check",
          index: 32,
        },
        {
          id: "brain-teens-34",
          title: "Puzzle of Relief",
          description:
            "Match 'Talk to Friend → Support' and 'Sleep → Refresh.'",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-34"] || false,
          isSpecial: true,
          path: "/student/brain/teen/puzzle-of-relief",
          index: 33,
        },
        {
          id: "brain-teens-35",
          title: "Failure Story",
          description: "Teen fails test. Should they give up? → No, try again.",
          icon: <Activity className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-35"] || false,
          isSpecial: true,
          path: "/student/brain/teen/failuree-story",
          index: 34,
        },
        {
          id: "brain-teens-36",
          title: "Debate: Stress Good or Bad?",
          description:
            "Can stress sometimes motivate us? → Yes, small stress helps, big stress harms.",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-36"] || false,
          isSpecial: true,
          path: "/student/brain/teen/debate-stress-good-or-bad",
          index: 35,
        },
        {
          id: "brain-teens-37",
          title: "Journal of Stress Relief",
          description: "Write: 'One way I reduce stress is ___.'",
          icon: <BookOpenCheck className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-37"] || false,
          isSpecial: true,
          path: "/student/brain/teen/journal-of-stress-relief",
          index: 36,
        },
        {
          id: "brain-teens-38",
          title: "Simulation: Stress Day",
          description:
            "You feel stressed. Options: (a) Eat junk, (b) Sleep, (c) Walk & breathe. Correct = Walk & breathe.",
          icon: <Cpu className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-38"] || false,
          isSpecial: true,
          path: "/student/brain/teen/simulation-stress-day",
          index: 37,
        },
        {
          id: "brain-teens-39",
          title: "Reflex Healthy Calm",
          description: "Tap for 'Exercise,' avoid 'Avoid Work.'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-39"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-healthy-calm",
          index: 38,
        },
        {
          id: "brain-teens-40",
          title: "Badge: Stress Manager",
          description:
            "Beat 5 stress challenges to earn your Stress Manager badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-40"] || false,
          isSpecial: true,
          path: "/student/brain/teen/badge-stress-manager",
          index: 39,
        },
        {
          id: "brain-teens-41",
          title: "Peer Pressure Story",
          description:
            "Teen feels anxious when friends tease. Best step? → Stay calm & talk.",
          icon: <Activity className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-41"] || false,
          isSpecial: true,
          path: "/student/brain/teen/peer-pressuree-story",
          index: 40,
        },
        {
          id: "brain-teens-42",
          title: "Emotion Quiz",
          description:
            "What is empathy? (a) Feeling others' feelings, (b) Ignoring them). Correct = Feeling others' feelings.",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-42"] || false,
          isSpecial: true,
          path: "/student/brain/teen/emotion-quiz",
          index: 41,
        },
        {
          id: "brain-teens-43",
          title: "Reflex Emotion Control",
          description: "Tap for 'Talk Calmly,' avoid 'Shout.'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-43"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-emotion-control",
          index: 42,
        },
        {
          id: "brain-teens-44",
          title: "Puzzle: Emotion Match",
          description:
            "Match 'Fear → Heart Racing' and 'Calm → Deep Breathing.'",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-44"] || false,
          isSpecial: true,
          path: "/student/brain/teen/puzzle-emotion-match",
          index: 43,
        },
        {
          id: "brain-teens-45",
          title: "Anger Story",
          description:
            "Teen argues with sibling. Best action? → Take break, then talk.",
          icon: <Activity className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-45"] || false,
          isSpecial: true,
          path: "/student/brain/teen/anger-story",
          index: 44,
        },
        {
          id: "brain-teens-46",
          title: "Debate: Show or Hide Emotions?",
          description: "Should we always hide emotions? → No, express healthy.",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-46"] || false,
          isSpecial: true,
          path: "/student/brain/teen/debate-show-hide-emotions",
          index: 45,
        },
        {
          id: "brain-teens-47",
          title: "Journal of Emotional Moment",
          description: "Write: 'A time I controlled anger was ___.'",
          icon: <BookOpenCheck className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-47"] || false,
          isSpecial: true,
          path: "/student/brain/teen/journal-emotional-moment",
          index: 46,
        },
        {
          id: "brain-teens-48",
          title: "Simulation: Stressful Day",
          description:
            "Options: (a) Bottle feelings, (b) Shout, (c) Journal/talk. Correct = Journal/talk.",
          icon: <Cpu className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-48"] || false,
          isSpecial: true,
          path: "/student/brain/teen/simulation-stressful-day",
          index: 47,
        },
        {
          id: "brain-teens-49",
          title: "Reflex Positive Emotion",
          description: "Tap for 'Empathy,' avoid 'Bullying.'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-49"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-positive-emotion",
          index: 48,
        },
        {
          id: "brain-teens-50",
          title: "Badge: Emotion Hero",
          description:
            "Handle 5 emotional scenarios positively to earn your Emotion Hero badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["brain-teens-50"] || false,
          isSpecial: true,
          path: "/student/brain/teen/badge-emotion-hero",
          index: 49,
        },
        {
          id: "brain-teens-51",
          title: "Failure Story",
          description:
            "Teen fails in test. Best response? → Learn from mistakes.",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-51"] || false,
          isSpecial: true,
          path: "/student/brain/teen/faillure-story",
          index: 50,
        },
        {
          id: "brain-teens-52",
          title: "Positivity Quiz",
          description:
            "Which is positive? (a) 'I'll try again,' (b) 'I'm useless.' Correct = 'I'll try again.'",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-52"] || false,
          isSpecial: true,
          path: "/student/brain/teen/positivitty-quiz",
          index: 51,
        },
        {
          id: "brain-teens-53",
          title: "Reflex Optimism",
          description: "Tap for 'Gratitude,' for 'Jealousy.'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-53"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-optimism",
          index: 52,
        },
        {
          id: "brain-teens-54",
          title: "Puzzle: Positive Practices",
          description: "Match 'Meditation → Calm, Affirmation → Confidence.'",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-54"] || false,
          isSpecial: true,
          path: "/student/brain/teen/puzzle-positive-practices",
          index: 53,
        },
        {
          id: "brain-teens-55",
          title: "Friend Betrayal Story",
          description:
            "Teen feels hurt. Positive action? → Forgive and move on.",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-55"] || false,
          isSpecial: true,
          path: "/student/brain/teen/friend-betrayal-story",
          index: 54,
        },
        {
          id: "brain-teens-56",
          title: "Debate: Optimism vs Realism",
          description:
            "Is it better to be optimistic or realistic? → Balanced optimism.",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-56"] || false,
          isSpecial: true,
          path: "/student/brain/teen/debate-optimism-vs-realism",
          index: 55,
        },
        {
          id: "brain-teens-57",
          title: "Journal of Gratitude",
          description: "Write: 'Today I am thankful for ___.'",
          icon: <BookOpenCheck className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-57"] || false,
          isSpecial: true,
          path: "/student/brain/teen/journall-of-gratitude",
          index: 56,
        },
        {
          id: "brain-teens-58",
          title: "Simulation: Negative Day",
          description:
            "Bad day at school. Choices: (a) Stay upset, (b) Think of positives, (c) Quit tasks. Correct = Think of positives.",
          icon: <PlayCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-58"] || false,
          isSpecial: true,
          path: "/student/brain/teen/simulation-negative-day",
          index: 57,
        },
        {
          id: "brain-teens-59",
          title: "Reflex Mindset Check",
          description: "Tap for 'Growth,' for 'Give Up.'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-59"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-mindset-check",
          index: 58,
        },
        {
          id: "brain-teens-60",
          title: "Badge: Optimist Hero",
          description:
            "Show positive thinking in 5 cases to earn your Optimist Hero badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-60"] || false,
          isSpecial: true,
          path: "/student/brain/teen/badge-optimist-hero",
          index: 59,
        },
        {
          id: "brain-teens-61",
          title: "Sleep Story",
          description:
            "Teen sleeps 5 hrs before exam, feels tired. Is this good? → No.",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-61"] || false,
          isSpecial: true,
          path: "/student/brain/teen/sleep-story",
          index: 60,
        },
        {
          id: "brain-teens-62",
          title: "Sleep Quiz",
          description:
            "How many hours should teens sleep? (a) 5, (b) 6–8, (c) 12). Correct = 6–8.",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-62"] || false,
          isSpecial: true,
          path: "/student/brain/teen/sleepp-quiz",
          index: 61,
        },
        {
          id: "brain-teens-63",
          title: "Reflex Rest Habits",
          description: "Tap for 'Consistent Sleep,' for 'All-nighter.'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-63"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-rest-habits",
          index: 62,
        },
        {
          id: "brain-teens-64",
          title: "Puzzle of Sleep Health",
          description: "Match 'Screen Off → Good Sleep, Noise → Bad Sleep.'",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-64"] || false,
          isSpecial: true,
          path: "/student/brain/teen/puzzle-of-sleep-health",
          index: 63,
        },
        {
          id: "brain-teens-65",
          title: "Phone Story",
          description:
            "Teen uses phone till 2 AM, sleeps in class. Is this healthy? → No.",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-65"] || false,
          isSpecial: true,
          path: "/student/brain/teen/phone-story",
          index: 64,
        },
        {
          id: "brain-teens-66",
          title: "Debate: Sleep vs Study",
          description:
            "Is it better to sleep or study late? → Balanced, sleep first.",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-66"] || false,
          isSpecial: true,
          path: "/student/brain/teen/debate-sleep-vs-study",
          index: 65,
        },
        {
          id: "brain-teens-67",
          title: "Journal of Sleep Health",
          description: "Write: 'One bedtime rule I follow is ___.'",
          icon: <BookOpenCheck className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-67"] || false,
          isSpecial: true,
          path: "/student/brain/teen/journal-of-sleep-health",
          index: 66,
        },
        {
          id: "brain-teens-68",
          title: "Simulation: Exam Prep",
          description:
            "Choices: (a) Study till 3 AM, (b) Sleep 8 hrs + study next day. Correct = Sleep + study.",
          icon: <PlayCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-68"] || false,
          isSpecial: true,
          path: "/student/brain/teen/simulation-exam-prep",
          index: 67,
        },
        {
          id: "brain-teens-69",
          title: "Reflex Smart Rest",
          description: "Tap for 'Nap Break,' for 'Overwork.'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-69"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-smart-rest",
          index: 68,
        },
        {
          id: "brain-teens-70",
          title: "Badge: Rest Hero",
          description:
            "Manage 5 sleep challenges to earn your Rest Hero badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-70"] || false,
          isSpecial: true,
          path: "/student/brain/teen/badge-rest-hero",
          index: 69,
        },
        {
          id: "brain-teens-71",
          title: "Midnight Story",
          description: "Teen scrolls till 1 AM, tired next day. Smart? → No.",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-71"] || false,
          isSpecial: true,
          path: "/student/brain/teen/midnight-story",
          index: 70,
        },
        {
          id: "brain-teens-72",
          title: "Quiz on Digital Balance",
          description:
            "What is digital detox? (a) Time without gadgets, (b) More gadgets). Correct = Time without gadgets.",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-72"] || false,
          isSpecial: true,
          path: "/student/brain/teen/quiz-on-digital-balance",
          index: 71,
        },
        {
          id: "brain-teens-73",
          title: "Reflex Tech Control",
          description: "Tap for 'Switch Off at Night,' for 'Always On.'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-73"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-tech-control",
          index: 72,
        },
        {
          id: "brain-teens-74",
          title: "Puzzle of Balance Habits",
          description: "Match 'Sleep Early → Healthy, Midnight Phone → Tired.'",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-74"] || false,
          path: "/student/brain/teen/puzzle-of-balance-habits",
          isSpecial: true,
          index: 73,
        },
        {
          id: "brain-teens-75",
          title: "Gaming Story",
          description:
            "Teen plays 6 hrs games daily, fails test. Healthy? → No.",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["brain-teens-75"] || false,
          isSpecial: true,
          path: "/student/brain/teen/gaming-story",
          index: 74,
        },
        {
          id: "brain-teens-76",
          title: "Debate: Tech Good or Bad?",
          description: "Is technology harmful? → No, harmful only if overused.",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "7 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-76"] || false,
          isSpecial: true,
          path: "/student/brain/teen/debate-tech-good-or-bad",
          index: 75,
        },
        {
          id: "brain-teens-77",
          title: "Journal of Balance",
          description: "Write: 'One way I control screen time is ___.'",
          icon: <BookOpenCheck className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-77"] || false,
          path: "/student/brain/teen/journal-balancee",
          isSpecial: true,
          index: 76,
        },
        {
          id: "brain-teens-78",
          title: "Simulation: Daily Routine",
          description:
            "4 hrs free. Choices: (a) All screen, (b) Sports + study + 1 hr screen. Correct = Balance.",
          icon: <PlayCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-78"] || false,
          path: "/student/brain/teen/simulation-daily-routinee",
          isSpecial: true,
          index: 77,
        },
        {
          id: "brain-teens-79",
          title: "Reflex Healthy Use",
          description: "Tap for 'Digital Detox,' for 'Screen All Day.'",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-79"] || false,
          path: "/student/brain/teen/reflex-healthy-use",
          isSpecial: true,
          index: 78,
        },
        {
          id: "brain-teens-80",
          title: "Badge: Digital Hero",
          description:
            "Complete 5 digital balance challenges to earn your Digital Hero badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-80"] || false,
          isSpecial: true,
          path: "/student/brain/teen/badge-digital-hero",
          index: 79,
        },
        {
          id: "brain-teens-81",
          title: "Science Project Story",
          description:
            "Teen's project fails. What should they do? → Improve & retry.",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-81"] || false,
          isSpecial: true,
          path: "/student/brain/teen/science-project-story",
          index: 80,
        },
        {
          id: "brain-teens-82",
          title: "Quiz on Innovation",
          description:
            "Who is an innovator? (a) Creates new ideas, (b) Copies, (c) Quits). Correct = Creates new ideas.",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-82"] || false,
          isSpecial: true,
          path: "/student/brain/teen/quiz-on-innovation",
          index: 81,
        },
        {
          id: "brain-teens-83",
          title: "Reflex Solution Mode",
          description: "Tap quickly for Find Solution not Complain.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-83"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-solution-mode",
          index: 82,
        },
        {
          id: "brain-teens-84",
          title: "Puzzle: Innovators",
          description:
            "Match: 'Wright Brothers → Plane,' 'Thomas Edison → Bulb.'",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-84"] || false,
          isSpecial: true,
          path: "/student/brain/teen/puzzle-innovators",
          index: 83,
        },
        {
          id: "brain-teens-85",
          title: "Startup Idea Story",
          description: "Teen designs eco-bag. Is that good innovation? → Yes.",
          icon: <Lightbulb className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-85"] || false,
          path: "/student/brain/teen/startup-idea-story",
          isSpecial: true,
          index: 84,
        },
        {
          id: "brain-teens-86",
          title: "Debate: Copy vs Create",
          description:
            "Is it better to copy success or create new? → Create new.",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-86"] || false,
          isSpecial: true,
          path: "/student/brain/teen/debate-copy-vs-create",
          index: 85,
        },
        {
          id: "brain-teens-87",
          title: "Journal of Creativity",
          description: "Write: 'One creative idea I had was ___.'",
          icon: <Book className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-87"] || false,
          isSpecial: true,
          path: "/student/brain/teen/journal-of-creativity",
          index: 86,
        },
        {
          id: "brain-teens-88",
          title: "Simulation: School Fair",
          description:
            "Budget ₹500. Choose: (a) Copy poster, (b) Build model. Best = Build model.",
          icon: <PlayCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-88"] || false,
          isSpecial: true,
          path: "/student/brain/teen/simulation-school-fair",
          index: 87,
        },
        {
          id: "brain-teens-89",
          title: "Reflex Innovator's Choice",
          description: "Tap for Original not Plagiarize.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-89"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-innovators-choice",
          index: 88,
        },
        {
          id: "brain-teens-90",
          title: "Badge: Innovator Hero",
          description:
            "Complete 5 creative problem-solving challenges to earn your Innovator Hero badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-90"] || false,
          isSpecial: true,
          path: "/student/brain/teen/badge-innovator-hero",
          index: 89,
        },
        {
          id: "brain-teens-91",
          title: "Exam Failure Story",
          description:
            "Teen fails exam. Best choice? → Learn mistakes, try again.",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-91"] || false,
          isSpecial: true,
          path: "/student/brain/teen/exam-failure-story",
          index: 90,
        },
        {
          id: "brain-teens-92",
          title: "Growth Mindset Quiz",
          description:
            "Which is growth mindset? (a) I can't do it, (b) I'll improve. Correct = I'll improve.",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-92"] || false,
          isSpecial: true,
          path: "/student/brain/teen/growth-mindset-quiz",
          index: 91,
        },
        {
          id: "brain-teens-93",
          title: "Reflex Growth Attitude",
          description: "Tap quickly for Practice More not Give Up.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-93"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-growth-attitude",
          index: 92,
        },
        {
          id: "brain-teens-94",
          title: "Puzzle of Growth",
          description: "Match: Effort → Success, Giving Up → Failure.",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-94"] || false,
          isSpecial: true,
          path: "/student/brain/teen/puzzle-of-growth",
          index: 93,
        },
        {
          id: "brain-teens-95",
          title: "Career Story",
          description:
            "Teen struggles in coding. Best path? → Practice until better.",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-95"] || false,
          isSpecial: true,
          path: "/student/brain/teen/career-story",
          index: 94,
        },
        {
          id: "brain-teens-96",
          title: "Debate: Talent vs Effort",
          description:
            "What matters more for success — talent or effort? → Effort.",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-96"] || false,
          isSpecial: true,
          path: "/student/brain/teen/debate-talent-vs-effort",
          index: 95,
        },
        {
          id: "brain-teens-97",
          title: "Journal of Growth",
          description: "Write: One skill I improved with practice was ___.",
          icon: <Book className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-97"] || false,
          isSpecial: true,
          path: "/student/brain/teen/journal-of-growth",
          index: 96,
        },
        {
          id: "brain-teens-98",
          title: "Simulation: Life Choices",
          description:
            "Fail in sports selection. Options: (a) Quit, (b) Practice harder. Correct = Practice harder.",
          icon: <PlayCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-98"] || false,
          isSpecial: true,
          path: "/student/brain/teen/simulation-life-choices",
          index: 97,
        },
        {
          id: "brain-teens-99",
          title: "Reflex Never Quit",
          description: "Tap for Keep Going not Stop Forever.",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-99"] || false,
          isSpecial: true,
          path: "/student/brain/teen/reflex-never-quit",
          index: 98,
        },
        {
          id: "brain-teens-100",
          title: "Badge: Growth Champion",
          description:
            "Pass 5 growth mindset scenarios to earn your Growth Champion badge.",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["brain-teens-100"] || false,
          isSpecial: true,
          path: "/student/brain/teen/badge-growth-champion",
          index: 99,
        },
      ];

    return brainTeenGames;
}