import {
    Activity,
    Apple,
    Moon,
    Shield,
    Heart,
    Target,
    BookOpen,
    Trophy,
    Zap,
    Droplets,
    Sun,
    Brain,
    HandHeart,
    Hand,
    Sparkles,
    Shirt,
    Badge,
    Stethoscope,
    Thermometer,
    Wine,
    Clock,
    Book,
    Hospital
} from "lucide-react";
import buildIds from "../buildGameIds";

export const healthMaleGameIdsKids = buildIds("health-male", "kids")

export const getHealthMaleKidsGames = (gameCompletionStatus) => {
    const healthMaleGamesKids = [
        {
            id: 'health-male-kids-1',
            title: 'Handwash Hero',
            icon: <Hand className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-1'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/handwash-hero',
            index: 0
        },
        {
            id: 'health-male-kids-2',
            title: 'Quiz on Cleanliness',
            icon: <Sparkles className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-2'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/quiz-cleanliness',
            index: 1
        },
        {
            id: 'health-male-kids-3',
            title: 'Reflex Hygiene',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-3'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/reflex-hygiene',
            index: 2
        },
        {
            id: 'health-male-kids-4',
            title: 'Hygiene Items Puzzle',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-4'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/hygiene-items-puzzle',
            index: 3
        },
        {
            id: 'health-male-kids-5',
            title: 'Bath Time Story',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-5'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/bath-time-story',
            index: 4
        },
        {
            id: 'health-male-kids-6',
            title: 'Stay Fresh Poster',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-6'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/stay-fresh-poster',
            index: 5
        },
        {
            id: 'health-male-kids-7',
            title: 'Journal of Hygiene',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-7'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/hygiene-journal',
            index: 6
        },
        {
            id: 'health-male-kids-8',
            title: 'Dirty Shirt Story',
            icon: <Shirt className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-8'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/dirty-shirt-story',
            index: 7
        },
        {
            id: 'health-male-kids-9',
            title: 'Germ Buster Reflex',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-9'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/germ-buster-reflex',
            index: 8
        },
        {
            id: 'health-male-kids-10',
            title: 'Clean Kid Badge',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-10'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/clean-kid-badge',
            index: 9
        },
        {
            id: 'health-male-kids-11',
            title: 'Fruit vs Candy Story',
            icon: <Apple className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-11'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/fruit-vs-candy-story',
            index: 10
        },
        {
            id: 'health-male-kids-12',
            title: 'Quiz on Food Groups',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-12'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/quiz-food-groups',
            index: 11
        },
        {
            id: 'health-male-kids-13',
            title: 'Reflex Healthy Choice',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-13'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/reflex-healthy-choice',
            index: 12
        },
        {
            id: 'health-male-kids-14',
            title: 'Food Match Puzzle',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-14'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/food-match-puzzle',
            index: 13
        },
        {
            id: 'health-male-kids-15',
            title: 'Lunchbox Story',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-15'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/lunchbox-story',
            index: 14
        },
        {
            id: 'health-male-kids-16',
            title: 'Healthy Plate Poster',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-16'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/healthy-plate-poster',
            index: 15
        },
        {
            id: 'health-male-kids-17',
            title: 'Journal of Food Habits',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-17'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/food-habits-journal',
            index: 16
        },
        {
            id: 'health-male-kids-18',
            title: 'Junk Food Story',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-18'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/junk-food-story',
            index: 17
        },
        {
            id: 'health-male-kids-19',
            title: 'Reflex Food Alert',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-19'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/reflex-food-alert',
            index: 18
        },
        {
            id: 'health-male-kids-20',
            title: 'Healthy Kid Badge',
            icon: <Trophy className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-20'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/healthy-kid-badge',
            index: 19
        },
        {
            id: 'health-male-kids-21',
            title: 'Growing Taller Story',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-21'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/growing-taller-story',
            index: 20
        },
        {
            id: 'health-male-kids-22',
            title: 'Quiz on Growth',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-22'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/quiz-growth',
            index: 21
        },
        {
            id: 'health-male-kids-23',
            title: 'Reflex Growth Basics',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-23'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/reflex-growth-basics',
            index: 22
        },
        {
            id: 'health-male-kids-24',
            title: 'Growth Helpers Puzzle',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-24'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/growth-helpers-puzzle',
            index: 23
        },
        {
            id: 'health-male-kids-25',
            title: 'Voice Change Story',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 5,
            xp: 10,
            completed: gameCompletionStatus['health-male-kids-25'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/voice-change-story',
            index: 24
        },
        {
            id: 'health-male-kids-26',
            title: 'Growing Up Poster',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-26'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/growing-up-poster',
            index: 25
        },
        {
            id: 'health-male-kids-27',
            title: 'Journal of Body Changes',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-27'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/body-changes-journal',
            index: 26
        },
        {
            id: 'health-male-kids-28',
            title: 'Hair Growth Story',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-28'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/hair-growth-story',
            index: 27
        },
        {
            id: 'health-male-kids-29',
            title: 'Reflex Growth Alert',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-29'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/reflex-growth-alert',
            index: 28
        },
        {
            id: 'health-male-kids-30',
            title: 'Growing Strong Badge',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-30'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/growing-strong-badge',
            index: 29
        },
        {
            id: 'health-male-kids-31',
            title: 'Body System Story',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-31'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/body-system-story',
            index: 30
        },
        {
            id: 'health-male-kids-32',
            title: 'Quiz on Body Functions',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-32'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/quiz-body-functions',
            index: 31
        },
        {
            id: 'health-male-kids-33',
            title: 'Reflex Body Basics',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-33'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/reflex-body-basics',
            index: 32
        },
        {
            id: 'health-male-kids-34',
            title: 'Body Match Puzzle',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-34'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/body-match-puzzle',
            index: 33
        },
        {
            id: 'health-male-kids-35',
            title: 'Respect Story',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-35'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/respect-story',
            index: 34
        },
        {
            id: 'health-male-kids-36',
            title: 'My Body, My Respect Poster',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-36'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/my-body-respect-poster',
            index: 35
        },
        {
            id: 'health-male-kids-37',
            title: 'Journal: Learning About My Body',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-37'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/learning-body-journal',
            index: 36
        },
        {
            id: 'health-male-kids-38',
            title: 'Growth Story',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-38'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/growth-story',
            index: 37
        },
        {
            id: 'health-male-kids-39',
            title: 'Reflex Safe Body',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-39'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/reflex-safe-body',
            index: 38
        },
        {
            id: 'health-male-kids-40',
            title: 'Body Basics Badge',
            icon: <Trophy className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-40'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/body-basics-badge',
            index: 39
        },
        {
            id: 'health-male-kids-41',
            title: 'Sweat Story',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-41'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/sweat-story',
            index: 40
        },
        {
            id: 'health-male-kids-42',
            title: 'Quiz on Hygiene',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-42'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/quiz-hygiene-advanced',
            index: 41
        },
        {
            id: 'health-male-kids-43',
            title: 'Reflex Hygiene Check',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-43'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/reflex-hygiene-check',
            index: 42
        },
        {
            id: 'health-male-kids-44',
            title: 'Hygiene Match Puzzle',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-44'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/hygiene-match-puzzle',
            index: 43
        },
        {
            id: 'health-male-kids-45',
            title: 'Shaving Story',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-45'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/shaving-story',
            index: 44
        },
        {
            id: 'health-male-kids-46',
            title: 'Stay Fresh Poster',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-46'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/stay-fresh-poster-advanced',
            index: 45
        },
        {
            id: 'health-male-kids-47',
            title: 'Journal: Hygiene Habits',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-47'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/hygiene-habits-journal',
            index: 46
        },
        {
            id: 'health-male-kids-48',
            title: 'Acne Story',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-48'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/acne-story',
            index: 47
        },
        {
            id: 'health-male-kids-49',
            title: 'Reflex Freshness',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-49'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/reflex-freshness',
            index: 48
        },
        {
            id: 'health-male-kids-50',
            title: 'Fresh Kid Badge',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 10,
            xp: 20,
            completed: gameCompletionStatus['health-male-kids-50'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/fresh-kid-badge',
            index: 49
        },
        {
            id: 'health-male-kids-51',
            title: 'Feelings Story',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-51'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/feelings-story',
            index: 50
        },
        {
            id: 'health-male-kids-52',
            title: 'Quiz on Emotions',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-52'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/quiz-emotions',
            index: 51
        },
        {
            id: 'health-male-kids-53',
            title: 'Reflex Emotion Check',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-53'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/reflex-emotion-check',
            index: 52
        },
        {
            id: 'health-male-kids-54',
            title: 'Emotion Match Puzzle',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-54'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/emotion-match-puzzle',
            index: 53
        },
        {
            id: 'health-male-kids-55',
            title: 'Sharing Story',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-55'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/sharing-story',
            index: 54
        },
        {
            id: 'health-male-kids-56',
            title: 'Feelings are Normal Poster',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-56'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/feelings-normal-poster',
            index: 55
        },
        {
            id: 'health-male-kids-57',
            title: 'Journal of Emotions',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-57'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/emotions-journal',
            index: 56
        },
        {
            id: 'health-male-kids-58',
            title: 'Anger Story',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-58'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/anger-story',
            index: 57
        },
        {
            id: 'health-male-kids-59',
            title: 'Reflex Emotion Alert',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-59'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/reflex-emotion-alert',
            index: 58
        },
        {
            id: 'health-male-kids-60',
            title: 'Emotion Explorer Badge',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-60'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/emotion-explorer-badge',
            index: 59
        },
        {
            id: 'health-male-kids-61',
            title: 'Friend\'s Dare Story',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-61'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/friends-dare-story',
            index: 60
        },
        {
            id: 'health-male-kids-62',
            title: 'Quiz on Peer Pressure',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-62'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/quiz-peer-pressure',
            index: 61
        },
        {
            id: 'health-male-kids-63',
            title: 'Reflex Peer Check',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-63'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/reflex-peer-check',
            index: 62
        },
        {
            id: 'health-male-kids-64',
            title: 'Peer Scenarios Puzzle',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-64'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/peer-scenarios-puzzle',
            index: 63
        },
        {
            id: 'health-male-kids-65',
            title: 'Bully Story',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-65'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/bully-story',
            index: 64
        },
        {
            id: 'health-male-kids-66',
            title: 'Power of No Poster',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-66'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/power-of-no-poster',
            index: 65
        },
        {
            id: 'health-male-kids-67',
            title: 'Journal of Pressure',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-67'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/pressure-journal',
            index: 66
        },
        {
            id: 'health-male-kids-68',
            title: 'Gaming Pressure Story',
            icon: <Activity className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-68'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/gaming-pressure-story',
            index: 67
        },
        {
            id: 'health-male-kids-69',
            title: 'Reflex Respect',
            icon: <HandHeart className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-69'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/reflex-respect',
            index: 68
        },
        {
            id: 'health-male-kids-70',
            title: 'Peer Pressure Fighter Badge',
            icon: <Trophy className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-70'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/peer-pressure-fighter-badge',
            index: 69
        },
        {
            id: 'health-male-kids-71',
            title: 'Vaccine Story',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-71'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/vaccine-story',
            index: 70
        },
        {
            id: 'health-male-kids-72',
            title: 'Quiz on Safety',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-72'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/quiz-safety',
            index: 71
        },
        {
            id: 'health-male-kids-73',
            title: 'Reflex Safety',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-73'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/reflex-safety',
            index: 72
        },
        {
            id: 'health-male-kids-74',
            title: 'Safety Match Puzzle',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-74'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/safety-match-puzzle',
            index: 73
        },
        {
            id: 'health-male-kids-75',
            title: 'Sickness Story',
            icon: <Thermometer className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 15,
            xp: 30,
            completed: gameCompletionStatus['health-male-kids-75'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/sickness-story',
            index: 74
        },
        {
            id: 'health-male-kids-76',
            title: 'Prevention First Poster',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-76'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/prevention-first-poster',
            index: 75
        },
        {
            id: 'health-male-kids-77',
            title: 'Journal of Safety',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-77'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/safety-journal',
            index: 76
        },
        {
            id: 'health-male-kids-78',
            title: 'Dentist Story',
            icon: <Hospital className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-78'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/dentist-story',
            index: 77
        },
        {
            id: 'health-male-kids-79',
            title: 'Reflex Healthy Steps',
            icon: <Stethoscope className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-79'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/reflex-healthy-steps',
            index: 78
        },
        {
            id: 'health-male-kids-80',
            title: 'Safety Smart Kid Badge',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-80'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/safety-smart-kid-badge',
            index: 79
        },
        {
            id: 'health-male-kids-81',
            title: 'Smoking Story',
            icon: <Shield className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-81'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/smoking-story',
            index: 80
        },
        {
            id: 'health-male-kids-82',
            title: 'Quiz on Substances',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-82'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/quiz-substances',
            index: 81
        },
        {
            id: 'health-male-kids-83',
            title: 'Reflex Safe Choice',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-83'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/reflex-safe-choice',
            index: 82
        },
        {
            id: 'health-male-kids-84',
            title: 'Healthy vs Harmful Puzzle',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-84'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/healthy-vs-harmful-puzzle',
            index: 83
        },
        {
            id: 'health-male-kids-85',
            title: 'Alcohol Story',
            icon: <Wine className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-85'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/alcohol-story',
            index: 84
        },
        {
            id: 'health-male-kids-86',
            title: 'Say No Poster',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-86'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/say-no-poster',
            index: 85
        },
        {
            id: 'health-male-kids-87',
            title: 'Journal of Refusal',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-87'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/refusal-journal',
            index: 86
        },
        {
            id: 'health-male-kids-88',
            title: 'Peer Story',
            icon: <Heart className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-88'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/peer-story',
            index: 87
        },
        {
            id: 'health-male-kids-89',
            title: 'Reflex Danger Alert',
            icon: <Droplets className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-89'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/reflex-danger-alert',
            index: 88
        },
        {
            id: 'health-male-kids-90',
            title: 'Safe Kid Badge',
            icon: <Badge className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-90'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/safe-kid-badge',
            index: 89
        },
        {
            id: 'health-male-kids-91',
            title: 'Morning Routine Story',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-91'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/morning-routine-story',
            index: 90
        },
        {
            id: 'health-male-kids-92',
            title: 'Quiz on Daily Habits',
            icon: <Brain className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-92'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/quiz-daily-habits',
            index: 91
        },
        {
            id: 'health-male-kids-93',
            title: 'Reflex Habit Check',
            icon: <Zap className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-93'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/reflex-habit-check',
            index: 92
        },
        {
            id: 'health-male-kids-94',
            title: 'Daily Match Puzzle',
            icon: <Target className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-94'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/daily-match-puzzle',
            index: 93
        },
        {
            id: 'health-male-kids-95',
            title: 'Sleep Story',
            icon: <Moon className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-95'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/sleep-story',
            index: 94
        },
        {
            id: 'health-male-kids-96',
            title: 'Good Habits Win Poster',
            icon: <Sun className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '6 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-96'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/good-habits-poster',
            index: 95
        },
        {
            id: 'health-male-kids-97',
            title: 'Journal of Habits',
            icon: <BookOpen className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-97'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/habits-journal',
            index: 96
        },
        {
            id: 'health-male-kids-98',
            title: 'Reading Story',
            icon: <Book className="w-6 h-6" />,
            difficulty: 'Easy',
            duration: '4 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-98'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/reading-story',
            index: 97
        },
        {
            id: 'health-male-kids-99',
            title: 'Reflex Habit Alert',
            icon: <Clock className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '3 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-99'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/reflex-habit-alert',
            index: 98
        },
        {
            id: 'health-male-kids-100',
            title: 'Healthy Routine Kid Badge',
            icon: <Trophy className="w-6 h-6" />,
            difficulty: 'Medium',
            duration: '5 min',
            coins: 20,
            xp: 40,
            completed: gameCompletionStatus['health-male-kids-100'] || false,
            isSpecial: true,
            path: '/student/health-male/kids/healthy-routine-kid-badge',
            index: 99
        },

    ];

    return healthMaleGamesKids;
};
