import {
  Star,
  Zap,
  Gamepad2,
  Brain,
  Heart,
  Target,
  Cpu,
  Eye,
  Smile,
  MessageSquare,
  Palette,
  Home,
} from "lucide-react";
import buildIds from "../buildGameIds";


export const aiGamesKidsIds = buildIds('ai', 'kids');

export const getAiKidsGames = (gameCompletionStatus)=> {
    const aiGamesKid = [
        {
          id: "ai-kids-1",
          title: "Spot the Pattern",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-1"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/spot-the-pattern",
          index: 0,
        },
        {
          id: "ai-kids-2",
          title: "Cat or Dog Game",
          icon: <Eye className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-2"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/cat-or-dog-game",
          index: 1,
        },
        {
          id: "ai-kids-3",
          title: "Sorting Colors",
          icon: <Palette className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-3"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/sorting-colors",
          index: 2,
        },
        {
          id: "ai-kids-4",
          title: "True or False AI Quiz",
          icon: <Brain className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-4"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/true-false-ai-quiz",
          index: 3,
        },
        {
          id: "ai-kids-5",
          title: "Emoji Classifier",
          icon: <Smile className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-5"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/emoji-classifier",
          index: 4,
        },
        {
          id: "ai-kids-6",
          title: "Self-Driving Car Game",
          icon: <Cpu className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-6"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/self-driving-car",
          index: 5,
        },
        {
          id: "ai-kids-7",
          title: "Pattern Finder Puzzle",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-7"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/pattern-finder-puzzle",
          index: 6,
        },
        {
          id: "ai-kids-8",
          title: "Robot Helper Story",
          icon: <Brain className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-8"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/robot-helper-story",
          index: 7,
        },
        {
          id: "ai-kids-9",
          title: "Spam vs Not Spam",
          icon: <MessageSquare className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-9"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/spam-vs-not-spam",
          index: 8,
        },
        {
          id: "ai-kids-10",
          title: "Siri/Alexa Quiz",
          icon: <Cpu className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-10"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/siri-alexa-quiz",
          index: 9,
        },
        {
          id: "ai-kids-11",
          title: "AI in Games",
          icon: <Gamepad2 className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-11"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-in-games",
          index: 10,
        },
        {
          id: "ai-kids-12",
          title: "Match AI Tools",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-12"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/match-ai-tools",
          index: 11,
        },
        {
          id: "ai-kids-13",
          title: "Pattern Music Game",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-13"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/pattern-music-game",
          index: 12,
        },
        {
          id: "ai-kids-14",
          title: "Robot Vision Game",
          icon: <Eye className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-14"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/robot-vision-game",
          index: 13,
        },
        {
          id: "ai-kids-15",
          title: "Smart Home Story",
          icon: <Home className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-15"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/smart-home-story",
          index: 14,
        },
        {
          id: "ai-kids-16",
          title: "Train the Robot",
          icon: <Brain className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-16"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/train-the-robot",
          index: 15,
        },
        {
          id: "ai-kids-17",
          title: "Prediction Puzzle",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-17"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/prediction-puzzle",
          index: 16,
        },
        {
          id: "ai-kids-18",
          title: "Friendly AI Quiz",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-18"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/friendly-ai-quiz",
          index: 17,
        },
        {
          id: "ai-kids-19",
          title: "Robot Emotion Story",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-19"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/robot-emotion-story",
          index: 18,
        },
        {
          id: "ai-kids-20",
          title: "Recommendation Game",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-20"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/recommendation-game",
          index: 19,
        },
        {
          id: "ai-kids-21",
          title: "AI or Not Quiz",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-21"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-or-not-quiz",
          index: 20,
        },
        {
          id: "ai-kids-22",
          title: "Robot Helper Reflex",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-22"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/robot-helper-reflex",
          index: 21,
        },
        {
          id: "ai-kids-23",
          title: "Match AI Uses",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-23"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/match-ai-uses",
          index: 22,
        },
        {
          id: "ai-kids-24",
          title: "Sorting Animals",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-24"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/sorting-animals",
          index: 23,
        },
        {
          id: "ai-kids-25",
          title: "AI Basics Badge",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10+ min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["ai-kids-25"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-basics-badge",
          index: 24,
        },
        {
          id: "ai-kids-26",
          title: "Traffic Light AI",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-26"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/traffic-light-ai",
          index: 25,
        },
        {
          id: "ai-kids-27",
          title: "AI in Maps Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-27"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-in-maps-story",
          index: 26,
        },
        {
          id: "ai-kids-28",
          title: "Voice Assistant Quiz",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-28"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/voice-assistant-quiz",
          index: 27,
        },
        {
          id: "ai-kids-29",
          title: "YouTube Recommendation Game",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-29"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/youtube-recommendation-game",
          index: 28,
        },
        {
          id: "ai-kids-30",
          title: "Smart Fridge Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-30"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/smart-fridge-story",
          index: 29,
        },
        {
          id: "ai-kids-31",
          title: "Chatbot Friend",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-31"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/chatbot-friend",
          index: 30,
        },
        {
          id: "ai-kids-32",
          title: "Face Unlock Game",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-32"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/face-unlock-game",
          index: 31,
        },
        {
          id: "ai-kids-33",
          title: "AI or Human Quiz",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-33"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-or-human-quiz",
          index: 32,
        },
        {
          id: "ai-kids-34",
          title: "Smart Speaker Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-34"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/smart-speaker-story",
          index: 33,
        },
        {
          id: "ai-kids-35",
          title: "AI Doctor Simulation",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-35"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-doctor-simulation",
          index: 34,
        },
        {
          id: "ai-kids-36",
          title: "Robot Vacuum Game",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-36"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/robot-vacuum-game",
          index: 35,
        },
        {
          id: "ai-kids-37",
          title: "AI Translator Quiz",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-37"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-translator-quiz",
          index: 36,
        },
        {
          id: "ai-kids-38",
          title: "Weather Prediction Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-38"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/weather-prediction-story",
          index: 37,
        },
        {
          id: "ai-kids-39",
          title: "Smartwatch Game",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-39"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/smartwatch-game",
          index: 38,
        },
        {
          id: "ai-kids-40",
          title: "Online Shopping AI",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-40"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/online-shopping-ai",
          index: 39,
        },
        {
          id: "ai-kids-41",
          title: "Airport Scanner Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-41"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/airport-scanner-story",
          index: 40,
        },
        {
          id: "ai-kids-42",
          title: "Smart Farming Quiz",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-42"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/smart-farming-quiz",
          index: 41,
        },
        {
          id: "ai-kids-43",
          title: "AI Artist Game",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-43"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-artist-game",
          index: 42,
        },
        {
          id: "ai-kids-44",
          title: "Music AI Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-44"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/music-ai-story",
          index: 43,
        },
        {
          id: "ai-kids-45",
          title: "AI in Banking Quiz",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-45"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-in-banking-quiz",
          index: 44,
        },
        {
          id: "ai-kids-46",
          title: "Smart City Traffic Game",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-46"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/smart-city-traffic-game",
          index: 45,
        },
        {
          id: "ai-kids-47",
          title: "AI News Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-47"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-news-story",
          index: 46,
        },
        {
          id: "ai-kids-48",
          title: "AI Doctor Quiz",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-48"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-doctor-quiz",
          index: 47,
        },
        {
          id: "ai-kids-49",
          title: "Smart Home Lights Game",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-49"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/smart-home-lights-game",
          index: 48,
        },
        {
          id: "ai-kids-50",
          title: "AI Daily Life Badge",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10+ min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["ai-kids-50"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-daily-life-badge",
          index: 49,
        },
        {
          id: "ai-kids-51",
          title: "Teach the Robot Colors",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-51"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/teach-robot-colors",
          index: 50,
        },
        {
          id: "ai-kids-52",
          title: "Robot Mistake Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-52"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/robot-mistake-story",
          index: 51,
        },
        {
          id: "ai-kids-53",
          title: "Data Cleaning Puzzle",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-53"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/data-cleaning-puzzle",
          index: 52,
        },
        {
          id: "ai-kids-54",
          title: "Training AI Reflex",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-54"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/training-ai-reflex",
          index: 53,
        },
        {
          id: "ai-kids-55",
          title: "Overfitting Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4-6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-55"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/overfitting-story",
          index: 54,
        },
        {
          id: "ai-kids-56",
          title: "Data Labeling Game",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-56"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/data-labeling-game",
          index: 55,
        },
        {
          id: "ai-kids-57",
          title: "AI Gets Smarter",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-57"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-gets-smarter",
          index: 56,
        },
        {
          id: "ai-kids-58",
          title: "Wrong Prediction Quiz",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-58"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/wrong-prediction-quiz",
          index: 57,
        },
        {
          id: "ai-kids-59",
          title: "Garbage In, Garbage Out Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4-6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-59"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/garbage-in-garbage-out-story",
          index: 58,
        },
        {
          id: "ai-kids-60",
          title: "AI Training Badge",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8-10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-60"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-training-badge",
          index: 59,
        },
        {
          id: "ai-kids-61",
          title: "Teach Numbers Game",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-61"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/teach-numbers-game",
          index: 60,
        },
        {
          id: "ai-kids-62",
          title: "Robot Confusion Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-62"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/robot-confusion-story",
          index: 61,
        },
        {
          id: "ai-kids-63",
          title: "Missing Data Puzzle",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-63"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/missing-data-puzzle",
          index: 62,
        },
        {
          id: "ai-kids-64",
          title: "Train AI with Sounds",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-64"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/train-ai-with-sounds",
          index: 63,
        },
        {
          id: "ai-kids-65",
          title: "Robot Exam Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-65"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/robot-exam-story",
          index: 64,
        },
        {
          id: "ai-kids-66",
          title: "Correct the Robot Reflex",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-66"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/correct-the-robot-reflex",
          index: 65,
        },
        {
          id: "ai-kids-67",
          title: "Bias in Data Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-67"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/bias-in-data-story",
          index: 66,
        },
        {
          id: "ai-kids-68",
          title: "Robot Learning Bar",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-68"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/robot-learning-bar",
          index: 67,
        },
        {
          id: "ai-kids-69",
          title: "AI Mistake Quiz",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-69"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-mistake-quiz",
          index: 68,
        },
        {
          id: "ai-kids-70",
          title: "Train Robot Shapes",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-70"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/train-robot-shapes",
          index: 69,
        },
        {
          id: "ai-kids-71",
          title: "Feedback Matters Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-71"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/feedback-matters-story",
          index: 70,
        },
        {
          id: "ai-kids-72",
          title: "Wrong Labels Puzzle",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-72"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/wrong-labels-puzzle",
          index: 71,
        },
        {
          id: "ai-kids-73",
          title: "Robot Practice Game",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-73"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/robot-practice-game",
          index: 72,
        },
        {
          id: "ai-kids-74",
          title: "Data Collector Simulation",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-74"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/data-collector-simulation",
          index: 73,
        },
        {
          id: "ai-kids-75",
          title: "Training Hero Badge",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10+ min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["ai-kids-75"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/training-hero-badge",
          index: 74,
        },
        {
          id: "ai-kids-76",
          title: "Good AI vs Bad AI Quiz",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-76"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/good-ai-vs-bad-ai-quiz",
          index: 75,
        },
        {
          id: "ai-kids-77",
          title: "Robot Honesty Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-77"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/robot-honesty-story",
          index: 76,
        },
        {
          id: "ai-kids-78",
          title: "Privacy Puzzle",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-78"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/privacy-puzzle",
          index: 77,
        },
        {
          id: "ai-kids-79",
          title: "AI Bias Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-79"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-bias-story",
          index: 78,
        },
        {
          id: "ai-kids-80",
          title: "Safe AI Quiz",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-80"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/safe-ai-quiz",
          index: 79,
        },
        {
          id: "ai-kids-81",
          title: "Robot Helper or Villain",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-81"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/robot-helper-or-villain",
          index: 80,
        },
        {
          id: "ai-kids-82",
          title: "AI & Jobs Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-82"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-and-jobs-story",
          index: 81,
        },
        {
          id: "ai-kids-83",
          title: "Fake News Detector",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-83"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/fake-news-detector",
          index: 82,
        },
        {
          id: "ai-kids-84",
          title: "Cyberbully Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-84"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/cyberbully-story",
          index: 83,
        },
        {
          id: "ai-kids-85",
          title: "AI Rights Puzzle",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-85"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-rights-puzzle",
          index: 84,
        },
        {
          id: "ai-kids-86",
          title: "Robot Friend Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-86"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/robot-friend-story",
          index: 85,
        },
        {
          id: "ai-kids-87",
          title: "Future of AI Quiz",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-87"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/future-of-ai-quiz",
          index: 86,
        },
        {
          id: "ai-kids-88",
          title: "AI in Space Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-88"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-in-space-story",
          index: 87,
        },
        {
          id: "ai-kids-89",
          title: "Good Data vs Bad Data Game",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-89"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/good-data-vs-bad-data-game",
          index: 88,
        },
        {
          id: "ai-kids-90",
          title: "AI Superpower Puzzle",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-90"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-superpower-puzzle",
          index: 89,
        },
        {
          id: "ai-kids-91",
          title: "Robot Spy Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4-6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-91"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/robot-spy-story",
          index: 90,
        },
        {
          id: "ai-kids-92",
          title: "AI & Environment Quiz",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-92"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-and-environment-quiz",
          index: 91,
        },
        {
          id: "ai-kids-93",
          title: "Fair AI Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4-6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-93"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/fair-ai-story",
          index: 92,
        },
        {
          id: "ai-kids-94",
          title: "Ethics Decision Game",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-94"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ethics-decision-game",
          index: 93,
        },
        {
          id: "ai-kids-95",
          title: "AI in Medicine Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4-6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-95"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-in-medicine-story",
          index: 94,
        },
        {
          id: "ai-kids-96",
          title: "Dangerous Robot Story",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4-6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-96"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/dangerous-robot-story",
          index: 95,
        },
        {
          id: "ai-kids-97",
          title: "AI Ethics Quiz",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-97"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-ethics-quiz",
          index: 96,
        },
        {
          id: "ai-kids-98",
          title: "Good AI Badge",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10+ min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-98"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/good-ai-badge",
          index: 97,
        },
        {
          id: "ai-kids-99",
          title: "Future Imagination Journal",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-99"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/future-imagination-journal",
          index: 98,
        },
        {
          id: "ai-kids-100",
          title: "AI Explorer Hero Badge",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "10+ min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["ai-kids-100"] || false,
          isSpecial: true,
          path: "/student/ai-for-all/kids/ai-explorer-hero-badge",
          index: 99,
        },
      ];

    return aiGamesKid;
}
