import {
  Trophy, 
  Coins, 
  Puzzle, 
  Users, 
  Calendar, 
  Star, 
  Zap,  
  Heart, 
  Target, 
  BookOpen, 
  GraduationCap, 
  HandHeart, 
  Eye, 
  Smile, 
  MessageSquare, 
  Flag,  
  Home,  
  Sun, 
  Book,  
  HelpCircle,  
  HeartHandshake, 
  Image, 
  AlertTriangle, 
  HandHelping, 
  Layers, 
  Notebook, 
  Drama, 
  Monitor, 
  ShieldCheck, 
  Wind, 
  Feather, 
  Settings, 
  Coffee, 
  Ear, 
  Volume, 
  Map, 
  Scale, 
  Eraser, 
  ListChecks, 
  CheckSquare, 
  Clock, 
} from "lucide-react";
import buildIds from "../buildGameIds";


export const uvlsGamesKidsIds = buildIds("uvls", "kids")

export const getUvlsKidsGames = (gameCompletionStatus)=> {
    const uvlsGamesKid = [
        {
          id: "uvls-kids-1",
          title: "Share Your Toy",
          icon: <HandHeart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-1"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/share-your-toy",
          index: 0,
        },
        {
          id: "uvls-kids-2",
          title: "Feelings Quiz",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-2"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/feelings-quiz",
          index: 1,
        },
        {
          id: "uvls-kids-3",
          title: "Kind Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "2-3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-3"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/kind-reflex",
          index: 2,
        },
        {
          id: "uvls-kids-4",
          title: "Match Faces",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-4"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/match-faces",
          index: 3,
        },
        {
          id: "uvls-kids-5",
          title: "Spot Help",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-5"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/spot-help",
          index: 4,
        },
        {
          id: "uvls-kids-6",
          title: "Kind Poster",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "10-12 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-6"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/kind-poster",
          index: 5,
        },
        {
          id: "uvls-kids-7",
          title: "Mini Journal",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-7"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/mini-journal",
          index: 6,
        },
        {
          id: "uvls-kids-8",
          title: "Comfort Roleplay",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-8"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/comfort-roleplay",
          index: 7,
        },
        {
          id: "uvls-kids-9",
          title: "Share Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "2-3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-9"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/share-reflex",
          index: 8,
        },
        {
          id: "uvls-kids-10",
          title: "Little Empath Badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "Cumulative",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-10"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/little-empath-badge",
          index: 9,
        },
        {
          id: "uvls-kids-11",
          title: "Greet the New Kid",
          icon: <HandHeart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-11"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/greet-the-new-kid",
          index: 10,
        },
        {
          id: "uvls-kids-12",
          title: "Polite Words Quiz",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-12"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/polite-words-quiz",
          index: 11,
        },
        {
          id: "uvls-kids-13",
          title: "Respect Tap",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "2-3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-13"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/respect-tap",
          index: 12,
        },
        {
          id: "uvls-kids-14",
          title: "Inclusion Match",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-14"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/inclusion-match",
          index: 13,
        },
        {
          id: "uvls-kids-15",
          title: "Invite to Play",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-15"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/invite-to-play",
          index: 14,
        },
        {
          id: "uvls-kids-16",
          title: "Inclusion Poster",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "10-12 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-16"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/inclusion-poster",
          index: 15,
        },
        {
          id: "uvls-kids-17",
          title: "Inclusion Journal",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-17"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/inclusion-journal",
          index: 16,
        },
        {
          id: "uvls-kids-18",
          title: "Invite Roleplay",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-18"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/invite-roleplay",
          index: 17,
        },
        {
          id: "uvls-kids-19",
          title: "Respect Signals",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3-4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-19"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/respect-signals",
          index: 18,
        },
        {
          id: "uvls-kids-20",
          title: "Inclusive Kid Badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "Cumulative",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-20"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/inclusive-kid-badge",
          index: 19,
        },
        {
          id: "uvls-kids-21",
          title: "Share Chores",
          icon: <HandHelping className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4â€“6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-21"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/share-chores",
          index: 20,
        },
        {
          id: "uvls-kids-22",
          title: "Equality Quiz",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4â€“5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-22"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/equality-quiz",
          index: 21,
        },
        {
          id: "uvls-kids-23",
          title: "Spot Stereotype",
          icon: <Eye className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3â€“4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-23"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/spot-stereotype",
          index: 22,
        },
        {
          id: "uvls-kids-24",
          title: "Rights Match",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-24"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/rights-match",
          index: 23,
        },
        {
          id: "uvls-kids-25",
          title: "Encourage Dream",
          icon: <Star className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5â€“7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-kids-25"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/encourage-dream",
          index: 24,
        },
        {
          id: "uvls-kids-26",
          title: "Equality Poster",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10â€“12 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-26"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/equality-poster",
          index: 25,
        },
        {
          id: "uvls-kids-27",
          title: "Role Model Journal",
          icon: <Book className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6â€“8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-27"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/role-model-journal",
          index: 26,
        },
        {
          id: "uvls-kids-28",
          title: "Support Roleplay",
          icon: <Smile className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6â€“8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-28"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/support-roleplay",
          index: 27,
        },
        {
          id: "uvls-kids-29",
          title: "Challenge Stereotypes",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "2â€“3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-29"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/challenge-stereotypes",
          index: 28,
        },
        {
          id: "uvls-kids-30",
          title: "Equality Ally Badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-30"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/equality-ally-badge",
          index: 29,
        },
        {
          id: "uvls-kids-31",
          title: "Stop the Tease",
          icon: <HandHelping className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5â€“7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-31"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/stop-the-tease",
          index: 30,
        },
        {
          id: "uvls-kids-32",
          title: "Bullying Quiz",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4â€“5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-32"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/bullying-quiz",
          index: 31,
        },
        {
          id: "uvls-kids-33",
          title: "Report Reflex",
          icon: <AlertTriangle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2â€“3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-33"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/report-reflex",
          index: 32,
        },
        {
          id: "uvls-kids-34",
          title: "Types Match",
          icon: <Layers className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-34"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/types-match",
          index: 33,
        },
        {
          id: "uvls-kids-35",
          title: "Support Friend",
          icon: <HeartHandshake className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6â€“8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-35"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/support-friend",
          index: 34,
        },
        {
          id: "uvls-kids-36",
          title: "Anti-Bullying Poster",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10â€“12 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-36"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/anti-bullying-poster",
          index: 35,
        },
        {
          id: "uvls-kids-37",
          title: "Witness Journal",
          icon: <Notebook className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6â€“8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-37"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/witness-journal",
          index: 36,
        },
        {
          id: "uvls-kids-38",
          title: "Bystander Roleplay",
          icon: <Drama className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8â€“10 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-38"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/bystander-roleplay",
          index: 37,
        },
        {
          id: "uvls-kids-39",
          title: "Cyber Spot",
          icon: <Monitor className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3â€“4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-39"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/cyber-spot",
          index: 38,
        },
        {
          id: "uvls-kids-40",
          title: "Peer Protector Badge",
          icon: <ShieldCheck className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-40"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/peer-protector-badge",
          index: 39,
        },
        {
          id: "uvls-kids-41",
          title: "Name That Feeling",
          icon: <Smile className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4â€“6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-41"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/name-that-feeling",
          index: 40,
        },
        {
          id: "uvls-kids-42",
          title: "Breathe with Me",
          icon: <Wind className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3â€“4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-42"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/breathe-with-me",
          index: 41,
        },
        {
          id: "uvls-kids-43",
          title: "Mood Match",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5â€“6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-43"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/mood-match",
          index: 42,
        },
        {
          id: "uvls-kids-44",
          title: "Mood Journal",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5â€“7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-44"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/mood-journal",
          index: 43,
        },
        {
          id: "uvls-kids-45",
          title: "Calm Choice",
          icon: <Feather className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5â€“7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-45"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/calm-choice",
          index: 44,
        },
        {
          id: "uvls-kids-46",
          title: "Toolbox Poster",
          icon: <Settings className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10â€“12 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-46"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/toolbox-poster",
          index: 45,
        },
        {
          id: "uvls-kids-47",
          title: "Ask for Help Roleplay",
          icon: <MessageSquare className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6â€“8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-47"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/ask-for-help-roleplay",
          index: 46,
        },
        {
          id: "uvls-kids-48",
          title: "Calm Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2â€“3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-48"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/calm-reflex",
          index: 47,
        },
        {
          id: "uvls-kids-49",
          title: "Trigger Map Puzzle",
          icon: <Map className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6â€“8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-49"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/trigger-map-puzzle",
          index: 48,
        },
        {
          id: "uvls-kids-50",
          title: "Self-Aware Badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-kids-50"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/self-aware-badge",
          index: 49,
        },
        {
          id: "uvls-kids-51",
          title: "Snack Choice",
          icon: <Coffee className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4â€“6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-51"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/snack-choice",
          index: 50,
        },
        {
          id: "uvls-kids-52",
          title: "Cause & Effect Quiz",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4â€“5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-52"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/cause-effect-quiz",
          index: 51,
        },
        {
          id: "uvls-kids-53",
          title: "True/False Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2â€“3 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-53"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/true-false-reflex",
          index: 52,
        },
        {
          id: "uvls-kids-54",
          title: "Logic Puzzle",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6â€“8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-54"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/logic-puzzle",
          index: 53,
        },
        {
          id: "uvls-kids-55",
          title: "Risky Offer",
          icon: <AlertTriangle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5â€“7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-55"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/risky-offer",
          index: 54,
        },
        {
          id: "uvls-kids-56",
          title: "Decision Poster",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8â€“10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-56"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/decision-poster",
          index: 55,
        },
        {
          id: "uvls-kids-57",
          title: "Decision Journal",
          icon: <Notebook className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6â€“8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-57"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/decision-journal",
          index: 56,
        },
        {
          id: "uvls-kids-58",
          title: "Ethics Roleplay",
          icon: <Drama className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6â€“8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-58"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/ethics-roleplay",
          index: 57,
        },
        {
          id: "uvls-kids-59",
          title: "Spot Fallacy",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4â€“6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-59"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/spot-fallacy",
          index: 58,
        },
        {
          id: "uvls-kids-60",
          title: "Critical Thinker Badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-60"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/critical-thinker-badge",
          index: 59,
        },
        {
          id: "uvls-kids-61",
          title: "Say Hello",
          icon: <Smile className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4â€“5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-61"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/say-hello",
          index: 60,
        },
        {
          id: "uvls-kids-62",
          title: "Active Listening Quiz",
          icon: <Ear className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4â€“6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-62"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/active-listening-quiz",
          index: 61,
        },
        {
          id: "uvls-kids-63",
          title: "Stop & Listen Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2â€“3 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-63"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/stop-listen-reflex",
          index: 62,
        },
        {
          id: "uvls-kids-64",
          title: "Tone Match",
          icon: <Volume className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5â€“7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-64"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/tone-match",
          index: 63,
        },
        {
          id: "uvls-kids-65",
          title: "Ask Clearly Story",
          icon: <MessageSquare className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5â€“7 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-65"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/ask-clearly-story",
          index: 64,
        },
        {
          id: "uvls-kids-66",
          title: "Communication Poster",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10â€“12 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-66"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/communication-poster",
          index: 65,
        },
        {
          id: "uvls-kids-67",
          title: "Feedback Journal",
          icon: <Notebook className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6â€“8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-67"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/feedback-journal",
          index: 66,
        },
        {
          id: "uvls-kids-68",
          title: "Difficult Talk Roleplay",
          icon: <Drama className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8â€“10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-68"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/difficult-talk-roleplay",
          index: 67,
        },
        {
          id: "uvls-kids-69",
          title: "Empathic Tap",
          icon: <HeartHandshake className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2â€“3 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-69"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/empathic-tap",
          index: 68,
        },
        {
          id: "uvls-kids-70",
          title: "Good Communicator Badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-70"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/good-communicator-badge",
          index: 69,
        },
        {
          id: "uvls-kids-71",
          title: "Toy Dispute",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6â€“8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-71"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/toy-dispute",
          index: 70,
        },
        {
          id: "uvls-kids-72",
          title: "Win-Win Quiz",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4â€“5 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-72"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/win-win-quiz",
          index: 71,
        },
        {
          id: "uvls-kids-73",
          title: "Calm Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2â€“3 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-73"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/calm-reflexx",
          index: 72,
        },
        {
          id: "uvls-kids-74",
          title: "Resolve Steps Puzzle",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-74"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/resolve-steps-puzzle",
          index: 73,
        },
        {
          id: "uvls-kids-75",
          title: "Split Fairly Roleplay",
          icon: <Scale className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8â€“10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-kids-75"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/split-fairly-roleplay",
          index: 74,
        },
        {
          id: "uvls-kids-76",
          title: "Mediation Poster",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10â€“12 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-76"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/mediation-poster",
          index: 75,
        },
        {
          id: "uvls-kids-77",
          title: "Resolution Journal",
          icon: <Notebook className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6â€“8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-77"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/resolution-journal",
          index: 76,
        },
        {
          id: "uvls-kids-78",
          title: "Family Simulation",
          icon: <Home className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8â€“10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-78"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/family-simulation",
          index: 77,
        },
        {
          id: "uvls-kids-79",
          title: "Identify Needs Reflex",
          icon: <HeartHandshake className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3â€“4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-79"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/identify-needs-reflex",
          index: 78,
        },
        {
          id: "uvls-kids-80",
          title: "Mediator Badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-80"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/mediator-badge",
          index: 79,
        },
        {
          id: "uvls-kids-81",
          title: "Clean-up Story",
          icon: <Eraser className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6â€“8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-81"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/clean-up-story",
          index: 80,
        },
        {
          id: "uvls-kids-82",
          title: "Citizen Duties Quiz",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4â€“5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-82"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/citizen-duties-quiz",
          index: 81,
        },
        {
          id: "uvls-kids-83",
          title: "Volunteer Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2â€“3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-83"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/volunteer-reflex",
          index: 82,
        },
        {
          id: "uvls-kids-84",
          title: "Community Roles Puzzle",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5â€“7 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-84"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/community-roles-puzzle",
          index: 83,
        },
        {
          id: "uvls-kids-85",
          title: "Fundraiser Story",
          icon: <Coins className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8â€“10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-85"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/fundraiser-story",
          index: 84,
        },
        {
          id: "uvls-kids-86",
          title: "Civic Poster",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10â€“12 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-86"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/civic-poster",
          index: 85,
        },
        {
          id: "uvls-kids-87",
          title: "Contribution Journal",
          icon: <Notebook className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6â€“8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-87"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/contribution-journal",
          index: 86,
        },
        {
          id: "uvls-kids-88",
          title: "Help Elder Roleplay",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8â€“10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-88"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/help-elder-roleplay",
          index: 87,
        },
        {
          id: "uvls-kids-89",
          title: "Report Need Reflex",
          icon: <AlertTriangle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3â€“4 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-89"] || false, 
          isSpecial: true,
          path: "/student/uvls/kids/report-need-reflex",
          index: 88,
        },
        {
          id: "uvls-kids-90",
          title: "Community Helper Badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-90"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/community-helper-badge",
          index: 89,
        },
        {
          id: "uvls-kids-91",
          title: "Morning Routine",
          icon: <Sun className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6â€“8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-91"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/morning-routine",
          index: 90,
        },
        {
          id: "uvls-kids-92",
          title: "Priority Quiz",
          icon: <ListChecks className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4â€“5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-92"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/priority-quiz",
          index: 91,
        },
        {
          id: "uvls-kids-93",
          title: "Task Done Reflex",
          icon: <CheckSquare className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2â€“3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-93"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/task-done-reflex",
          index: 92,
        },
        {
          id: "uvls-kids-94",
          title: "Plan Your Day Puzzle",
          icon: <Calendar className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6â€“8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-94"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/plan-your-day-puzzle",
          index: 93,
        },
        {
          id: "uvls-kids-95",
          title: "Goal Steps",
          icon: <Flag className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6â€“8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-95"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/goal-steps",
          index: 94,
        },
        {
          id: "uvls-kids-96",
          title: "SMART Poster",
          icon: <Image className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10â€“12 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-96"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/smart-poster",
          index: 95,
        },
        {
          id: "uvls-kids-97",
          title: "Weekly Plan Journal",
          icon: <Notebook className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6â€“8 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-97"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/weekly-plan-journal",
          index: 96,
        },
        {
          id: "uvls-kids-98",
          title: "Time Budget Simulation",
          icon: <Clock className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8â€“10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-98"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/time-budget-simulation",
          index: 97,
        },
        {
          id: "uvls-kids-99",
          title: "Safety Reflex",
          icon: <ShieldCheck className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2â€“3 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-99"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/safety-reflexx",
          index: 98,
        },
        {
          id: "uvls-kids-100",
          title: "Life Skills Starter Badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-kids-100"] || false,
          isSpecial: true,
          path: "/student/uvls/kids/life-skills-starter-badge",
          index: 99,
        },
      ];

    return uvlsGamesKid;
}
