import {
  Trophy, 
  Timer, 
  Puzzle, 
  Users, 
  Calendar, 
  Lightbulb, 
  Zap,  
  Heart, 
  Shield, 
  Globe, 
  Target, 
  BookOpen, 
  GraduationCap, 
  HandHeart,  
  Eye, 
  MessageSquare,  
  RefreshCw,  
  Book, 
  HelpCircle,  
  FileText, 
  Mic, 
  AlertCircle, 
  MessageCircle, 
  PlayCircle, 
  Wind, 
  Scale, 
  CheckSquare, 
  Clock, 
  MonitorPlay, 
  Megaphone, 
  PenLine, 
  Theater, 
  ShieldAlert, 
  ClipboardCheck, 
  CheckCircle, 
  Briefcase, 
  ThumbsUp, 
  Edit3, 
  Handshake, 
  LogOut, 
  DollarSign, 
  Speech, 
  BarChart3, 
  Bell, 
  Siren, 
  Mail, 
  Link, 
  MapPin, 
} from "lucide-react";
import buildIds from "../buildGameIds";


export const uvlsGamesTeenIds = buildIds("uvls", "teen")

export const getUvlsTeenGames = (gameCompletionStatus)=> {
    const uvlsGamesTeen = [
        {
          id: "uvls-teen-1",
          title: "Listen Deep",
          icon: <HandHeart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-1"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/listen-deep",
          index: 0,
        },
        {
          id: "uvls-teen-2",
          title: "Empathy Quiz",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-2"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/empathy-quiz",
          index: 1,
        },
        {
          id: "uvls-teen-3",
          title: "Perspective Puzzle",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-3"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/perspective-puzzle",
          index: 2,
        },
        {
          id: "uvls-teen-4",
          title: "Walk in Shoes Simulation",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-4"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/walk-in-shoes",
          index: 3,
        },
        {
          id: "uvls-teen-5",
          title: "Empathy Debate",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "20-30 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-5"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/empathy-debate",
          index: 4,
        },
        {
          id: "uvls-teen-6",
          title: "Reflective Journal",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10-12 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-6"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/reflective-journal",
          index: 5,
        },
        {
          id: "uvls-teen-7",
          title: "Peer Support Roleplay",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-7"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/peer-support-roleplay",
          index: 6,
        },
        {
          id: "uvls-teen-8",
          title: "Case-Response Puzzle",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-8"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/case-response-puzzle",
          index: 7,
        },
        {
          id: "uvls-teen-9",
          title: "Spot Distress Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-9"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/spot-distress-reflex",
          index: 8,
        },
        {
          id: "uvls-teen-10",
          title: "Empathy Champion Badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "Cumulative",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-10"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/empathy-champion-badge",
          index: 9,
        },
        {
          id: "uvls-teen-11",
          title: "Cultural Greeting",
          icon: <HandHeart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-11"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/cultural-greeting",
          index: 10,
        },
        {
          id: "uvls-teen-12",
          title: "Inclusion Quiz",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-12"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/inclusion-quiz",
          index: 11,
        },
        {
          id: "uvls-teen-13",
          title: "Accessibility Puzzle",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-13"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/accessibility-puzzle",
          index: 12,
        },
        {
          id: "uvls-teen-14",
          title: "Inclusive Class Simulation",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "10-12 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-14"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/inclusive-class-simulation",
          index: 13,
        },
        {
          id: "uvls-teen-15",
          title: "Respect Debate",
          icon: <GraduationCap className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "20 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-15"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/respect-debate",
          index: 14,
        },
        {
          id: "uvls-teen-16",
          title: "Inclusion Journal",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-16"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/inclusion-journal",
          index: 15,
        },
        {
          id: "uvls-teen-17",
          title: "Correcting Bias Roleplay",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-17"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/correcting-bias-roleplay",
          index: 16,
        },
        {
          id: "uvls-teen-18",
          title: "Name Respect Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-18"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/name-respect-reflex",
          index: 17,
        },
        {
          id: "uvls-teen-19",
          title: "Policy Case Puzzle",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-19"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/policy-case-puzzle",
          index: 18,
        },
        {
          id: "uvls-teen-20",
          title: "Respect Leader Badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Variable",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-20"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/respect-leader-badge",
          index: 19,
        },
        {
          id: "uvls-teen-21",
          title: "Encourage Ambition",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-21"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/encourage-ambition",
          index: 20,
        },
        {
          id: "uvls-teen-22",
          title: "Rights & Law Quiz",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-22"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/rights-law-quiz",
          index: 21,
        },
        {
          id: "uvls-teen-23",
          title: "Bias Spot Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-23"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/bias-spot-reflex",
          index: 22,
        },
        {
          id: "uvls-teen-24",
          title: "Workplace Puzzle",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8â€“10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-24"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/workplace-puzzle",
          index: 23,
        },
        {
          id: "uvls-teen-25",
          title: "Program Design Simulation",
          icon: <MonitorPlay className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "12â€“15 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["uvls-teen-25"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/program-design-simulation",
          index: 24,
        },
        {
          id: "uvls-teen-26",
          title: "Equality Debate",
          icon: <Megaphone className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "20 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-26"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/equality-debate",
          index: 25,
        },
        {
          id: "uvls-teen-27",
          title: "Ally Journal",
          icon: <PenLine className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-27"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/ally-journal",
          index: 26,
        },
        {
          id: "uvls-teen-28",
          title: "Intervention Roleplay",
          icon: <Theater className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8â€“10 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-28"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/intervention-roleplay",
          index: 27,
        },
        {
          id: "uvls-teen-29",
          title: "Rights Application Puzzle",
          icon: <Scale className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-29"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/rights-application-puzzle",
          index: 28,
        },
        {
          id: "uvls-teen-30",
          title: "Gender Justice Leader Badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Variable",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-30"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/gender-justice-leader-badge",
          index: 29,
        },
        {
          id: "uvls-teen-31",
          title: "Online Harass Scenario",
          icon: <ShieldAlert className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6â€“8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-31"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/online-harass-scenario",
          index: 30,
        },
        {
          id: "uvls-teen-32",
          title: "Reporting Quiz",
          icon: <ClipboardCheck className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-32"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/reporting-quiz",
          index: 31,
        },
        {
          id: "uvls-teen-33",
          title: "Support Network Puzzle",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-33"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/support-network-puzzle",
          index: 32,
        },
        {
          id: "uvls-teen-34",
          title: "Intervention Simulation",
          icon: <MonitorPlay className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-34"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/intervention-simulation",
          index: 33,
        },
        {
          id: "uvls-teen-35",
          title: "Rehab vs Punish Debate",
          icon: <Megaphone className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "20 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-35"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/rehab-vs-punish-debate",
          index: 34,
        },
        {
          id: "uvls-teen-36",
          title: "Long-term Journal",
          icon: <PenLine className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "12 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-36"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/long-term-journal",
          index: 35,
        },
        {
          id: "uvls-teen-37",
          title: "Counselor Roleplay",
          icon: <Theater className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8â€“10 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-37"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/counselor-roleplay",
          index: 36,
        },
        {
          id: "uvls-teen-38",
          title: "Cyber Safety Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4â€“6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-38"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/cyber-safety-reflex",
          index: 37,
        },
        {
          id: "uvls-teen-39",
          title: "Systemic Case Puzzle",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "12â€“15 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-39"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/systemic-case-puzzle",
          index: 38,
        },
        {
          id: "uvls-teen-40",
          title: "Anti-Bullying Champion Badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Variable",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-40"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/anti-bullying-champion-badge",
          index: 39,
        },
        {
          id: "uvls-teen-41",
          title: "Emotional Check-in",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-41"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/emotional-check-in",
          index: 40,
        },
        {
          id: "uvls-teen-42",
          title: "Trigger Quiz",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-42"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/trigger-quiz",
          index: 41,
        },
        {
          id: "uvls-teen-43",
          title: "Advanced Breathing Simulation",
          icon: <Wind className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5â€“8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-43"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/advanced-breathing-sim",
          index: 42,
        },
        {
          id: "uvls-teen-44",
          title: "Coping Strategy Puzzle",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-44"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/coping-strategy-puzzle",
          index: 43,
        },
        {
          id: "uvls-teen-45",
          title: "De-escalation Roleplay",
          icon: <Theater className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8â€“10 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-45"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/de-escalation-roleplay",
          index: 44,
        },
        {
          id: "uvls-teen-46",
          title: "Emotion Pattern Journal",
          icon: <PenLine className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "15â€“20 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-46"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/emotion-pattern-journal",
          index: 45,
        },
        {
          id: "uvls-teen-47",
          title: "Peer Support Simulation",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10â€“12 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-47"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/peer-support-simulation",
          index: 46,
        },
        {
          id: "uvls-teen-48",
          title: "Self-check Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4â€“6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-48"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/self-check-reflex",
          index: 47,
        },
        {
          id: "uvls-teen-49",
          title: "Build Toolbox Puzzle",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8â€“10 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-49"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/build-toolbox-puzzle",
          index: 48,
        },
        {
          id: "uvls-teen-50",
          title: "Emotional Responder Badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["uvls-teen-50"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/emotional-responder-badge",
          index: 49,
        },
        {
          id: "uvls-teen-51",
          title: "Evidence Check",
          icon: <CheckCircle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6â€“8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-51"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/evidence-check",
          index: 50,
        },
        {
          id: "uvls-teen-52",
          title: "Fake News Quiz",
          icon: <AlertCircle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-52"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/fake-news-quiz",
          index: 51,
        },
        {
          id: "uvls-teen-53",
          title: "Trade-offs Puzzle",
          icon: <Scale className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-53"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/trade-offs-puzzle",
          index: 52,
        },
        {
          id: "uvls-teen-54",
          title: "Scenario Simulation",
          icon: <PlayCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10â€“12 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-54"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/scenario-simulation",
          index: 53,
        },
        {
          id: "uvls-teen-55",
          title: "Ethical Roleplay",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8â€“10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-55"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/ethical-roleplay",
          index: 54,
        },
        {
          id: "uvls-teen-56",
          title: "Bias Detection Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4â€“6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-56"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/bias-detection-reflex",
          index: 55,
        },
        {
          id: "uvls-teen-57",
          title: "Evidence Journal",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-57"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/evidence-journal",
          index: 56,
        },
        {
          id: "uvls-teen-58",
          title: "Timed Debate",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "10â€“15 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-58"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/timed-debate",
          index: 57,
        },
        {
          id: "uvls-teen-59",
          title: "Policy Puzzle",
          icon: <FileText className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "12 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-59"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/policy-puzzle",
          index: 58,
        },
        {
          id: "uvls-teen-60",
          title: "Decision Master Badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-60"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/decision-master-badge",
          index: 59,
        },
        {
          id: "uvls-teen-61",
          title: "Tough Conversation",
          icon: <MessageCircle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-61"] || false, 
          isSpecial: true,
          path: "/student/uvls/teen/tough-conversation",
          index: 60,
        },
        {
          id: "uvls-teen-62",
          title: "Nonverbal Quiz",
          icon: <Eye className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-62"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/nonverbal-quiz",
          index: 61,
        },
        {
          id: "uvls-teen-63",
          title: "Clarify Reflex",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4â€“6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-63"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/clarify-reflex",
          index: 62,
        },
        {
          id: "uvls-teen-64",
          title: "Interview Simulation",
          icon: <Briefcase className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10â€“12 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-64"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/interview-simulation",
          index: 63,
        },
        {
          id: "uvls-teen-65",
          title: "Feedback Roleplay",
          icon: <ThumbsUp className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8â€“10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-65"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/feedback-roleplay",
          index: 64,
        },
        {
          id: "uvls-teen-66",
          title: "Persuasion Puzzle",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "7â€“8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-66"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/persuasion-puzzle",
          index: 65,
        },
        {
          id: "uvls-teen-67",
          title: "Communication Journal",
          icon: <Edit3 className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-67"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/communication-journal",
          index: 66,
        },
        {
          id: "uvls-teen-68",
          title: "Public Speaking Prep",
          icon: <Mic className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8â€“10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-68"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/public-speaking-prep",
          index: 67,
        },
        {
          id: "uvls-teen-69",
          title: "Listening vs Speaking Debate",
          icon: <MessageSquare className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "20 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-69"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/listening-vs-speaking-debate",
          index: 68,
        },
        {
          id: "uvls-teen-70",
          title: "Communication Pro Badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-70"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/communication-pro-badge",
          index: 69,
        },
        {
          id: "uvls-teen-71",
          title: "Power Dynamics Scenario",
          icon: <Shield className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8â€“10 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-71"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/power-dynamics-scenario",
          index: 70,
        },
        {
          id: "uvls-teen-72",
          title: "Negotiation Tactics Quiz",
          icon: <CheckSquare className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-72"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/negotiation-tactics-quiz",
          index: 71,
        },
        {
          id: "uvls-teen-73",
          title: "Mediation Simulation",
          icon: <Handshake className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "12â€“15 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-73"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/mediation-simulation",
          index: 72,
        },
        {
          id: "uvls-teen-74",
          title: "BATNA Puzzle",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6â€“8 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-74"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/batna-puzzle",
          index: 73,
        },
        {
          id: "uvls-teen-75",
          title: "Tough Bargain Roleplay",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "10â€“12 min",
          coins: 15,
          xp: 30,
          completed: gameCompletionStatus["uvls-teen-75"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/tough-bargain-roleplay",
          index: 74,
        },
        {
          id: "uvls-teen-76",
          title: "Ethics in Negotiation Debate",
          icon: <Scale className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "20 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-76"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/ethics-in-negotiation-debate",
          index: 75,
        },
        {
          id: "uvls-teen-77",
          title: "Negotiation Journal",
          icon: <Book className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-77"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/negotiation-journal",
          index: 76,
        },
        {
          id: "uvls-teen-78",
          title: "Walk-away Reflex",
          icon: <LogOut className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4â€“6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-78"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/walk-away-reflex",
          index: 77,
        },
        {
          id: "uvls-teen-79",
          title: "Workplace Conflict Sim",
          icon: <Briefcase className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "12â€“15 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-79"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/workplace-conflict-sim",
          index: 78,
        },
        {
          id: "uvls-teen-80",
          title: "Conflict Solver Badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-80"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/conflict-solver-badge",
          index: 79,
        },
        {
          id: "uvls-teen-81",
          title: "Campaign Story",
          icon: <Megaphone className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "12â€“15 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-81"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/campaign-story",
          index: 80,
        },
        {
          id: "uvls-teen-82",
          title: "SDG Quiz",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-82"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/sdg-quiz",
          index: 81,
        },
        {
          id: "uvls-teen-83",
          title: "Volunteer Simulation",
          icon: <Calendar className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "12 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-83"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/volunteer-simulation",
          index: 82,
        },
        {
          id: "uvls-teen-84",
          title: "Public Budget Puzzle",
          icon: <DollarSign className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-84"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/public-budget-puzzle",
          index: 83,
        },
        {
          id: "uvls-teen-85",
          title: "Advocacy Roleplay",
          icon: <Speech className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "10â€“12 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-85"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/advocacy-roleplay",
          index: 84,
        },
        {
          id: "uvls-teen-86",
          title: "Impact Journal",
          icon: <BarChart3 className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8â€“10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-86"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/impact-journal",
          index: 85,
        },
        {
          id: "uvls-teen-87",
          title: "Service Design Puzzle",
          icon: <Lightbulb className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "12 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-87"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/service-design-puzzle",
          index: 86,
        },
        {
          id: "uvls-teen-88",
          title: "Coalition Simulation",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "15 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-88"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/coalition-simulation",
          index: 87,
        },
        {
          id: "uvls-teen-89",
          title: "Civic Reflex",
          icon: <Bell className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4â€“6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-89"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/civic-reflex",
          index: 88,
        },
        {
          id: "uvls-teen-90",
          title: "Citizen Leader Badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Variable",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-90"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/citizen-leader-badge",
          index: 89,
        },
        {
          id: "uvls-teen-91",
          title: "Short vs Long Goals Debate",
          icon: <Clock className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "20 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-91"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/short-vs-long-goals-debate",
          index: 90,
        },
        {
          id: "uvls-teen-92",
          title: "Emergency Steps Quiz",
          icon: <Siren className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-92"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/emergency-steps-quiz",
          index: 91,
        },
        {
          id: "uvls-teen-93",
          title: "One-year Plan Journal",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "12 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-93"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/one-year-plan-journal",
          index: 92,
        },
        {
          id: "uvls-teen-94",
          title: "Crisis Simulation",
          icon: <Timer className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8â€“12 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-94"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/crisis-simulation",
          index: 93,
        },
        {
          id: "uvls-teen-95",
          title: "Request Extension Roleplay",
          icon: <Mail className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "8â€“10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-95"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/request-extension-roleplay",
          index: 94,
        },
        {
          id: "uvls-teen-96",
          title: "Safety Offer Reflex",
          icon: <Shield className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3â€“5 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-96"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/safety-offer-reflex",
          index: 95,
        },
        {
          id: "uvls-teen-97",
          title: "Habit Chain Puzzle",
          icon: <Link className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8â€“10 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-97"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/habit-chain-puzzle",
          index: 96,
        },
        {
          id: "uvls-teen-98",
          title: "Habit Change Journal",
          icon: <RefreshCw className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "10â€“12 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-98"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/habit-change-journal",
          index: 97,
        },
        {
          id: "uvls-teen-99",
          title: "Solo Trip Simulation",
          icon: <MapPin className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "12â€“15 min",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-99"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/solo-trip-simulation",
          index: 98,
        },
        {
          id: "uvls-teen-100",
          title: "Life Skills Champion Badge",
          icon: <Trophy className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "Cumulative",
          coins: 20,
          xp: 40,
          completed: gameCompletionStatus["uvls-teen-100"] || false,
          isSpecial: true,
          path: "/student/uvls/teen/life-skills-champion-badge",
          index: 99,
        },
      ];

    return uvlsGamesTeen;
}
