import {
  Lock,  
  Puzzle, 
  Users, 
  Zap, 
  Gamepad2, 
  Heart, 
  Shield,  
  BookOpen, 
  HandHeart, 
  Camera, 
  Smartphone, 
  UserX, 
  Eye, 
  Smile, 
  MessageSquare, 
  Flag, 
  RefreshCw, 
  Award, 
  Palette, 
  Home, 
  HelpCircle, 
  PenTool, 
} from "lucide-react";
import buildIds from "../buildGameIds";


export const dcosGamesKidsIds = buildIds("dcos", "kids")

export const getDcosKidsGames = (gameCompletionStatus)=> {
    const dcosKidsGame = [
        {
          id: "dcos-kids-1",
          title: "Strong Password Reflex",
          icon: <Lock className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2-3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-1"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/strong-password-reflex",
          index: 0,
        },
        {
          id: "dcos-kids-2",
          title: "Stranger Chat Story",
          icon: <Shield className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-2"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/stranger-chat-story",
          index: 1,
        },
        {
          id: "dcos-kids-3",
          title: "Photo Share Quiz",
          icon: <Camera className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-3"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/photo-share-quiz",
          index: 2,
        },
        {
          id: "dcos-kids-4",
          title: "Personal Info Puzzle",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-4"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/personal-info-puzzle",
          index: 3,
        },
        {
          id: "dcos-kids-5",
          title: "Game Invite Reflex",
          icon: <Gamepad2 className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-5"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/game-invite-reflex",
          index: 4,
        },
        {
          id: "dcos-kids-6",
          title: "Safety Poster Task",
          icon: <Palette className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-6"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/safety-poster",
          index: 5,
        },
        {
          id: "dcos-kids-7",
          title: "Family Rules Story",
          icon: <Home className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-7"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/family-rules-story",
          index: 6,
        },
        {
          id: "dcos-kids-8",
          title: "Device Sharing Quiz",
          icon: <Smartphone className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-8"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/device-sharing-quiz",
          index: 7,
        },
        {
          id: "dcos-kids-9",
          title: "Online Friend Reflex",
          icon: <UserX className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-9"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/online-friend-reflex",
          index: 8,
        },
        {
          id: "dcos-kids-10",
          title: "Safe User Badge",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-10"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/safe-user-badge",
          index: 9,
        },
        {
          id: "dcos-kids-11",
          title: "Spot the Bully Quiz",
          icon: <Eye className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-11"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/spot-bully-quiz",
          index: 10,
        },
        {
          id: "dcos-kids-12",
          title: "Kind Words Reflex",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2-3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-12"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/kind-words-reflex",
          index: 11,
        },
        {
          id: "dcos-kids-13",
          title: "Smile Story",
          icon: <Smile className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-13"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/smile-story",
          index: 12,
        },
        {
          id: "dcos-kids-14",
          title: "Gossip Puzzle",
          icon: <MessageSquare className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-14"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/gossip-puzzle",
          index: 13,
        },
        {
          id: "dcos-kids-15",
          title: "Playground Bystander",
          icon: <HandHeart className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-15"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/playground-bystander",
          index: 14,
        },
        {
          id: "dcos-kids-16",
          title: "Cyberbully Report",
          icon: <Flag className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-16"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/cyberbully-report",
          index: 15,
        },
        {
          id: "dcos-kids-17",
          title: "Role Swap Simulation",
          icon: <RefreshCw className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-17"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/role-swap",
          index: 16,
        },
        {
          id: "dcos-kids-18",
          title: "Journal of Kindness",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-18"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/kindness-journal",
          index: 17,
        },
        {
          id: "dcos-kids-19",
          title: "Friendship Reflex",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-19"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/friendship-reflex",
          index: 18,
        },
        {
          id: "dcos-kids-20",
          title: "Kind Friend Badge",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "5-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-20"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/kind-friend-badge",
          index: 19,
        },
        {
          id: "dcos-kids-21",
          title: "Screen Timer Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2-3 min",
          coins: 5,
            xp: 10,
          completed: gameCompletionStatus["dcos-kids-21"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/screen-timer-reflex",
          index: 20,
        },
        {
          id: "dcos-kids-22",
          title: "Play vs Study Puzzle",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4-5 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-22"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/play-vs-study-puzzle",
          index: 21,
        },
        {
          id: "dcos-kids-23",
          title: "Family Rules Story 2",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-4 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-23"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/family-rules-story1",
          index: 22,
        },
        {
          id: "dcos-kids-24",
          title: "Eye Strain Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2-3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-24"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/eye-strain-reflex",
          index: 23,
        },
        {
          id: "dcos-kids-25",
          title: "Sleep Quiz",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2-3 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-kids-25"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/sleep-quiz",
          index: 24,
        },
        {
          id: "dcos-kids-26",
          title: "Balance Poster Task",
          icon: <PenTool className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["dcos-kids-26"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/balance-poster-task",
          index: 25,
        },
        {
          id: "dcos-kids-27",
          title: "Outdoor Fun Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4-5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["dcos-kids-27"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/outdoor-fun-story",
          index: 26,
        },
        {
          id: "dcos-kids-28",
          title: "Addiction Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3-4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["dcos-kids-28"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/addiction-reflex",
          index: 27,
        },
        {
          id: "dcos-kids-29",
          title: "Journal: My Balance",
          icon: <PenTool className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4-5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["dcos-kids-29"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/journal-my-balance",
          index: 28,
        },
        {
          id: "dcos-kids-30",
          title: "Balance Badge",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["dcos-kids-30"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/balance-badge",
          index: 29,
        },
        {
          id: "dcos-kids-31",
          title: "Spot the Truth Quiz",
          icon: <HelpCircle className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2-3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["dcos-kids-31"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/spot-the-truth-quiz",
          index: 30,
        },
        {
          id: "dcos-kids-32",
          title: "Cartoon News Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2-3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["dcos-kids-32"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/cartoon-news-reflex",
          index: 31,
        },
        {
          id: "dcos-kids-33",
          title: "Forward Message Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3-4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["dcos-kids-33"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/forward-message-story",
          index: 32,
        },
        {
          id: "dcos-kids-34",
          title: "Picture Puzzle",
          icon: <Puzzle className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4-5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["dcos-kids-34"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/picture-puzzle",
          index: 33,
        },
        {
          id: "dcos-kids-35",
          title: "Gossip Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2-3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["dcos-kids-35"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/gossip-reflex",
          index: 34,
        },
        {
          id: "dcos-kids-36",
          title: "Family Talk Story",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "3-4 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["dcos-kids-36"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/family-talk-story",
          index: 35,
        },
        {
          id: "dcos-kids-37",
          title: "Fact-Check Poster Task",
          icon: <PenTool className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["dcos-kids-37"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/fact-check-poster-task",
          index: 36,
        },
        {
          id: "dcos-kids-38",
          title: "Journal of Truth",
          icon: <PenTool className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4-5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["dcos-kids-38"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/journal-of-truth1",
          index: 37,
        },
        {
          id: "dcos-kids-39",
          title: "Emoji Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "2-3 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["dcos-kids-39"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/emoji-reflex",
          index: 38,
        },
        {
          id: "dcos-kids-40",
          title: "Truth Badge",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["dcos-kids-40"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/truth-badge",
          index: 39,
        },
        {
          id: "dcos-kids-41",
          title: "Free Gift Story",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "4-6 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["dcos-kids-41"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/free-gift-story",
          index: 40,
        },
        {
          id: "dcos-kids-42",
          title: "Fake Link Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Easy",
          duration: "3-5 min",
          coins: 10,
          xp: 20,
          completed: gameCompletionStatus["dcos-kids-42"] || false,
          isSpecial: true,
          path: "/student/dcos/kids/fake-link-reflex",
          index: 41,
        },
      {
        id: "dcos-kids-43",
        title: "Game Coin Scam Quiz",
        icon: <HelpCircle className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "4-6 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["dcos-kids-43"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/game-coin-scam-quiz",
        index: 42,
      },
      {
        id: "dcos-kids-44",
        title: "Stranger Gift Story",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5-7 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["dcos-kids-44"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/stranger-gift-story",
        index: 43,
      },
      {
        id: "dcos-kids-45",
        title: "OTP Reflex",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3-4 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["dcos-kids-45"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/otp-reflex",
        index: 44,
      },
      {
        id: "dcos-kids-46",
        title: "Puzzle of Traps",
        icon: <Puzzle className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5-8 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["dcos-kids-46"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/puzzle-of-traps",
        index: 45,
      },
      {
        id: "dcos-kids-47",
        title: "Poster Task",
        icon: <PenTool className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6-8 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["dcos-kids-47"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/poster-task",
        index: 46,
      },
      {
        id: "dcos-kids-48",
        title: "Chat Trick Story",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5-7 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["dcos-kids-48"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/chat-trick-story",
        index: 47,
      },
      {
        id: "dcos-kids-49",
        title: "Reflex Block Game",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3-5 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["dcos-kids-49"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/reflex-block-game",
        index: 48,
      },
      {
        id: "dcos-kids-50",
        title: "Scam Aware Badge",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5-8 min",
        coins: 10,
        xp: 20,
        completed: gameCompletionStatus["dcos-kids-50"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/scam-aware-badge",
        index: 49,
      },
      {
        id: "dcos-kids-51",
        title: "Password Privacy Story",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5-7 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-51"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/password-privacy-story",
        index: 50,
      },
      {
        id: "dcos-kids-52",
        title: "Profile Quiz",
        icon: <HelpCircle className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3-5 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-52"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/profile-quiz",
        index: 51,
      },
      {
        id: "dcos-kids-53",
        title: "Photo Consent Reflex",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3-4 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-53"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/photo-consent-reflex",
        index: 52,
      },
      {
        id: "dcos-kids-54",
        title: "Puzzle: Public vs Private",
        icon: <Puzzle className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5-8 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-54"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/puzzle-public-private",
        index: 53,
      },
      {
        id: "dcos-kids-55",
        title: "Stranger Request Story",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5-7 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-55"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/stranger-request-story",
        index: 54,
      },
      {
        id: "dcos-kids-56",
        title: "Device Privacy Reflex",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3-5 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-56"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/device-privacy-reflex",
        index: 55,
      },
      {
        id: "dcos-kids-57",
        title: "Rights Poster Task",
        icon: <PenTool className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6-8 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-57"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/rights-poster-task",
        index: 56,
      },
      {
        id: "dcos-kids-58",
        title: "Journal: My Private Info",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5-7 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-58"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/journal-private-info",
        index: 57,
      },
      {
        id: "dcos-kids-59",
        title: "Safe Friend Quiz",
        icon: <HelpCircle className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3-5 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-59"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/safe-friend-quiz",
        index: 58,
      },
      {
        id: "dcos-kids-60",
        title: "Privacy Hero Badge",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6-8 min",
        coins: 15,
          xp: 30,
        completed: gameCompletionStatus["dcos-kids-60"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/privacy-hero-badge",
        index: 59,
      },
      {
        id: "dcos-kids-61",
        title: "Digital Footprint Story",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5-7 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-61"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/digital-footprint-story",
        index: 60,
      },
      {
        id: "dcos-kids-62",
        title: "Reflex Delete",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3-5 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-62"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/reflex-delete",
        index: 61,
      },
      {
        id: "dcos-kids-63",
        title: "Puzzle: Online Forever",
        icon: <Puzzle className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5-8 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-63"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/puzzle-online-forever",
        index: 62,
      },
      {
        id: "dcos-kids-64",
        title: "Good vs Bad Post Quiz",
        icon: <HelpCircle className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3-5 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-64"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/good-vs-bad-post-quiz",
        index: 63,
      },
      {
        id: "dcos-kids-65",
        title: "Emoji Reflex 2",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3-5 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-65"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/emoji-reflex1",
        index: 64,
      },
      {
        id: "dcos-kids-66",
        title: "School Reputation Story",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5-7 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-66"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/school-reputation-story",
        index: 65,
      },
      {
        id: "dcos-kids-67",
        title: "Poster: Digital Footprint",
        icon: <PenTool className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6-8 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-67"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/poster-task1",
        index: 66,
      },
      {
        id: "dcos-kids-68",
        title: "Journal of Posts",
        icon: <BookOpen className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5-7 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-68"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/journal-of-posts",
        index: 67,
      },
      {
        id: "dcos-kids-69",
        title: "Reflex Share Safe",
        icon: <Zap className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3-5 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-69"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/reflex-share-safe",
        index: 68,
      },
      {
        id: "dcos-kids-70",
        title: "Footprint Badge",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "6-8 min",
        coins: 15,
          xp: 30,
        completed: gameCompletionStatus["dcos-kids-70"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/footprint-badge",
        index: 69,
      },
      {
        id: "dcos-kids-71",
        title: "Smart Robot Story",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5-6 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-71"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/smart-robot-story",
        index: 70,
      },

      {
        id: "dcos-kids-72",
        title: "Reflex AI Safety",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3-4 min",
        coins: 15,
          xp: 30,
        completed: gameCompletionStatus["dcos-kids-72"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/reflex-ai-safety1",
        index: 71,
      },

      {
        id: "dcos-kids-73",
        title: "Puzzle: AI Good vs Bad",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "4-5 min",
        coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-73"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/puzzle-ai-good-bad",
        index: 72,
      },

      {
        id: "dcos-kids-74",
        title: "Fairness Quiz",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3-4 min",
        coins: 15,
          xp: 30,
        completed: gameCompletionStatus["dcos-kids-74"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/fairness-quiz1",
        index: 73,
      },

      {
        id: "dcos-kids-75",
        title: "AI Friend Story",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "6-7 min",
                coins: 15,
        xp: 30,
        completed: gameCompletionStatus["dcos-kids-75"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/ai-friend-story",
        index: 74,
      },

      {
        id: "dcos-kids-76",
        title: "Reflex Deepfake Spotter",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "3-4 min",
        coins: 20,
          xp: 40,
        completed: gameCompletionStatus["dcos-kids-76"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/reflex-deepfake-spotter",
        index: 75,
      },

      {
        id: "dcos-kids-77",
        title: "Poster Task 2",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5-6 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["dcos-kids-77"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/poster-task2",
        index: 76,
      },

      {
        id: "dcos-kids-78",
        title: "AI Helper Journal",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "5 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["dcos-kids-78"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/ai-helper-journal",
        index: 77,
      },

      {
        id: "dcos-kids-79",
        title: "Classroom Story",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "5-6 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["dcos-kids-79"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/classroom-story3",
        index: 78,
      },

      {
        id: "dcos-kids-80",
        title: "AI Ethics Badge",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "6-8 min",
        coins: 20,
          xp: 40,
        completed: gameCompletionStatus["dcos-kids-80"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/ai-ethics-badge",
        index: 79,
      },
      {
        id: "dcos-kids-81",
        title: "Kind vs Mean Words Quiz",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3-4 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["dcos-kids-81"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/kind-vs-mean-quiz",
        index: 80,
      },
      {
        id: "dcos-kids-82",
        title: "Reflex Respect",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "3-4 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["dcos-kids-82"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/reflex-respect1",
        index: 81,
      },
      {
        id: "dcos-kids-83",
        title: "Class Chat Story",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "4-5 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["dcos-kids-83"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/class-chat-story",
        index: 82,
      },
      {
        id: "dcos-kids-84",
        title: "Puzzle: Respect Match",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "4-5 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["dcos-kids-84"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/puzzle-respect-match1",
        index: 83,
      },
      {
        id: "dcos-kids-85",
        title: "School Team Reflex",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3-4 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["dcos-kids-85"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/school-team-reflex",
        index: 84,
      },
      {
        id: "dcos-kids-86",
        title: "Poster Task 3",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Creative",
        duration: "6-8 min",
        coins: 20,
          xp: 40,
        completed: gameCompletionStatus["dcos-kids-86"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/poster-task3",
        index: 85,
      },
      {
        id: "dcos-kids-87",
        title: "Story of Difference",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "4-5 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["dcos-kids-87"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/story-of-difference",
        index: 86,
      },
      {
        id: "dcos-kids-88",
        title: "Journal: My Words",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Creative",
        duration: "5-6 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["dcos-kids-88"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/journal-my-words",
        index: 87,
      },
      {
        id: "dcos-kids-89",
        title: "Playground Reflex",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3-4 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["dcos-kids-89"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/playground-reflex",
        index: 88,
      },
      {
        id: "dcos-kids-90",
        title: "Respect Hero Badge",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "6-8 min",
        coins: 20,
          xp: 40,
        completed: gameCompletionStatus["dcos-kids-90"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/respect-hero-badge",
        index: 89,
      },
      {
        id: "dcos-kids-91",
        title: "Study App Story",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "4-5 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["dcos-kids-91"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/study-app-story",
        index: 90,
      },
      {
        id: "dcos-kids-92",
        title: "Reflex Learning Tools",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3-4 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["dcos-kids-92"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/reflex-learning-tools",
        index: 91,
      },
      {
        id: "dcos-kids-93",
        title: "Puzzle: Good vs Waste Apps",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "4-5 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["dcos-kids-93"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/puzzle-good-vs-waste-apps",
        index: 92,
      },
      {
        id: "dcos-kids-94",
        title: "Homework Story",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "4-5 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["dcos-kids-94"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/homework-story1",
        index: 93,
      },
      {
        id: "dcos-kids-95",
        title: "Reflex Offline Fun",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3-4 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["dcos-kids-95"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/reflex-offline-fun",
        index: 94,
      },
      {
        id: "dcos-kids-96",
        title: "Poster Task 4",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Creative",
        duration: "6-8 min",
        coins: 20,
          xp: 40,
        completed: gameCompletionStatus["dcos-kids-96"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/poster-task4",
        index: 95,
      },
      {
        id: "dcos-kids-97",
        title: "Sharing Good Content Story",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Medium",
        duration: "4-5 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["dcos-kids-97"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/sharing-good-content-story",
        index: 96,
      },
      {
        id: "dcos-kids-98",
        title: "Journal of Smart Use",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Creative",
        duration: "5-6 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["dcos-kids-98"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/journal-of-smart-use",
        index: 97,
      },
      {
        id: "dcos-kids-99",
        title: "Reflex Reading",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Easy",
        duration: "3-4 min",
        coins: 20,
        xp: 40,
        completed: gameCompletionStatus["dcos-kids-99"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/reflex-reading",
        index: 98,
      },
      {
        id: "dcos-kids-100",
        title: "Smart User Badge",
        icon: <Award className="w-6 h-6" />,
        difficulty: "Hard",
        duration: "6-8 min",
        coins: 20,
          xp: 40,
        completed: gameCompletionStatus["dcos-kids-100"] || false,
        isSpecial: true,
        path: "/student/dcos/kids/smart-user-badge",
        index: 99,
      },
    ];

    return dcosKidsGame;
}
