import {
  Lock, 
  Puzzle, 
  Users, 
  Zap, 
  Heart, 
  Shield, 
  Globe, 
  Target, 
  BookOpen, 
  HandHeart,  
  Camera, 
  Smartphone, 
  UserX, 
  Eye, 
  MessageSquare, 
  Flag, 
  Award, 
  HelpCircle,  
  PenTool,  
  Monitor,
  UserCheck, 
} from "lucide-react";
import buildIds from "../buildGameIds";


export const dcosGamesTeenIds = buildIds("dcos", "teen")

export const getDcosTeenGames = (gameCompletionStatus)=> {
    const dcosTeenGame = [
        {
          id: "dcos-teen-1",
          title: "Password Sharing Story",
          icon: <Lock className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-teen-1"] || false,
          isSpecial: true,
          path: "/student/dcos/teens/password-sharing-story",
          index: 0,
        },
        {
          id: "dcos-teen-2",
          title: "Privacy Settings Quiz",
          icon: <Shield className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-teen-2"] || false,
          isSpecial: true,
          path: "/student/dcos/teens/privacy-settings-quiz",
          index: 1,
        },
        {
          id: "dcos-teen-3",
          title: "OTP Fraud Reflex",
          icon: <MessageSquare className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-teen-3"] || false,
          isSpecial: true,
          path: "/student/dcos/teens/otp-fraud-reflex",
          index: 2,
        },
        {
          id: "dcos-teen-4",
          title: "Profile Picture Simulation",
          icon: <Camera className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-teen-4"] || false,
          isSpecial: true,
          path: "/student/dcos/teens/profile-picture-simulation",
          index: 3,
        },
        {
          id: "dcos-teen-5",
          title: "Social Media Journal",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-teen-5"] || false,
          isSpecial: true,
          path: "/student/dcos/teens/social-media-journal",
          index: 4,
        },
        {
          id: "dcos-teen-6",
          title: "Data Consent Quiz",
          icon: <Smartphone className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-teen-6"] || false,
          isSpecial: true,
          path: "/student/dcos/teens/data-consent-quiz",
          index: 5,
        },
        {
          id: "dcos-teen-7",
          title: "Fake Friend Story",
          icon: <UserX className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-teen-7"] || false,
          isSpecial: true,
          path: "/student/dcos/teens/fake-friend-story",
          index: 6,
        },
        {
          id: "dcos-teen-8",
          title: "Safety Reflex",
          icon: <Eye className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-teen-8"] || false,
          isSpecial: true,
          path: "/student/dcos/teens/safety-reflex",
          index: 7,
        },
        {
          id: "dcos-teen-9",
          title: "Debate: Online Friends",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "15-20 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-teen-9"] || false,
          isSpecial: true,
          path: "/student/dcos/teens/debate-stage-online-friends",
          index: 8,
        },
        {
          id: "dcos-teen-10",
          title: "Online Safety Badge",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-teen-10"] || false,
          isSpecial: true,
          path: "/student/dcos/teens/online-safety-badge",
          index: 9,
        },
        {
          id: "dcos-teen-11",
          title: "Cyberbully Reflex",
          icon: <Shield className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-teen-11"] || false,
          isSpecial: true,
          path: "/student/dcos/teens/cyberbully-reflex",
          index: 10,
        },
        {
          id: "dcos-teen-12",
          title: "Peer Pressure Story",
          icon: <Users className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-teen-12"] || false,
          isSpecial: true,
          path: "/student/dcos/teens/peer-pressure-story",
          index: 11,
        },
        {
          id: "dcos-teen-13",
          title: "Gossip Chain Simulation",
          icon: <MessageSquare className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-teen-13"] || false,
          isSpecial: true,
          path: "/student/dcos/teens/gossip-chain-simulation",
          index: 12,
        },
        {
          id: "dcos-teen-14",
          title: "Debate: Trolling",
          icon: <Target className="w-6 h-6" />,
          difficulty: "Hard",
          duration: "15-20 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-teen-14"] || false,
          isSpecial: true,
          path: "/student/dcos/teens/debate-stage-trolling",
          index: 13,
        },
        {
          id: "dcos-teen-15",
          title: "Diversity Quiz",
          icon: <Globe className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "5-7 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-teen-15"] || false,
          isSpecial: true,
          path: "/student/dcos/teens/diversity-quiz",
          index: 14,
        },
        {
          id: "dcos-teen-16",
          title: "Encourage Roleplay",
          icon: <Heart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-teen-16"] || false,
          isSpecial: true,
          path: "/student/dcos/teens/encourage-roleplay",
          index: 15,
        },
        {
          id: "dcos-teen-17",
          title: "Empathy Journal",
          icon: <BookOpen className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "8-10 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-teen-17"] || false,
          isSpecial: true,
          path: "/student/dcos/teens/empathy-journal",
          index: 16,
        },
        {
          id: "dcos-teen-18",
          title: "Anti-Bully Reflex",
          icon: <Zap className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "4-6 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-teen-18"] || false,
          isSpecial: true,
          path: "/student/dcos/teens/anti-bully-reflex",
          index: 17,
        },
        {
          id: "dcos-teen-19",
          title: "Upstander Simulation",
          icon: <HandHeart className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-teen-19"] || false,
          isSpecial: true,
          path: "/student/dcos/teens/upstander-simulation",
          index: 18,
        },
        {
          id: "dcos-teen-20",
          title: "Courage Badge",
          icon: <Award className="w-6 h-6" />,
          difficulty: "Medium",
          duration: "6-8 min",
          coins: 5,
          xp: 10,
          completed: gameCompletionStatus["dcos-teen-20"] || false,
          isSpecial: true,
          path: "/student/dcos/teens/courage-badge",
          index: 19,
        },
        {
  id: "dcos-teen-21",
  title: "Screen Log Story",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-6 min",
  coins: 5,
  xp: 10,
  completed: gameCompletionStatus["dcos-teen-21"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/screen-log-story",
  index: 20,
},
{
  id: "dcos-teen-22",
  title: "Sleep Health Quiz",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "3-4 min",
  coins: 5,
  xp: 10,
  completed: gameCompletionStatus["dcos-teen-22"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/sleep-health-quiz",
  index: 21,
},
{
  id: "dcos-teen-23",
  title: "Dopamine Reflex",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "4-5 min",
  coins: 5,
  xp: 10,
  completed: gameCompletionStatus["dcos-teen-23"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/dopamine-reflex",
  index: 22,
},
{
  id: "dcos-teen-24",
  title: "Digital Detox Simulation",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-6 min",
  coins: 5,
  xp: 10,
  completed: gameCompletionStatus["dcos-teen-24"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/digital-detox-simulation",
  index: 23,
},
{
  id: "dcos-teen-25",
  title: "Balance Journal",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "4-5 min",
  coins: 5,
  xp: 10,
  completed: gameCompletionStatus["dcos-teen-25"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/balance-journal",
  index: 24,
},
{
  id: "dcos-teen-26",
  title: "Productivity Puzzle",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-6 min",
  coins: 10,
  xp: 20,
  completed: gameCompletionStatus["dcos-teen-26"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/productivity-puzzle",
  index: 25,
},
{
  id: "dcos-teen-27",
  title: "Family Rule Debate",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Hard",
  duration: "6-8 min",
  coins: 10,
          xp: 20,
  completed: gameCompletionStatus["dcos-teen-27"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/family-rule-debate",
  index: 26,
},
{
  id: "dcos-teen-28",
  title: "Sleep Hygiene Reflex",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "3-4 min",
  coins: 10,
  xp: 20,
  completed: gameCompletionStatus["dcos-teen-28"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/sleep-hygiene-reflex",
  index: 27,
},
{
  id: "dcos-teen-29",
  title: "Success Story Simulation",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-6 min",
  coins: 10,
  xp: 20,
  completed: gameCompletionStatus["dcos-teen-29"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/success-story-simulation",
  index: 28,
},
{
  id: "dcos-teen-30",
  title: "Wellbeing Badge",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Hard",
  duration: "6-8 min",
  coins: 10,
          xp: 20,
  completed: gameCompletionStatus["dcos-teen-30"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/wellbeing-badge",
  index: 29,
},
{
  id: "dcos-teen-31",
  title: "Viral Post Story",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-6 min",
  coins: 10,
  xp: 20,
  completed: gameCompletionStatus["dcos-teen-31"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/viral-post-story",
  index: 30,
},
{
  id: "dcos-teen-32",
  title: "Deepfake Video Quiz",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-6 min",
  coins: 10,
  xp: 20,
  completed: gameCompletionStatus["dcos-teen-32"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/deepfake-video-quiz",
  index: 31,
},
{
  id: "dcos-teen-33",
  title: "Forward Reflex",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "3-4 min",
  coins: 10,
  xp: 20,
  completed: gameCompletionStatus["dcos-teen-33"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/forward-reflex",
  index: 32,
},
{
  id: "dcos-teen-34",
  title: "Fact-Check Simulation",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-6 min",
  coins: 10,
  xp: 20,
  completed: gameCompletionStatus["dcos-teen-34"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/fact-check-simulation",
  index: 33,
},
{
  id: "dcos-teen-35",
  title: "Meme Truth Puzzle",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "4-6 min",
  coins: 10,
  xp: 20,
  completed: gameCompletionStatus["dcos-teen-35"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/meme-truth-puzzle",
  index: 34,
},
{
  id: "dcos-teen-36",
  title: "WhatsApp Debate",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Hard",
  duration: "6-8 min",
  coins: 10,
    xp: 20,
  completed: gameCompletionStatus["dcos-teen-36"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/whatsapp-debate",
  index: 35,
},
{
  id: "dcos-teen-37",
  title: "Fake Job Scam Story",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-6 min",
  coins: 10,
  xp: 20,
  completed: gameCompletionStatus["dcos-teen-37"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/fake-job-scam-story",
  index: 36,
},
{
  id: "dcos-teen-38",
  title: "Truth Journal",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "4-5 min",
  coins: 10,
  xp: 20,
  completed: gameCompletionStatus["dcos-teen-38"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/truth-journal2",
  index: 37,
},
{
  id: "dcos-teen-39",
  title: "News Reflex",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "3-4 min",
  coins: 10,
  xp: 20,
  completed: gameCompletionStatus["dcos-teen-39"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/news-reflex",
  index: 38,
},
{
  id: "dcos-teen-40",
  title: "Fact-Check Badge",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Hard",
  duration: "6-8 min",
  coins: 10,
          xp: 20,
  completed: gameCompletionStatus["dcos-teen-40"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/fact-check-badge",
  index: 39,
},
{
  id: "dcos-teen-41",
  title: "Fake Job Ad Story",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-7 min",
  coins: 10,
  xp: 20,
  completed: gameCompletionStatus["dcos-teen-41"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/fake-job-ad-story",
  index: 40,
},
{
  id: "dcos-teen-42",
  title: "Phishing Email Quiz",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-7 min",
  coins: 10,
  xp: 20,
  completed: gameCompletionStatus["dcos-teen-42"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/phishing-email-quiz",
  index: 41,
},
{
  id: "dcos-teen-43",
  title: "OTP Scam Reflex",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "3-5 min",
  coins: 10,
  xp: 20,
  completed: gameCompletionStatus["dcos-teen-43"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/otp-scam-reflex",
  index: 42,
},
{
  id: "dcos-teen-44",
  title: "Shopping Simulation",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "6-8 min",
  coins: 10,
  xp: 20,
  completed: gameCompletionStatus["dcos-teen-44"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/shopping-simulation",
  index: 43,
},
{
  id: "dcos-teen-45",
  title: "Loan Trap Story",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-7 min",
  coins: 10,
  xp: 20,
  completed: gameCompletionStatus["dcos-teen-45"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/loan-trap-story",
  index: 44,
},
{
  id: "dcos-teen-46",
  title: "Scam Debate",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Hard",
  duration: "7-9 min",
  coins: 10,
          xp: 20,
  completed: gameCompletionStatus["dcos-teen-46"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/scam-debate",
  index: 45,
},
{
  id: "dcos-teen-47",
  title: "Banking Safety Puzzle",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-7 min",
  coins: 10,
  xp: 20,
  completed: gameCompletionStatus["dcos-teen-47"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/banking-safety-puzzle",
  index: 46,
},
{
  id: "dcos-teen-48",
  title: "Fraud Journal",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "5-6 min",
  coins: 10,
  xp: 20,
  completed: gameCompletionStatus["dcos-teen-48"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/fraud-journal",
  index: 47,
},
{
  id: "dcos-teen-49",
  title: "Reflex Ad Trap",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "3-5 min",
  coins: 10,
  xp: 20,
  completed: gameCompletionStatus["dcos-teen-49"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/reflex-ad-trap",
  index: 48,
},
{
  id: "dcos-teen-50",
  title: "Fraud Fighter Badge",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Hard",
  duration: "7-9 min",
  coins: 10,
          xp: 20,
  completed: gameCompletionStatus["dcos-teen-50"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/fraud-fighter-badge",
  index: 49,
},
{
  id: "dcos-teen-51",
  title: "Consent Story",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-7 min",
  coins: 15,
  xp: 30,
  completed: gameCompletionStatus["dcos-teen-51"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/consent-story",
  index: 50,
},
{
  id: "dcos-teen-52",
  title: "Data Quiz",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "4-6 min",
  coins: 15,
  xp: 30,
  completed: gameCompletionStatus["dcos-teen-52"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/data-quiz",
  index: 51,
},
{
  id: "dcos-teen-53",
  title: "Fake App Reflex",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "3-5 min",
  coins: 15,
  xp: 30,
  completed: gameCompletionStatus["dcos-teen-53"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/fake-app-reflex",
  index: 52,
},
{
  id: "dcos-teen-54",
  title: "Sharing Rights Simulation",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-7 min",
  coins: 15,
  xp: 30,
  completed: gameCompletionStatus["dcos-teen-54"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/sharing-rights-simulation",
  index: 53,
},
{
  id: "dcos-teen-55",
  title: "Privacy Laws Puzzle",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "6-8 min",
  coins: 15,
  xp: 30,
  completed: gameCompletionStatus["dcos-teen-55"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/privacy-laws-puzzle",
  index: 54,
},
{
  id: "dcos-teen-56",
  title: "Debate Stage",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Hard",
  duration: "7-9 min",
  coins: 15,
          xp: 30,
  completed: gameCompletionStatus["dcos-teen-56"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/debate-stage",
  index: 55,
},
{
  id: "dcos-teen-57",
  title: "Digital Footprint Story",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-7 min",
  coins: 15,
  xp: 30,
  completed: gameCompletionStatus["dcos-teen-57"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/digital-footprint-story1",
  index: 56,
},
{
  id: "dcos-teen-58",
  title: "Journal of Privacy",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "5-6 min",
  coins: 15,
  xp: 30,
  completed: gameCompletionStatus["dcos-teen-58"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/journal-of-privacy",
  index: 57,
},
{
  id: "dcos-teen-59",
  title: "Content Ownership Quiz",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "4-6 min",
  coins: 15,
  xp: 30,
  completed: gameCompletionStatus["dcos-teen-59"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/content-ownership-quiz",
  index: 58,
},
{
  id: "dcos-teen-60",
  title: "Rights Defender Badge",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Hard",
  duration: "7-9 min",
  coins: 15,
          xp: 30,
  completed: gameCompletionStatus["dcos-teen-60"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/rights-defender-badge",
  index: 59,
},
{
  id: "dcos-teen-61",
  title: "Future Job Story",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-7 min",
  coins: 15,
  xp: 30,
  completed: gameCompletionStatus["dcos-teen-61"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/future-job-story",
  index: 60,
},
{
  id: "dcos-teen-62",
  title: "Cancel Culture Quiz",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "6-8 min",
  coins: 15,
          xp: 30,
  completed: gameCompletionStatus["dcos-teen-62"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/cancel-culture-quiz",
  index: 61,
},
{
  id: "dcos-teen-63",
  title: "Reflex Positive Identity",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "4-6 min",
  coins: 15,
  xp: 30,
  completed: gameCompletionStatus["dcos-teen-63"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/reflex-positive-identity",
  index: 62,
},
{
  id: "dcos-teen-64",
  title: "College Application Simulation",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-7 min",
  coins: 15,
  xp: 30,
  completed: gameCompletionStatus["dcos-teen-64"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/college-application-simulation",
  index: 63,
},
{
  id: "dcos-teen-65",
  title: "Debate Stage 2",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Hard",
  duration: "7-9 min",
  coins: 15,
          xp: 30,
  completed: gameCompletionStatus["dcos-teen-65"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/debate-stage1",
  index: 64,
},
{
  id: "dcos-teen-66",
  title: "Digital Reputation Puzzle",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "6-8 min",
  coins: 15,
  xp: 30,
  completed: gameCompletionStatus["dcos-teen-66"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/digital-reputation-puzzle",
  index: 65,
},
{
  id: "dcos-teen-67",
  title: "Journal: My Identity",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "5-6 min",
  coins: 15,
  xp: 30,
  completed: gameCompletionStatus["dcos-teen-67"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/journal-my-identity",
  index: 66,
},
{
  id: "dcos-teen-68",
  title: "Story of Positivity",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-7 min",
  coins: 15,
  xp: 30,
  completed: gameCompletionStatus["dcos-teen-68"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/story-of-positivity",
  index: 67,
},
{
  id: "dcos-teen-69",
  title: "Reflex Recruiter",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "4-6 min",
  coins: 15,
  xp: 30,
  completed: gameCompletionStatus["dcos-teen-69"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/reflex-recruiter",
  index: 68,
},
{
  id: "dcos-teen-70",
  title: "Identity Badge",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Hard",
  duration: "7-9 min",
  coins: 15,
          xp: 30,
  completed: gameCompletionStatus["dcos-teen-70"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/identity-badge",
  index: 69,
},
{
  id: "dcos-teen-71",
  title: "Bias Story",
  icon: <BookOpen className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "4-6 min",
  coins: 15,
  xp: 30,
  completed: gameCompletionStatus["dcos-teen-71"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/bias-story",
  index: 70,
},
{
  id: "dcos-teen-72",
  title: "Deepfake Quiz",
  icon: <HelpCircle className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-7 min",
  coins: 15,
  xp: 30,
  completed: gameCompletionStatus["dcos-teen-72"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/deepfake-quiz",
  index: 71,
},
{
  id: "dcos-teen-73",
  title: "Reflex Fair AI",
  icon: <Zap className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "3-5 min",
  coins: 15,
  xp: 30,
  completed: gameCompletionStatus["dcos-teen-73"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/reflex-fair-ai",
  index: 72,
},
{
  id: "dcos-teen-74",
  title: "Simulation: AI in Exams",
  icon: <Monitor className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "6-8 min",
  coins: 15,
  xp: 30,
  completed: gameCompletionStatus["dcos-teen-74"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/ai-in-exams",
  index: 73,
},
{
  id: "dcos-teen-75",
  title: "AI in Jobs Debate",
  icon: <MessageSquare className="w-6 h-6" />,
  difficulty: "Hard",
  duration: "6-8 min",
  coins: 15,
          xp: 30,
  completed: gameCompletionStatus["dcos-teen-75"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/ai-jobs-debate1",
  index: 74,
},
{
  id: "dcos-teen-76",
  title: "Puzzle: AI Uses",
  icon: <Puzzle className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-7 min",
  coins: 20,
  xp: 40,
  completed: gameCompletionStatus["dcos-teen-76"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/puzzle-ai-uses",
  index: 75,
},
{
  id: "dcos-teen-77",
  title: "Journal: My AI Rule",
  icon: <PenTool className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "4-6 min",
  coins: 20,
  xp: 40,
  completed: gameCompletionStatus["dcos-teen-77"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/journal-ai-rule",
  index: 76,
},
{
  id: "dcos-teen-78",
  title: "Copyright Story",
  icon: <BookOpen className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "4-6 min",
  coins: 20,
  xp: 40,
  completed: gameCompletionStatus["dcos-teen-78"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/copyright-story",
  index: 77,
},
{
  id: "dcos-teen-79",
  title: "Reflex AI Responsibility",
  icon: <Zap className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "3-5 min",
  coins: 20,
  xp: 40,
  completed: gameCompletionStatus["dcos-teen-79"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/reflex-ai-responsibility",
  index: 78,
},
{
  id: "dcos-teen-80",
  title: "AI Leader Badge",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Hard",
  duration: "6-8 min",
  coins: 20,
          xp: 40,
  completed: gameCompletionStatus["dcos-teen-80"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/ai-leader-badge",
  index: 79,
},
{
  id: "dcos-teen-81",
  title: "Hate Comment Story",
  icon: <BookOpen className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "4-6 min",
  coins: 20,
  xp: 40,
  completed: gameCompletionStatus["dcos-teen-81"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/hate-comment-story",
  index: 80,
},
{
  id: "dcos-teen-82",
  title: "Freedom vs Abuse Quiz",
  icon: <HelpCircle className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-7 min",
  coins: 20,
  xp: 40,
  completed: gameCompletionStatus["dcos-teen-82"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/freedom-vs-abuse-quiz",
  index: 81,
},
{
  id: "dcos-teen-83",
  title: "Reflex Support",
  icon: <Zap className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "3-5 min",
  coins: 20,
  xp: 40,
  completed: gameCompletionStatus["dcos-teen-83"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/reflex-support",
  index: 82,
},
{
  id: "dcos-teen-84",
  title: "Simulation: Group Chat",
  icon: <Monitor className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "6-8 min",
  coins: 20,
  xp: 40,
  completed: gameCompletionStatus["dcos-teen-84"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/group-chat-simulation",
  index: 83,
},
{
  id: "dcos-teen-85",
  title: "Debate Stage 3",
  icon: <MessageSquare className="w-6 h-6" />,
  difficulty: "Hard",
  duration: "6-8 min",
  coins: 20,
          xp: 40,
  completed: gameCompletionStatus["dcos-teen-85"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/debate-stage2",
  index: 84,
},
{
  id: "dcos-teen-86",
  title: "Puzzle: Respect vs Hate",
  icon: <Puzzle className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-7 min",
  coins: 20,
  xp: 40,
  completed: gameCompletionStatus["dcos-teen-86"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/puzzle-respect-vs-hate",
  index: 85,
},
{
  id: "dcos-teen-87",
  title: "Journal: My Online Respect",
  icon: <PenTool className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "4-6 min",
  coins: 20,
  xp: 40,
  completed: gameCompletionStatus["dcos-teen-87"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/journal-online-respect",
  index: 86,
},
{
  id: "dcos-teen-88",
  title: "Roleplay: Calm Reply",
  icon: <UserCheck className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-7 min",
  coins: 20,
  xp: 40,
  completed: gameCompletionStatus["dcos-teen-88"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/roleplay-calm-reply",
  index: 87,
},
{
  id: "dcos-teen-89",
  title: "Reflex Flag",
  icon: <Flag className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "3-5 min",
  coins: 20,
  xp: 40,
  completed: gameCompletionStatus["dcos-teen-89"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/reflex-flag1",
  index: 88,
},
{
  id: "dcos-teen-90",
  title: "Respect Champion Badge",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Hard",
  duration: "6-8 min",
  coins: 20,
          xp: 40,
  completed: gameCompletionStatus["dcos-teen-90"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/respect-champion-badge",
  index: 89,
},
{
  id: "dcos-teen-91",
  title: "Entrepreneur Story",
  icon: <BookOpen className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-7 min",
  coins: 20,
  xp: 40,
  completed: gameCompletionStatus["dcos-teen-91"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/entrepreneur-story",
  index: 90,
},
{
  id: "dcos-teen-92",
  title: "Reflex Productivity",
  icon: <Zap className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "3-5 min",
  coins: 20,
  xp: 40,
  completed: gameCompletionStatus["dcos-teen-92"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/reflex-productivity",
  index: 91,
},
{
  id: "dcos-teen-93",
  title: "Debate Stage 4",
  icon: <MessageSquare className="w-6 h-6" />,
  difficulty: "Hard",
  duration: "6-8 min",
  coins: 20,
          xp: 40,
  completed: gameCompletionStatus["dcos-teen-93"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/debate-stage3",
  index: 92,
},
{
  id: "dcos-teen-94",
  title: "Online Course Simulation",
  icon: <Monitor className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "6-8 min",
  coins: 20,
  xp: 40,
  completed: gameCompletionStatus["dcos-teen-94"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/online-course-simulation",
  index: 93,
},
{
  id: "dcos-teen-95",
  title: "Career Puzzle",
  icon: <Puzzle className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-7 min",
  coins: 20,
  xp: 40,
  completed: gameCompletionStatus["dcos-teen-95"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/career-puzzle",
  index: 94,
},
{
  id: "dcos-teen-96",
  title: "Journal of Future Use",
  icon: <PenTool className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "4-6 min",
  coins: 20,
  xp: 40,
  completed: gameCompletionStatus["dcos-teen-96"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/journal-future-use",
  index: 95,
},
{
  id: "dcos-teen-97",
  title: "Social Media Story",
  icon: <BookOpen className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "5-7 min",
  coins: 20,
  xp: 40,
  completed: gameCompletionStatus["dcos-teen-97"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/social-media-story1",
  index: 96,
},
{
  id: "dcos-teen-98",
  title: "Reflex Smart Screen",
  icon: <Zap className="w-6 h-6" />,
  difficulty: "Easy",
  duration: "3-5 min",
  coins: 20,
  xp: 40,
  completed: gameCompletionStatus["dcos-teen-98"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/reflex-smart-screen",
  index: 97,
},
{
  id: "dcos-teen-99",
  title: "Role Model Task",
  icon: <UserCheck className="w-6 h-6" />,
  difficulty: "Medium",
  duration: "6-8 min",
  coins: 20,
          xp: 40,
  completed: gameCompletionStatus["dcos-teen-99"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/role-model-task",
  index: 98,
},
{
  id: "dcos-teen-100",
  title: "Productivity Hero Badge",
  icon: <Award className="w-6 h-6" />,
  difficulty: "Hard",
  duration: "6-8 min",
  coins: 20,
          xp: 40,
  completed: gameCompletionStatus["dcos-teen-100"] || false,
  isSpecial: true,
  path: "/student/dcos/teens/productivity-hero-badge",
  index: 99,
},
      ];

    return dcosTeenGame;
}
